objects/AQI_Audit__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Author</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserAQIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AQI Audit</label>
    <nameField>
        <displayFormat>AQI-{0000}</displayFormat>
        <label>AQI  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AQI Audits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestAQIAverageCtrl.cls
@IsTest(SeeAllData=true)

private class TestAQIAverageCtrl {

    static testMethod void testAQIAverage() {	
    	
    	AQI_Audit__c assessment = new AQI_Audit__c(Status__c='Complete' ,Author__c = TestAQIRQIUtils.createTestAgent(UserInfo.getUserID()).Id);
     	insert assessment;
    	
		AQIAverageCtrl AAC = new AQIAverageCtrl(new ApexPages.standardController(assessment));
		System.assert(AAC.theAverage != null);
    }
}