objects/Auto_number__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>values__c</fullName>
        <label>values</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Auto number</label>
</CustomObject>

objects/Global_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Information__c</fullName>
        <label>Information</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders(Revenue/Non-Revenue)</relationshipLabel>
        <relationshipName>End_User_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order (Sold To)</relationshipLabel>
        <relationshipName>Sold_To_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>Non_Revenue_Orders</fullName>
        <active>true</active>
        <label>Non-Revenue Orders</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>APN_Number__c</fullName>
        <label>APN Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <label>End User Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maintenance_End_Date__c</fullName>
        <label>Maintenance End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maintenance_Start_Date__c</fullName>
        <label>Maintenance Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <label>Sold To Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LMSIntegrationMirrorNRO_Test.cls
@isTest
public class LMSIntegrationMirrorNRO_Test {
	
	static testMethod void tstMirr() {

		TestUtil.setConfigValues();
		Util.Bypass_Trigger_Chk = true;

		Account acc = new Account( Name='Account', Status__c = 'Active' );  
	 	insert acc;   
	
        Product2 prod = new Product2 (Name = 'ProdName', ProductCode = 'ProdCode', APN_Number__c = 'APN', 
                                     	OfferingType__c = 'PureConnect Cloud', IsActive = true);
        insert prod;
            
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(CurrencyIsoCode ='USD',
				        Pricebook2Id = pricebookId, Product2Id = prod.Id,
				        UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        Product2 prod1 = new Product2 (Name = 'ProdName', ProductCode = 'ProdCode', APN_Number__c = 'A', 
                                     	OfferingType__c = 'PureConnect Cloud', IsActive = true);
        insert prod1;
            
        PricebookEntry standardPrice1 = new PricebookEntry(CurrencyIsoCode ='USD',
				        Pricebook2Id = pricebookId, Product2Id = prod1.Id,
				        UnitPrice = 10000, IsActive = true);
        insert standardPrice1;
        
        
        LMSIntegrationMirrorNRO.OrderProduct pr1 = new LMSIntegrationMirrorNRO.OrderProduct();
        pr1.PartNum = 'APN';
        pr1.Qty = 1;
        LMSIntegrationMirrorNRO.OrderProduct pr2 = new LMSIntegrationMirrorNRO.OrderProduct();
        pr2.PartNum = 'A';
        pr2.Qty = 1;
        
        LIst<LMSIntegrationMirrorNRO.OrderProduct> plst1 = new LIst<LMSIntegrationMirrorNRO.OrderProduct>();
        plst1.add(pr1);
        LIst<LMSIntegrationMirrorNRO.OrderProduct> plst2 = new LIst<LMSIntegrationMirrorNRO.OrderProduct>();
        plst2.add(pr2);
        
        
        List<RecordType> nroContractType = [SELECT Id From RecordType WHERE DeveloperName = 'Non_Revenue_Orders' AND SObjectType ='Order__c'];
        
        List<RecordType> orderLineType = [SELECT Id From RecordType WHERE DeveloperName = 'Default' AND SobjectType ='Order_Line_Item__c'];
       
        Global_Setting__c gs1 = new Global_Setting__c(Name='NRO RT', ID__c = nroContractType[0].Id );
        insert gs1;
        Global_Setting__c gs2 = new Global_Setting__c(Name='Mirror', Information__c = 'Mirror');
        insert gs2;
        Global_Setting__c gs3 = new Global_Setting__c(Name='Order Line Default RT', ID__c = orderLineType[0].Id);
        insert gs3;
        
        Auto_number__c myCS1 = new Auto_number__c(Name='start', values__c = 1);
        insert myCS1;
        
        ServiceContract sc = new ServiceContract();
        sc.Name = 'Test Service Contract';
        sc.Agreement_Status__c = 'Active';
        sc.Service_Contract_Type__c = 'Mirror';
        sc.AccountId = acc.id;
        sc.End_User_Name__c = acc.id;
        sc.Sold_To_Name__c = acc.Id;
        sc.EndDate = Date.Today().addDays(200);
        sc.StartDate = Date.Today();
        sc.pricebook2id = pricebookId;
        insert sc;
                
        ContractLineItem cLI = new ContractLineItem(ServiceContractId = sc.Id);
        cLI.Quantity = 10;
        cLI.UnitPrice = 100;
        cLI.pricebookEntryId = standardPrice.Id;
        cLI.Upgraded_Product__c = prod.Id;
        cLI.Current_Quantity__c = 1;
        cLI.Maintenance_Start_Date__c = Date.Today();
        cLI.Maintenance_End_Date__c = Date.Today().addDays(200);
        insert cLI;
        
        Util.Bypass_Trigger_Chk = true;
             
        Test.startTest();
        
        LMSIntegrationMirrorNRO.LMSIntegrationMirrorNRO(acc.Id, acc.Id, '', plst1);
        // duplicate
        LMSIntegrationMirrorNRO.LMSIntegrationMirrorNRO(acc.Id, acc.Id, '', plst1);
        
        LMSIntegrationMirrorNRO.LMSIntegrationMirrorNRO(acc.Id, acc.Id, '', plst2);
        
        LMSIntegrationMirrorNRO.LMSIntegrationMirrorNRO('', acc.Id, '', plst2);
        LMSIntegrationMirrorNRO.LMSIntegrationMirrorNRO(acc.Id, '', '', plst2);
        LMSIntegrationMirrorNRO.LMSIntegrationMirrorNRO('12', acc.Id, '', plst2);
        LMSIntegrationMirrorNRO.LMSIntegrationMirrorNRO(acc.Id, acc.Id, '', plst2);
        LMSIntegrationMirrorNRO.LMSIntegrationMirrorNRO(acc.Id, acc.Id, '', new LIst<LMSIntegrationMirrorNRO.OrderProduct>());
        
        Test.stopTest();
	}
    
}