objects/Back_Office_Account__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>BOA Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>BOA Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts</relationshipLabel>
        <relationshipName>Back_Office_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PureEngage On Premise</fullName>
                    <default>true</default>
                    <label>PureEngage On Premise</label>
                </value>
                <value>
                    <fullName>PureConnect On Premise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Back Office Account</label>
    <nameField>
        <displayFormat>BOA-{000000}</displayFormat>
        <label>Back Office Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Back Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Platform__c.object
<CustomObject>
    <description>What it does?  Object holding information about platforms associated with demo requests.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Support_Access__c.object
<CustomObject>
    <fields>
        <fullName>Back_Office_Account__c</fullName>
        <label>Back Office Account</label>
        <referenceTo>Back_Office_Account__c</referenceTo>
        <relationshipName>Support_Access</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>eService_Access</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>eService_Access</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Support Access Premise</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Support Access ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Access Premise</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LicenseManagementControllerTest.cls
@isTest(seeAllData=true)
public class LicenseManagementControllerTest {
    @isTest
    static void testLicenseManagementController1(){
    	LicenseManagementController lmController = new LicenseManagementController();
    	lmController.tabClicked();
    	lmController.accountSelection.AccountId = [SELECT id FROM Account WHERE Name = 'Avtex' AND RecordType.Name = 'Enterprise - Business Partner' LIMIT 1].Id;
    	lmController.goClicked();
    }

    @isTest
    static void testLicenseManagementController2(){
    	List<Support_Access__c> supportAccessCustomer = [SELECT id, Name, Contact__c, End_User_Account__c FROM Support_Access__c WHERE 
    																End_User_Account__r.ININ_ID__c != NULL
    																AND End_User_Account__r.Type = 'Customer'
    																AND Back_Office_Account__r.Approval_Status__c = 'Active' 
																 	AND Back_Office_Account__r.Contract_Status__c = 'Active' 
																 	AND Back_Office_Account__r.Platform__c = 'PureConnect On Premise' LIMIT 2];
    	if(supportAccessCustomer.size() > 0 ){
			User u1 = [SELECT id FROM User WHERE ContactId = :supportAccessCustomer[0].Contact__c];
			
    		System.runAs(u1){
		    	LicenseManagementController lmController = new LicenseManagementController();
		    	lmController.tabClicked();
		    	lmController.accountSelection.AccountId = supportAccessCustomer[0].End_User_Account__c;
		    	lmController.goClicked();
		    	List<SelectOption> endUserAccounts = lmController.getEndUserAccounts();
    		}	
		}
    }
    
    @isTest
    static void testLicenseManagementController3(){
    	List<Support_Access__c> supportAccessPartner = [SELECT id, Name, Contact__c, End_User_Account__c FROM Support_Access__c WHERE 
    																End_User_Account__r.ININ_ID__c != NULL
    																AND End_User_Account__r.RecordType.Name = 'Enterprise - Business Partner'
    																AND Back_Office_Account__r.Approval_Status__c = 'Active' 
																 	AND Back_Office_Account__r.Contract_Status__c = 'Active' 
																 	AND Back_Office_Account__r.Platform__c = 'PureConnect On Premise' 
																 	AND End_User_Account__r.Name = 'Avtex' LIMIT 2];
    	if(supportAccessPartner.size() > 0 ){
			User u1 = [SELECT id FROM User WHERE ContactId = :supportAccessPartner[0].Contact__c];
			
    		System.runAs(u1){
		    	LicenseManagementController lmController = new LicenseManagementController();
		    	lmController.tabClicked();
		    	lmController.selectedEndUserAccountId = supportAccessPartner[0].End_User_Account__c;
		    	lmController.accountSelection.AccountId = supportAccessPartner[0].End_User_Account__c;
		    	lmController.goClicked();
		    	List<SelectOption> endUserAccounts = lmController.getEndUserAccounts();
    		}	
		}
    }
    
}