objects/Back_Office_Account__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>BOA Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts</relationshipLabel>
        <relationshipName>Back_Office_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <label>End User Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PureEngage On Premise</fullName>
                    <default>true</default>
                    <label>PureEngage On Premise</label>
                </value>
                <value>
                    <fullName>PureConnect On Premise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts (Sold To Account)</relationshipLabel>
        <relationshipName>Back_Office_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <description>used in searches</description>
        <label>Sold To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_STEU__c</fullName>
        <externalId>true</externalId>
        <label>Unique STEU</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Back Office Account</label>
    <nameField>
        <displayFormat>BOA-{000000}</displayFormat>
        <label>Back Office Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Back Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Platform__c.object
<CustomObject>
    <description>What it does?  Object holding information about platforms associated with demo requests.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BackOfficeAccountUtil.cls
public class BackOfficeAccountUtil {
    
   static Map<String, Back_Office_Account__c> upsertBoaMap;
    
   @InvocableMethod
   public static void addBOAbyServiceContract (List<ServiceContract> srvConList) {
   	 // process flow when a new Service Contract Created
   	  try {
   	 	 upsertBoaByServiceContracts(srvConList);
   	  }
   	  catch(Exception ex) {
   	  	 ErrorLogUtil.insertLog('BackOfficeAccountUtil', 'Error from method addBOAbyServiceContract: ' +  ex.getMessage(), 'BackOfficeAccountUtil.upsertBoaByServiceContracts(srvConList)');     
    	 return;	
   	  }
   }
      
   public static void upsertBoaByServiceContracts (List<ServiceContract> srvConList) {
        if ( srvConList == null || upsertBoaMap != null)
              return;

        upsertBoaMap = new Map<String, Back_Office_Account__c>();
       
        for ( ServiceContract srvCon : srvConList )  {

            if ( srvCon.Sold_To_Name__c == null || srvCon.End_User_Name__c == null  || srvCon.Service_Contract_Type__c == 'Cloud' ||
                (upsertBoaMap.get((Id) srvCon.Sold_To_Name__c + '_' + (Id) srvCon.End_User_Name__c) != null) )  {
                     continue;
            }

            String contrOffering = BackOfficeAccountService.getServiceContractOffering(srvCon);
            if ( contrOffering != 'PureConnect On Premise' && contrOffering  != 'PureEngage On Premise' )
                  continue;

            BackOfficeAccountService.BoaInstance boa = new BackOfficeAccountService.BoaInstance(srvCon.Sold_To_Name__c, srvCon.End_User_Name__c, false, contrOffering);
            
            if (boa.boaInst != null )
               upsertBoaMap.put(boa.boaInst.Unique_STEU__c, boa.boaInst);   
        }

        if ( !upsertBoaMap.isEmpty() )  {

              List<Database.upsertResult> upsertResults = Database.upsert(upsertBoaMap.values(), false);
              
              for (Database.UpsertResult result : upsertResults) {
                   if (!result.isSuccess())
                        System.debug('UPSERT FAILED : ' + result.getErrors()[0].getMessage());
             }
  
        }
    }
    
  public static void setBoaFields (List<Back_Office_Account__c> boaList) {

         if ( boaList == null || upsertBoaMap != null )
              return;
         
         upsertBoaMap = new Map<String, Back_Office_Account__c>();
         
         for (Back_Office_Account__c boa : boaList)  {
            
            if ( boa.Sold_To_Account__c == null || boa.End_User_Account__c == null  ||
                (upsertBoaMap.get((Id) boa.Sold_To_Account__c + '_' + (Id) boa.End_User_Account__c) != null) )  {
                     continue;
            }
            
            Back_Office_Account__c verifiedBoa = BackOfficeAccountService.getBoaContractFieldsBySTEU (boa.Sold_To_Account__c, boa.End_User_Account__c, boa.Platform__c);
            
            if ( verifiedBoa != null ) {                                
                boa.Contract_Status__c = verifiedBoa.Contract_Status__c;
                boa.Platform__c     = verifiedBoa.Platform__c;
                boa.Unique_STEU__c  = verifiedBoa.Unique_STEU__c;
                boa.End_User_Name__c = verifiedBoa.End_User_Name__c;
                boa.Sold_To_Name__c = verifiedBoa.Sold_To_Name__c;       
            }                       
         }                        
    }
    
}