objects/Back_Office_Account__c.object
<CustomObject>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts</relationshipLabel>
        <relationshipName>Back_Office_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts (Sold To Account)</relationshipLabel>
        <relationshipName>Back_Office_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Back Office Account</label>
    <nameField>
        <displayFormat>BOA-{000000}</displayFormat>
        <label>Back Office Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Back Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case_Email_Subscription__c.object
<CustomObject>
    <description>Allow internal employees and external contacts to subscribe to case email notifications.</description>
    <fields>
        <fullName>Additional_Email_Addr__c</fullName>
        <label>Additional Email Addr</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Case_Email_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Genesys Customer Contact</inlineHelpText>
        <label>Customer Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>notContain</operation>
                <value>Genesys</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Case_Email_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genesys_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Genesys internal user</inlineHelpText>
        <label>Genesys Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notContain</operation>
                <value>Portal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Email_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <defaultValue>&quot;Internal&quot;</defaultValue>
        <label>Subscription Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Email Subscription</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Email Subscriptions</pluralLabel>
    <recordTypes>
        <fullName>Additional_Email_Addr</fullName>
        <active>true</active>
        <label>Additional Email Addr</label>
    </recordTypes>
    <recordTypes>
        <fullName>Customer_Contact</fullName>
        <active>true</active>
        <label>Customer Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Genesys_Employee</fullName>
        <active>true</active>
        <description>Genesys Employee</description>
        <label>Genesys Employee</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case_Email_Subscription_BOA__c.object
<CustomObject>
    <description>Allow internal employees and external contacts to subscribe to email notifications for cases under specific Back Office Account</description>
    <fields>
        <fullName>Additional_Email_Addr__c</fullName>
        <label>Additional Email Addr</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Back_Office_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Back Office Account</label>
        <referenceTo>Back_Office_Account__c</referenceTo>
        <relationshipLabel>Case Email Subscriptions</relationshipLabel>
        <relationshipName>Case_Email_Subscriptions_BOA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>notContain</operation>
                <value>Genesys</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Email Subscriptions BOA</relationshipLabel>
        <relationshipName>Case_Email_Subscriptions_BOA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genesys_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genesys Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notContain</operation>
                <value>Portal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Email_Subscriptions_BOA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <label>Subscription Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Email Subscription BOA</label>
    <nameField>
        <displayFormat>BOAS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Email Subscriptions BOA</pluralLabel>
    <recordTypes>
        <fullName>Additional_Email_Addr</fullName>
        <active>true</active>
        <label>Additional Email Addr</label>
    </recordTypes>
    <recordTypes>
        <fullName>Customer_Contact</fullName>
        <active>true</active>
        <label>Customer Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Genesys_Employee</fullName>
        <active>true</active>
        <label>Genesys Employee</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case_Email_Subscription_CD__c.object
<CustomObject>
    <description>Allow internal employees and external contacts to subscribe to email notifications for cases under specific Cloud Deployment</description>
    <fields>
        <fullName>Additional_Email_Addr__c</fullName>
        <label>Additional Email Addr</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Cloud_Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cloud Deployment</label>
        <referenceTo>Cloud_Deployment__c</referenceTo>
        <relationshipLabel>Case Email Subscriptions</relationshipLabel>
        <relationshipName>Case_Email_Subscriptions_CD</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>notContain</operation>
                <value>Genesys</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Email Subscriptions CD</relationshipLabel>
        <relationshipName>Case_Email_Subscriptions_CD</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genesys_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genesys Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notContain</operation>
                <value>Portal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Email_Subscriptions_CD</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <label>Subscription Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                    <default>true</default>
                    <label>Internal</label>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Email Subscription CD</label>
    <nameField>
        <displayFormat>CDS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Email Subscriptions CD</pluralLabel>
    <recordTypes>
        <fullName>Additional_Email_Addr</fullName>
        <active>true</active>
        <label>Additional Email Addr</label>
    </recordTypes>
    <recordTypes>
        <fullName>Customer_Contact</fullName>
        <active>true</active>
        <label>Customer Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Genesys_Employee</fullName>
        <active>true</active>
        <label>Genesys Employee</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cloud_Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Downstream Impact: CM and Cloud Billing
Department Owner: CM
Help Text: Used to reference the Account for this Cloud Deployment</description>
        <inlineHelpText>Used to reference the Account for this Cloud Deployment</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cloud Deployments (Account)</relationshipLabel>
        <relationshipName>Account_Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Care_Level__c</fullName>
        <label>Support Package</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PureEngage Standard</fullName>
                </value>
                <value>
                    <fullName>PureConnect Standard</fullName>
                </value>
                <value>
                    <fullName>PureCloud Standard</fullName>
                </value>
                <value>
                    <fullName>PureCloud Bronze</fullName>
                </value>
                <value>
                    <fullName>PureCloud Silver</fullName>
                </value>
                <value>
                    <fullName>PureCloud Gold</fullName>
                </value>
                <value>
                    <fullName>PureConnect Legacy</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>PureSuccess PEngage</fullName>
                </value>
                <value>
                    <fullName>PureSuccess PConnect</fullName>
                </value>
                <value>
                    <fullName>Care for Cloud</fullName>
                </value>
                <value>
                    <fullName>Business Care for Cloud</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cloud_Platform__c</fullName>
        <label>Cloud Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PureEngage Cloud</fullName>
                </value>
                <value>
                    <fullName>PureConnect Cloud</fullName>
                </value>
                <value>
                    <fullName>PureCloud</fullName>
                </value>
                <value>
                    <fullName>Outbound Engagement</fullName>
                </value>
                <value>
                    <fullName>Premier Edition</fullName>
                </value>
                <value>
                    <fullName>SpeechStorm</fullName>
                </value>
                <value>
                    <fullName>PureEngage Subscription</fullName>
                </value>
                <value>
                    <fullName>PureConnect Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Same as Account in case of direct relationship.</inlineHelpText>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cloud Deployments (Sold To Account)</relationshipLabel>
        <relationshipName>Cloud_Deployments_ST</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Status__c</fullName>
        <label>Support Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Billing Only</fullName>
                </value>
                <value>
                    <fullName>Order Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cloud Deployment</label>
    <nameField>
        <label>Cloud Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cloud Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Contact__c.object
<CustomObject>
    <description>This custom object will be used to replace the customer distribution list, within Salesforce.</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>This field will show the case to which this customer contact belongs to</description>
        <inlineHelpText>This field will show the case to which this customer contact belongs to</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Customer Contacts</relationshipLabel>
        <relationshipName>Customer_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CaseMgmtEmailingService_Test.cls
@isTest
public class CaseMgmtEmailingService_Test {
	
   public static EmailTemplate et;
   public static Account acct;
   public static Case trigCase;
   public static List<Contact> testContacts;
   public static Map<String, Id> caseSubRecTypes = new  Map<String, Id>();
   public static Map<String, Id> cldSubRecTypes = new  Map<String, Id>();
   public static Map<String, Id> boaSubRecTypes = new  Map<String, Id>();
	
   public static void setupdata() {		
		et = new EmailTemplate();  
		et.isActive = true;  
		et.Name = 'testTemplate';  
		et.DeveloperName = 'testTemplate' + System.now().getTime();  
		et.TemplateType = 'text';  
		et.FolderId = UserInfo.getUserId();  
		et.Body = ''; 		
		insert et;  
		
		acct = TestUtil.createAccounts(1, true)[0];	   
	    testContacts = TestUtil.createContacts(1, acct, true);  
	     testContacts[0].Alternate_Email__c = 'tst@tst.com';
	    update  testContacts[0];
	                		
		for(RecordType tp : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Case_Email_Subscription__c'])
		    caseSubRecTypes.put(tp.DeveloperName, tp.Id);
				
		for(RecordType tp : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Case_Email_Subscription_CD__c'])
		    cldSubRecTypes.put(tp.DeveloperName, tp.Id);
		    
		for(RecordType tp : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Case_Email_Subscription_BOA__c'])
		    boaSubRecTypes.put(tp.DeveloperName, tp.Id);
		
	}
		
	static testMethod void emtst1() {
		
		User runasuser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (runasuser) {
        	Util.Bypass_Trigger_Chk = true; 
		
			setupdata(); 
	 
	        List<RecordType> rectp = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SobjectType = 'Case' AND DeveloperName = 'Genesys_Admin_Case'];
	        	                
	        Case cs = new Case(status='Awaiting Info',subject='test', priority = '3-Medium', ContactId = testContacts[0].Id,                      
	                           recordtypeid = rectp[0].id);                        
	        insert cs;
	       
            
	        Case_Email_Subscription__c cssub1 = new Case_Email_Subscription__c( Case__c = cs.Id, Subscription_Type__c='Internal', 
	                                          Genesys_Employee__c = UserInfo.getUserId(), RecordTypeId = caseSubRecTypes.get('Genesys_Employee') );
	        insert cssub1;
	        
	        Case_Email_Subscription__c cssub2 = new Case_Email_Subscription__c( Case__c = cs.Id, Subscription_Type__c='External', 
	                                        Customer_Contact__c = testContacts[0].Id, RecordTypeId = caseSubRecTypes.get('Customer_Contact') );
	        insert cssub2;
	       
	        Case_Email_Subscription__c cssub3 = new Case_Email_Subscription__c( Case__c = cs.Id, Subscription_Type__c='External', 
	                                        Additional_Email_Addr__c = 'ts@tst.com', RecordTypeId = caseSubRecTypes.get('Additional_Email_Addr') );
	        insert cssub3;
			
			CaseMgmtEmailingService.EmailRequest req = new CaseMgmtEmailingService.EmailRequest();		
			req.sourceId = cs.Id;
			req.sourceObject = 'Case';
			req.templateName = et.DeveloperName;
			req.sendToContact = true;
			req.sendToOwner = false;
			
			Test.startTest();
			CaseMgmtEmailingService.emailNotificationRequest(new List<CaseMgmtEmailingService.EmailRequest>{req});
			Test.stopTest();
		
        }
	}
	
	static testMethod void emtstCD() {
		
		User runasuser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (runasuser) {
        	Util.Bypass_Trigger_Chk = true; 
		
			setupdata();
					
	        List<RecordType> rectp = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SobjectType = 'Case' AND DeveloperName = 'Genesys_Cloud_Incident'];
	        
	        Cloud_Deployment__c depl = new Cloud_Deployment__c();
			depl.Support_Status__c = 'Active';
		   	depl.Cloud_Platform__c = 'Premier Edition';
		   	depl.Account__c = acct.id;
		   	depl.Sold_To_Account__c = acct.id;
		   	depl.Care_Level__c = 'Care for Cloud';
	        insert depl;   
	           
	        Case cs = new Case(status='Awaiting Info',subject='test', priority = '3-Medium', ContactId = testContacts[0].Id,                      
	                           Cloud_Deployment__c = depl.Id, recordtypeid = rectp[0].id);                        
	        insert cs;
	       
            
	        Case_Email_Subscription_CD__c cssub1 = new Case_Email_Subscription_CD__c( Cloud_Deployment__c = depl.Id, Subscription_Type__c='Internal', 
	                                          Genesys_Employee__c = UserInfo.getUserId(), RecordTypeId = cldSubRecTypes.get('Genesys_Employee') );
	        insert cssub1;
	        
	        Case_Email_Subscription_CD__c cssub2 = new Case_Email_Subscription_CD__c( Cloud_Deployment__c = depl.Id, Subscription_Type__c='External', 
	                                        Customer_Contact__c = testContacts[0].Id, RecordTypeId = cldSubRecTypes.get('Customer_Contact') );
	        insert cssub2;
	       
	        Case_Email_Subscription_CD__c cssub3 = new Case_Email_Subscription_CD__c( Cloud_Deployment__c = depl.Id, Subscription_Type__c='External', 
	                                         	Additional_Email_Addr__c = 'ts@tst.com', RecordTypeId = cldSubRecTypes.get('Additional_Email_Addr') );
	        insert cssub3;
			
			CaseMgmtEmailingService.EmailRequest req = new CaseMgmtEmailingService.EmailRequest();		
			req.sourceId = cs.Id;
			req.sourceObject = 'Case';
			req.templateName = et.DeveloperName;
			req.sendToContact = true;
			req.sendToOwner = false;
			
			Test.startTest();
			CaseMgmtEmailingService.emailNotificationRequest(new List<CaseMgmtEmailingService.EmailRequest>{req});
			Test.stopTest();
		
        }
	}
	
	static testMethod void emtstBOA() {
		
		User runasuser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (runasuser) {
        	Util.Bypass_Trigger_Chk = true; 
		
			setupdata();
					
	        List<RecordType> rectp = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SobjectType = 'Case' AND DeveloperName = 'Genesys_Admin_Case'];

	        Back_Office_Account__c boa = new Back_Office_Account__c();
			boa.Sold_To_Account__c = acct.Id;
			boa.End_User_Account__c = acct.Id;
			insert boa;
	            
	        Case cs = new Case(status='Awaiting Info',subject='test', priority = '3-Medium', ContactId = testContacts[0].Id,                      
	                           Back_Office_Account__c= boa.Id, recordtypeid = rectp[0].id);                        
	        insert cs;
	       
            
	        Case_Email_Subscription_BOA__c cssub1 = new  Case_Email_Subscription_BOA__c( Back_Office_Account__c= boa.Id, Subscription_Type__c='Internal', 
	                                          Genesys_Employee__c = UserInfo.getUserId(), RecordTypeId = boaSubRecTypes.get('Genesys_Employee') );
	        insert cssub1;
	        
	         Case_Email_Subscription_BOA__c cssub2 = new  Case_Email_Subscription_BOA__c( Back_Office_Account__c= boa.Id, Subscription_Type__c='External', 
	                                        Customer_Contact__c = testContacts[0].Id, RecordTypeId = boaSubRecTypes.get('Customer_Contact') );
	        insert cssub2;
	       
	         Case_Email_Subscription_BOA__c cssub3 = new  Case_Email_Subscription_BOA__c( Back_Office_Account__c= boa.Id, Subscription_Type__c='External', 
	                                         	Additional_Email_Addr__c = 'ts@tst.com', RecordTypeId = boaSubRecTypes.get('Additional_Email_Addr') );
	        insert cssub3;
			
			CaseMgmtEmailingService.EmailRequest req = new CaseMgmtEmailingService.EmailRequest();		
			req.sourceId = cs.Id;
			req.sourceObject = 'Case';
			req.templateName = et.DeveloperName;
			req.sendToContact = true;
			req.sendToOwner = false;
			
			Test.startTest();
			CaseMgmtEmailingService.emailNotificationRequest(new List<CaseMgmtEmailingService.EmailRequest>{req});
			Test.stopTest();
		
        }
	}
	
	static testMethod void emtstPost() {
		User runasuser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
		System.runAs (runasuser) {
        	Util.Bypass_Trigger_Chk = true; 
        	
        	setupdata();
        	
            List<RecordType> rectp = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SobjectType = 'Case' AND DeveloperName = 'Genesys_Admin_Case'];
         
            Case cs = new Case(status='Awaiting Info',subject='test', priority = '3-Medium', ContactId = testContacts[0].Id,                      
	                           recordtypeid = rectp[0].id);                        
	        insert cs;

	        FeedItem fdi = new FeedItem();
		      fdi.Body = 'caseupdate';
		      fdi.ParentId = cs.Id;
		      fdi.Visibility = 'AllUsers';
		      fdi.Title = 'Update from Customer';
		      insert fdi;
		    
		    CaseMgmtEmailingService.EmailRequest req = new CaseMgmtEmailingService.EmailRequest();		
			req.sourceId = fdi.Id;
			req.sourceObject = 'FeedItemLog';
			req.templateName = et.DeveloperName;
			req.sendToContact = false;
			req.sendToOwner = true;

		    Test.startTest();
		 		CaseMgmtEmailingService.getCaseIdByFeedPostId(fdi.Id);
		 		CaseMgmtEmailingService.emailNotificationRequest(new List<CaseMgmtEmailingService.EmailRequest>{req});
			Test.stopTest();  
		      		
		}
		
	}
	
	static testMethod void testTrigger_EmailMessageToCase() {
		
     User runasuser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (runasuser) {
        	
		Util.Bypass_Trigger_Chk = true; 
		setupdata();
		
		List<RecordType> rectp = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SobjectType = 'Case' AND DeveloperName = 'Genesys_Admin_Case'];
         
        trigCase = new Case(status='Awaiting Info',subject='test', priority = '3-Medium', ContactId = testContacts[0].Id,                      
	                           recordtypeid = rectp[0].id);                        
	    insert trigCase;
		
        }
        
		Util.Bypass_Trigger_Chk = false;
		EmailMessage em = new EmailMessage (Incoming = true, ParentId = trigCase.Id, FromAddress = 'tst@tst.com', TextBody='body');
		insert em;
		
        
	}
    
}