objects/Back_Office_Account__c.object
<CustomObject>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts</relationshipLabel>
        <relationshipName>Back_Office_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts (Sold To Account)</relationshipLabel>
        <relationshipName>Back_Office_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Back Office Account</label>
    <nameField>
        <displayFormat>BOA-{000000}</displayFormat>
        <label>Back Office Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Back Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Bypass_Triggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Bypass flags for triggers</description>
    <label>Bypass Triggers</label>
</CustomObject>

objects/Cloud_Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Downstream Impact: CM and Cloud Billing
Department Owner: CM
Help Text: Used to reference the Account for this Cloud Deployment</description>
        <inlineHelpText>Used to reference the Account for this Cloud Deployment</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cloud Deployments (Account)</relationshipLabel>
        <relationshipName>Account_Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cloud_Offering__c</fullName>
        <label>Cloud Offering OBSOLETE</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business/Enterprise Edition</fullName>
                </value>
                <value>
                    <fullName>Enterprise Edition-Echopass</fullName>
                </value>
                <value>
                    <fullName>Outbound Engagement</fullName>
                </value>
                <value>
                    <fullName>Premier Edition</fullName>
                </value>
                <value>
                    <fullName>PureConnect Cloud</fullName>
                    <label>PureConnect</label>
                </value>
                <value>
                    <fullName>Self Service</fullName>
                </value>
                <value>
                    <fullName>Social Analytics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Same as Account in case of direct relationship.</inlineHelpText>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cloud Deployments (Sold To Account)</relationshipLabel>
        <relationshipName>Cloud_Deployments_ST</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Implementation Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deployment</fullName>
                </value>
                <value>
                    <fullName>UAT</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                    <default>true</default>
                    <label>Production</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Status__c</fullName>
        <label>Support Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Billing Only</fullName>
                </value>
                <value>
                    <fullName>Order Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cloud Deployment</label>
    <nameField>
        <label>Cloud Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cloud Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Global_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

objects/Product_Version__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipLabel>Product Versions</relationshipLabel>
        <relationshipName>Product_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Version</label>
    <nameField>
        <label>Product Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Support_Access__c.object
<CustomObject>
    <fields>
        <fullName>Back_Office_Account__c</fullName>
        <label>Back Office Account</label>
        <referenceTo>Back_Office_Account__c</referenceTo>
        <relationshipName>Support_Access</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>eService_Access</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>eService_Access</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SR_Access_Level__c</fullName>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
                <value>
                    <fullName>Read Only</fullName>
                </value>
                <value>
                    <fullName>Basic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>eService_Access1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Access Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Support Access Premise</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Support Access ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Access Premise</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Support_Access_Cloud__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
                <value>
                    <fullName>Read Only</fullName>
                </value>
                <value>
                    <fullName>Basic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Access_Status__c</fullName>
        <label>Access Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cloud_Deployment__c</fullName>
        <label>Cloud Deployment</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cloud_Deployment__c.Support_Status__c</field>
                <operation>notEqual</operation>
                <value>Billing Only, Order Processing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cloud_Deployment__c</referenceTo>
        <relationshipLabel>Support Access Cloud</relationshipLabel>
        <relationshipName>Support_Access_Cloud</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cloud_Offering__c</fullName>
        <formula>TEXT(Cloud_Deployment__r.Cloud_Offering__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cloud Offering</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Support Access Cloud</relationshipLabel>
        <relationshipName>Support_Access_Cloud</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Support Access Cloud</label>
    <nameField>
        <displayFormat>SACloud-{000000}</displayFormat>
        <label>SA Cloud ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Access Cloud</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Support_Product__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipLabel>Support Products</relationshipLabel>
        <relationshipName>Support_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Version</label>
        <referenceTo>Product_Version__c</referenceTo>
        <relationshipLabel>Support Products</relationshipLabel>
        <relationshipName>Support_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Support Product</label>
    <nameField>
        <label>Support Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateCaseProductControllerNew_Test.cls
/*
	Naresh Kumar	06/15/2013
	Test class for the main controller class UpdateCaseProductControllerNew.
*/
//@isTest(seeAllData = true)
@isTest
private class UpdateCaseProductControllerNew_Test {

	 public static  User testUser;
     public static Contact testContact;
     public static Account accnt;
     public static Product_Version__c testPV;
     public static List<Account> testAccounts;
     public static List<Support_Product__c> testParentSupportProducts;
     public static List<Support_Product__c> testSupportProducts;
     public static Cloud_Deployment__c cldDep;
     
     public static void setTstData() {
     	    TestUtil.setConfigValues();
         List<User> runAsUser = TestUtil.createUsers(1, true);
        runAsUser[0].Bypass_Triggers__c = true;
        runAsUser[0].BypassWorkflows__c = true;
        runAsUser[0].BypassValidationRules__c = true;
        update runAsUser[0];
       
        System.runAs(runAsUser[0]) {
           TestUtil.setCaseSupportTypesSettings();
        }
     	
     	Util.Bypass_Trigger_Chk = true;
	    Profile prof = [SELECT id FROM Profile WHERE Name = 'Genesys Portal End User' LIMIT 1];    	
	    accnt = TestUtil.createAccounts(1, true)[0];
	    testContact = TestUtil.createContacts(1, accnt, true)[0];
	    	
	    testUser = TestCommon.createUser('testU', 'testUser132@test132.com.test', 'Test', 'Test', prof.id, false);    	
		testUser.ContactId = testContact.id;
		insert testUser;

	    cldDep = new Cloud_Deployment__c(Name = 'Test2', Account__c = accnt.id, Status__c = 'Production',
	                                          Cloud_Offering__c = 'Prod', Support_Status__c = 'Active', Sold_To_Account__c = accnt.id);
	    insert cldDep;
	        
        Support_Access_Cloud__c sa = new Support_Access_Cloud__c (Contact__c = testContact.id, Cloud_Deployment__c = cldDep.Id,
                                          Access_Status__c = 'Active', Access_Level__c = 'Read/Write');
        insert sa;
         
        Back_Office_Account__c boa = new Back_Office_Account__c();
			boa.Sold_To_Account__c = accnt.Id;
			boa.End_User_Account__c = accnt.Id;
			insert boa;
			
	    List<Support_Access__c> saLst = new List<Support_Access__c>();
		Support_Access__c pr = new Support_Access__c(Back_Office_Account__c = boa.Id,
			                                             Contact__c = testContact.id,
			                                 Status__c = 'Active', SR_Access_Level__c = 'Read/Write');
			                                             
		insert pr;   

    	testParentSupportProducts = TestUtil.createSupportProducts(3, true);  
    	
    	testParentSupportProducts[2].Product_Type__c = 'Product Line';
    	testParentSupportProducts[2].Name = 'Cloud';
    	update testParentSupportProducts[2];
    	 	
    	testSupportProducts = TestUtil.createSupportProducts(7, false);
    	testSupportProducts[0].Product_Type__c = 'Component';
    	testSupportProducts[0].Parent_Product__c = testParentSupportProducts[0].id;
    	testSupportProducts[1].Product_Type__c = 'Component';
    	testSupportProducts[1].Parent_Product__c = testParentSupportProducts[1].id;    
    	testSupportProducts[2].Product_Type__c = 'Product Line';
    	testSupportProducts[3].Product_Type__c = 'Product Line';    	
    	testSupportProducts[4].Product_Type__c = 'Product';
    	testSupportProducts[4].Parent_Product__c = testParentSupportProducts[0].id;
    	testSupportProducts[5].Product_Type__c = 'Product';
    	testSupportProducts[5].Parent_Product__c = testParentSupportProducts[1].id;
    
    	testSupportProducts[6].Product_Type__c = 'Product';
    	testSupportProducts[6].Name = 'Cloud Products';
    	testSupportProducts[6].Parent_Product__c = testParentSupportProducts[2].id;
    	
    	insert testSupportProducts;
       	  	
    	testPV = TestUtil.createProductVerion(1, true, testSupportProducts[0])[0];
    	testAccounts = TestUtil.createAccounts(2, true);
    	
     }
     
    static testMethod void tstFR() 
    {
    	setTstData();
    	
    	Case testCase1 = new Case();
    	String rtype1 = Global_Setting__c.getInstance('Genesys_Feature_Request_Case').ID__c;
    	testCase1.RecordTypeId= Global_Setting__c.getInstance('Genesys_Feature_Request_Case').ID__c;
    	testCase1.Component__c = testSupportProducts[0].id;    	
    	testCase1.End_User_Account__c = testAccounts[0].id;
    	testCase1.Sold_To_Account__c = testAccounts[1].id;    		
    	testCase1.Support_Product__c = testSupportProducts[4].id;
    	testCase1.Product_Line__c = testParentSupportProducts[0].id;
    	testCase1.Product_Version__c = testPV.id;
    	testCase1.ContactId = testContact.id;
    	testCase1.Feature_Description__c = 'test description';
    	insert testCase1;
    	
    	Apexpages.currentPage().getParameters().put('page','2');
    	Apexpages.currentPage().getParameters().put('RecordType', rtype1);
    	Apexpages.currentPage().getParameters().put('cont', testContact.id);
    	Apexpages.currentPage().getParameters().put('eu', testAccounts[0].id);
    	Apexpages.currentPage().getParameters().put('sto', testAccounts[1].id);
    	Apexpages.currentPage().getParameters().put('pl', testParentSupportProducts[0].id);
    	Apexpages.currentPage().getParameters().put('cm', testSupportProducts[0].id);
    	Apexpages.currentPage().getParameters().put('pv', testPV.id);
    	Apexpages.currentPage().getParameters().put('sp', testSupportProducts[4].id);
    	ApexPages.currentPage().getParameters().put('isSaas','true');
    	Apexpages.currentPage().getParameters().put('conid', testContact.id);
   		
   	    Test.startTest();
 
    	ApexPages.StandardController stdController = new ApexPages.StandardController(testCase1);
        UpdateCaseProductControllerNew objExtension = new UpdateCaseProductControllerNew(stdController);    
        objExtension.populateProdLines();
        objExtension.isProductNotFound = true;
    
        objExtension.populatesProds();
        objExtension.populateMajorVersion();
        objExtension.populatesComponents();
        objExtension.populatesProductVersions();
        objExtension.setVersion();
        objExtension.next();
        
        objExtension.lazyLoad();
        objExtension.save();
        objExtension.saveCase();
        objExtension.cancel();
   
        Test.stopTest();
   }
   
   static testMethod void adminCase() {
    	
   	    setTstData();
   	    
    	Case testCase1 = new Case();
    	String rtype1 = Global_Setting__c.getInstance('Genesys_Admin_Case').ID__c;
    	testCase1.RecordTypeId= Global_Setting__c.getInstance('Genesys_Admin_Case').ID__c;
    	testCase1.Component__c = testSupportProducts[0].id;    	
    	testCase1.End_User_Account__c = testAccounts[0].id;
    	testCase1.Sold_To_Account__c = testAccounts[1].id;    		
    	testCase1.Support_Product__c = testSupportProducts[4].id;
    	testCase1.Product_Line__c = testParentSupportProducts[0].id;
    	testCase1.Product_Version__c = testPV.id;
    	testCase1.ContactId = testContact.id;
    	testCase1.Feature_Description__c = 'test description';
   // 	insert testCase1;
    	    	
    	Apexpages.currentPage().getParameters().put('page','2');
    	Apexpages.currentPage().getParameters().put('RecordType', rtype1);
    	Apexpages.currentPage().getParameters().put('cont', testContact.id);
    	Apexpages.currentPage().getParameters().put('eu', testAccounts[0].id);
    	Apexpages.currentPage().getParameters().put('sto', testAccounts[1].id);
    	Apexpages.currentPage().getParameters().put('pl', testParentSupportProducts[0].id);
    	Apexpages.currentPage().getParameters().put('cm', testSupportProducts[0].id);
    	ApexPages.currentPage().getParameters().put('ct', 'Cloud');
    	Apexpages.currentPage().getParameters().put('conid', testContact.id);
    	ApexPages.currentPage().getParameters().put('dpl', cldDep.Id);
   	
   	    Test.startTest();
   	    
   	    System.runAs(testUser) {
	    	ApexPages.StandardController stdController = new ApexPages.StandardController(testCase1);
	        UpdateCaseProductControllerNew objExtension = new UpdateCaseProductControllerNew(stdController); 
	        objExtension.isPortalCloudUser = true;  
            objExtension.setContact();
   
	        objExtension.populateProdLines();
	        objExtension.isProductNotFound = true;
	   
	        objExtension.populatesProds();
	        objExtension.populateMajorVersion();
	        objExtension.populatesComponents();
	        objExtension.populatesProductVersions();
	        objExtension.lazyLoad();
	        objExtension.next();
	        objExtension.saveCase();
   	    }
        Test.stopTest();     	
   }
   
    static testMethod void tstOutage() 
    {
    	setTstData();
    	
    	Case testCase1 = new Case();
    	String rtype1 = Global_Setting__c.getInstance('Genesys_Outage').ID__c;
    	testCase1.RecordTypeId= Global_Setting__c.getInstance('Genesys_Outage').ID__c;
    	testCase1.Component__c = testSupportProducts[0].id;    	
    	testCase1.End_User_Account__c = testAccounts[0].id;
    	testCase1.Sold_To_Account__c = testAccounts[1].id;    		
    	testCase1.Support_Product__c = testSupportProducts[4].id;
    	testCase1.Product_Line__c = testParentSupportProducts[0].id;
    	testCase1.Product_Version__c = testPV.id;
    	testCase1.ContactId = testContact.id;
    	testCase1.Feature_Description__c = 'test description';
    	insert testCase1;
    	
    	Apexpages.currentPage().getParameters().put('page','2');
    	Apexpages.currentPage().getParameters().put('RecordType', rtype1);
    	Apexpages.currentPage().getParameters().put('cont', testContact.id);
    	Apexpages.currentPage().getParameters().put('eu', testAccounts[0].id);
    	Apexpages.currentPage().getParameters().put('sto', testAccounts[1].id);
    	Apexpages.currentPage().getParameters().put('pl', testParentSupportProducts[0].id);
    	Apexpages.currentPage().getParameters().put('cm', testSupportProducts[0].id);
    	Apexpages.currentPage().getParameters().put('pv', testPV.id);
    	Apexpages.currentPage().getParameters().put('sp', testSupportProducts[4].id);
    	ApexPages.currentPage().getParameters().put('isSaas','true');
    	Apexpages.currentPage().getParameters().put('conid', testContact.id);
   		
   	    Test.startTest();
 
    	ApexPages.StandardController stdController = new ApexPages.StandardController(testCase1);
        UpdateCaseProductControllerNew objExtension = new UpdateCaseProductControllerNew(stdController);  
  
        objExtension.populateProdLines();
        objExtension.populatesProds();
        objExtension.populateMajorVersion();
        objExtension.populatesComponents();
        objExtension.populatesProductVersions();
        objExtension.setVersion();
        objExtension.next();
        
        objExtension.lazyLoad();
        objExtension.save();
        objExtension.caseType = 'Genesys_Outage';  
        objExtension.goToFRCasePage();
        objExtension.cancel();
   
        Test.stopTest();
   }
   
    static testMethod void tstIntCloud() 
    {
    	setTstData();
    	
    	Case testCase1 = new Case();
    	String rtype1 = Global_Setting__c.getInstance('Genesys_Product_Case').ID__c;
    	testCase1.RecordTypeId= Global_Setting__c.getInstance('Genesys_Product_Case').ID__c;
    	testCase1.Component__c = testSupportProducts[0].id;    	
    	testCase1.End_User_Account__c = testAccounts[0].id;
    	testCase1.Sold_To_Account__c = testAccounts[1].id;  
    	testCase1.Cloud_Deployment__c =  cldDep.Id;		
    	testCase1.Support_Product__c = testSupportProducts[4].id;
    	testCase1.Product_Line__c = testParentSupportProducts[0].id;
    	testCase1.ContactId = testContact.id;

    	insert testCase1;
    	
    	Apexpages.currentPage().getParameters().put('RecordType', rtype1);
    	Apexpages.currentPage().getParameters().put('cont', testContact.id);
    	Apexpages.currentPage().getParameters().put('eu', testAccounts[0].id);
    	Apexpages.currentPage().getParameters().put('sto', testAccounts[1].id);
     	Apexpages.currentPage().getParameters().put('conid', testContact.id);
   		
   	    Test.startTest();
 
    	ApexPages.StandardController stdController = new ApexPages.StandardController(testCase1);
        UpdateCaseProductControllerNew objExtension = new UpdateCaseProductControllerNew(stdController);  
  
        objExtension.saveNewCloudCaseInternal();
        objExtension.cancel();
   
        Test.stopTest(); 
   }
   
 
}