objects/Back_Office_Account__c.object
<CustomObject>
    <fields>
        <fullName>Access_Approval__c</fullName>
        <formula>IF (EU_Approval__c || ST_Approval__c, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Access Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts</relationshipLabel>
        <relationshipName>Back_Office_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts (Sold To Account)</relationshipLabel>
        <relationshipName>Back_Office_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Back Office Account</label>
    <nameField>
        <displayFormat>BOA-{000000}</displayFormat>
        <label>Back Office Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Back Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cloud_Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Approval__c</fullName>
        <formula>IF( NOT(ISBLANK( Access_Instructions_Approval__c ) &amp;&amp; ISBLANK(EU_Access_Approval__c) &amp;&amp; ISBLANK(ST_Access_Approval__c)), true, false )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Access Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Downstream Impact: CM and Cloud Billing
Department Owner: CM
Help Text: Used to reference the Account for this Cloud Deployment</description>
        <inlineHelpText>Used to reference the Account for this Cloud Deployment</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cloud Deployments (Account)</relationshipLabel>
        <relationshipName>Account_Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cloud_Platform__c</fullName>
        <label>Cloud Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PureEngage Cloud</fullName>
                </value>
                <value>
                    <fullName>PureConnect Cloud</fullName>
                </value>
                <value>
                    <fullName>PureCloud</fullName>
                </value>
                <value>
                    <fullName>Outbound Engagement</fullName>
                </value>
                <value>
                    <fullName>Premier Edition</fullName>
                </value>
                <value>
                    <fullName>SpeechStorm</fullName>
                </value>
                <value>
                    <fullName>PureEngage Subscription</fullName>
                </value>
                <value>
                    <fullName>PureConnect Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Same as Account in case of direct relationship.</inlineHelpText>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cloud Deployments (Sold To Account)</relationshipLabel>
        <relationshipName>Cloud_Deployments_ST</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Implementation Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deployment</fullName>
                </value>
                <value>
                    <fullName>UAT</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                    <default>true</default>
                    <label>Production</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cloud Deployment</label>
    <nameField>
        <label>Cloud Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cloud Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Support_Access__c.object
<CustomObject>
    <fields>
        <fullName>BOA_Platform__c</fullName>
        <formula>TEXT(Back_Office_Account__r.Platform__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BOA Platform</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOA_Support_Package__c</fullName>
        <formula>TEXT(Back_Office_Account__r.Support_Package__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BOA Support Package</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Back_Office_Account__c</fullName>
        <label>Back Office Account</label>
        <referenceTo>Back_Office_Account__c</referenceTo>
        <relationshipName>Support_Access</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>eService_Access</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Contact__r.Country__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>eService_Access</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SR_Access_Level__c</fullName>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
                <value>
                    <fullName>Read Only</fullName>
                </value>
                <value>
                    <fullName>Basic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Contract_Status__c</fullName>
        <description>Old value: TEXT( Service_Contract__r.Agreement_Status__c )</description>
        <formula>TEXT(Back_Office_Account__r.Contract_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BOA Contract Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>eService_Access1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Access Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Support Access Premise</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Support Access ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Access Premise</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Support_Access_Cloud__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
                <value>
                    <fullName>Read Only</fullName>
                </value>
                <value>
                    <fullName>Basic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Access_Status__c</fullName>
        <label>Access Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CD_Platform__c</fullName>
        <formula>CASE( Cloud_Deployment__r.Cloud_Platform__c,
&quot;PureCloud&quot;, &quot;PureCloud&quot;,
&quot;PureConnect Cloud&quot;, &quot;PureConnect&quot;,
&quot;PureEngage&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CD Platform</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cloud_Deployment__c</fullName>
        <label>Cloud Deployment</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cloud_Deployment__c.Support_Status__c</field>
                <operation>notEqual</operation>
                <value>Billing Only, Order Processing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cloud_Deployment__c</referenceTo>
        <relationshipLabel>Support Access Cloud</relationshipLabel>
        <relationshipName>Support_Access_Cloud</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Support Access Cloud</relationshipLabel>
        <relationshipName>Support_Access_Cloud</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deployment_Support_Status__c</fullName>
        <formula>TEXT(Cloud_Deployment__r.Support_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deployment Support Status</label>
        <type>Text</type>
    </fields>
    <label>Support Access Cloud</label>
    <nameField>
        <displayFormat>SACloud-{000000}</displayFormat>
        <label>SA Cloud ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Access Cloud</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CustomLookupController.cls
public class CustomLookupController {
    public string searchStr {
        get;
        set {
            searchStr = value;
            if (null != value) {
                searchStr = value.trim();
            }
        }
    }
    public string obj {get;set;}
    private string accType;
    private string contactId;
    private string endUserId;
    private string soldToId;  
    private String deplId;  
    private String boaId; 
    private String portalFilter;
    private String portalReqst;
    public List<Support_Access__c> supportAccessRecords {get;set;}
    public List<Support_Access_Cloud__c> supportCloudAccessRecords {get;set;}  
    public List<Cloud_Deployment__c>  cloudDeployments {get; set;} 
    public List<Contact> contactRecords {get;set;}
    public Boolean contactsOnly {get;set;}
    public Boolean cloudContacts {get; set;}
    public Boolean searchOnlyEmployeeContacts {get;set;}
    public Boolean isPortal {get;set;}  
        
    public CustomLookupController()   {
        List<User> lstUser = [Select IsPortalEnabled From  User Where  Id = :UserInfo.getUserId()];
        isPortal = lstUser[0].IsPortalEnabled;
        searchOnlyEmployeeContacts = false;        
        contactsOnly = false;
        cloudContacts = false;
        if(searchStr == null || searchStr == '')
            searchStr = Apexpages.currentPage().getParameters().get('searchText');
        if(Apexpages.currentPage().getParameters().get('obj') != null)
            obj = Apexpages.currentPage().getParameters().get('obj');
        if(Apexpages.currentPage().getParameters().get('type') != null)
            accType = Apexpages.currentPage().getParameters().get('type');
        if(Apexpages.currentPage().getParameters().get('contactId') != null)
            contactId = Apexpages.currentPage().getParameters().get('contactId');
        if(Apexpages.currentPage().getParameters().get('endUserId') != null)
            endUserId = Apexpages.currentPage().getParameters().get('endUserId');
        if(Apexpages.currentPage().getParameters().get('soldToId') != null)
            soldToId = Apexpages.currentPage().getParameters().get('soldToId');
        if(Apexpages.currentPage().getParameters().get('contactsOnly') != null)
            contactsOnly = true; 
        if(Apexpages.currentPage().getParameters().get('cloudContacts') != null)
            cloudContacts = true;   
        if( Apexpages.currentPage().getParameters().get('dplId') != null)
            deplId = Apexpages.currentPage().getParameters().get('dplId');
        if( Apexpages.currentPage().getParameters().get('boaId') != null)
            boaId = Apexpages.currentPage().getParameters().get('boaId');
        
        portalFilter = Apexpages.currentPage().getParameters().get('fltr');
        portalReqst = Apexpages.currentPage().getParameters().get('rqst');
                         
        System.debug('NKC debug searchStr ['+searchStr+']');
        go();
    }
    
    public void go(){
        if(obj == 'Contact')
            populateContactRecords();  
        else if(obj == 'Account') 
            populateAccountRecords();   
        else if ( obj == 'CloudDepl' ) 
            populateCloudDeplRecords();
    }
    
    private void populateContactRecords(){
        String query;   

        if(searchOnlyEmployeeContacts){
            query = 'SELECT id, Name, Email, Contact_Pin__c FROM Contact WHERE Account.Name = \'Genesys - Employees\' ';
            
            query += ' AND Name LIKE \'%'+ String.escapeSingleQuotes(searchStr) +'%\' '+
                'order by FirstName asc, LastName asc LIMIT 100';
            contactRecords = Database.query(query);
        }
        else if (contactsOnly) {

          query = 'SELECT id, Name, Email, Contact_Pin__c FROM Contact WHERE (AccountId =\''+endUserId+'\' OR AccountId =\''+soldToId+'\')';
          if( String.isNotBlank(searchStr) )
              query += ' AND Name LIKE \'%'+ String.escapeSingleQuotes(searchStr) +'%\' ' +
                'ORDER BY FirstName ASC LIMIT 100';            
            System.debug('NKC debug query ['+query+']');            
            contactRecords = Database.query(query);            
        }
        else if (cloudContacts) {
        
          query = 'SELECT id, Name, Email, Contact_Pin__c FROM Contact WHERE ';
          query += ' ID IN (SELECT Contact__c FROM Support_Access_Cloud__c WHERE Access_Status__c = \'Active\' AND Access_Level__c = \'Read/Write\'';
          
          if ( portalFilter != null && portalFilter.equals('cnct') )
               query += ' AND CD_Platform__c LIKE \'PureConnect%\'';               
          else if ( portalFilter != null && portalFilter.equals('pcld') )
               query += ' AND CD_Platform__c LIKE \'PureCloud%\'';
          else if ( portalFilter != null )
               query += ' AND CD_Platform__c LIKE \'PureEngage%\'';
          
          
          if ( String.isNotBlank(deplId) )
             query += ' AND Cloud_Deployment__c =\'' + deplId + '\')';
          else
             query += ')';
             
          if ( String.isNotBlank(searchStr) )  
              query += ' AND Name LIKE \'%'+ String.escapeSingleQuotes(searchStr) +'%\' ';
           
            query += ' ORDER BY Name asc LIMIT 100';   
 
 System.debug('### q= ' + query);
                              
            contactRecords = Database.query(query);        
        }
        else {
                
            query = 'SELECT Contact__c, Contact__r.Name, Contact__r.Email, Contact__r.Contact_Pin__c FROM Support_Access__c WHERE Status__c = \'Active\' ' +
                    ' AND SR_Access_Level__c = \'Read/Write\' AND Service_Contract_Status__c = \'Active\'';
                    
          if ( portalFilter != null && portalFilter.equals('cnct') )
               query += ' AND BOA_Platform__c LIKE \'PureConnect%\'';               
          else if ( portalFilter != null && portalFilter.equals('eng') )
               query += ' AND BOA_Platform__c LIKE \'PureEngage%\'';
           else if ( portalFilter != null && portalFilter.equals('mac') )
               query += ' AND BOA_Support_Package__c LIKE \'Managed%\'';
               
            if( String.isNotBlank(endUserId) )
                query += ' AND End_User_Account__c =\''+endUserId+'\'';
            
            if( String.isNotBlank(soldToId) )
                query += ' AND Sold_To_Account__c =\''+soldToId+'\'';
            
            query += ' AND Contact__r.Name LIKE \'%'+ String.escapeSingleQuotes(searchStr) +'%\' ' +
                'order by Contact__r.FirstName asc, Contact__r.LastName asc LIMIT 300';
            
            System.debug('NKC debug query ['+query+']');
            
            supportAccessRecords = Database.query(query);
            Map<Id, Support_Access__c> mapSC = new Map<Id, Support_Access__c>();
            for(Support_Access__c eachSA : supportAccessRecords) 
                mapSC.put(eachSA.Contact__c, eachSA);
            supportAccessRecords = mapSC.values();
            supportAccessRecords.sort();
        }

    }
    
    private void populateAccountRecords() {
      if ( String.isBlank(contactId) && isPortal )
    	   return;
    	
        String query;
        query = 'SELECT End_User_Account__c, End_User_Account__r.Name, End_User_Account__r.City__c, End_User_Account__r.Country__r.Name, ' +
                ' Sold_To_Account__c, Sold_To_Account__r.Name, Sold_To_Account__r.City__c, Sold_To_Account__r.Country__r.Name, BOA_Platform__c, Back_Office_Account__c ' +
                ' FROM Support_Access__c WHERE  SR_Access_Level__c = \'Read/Write\' AND Status__c = \'Active\' AND Service_Contract_Status__c = \'Active\'';
        
        if ( portalFilter != null && portalFilter.equals('cnct') )
               query += ' AND BOA_Platform__c LIKE \'PureConnect%\'';               
          else if ( portalFilter != null && portalFilter.equals('eng') )
               query += ' AND BOA_Platform__c LIKE \'PureEngage%\'';
               
         if ( portalReqst != null && (portalReqst.equals('mac') || portalReqst.equals('dtprv')) )
               query += ' AND BOA_Support_Package__c LIKE \'Managed%\'';
               
        if ( isContactEmployee() == false && String.isNotBlank(contactId) )
            query += ' AND Contact__c =\''+contactId+'\'';
        
        if( String.isNotBlank(soldToId) )
            query += ' AND Sold_To_Account__c = \''+ soldToId +'\'';   
 
        query += ' AND End_User_Account__r.Name LIKE \'%'+ String.escapeSingleQuotes(searchStr) +'%\' ' +
            'order by End_User_Account__r.Name asc LIMIT 300';
        
        System.debug('NKC debug query ['+query+']');    
        
        supportAccessRecords = Database.query(query);
        Map<String, Support_Access__c> mapSC = new Map<String, Support_Access__c>();
        for(Support_Access__c eachSA : supportAccessRecords) 
            mapSC.put(eachSA.End_User_Account__c + '-' + eachSA.Sold_To_Account__c + '-' + eachSA.BOA_Platform__c, eachSA);
            
        supportAccessRecords = mapSC.values();
        supportAccessRecords.sort();
    }
    
   private void populateCloudDeplRecords() {
   	     if ( String.isBlank(contactId) && isPortal )
    	   return;
    	   
           String query;
           
           query = 'SELECT Id, Name, Cloud_Platform__c, Status__c, Account__r.Name, Account__c, Sold_To_Account__c, Access_Approval__c ' +               
               'FROM Cloud_Deployment__c WHERE Name LIKE \'%'+ String.escapeSingleQuotes(searchStr) +'%\' ' +               
                'AND ID IN ' +
               '(SELECT Cloud_Deployment__c FROM Support_Access_Cloud__c ' +
                 'WHERE Access_Level__c = \'Read/Write\' AND Access_Status__c = \'Active\' AND Deployment_Support_Status__c = \'Active\' ';
  
         if ( portalFilter != null && portalFilter.equals('cnct') )
               query += ' AND CD_Platform__c LIKE \'PureConnect%\'';               
          else if ( portalFilter != null && portalFilter.equals('pcld') )
               query += ' AND CD_Platform__c LIKE \'PureCloud%\'';
          else if ( portalFilter != null )
               query += ' AND CD_Platform__c LIKE \'PureEngage%\'';
                  
        if ( isContactEmployee() == false && String.isNotBlank(contactId) )
            query += ' AND Contact__c =\''+ contactId +'\'';
        
        query += ') ORDER BY Name LIMIT 300';
  
 System.debug('Q ' + query) ;
       
            cloudDeployments = Database.query(query);
   }
   
   private Boolean isContactEmployee() {
           Boolean isContactEmployee = false;
        List<Contact> conts = [SELECT Account.Name FROM Contact WHERE id =: contactId];
        if(conts.size() > 0 && conts[0].Account.Name == 'Genesys - Employees')
            isContactEmployee = true;
        
        return isContactEmployee;
   }
}