objects/Back_Office_Account__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>BOA Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts</relationshipLabel>
        <relationshipName>Back_Office_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PureEngage On Premise</fullName>
                    <default>true</default>
                    <label>PureEngage On Premise</label>
                </value>
                <value>
                    <fullName>PureConnect On Premise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts (Sold To Account)</relationshipLabel>
        <relationshipName>Back_Office_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Back Office Account</label>
    <nameField>
        <displayFormat>BOA-{000000}</displayFormat>
        <label>Back Office Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Back Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SW_Download_Site__c</fullName>
        <description>Site of the software download. Actual URL is stored in Custom Settings.</description>
        <inlineHelpText>This is the location of the software download server.</inlineHelpText>
        <label>SW Download Site</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_SW_Download_History__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer SW Downloads History</relationshipLabel>
        <relationshipName>Customer_SW_Downloads_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer SW Downloads History</relationshipLabel>
        <relationshipName>Customer_SW_Downloads_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Major_Release__c</fullName>
        <label>Major Release</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipLabel>Customer SW Downloads History</relationshipLabel>
        <relationshipName>Customer_SW_Downloads_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer SW Downloads History (Sold To Account)</relationshipLabel>
        <relationshipName>Customer_SW_Downloads_History1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Customer SW Download History</label>
    <nameField>
        <displayFormat>DLH-{000000}</displayFormat>
        <label>SW Download History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer SW Downloads History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Platform__c.object
<CustomObject>
    <description>What it does?  Object holding information about platforms associated with demo requests.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>What it does?  Indicates whether or not the platform is active.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Software_Download__c.object
<CustomObject>
    <fields>
        <fullName>File_Type__c</fullName>
        <description>This field will contain the types of files that will be available for download.</description>
        <inlineHelpText>The type of the file to be downloaded.</inlineHelpText>
        <label>File Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>gz</fullName>
                </value>
                <value>
                    <fullName>zip</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Localization__c</fullName>
        <description>This field will track the language for this download.</description>
        <inlineHelpText>This field will track the language for this download.</inlineHelpText>
        <label>Language</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Release__c</fullName>
        <label>Major Release</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_Systam__c</fullName>
        <label>O/S</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will track the product to which this download is linked to.</description>
        <inlineHelpText>This field will track the product to which this download is linked to.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipName>Software_Downloads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Software_Downloads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Software Download</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Downloads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidary__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Store the country related to Subsidiary
Downstream Impact? To be used by PureCloud Billing
Which department is owner? IT/PureCloud Team</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Subsidaries</relationshipLabel>
        <relationshipName>Subsidaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subsidary</label>
    <nameField>
        <label>Subsidary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Support_Access__c.object
<CustomObject>
    <fields>
        <fullName>Back_Office_Account__c</fullName>
        <label>Back Office Account</label>
        <referenceTo>Back_Office_Account__c</referenceTo>
        <relationshipName>Support_Access</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>eService_Access</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Contact__r.Country__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>eService_Access</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SR_Access_Level__c</fullName>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
                <value>
                    <fullName>Read Only</fullName>
                </value>
                <value>
                    <fullName>Basic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>eService_Access1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Access Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Support Access Premise</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Support Access ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Access Premise</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Support_Product__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Software_Download__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Software Download</label>
        <referenceTo>Software_Download__c</referenceTo>
        <relationshipLabel>Support Products</relationshipLabel>
        <relationshipName>Support_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Support Product</label>
    <nameField>
        <label>Support Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_DownloadsControllers.cls
@isTest (seeAllData= true)
private class Test_DownloadsControllers {
	
	static testMethod void testDownloadsCD() {
		
		 Util.Bypass_Trigger_Chk = true;

        Support_Product__c prod = new Support_Product__c(Product_Type__c = 'Product',Customer_Available__c = true,Active__c = true); 
        insert prod;
        Support_Product__c comp = new Support_Product__c(Product_Type__c = 'Component',Customer_Available__c = true,Active__c = true);
        insert comp;
    
        Software_Download__c swDet = new Software_Download__c(name='sw');
        swDet.File_Type__c ='CD';
        swDet.Major_Release__c = '8.1.3';
        swDet.Product__c = prod.Id;
        swDet.Localization__c = 'ENU';
        swDet.Version__c = '8.1.0';
        swDet.Operating_Systam__c = 'Windows';
		insert swDet;
		
        Account acc = TestUtil.createAccounts(1, true)[0];
        Contact cont = TestUtil.createContacts(1, acc, true)[0];
        
        //Support_Access__c supaccs = TestUtil.createSupportAccess(1, true, cont)[0];
        
        Back_Office_Account__c boa = new Back_Office_Account__c(Sold_To_Account__c = acc.Id, Platform__c = 'PureEngage on Premise',Contract_Status__c = 'Active',
                                                             End_User_Account__c = acc.Id);
        insert boa;
        
        Support_Access__c supaccs = new Support_Access__c (Contact__c = cont.Id, Back_Office_Account__c = boa.Id, Status__c ='Active', SR_Access_Level__c = 'Read/Write');
        insert supaccs;   
 
        Profile prof = [SELECT id FROM Profile WHERE Name = 'Genesys Portal End User' LIMIT 1];    		
        User testUser = TestCommon.createUser('testU', 'testUser132@test132.com.test', 'Test', 'Test', prof.id, false);    	
		testUser.ContactId = cont.id;
		testUser.isactive = true;
		testUser.Bypass_Triggers__c = true;
		testUser.BypassValidationRules__c = true;
		testUser.BypassWorkflows__c = true;
		insert testUser;
		
      System.runAs(testUser)  {
            //Pagereference pg = Page.DowloadsTabInternal;  
            //Test.setCurrentPageReference(pg);
              
            ApexPages.currentPage().getParameters().put('isDloadTypeCD', 'true');
                
            DownloadsController dc = new DownloadsController();		
            dc.currentCase.Sold_To_Account__c = acc.Id;
            dc.currentCase.End_User_Account__c = acc.Id;
            
            dc.conId = cont.Id;
            dc.setContact();
            dc.isDloadTypeCD = true;
            dc.selectedProduct = prod.Id;
            dc.selectedComponent = comp.Id;
            dc.selectedMajorRelease ='8.1.3';
            dc.selectedLanguage = 'ENU';
            dc.selectedOSVersion = 'All';
            dc.selectedProductVersion = 'All';
            dc.version='8.0';
            dc.lang ='ENU';
            dc.mjrRlease = '8.0';
            dc.acceptTnc = true;            
            dc.populateFields();
            
            dc.selectedProduct = null;
            dc.populateAllOnProdChange();
            
            dc.closeTNC();
            dc.closeNTNC();
            dc.next();
            dc.previous();
            
            String q = dc.query2;
            String f = dc.fields;
            
            DownloadsControllerExtension dext = new DownloadsControllerExtension(dc);		
         
           MockHttpResponseSwDownloads testMock = new MockHttpResponseSwDownloads();              
	        Test.setMock(HttpCalloutMock.class, testMock);
            
            dext.swdLoadId = swDet.Id;
            dext.gtDload();
            
            DownloadController dlc = new DownloadController();
            dlc.isPremiseUser = true;
            dlc.dltype = 'CD';
            
            dc.endUserName = '';
            dc.setContact();
		}
	}
    
    static testMethod void testDownloadsIP() {
    	
    	 Util.Bypass_Trigger_Chk = true;
		
        Support_Product__c prod = new Support_Product__c(Product_Type__c = 'Product',Customer_Available__c = true,Active__c = true); 
        insert prod;
        Support_Product__c comp = new Support_Product__c(Product_Type__c = 'Component',Customer_Available__c = true,Active__c = true);
        insert comp;
    
        Software_Download__c swDet = new Software_Download__c(name='sw');
        swDet.File_Type__c ='IP';
        swDet.Major_Release__c = '8.1.3';
        swDet.Product__c = prod.Id;
        swDet.Localization__c = 'ENU';
        swDet.Version__c = '8.1.0';
        swDet.Operating_Systam__c = 'Windows';
		insert swDet;
              
        Account acc = TestUtil.createAccounts(1, true)[0];
        Country__c country = new Country__c(name='United States', SW_Download_Site__c = 'USA', Country__c='United States');
        insert country;
        Subsidary__c subs = new Subsidary__c(name='Subsidary');
    	insert subs; 
        acc.Country__c = country.Id;
        acc.Subsidary__c = subs.Id;
        update acc;
        
        Id profileId = [Select Id from profile where name LIKE 'Genesys Portal End User%' LIMIT 1].Id;      
    	Account testAccount = TestUtil.createAccounts(1, true)[0];
        Contact testContact = TestUtil.createContacts(1, testAccount, true)[0];
    	User usr = TestCommon.createUser('testU', 'testUser55@test55.com.test', 'Test1', 'Test1', profileId, false);    	
    	usr.ContactId = testContact.Id;
    	usr.Bypass_Triggers__c = true;
		usr.BypassValidationRules__c = true;
		usr.BypassWorkflows__c = true;
    	insert usr;
    	
    	 Back_Office_Account__c boa = new Back_Office_Account__c(Sold_To_Account__c = acc.Id, Platform__c ='PureEngage on Premise',Contract_Status__c = 'Active',
                                                             End_User_Account__c = acc.Id);
        insert boa;
        
        Support_Access__c supaccs = new Support_Access__c (Contact__c = testContact.Id, Back_Office_Account__c = boa.Id, Status__c ='Active', SR_Access_Level__c = 'Read/Write');
        insert supaccs;   
    	
        supaccs.End_User_Account__c = acc.Id;
        supaccs.Sold_To_Account__c = acc.Id;
        update supaccs;
        
      
       System.runAs(usr){
				
            Pagereference pg = Page.DownloadsTab;  
            Test.setCurrentPageReference(pg);  
                
            DownloadsController dc = new DownloadsController();	
            
            dc.endUserAccName = 'Test'	;
            dc.soldToAccName = 'Test';
            dc.currentCase.Sold_To_Account__c = acc.Id;
            dc.currentCase.End_User_Account__c = acc.Id;
            
            dc.conId = testContact.Id;
            dc.setContact();
            dc.isDloadTypeCD = false;
            dc.selectedProduct = null;
            dc.selectedComponent = null;
            dc.selectedMajorRelease = null;
            dc.selectedLanguage = null;
            dc.selectedOSVersion = null;
            dc.isEndSoldToSelected = true;
            dc.queryFilter();
           
            dc.showNTNC();
            dc.showTNC();
            dc.acceptTnc = true;
            
            dc.isDloadTypeCD = false;
            dc.populateSoftwares();
            dc.selectedProduct = prod.Id;
            dc.selectedComponent = comp.Id;
            dc.selectedMajorRelease ='8.1.3';
            dc.selectedLanguage = 'ENU';
            dc.selectedOSVersion = 'All';
            dc.query2 = null;
            dc.acceptTnc = true;
            dc.populateFields();
            dc.populatesProds();
                            
            dc.populateAllOnProdChange();
            dc.isProductNotFound = true;
            dc.populateAllOnProdChange();
            List<SelectOption> ft = dc.getFlType();
            List<SelectOption> dt = dc.getDtype();  
            List<SelectOption> sft = dc.sortListByValue(ft, 'disc', null);
            List<selectOption> sdt = dc.sortListByLabel(ft);       
         
           DownloadsControllerExtension dext = new DownloadsControllerExtension(dc);	

           MockHttpResponseSwDownloads testMock = new MockHttpResponseSwDownloads();                     
	       Test.setMock(HttpCalloutMock.class, testMock);
          	
            dext.swdLoadId = swDet.Id;
            dext.gtDload();
            dext.logHistory();
            
        }
	}

    static testMethod void testDownloadExt() {

        List<Customer_SW_Download_History__c> dlst = [SELECT User__c, User__r.ContactId, User__r.Contact.AccountId,SWDL_Id__c FROM Customer_SW_Download_History__c
                                                      WHERE User__r.isActive = true 
                                                      AND User__r.Profile.Name LIKE '%Portal%'
                                                      AND CreatedDate = LAST_N_DAYS:6 LIMIT 1];

        List<User> us = [SELECT id FROM User WHERE id = :dlst[0].User__c];

        System.runAs(us[0]) {

            PageReference pg= new PageReference('DownloadsTab');         
           Test.setCurrentPage(pg);  
            DownloadsController dc = new DownloadsController();
            dc.conId = dlst[0].User__r.ContactId;
            dc.sdLoadId = dlst[0].SWDL_Id__c;
            dc.endUserAccId = dlst[0].User__r.Contact.AccountId;
            String q = dc.query2;
            String f = dc.fields;

           MockHttpResponseSwDownloads testMock = new MockHttpResponseSwDownloads();            
	       Test.setMock(HttpCalloutMock.class, testMock);
    
            DownloadsControllerExtension dext = new DownloadsControllerExtension(dc);	
            dext.swdLoadId = dlst[0].SWDL_Id__c;
 
            dc.endUserAccId = dlst[0].User__r.Contact.AccountId;         
            dext.sdSite();
            dext.gtDload();
        }
    }
    
}