objects/Back_Office_Account__c.object
<CustomObject>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts</relationshipLabel>
        <relationshipName>Back_Office_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts (Sold To Account)</relationshipLabel>
        <relationshipName>Back_Office_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Back Office Account</label>
    <nameField>
        <displayFormat>BOA-{000000}</displayFormat>
        <label>Back Office Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Back Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Support_Access__c.object
<CustomObject>
    <fields>
        <fullName>Back_Office_Account__c</fullName>
        <label>Back Office Account</label>
        <referenceTo>Back_Office_Account__c</referenceTo>
        <relationshipName>Support_Access</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>eService_Access</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>eService_Access</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>eService_Access1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Access Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Boa_Contact_Combination__c</fullName>
        <description>To enforce unique BOA/Contact combination. Format: BOA Id + &quot;_&quot; + Contact Id</description>
        <label>Unique Boa Constraint</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Support Access Premise</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Support Access ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Access Premise</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SupportAccessUtil.cls
public with sharing class SupportAccessUtil {
   
     public static void disableEnablePartnerPortal(List<Contact> newList, Map<Id, Contact> oldMap){
        Set<Id> contSetEnable = new Set<Id>();
        Set<Id> contSetDisable = new Set<Id>();
        
        for(Contact eachContact : newList){
            if(eachContact.Status__c == 'Inactive' && (oldMap.get(eachContact.id).Status__c == 'Active' || oldMap.get(eachContact.id).Status__c == null || oldMap.get(eachContact.id).Status__c == ''))
                contSetDisable.add(eachContact.id);
            
            if(eachContact.Status__c == 'Active' && (oldMap.get(eachContact.id).Status__c == 'Inactive' || oldMap.get(eachContact.id).Status__c == null || oldMap.get(eachContact.id).Status__c == ''))
                contSetEnable.add(eachContact.id);
                
        }
        if(!contSetDisable.isEmpty()){
            updateUserFuture(contSetDisable, false);
        }
        if(!contSetEnable.isEmpty()){
            updateUserFuture(contSetEnable, true);
        }
        
    }
     
    @future
    private static void updateUserFuture(Set<Id> contactsNotHavingSA, Boolean enable){
        System.debug('NKC debug enable ['+enable+']');
        List<User> usersToBeUpdated = [SELECT id FROM User WHERE ContactId IN : contactsNotHavingSA];
        if(!usersToBeUpdated.isEmpty()){
            for(User eachUser : usersToBeUpdated) {
                eachUser.isActive = enable;
                eachUser.IsPortalEnabled = enable;
            }
            
            update usersToBeUpdated;
        }       
    }
    @future
    private static void updateUserProfileFuture(Map<Id,Id> contactIdVsProfileId){
        System.debug('NKC debug contactIdVsProfileId ['+contactIdVsProfileId+']');
        List<User> users = [SELECT id, profileId, contactId FROM User WHERE ContactId IN : contactIdVsProfileId.keyset()];
        List<User> usersToBeUpdated = new List<User>();
        if(!users.isEmpty()){
            for(User eachUser : users){
                if(eachUser.profileId != contactIdVsProfileId.get(eachUser.contactId)){
                    eachUser.profileId = contactIdVsProfileId.get(eachUser.contactId);
                    usersToBeUpdated.add(eachUser); 
                }               
            }
            if(!usersToBeUpdated.isEmpty())
                update usersToBeUpdated;
        }       
    }
    
    
    public static void setSupportAccessFields (List<Support_Access__c> newSAList) {
        for ( Support_Access__c sa : newSAList ) {
           if ( sa.Back_Office_Account__c != null )  {
              List<Back_Office_Account__c> boa = [SELECT End_User_Account__c, Sold_To_Account__c
                                                    FROM Back_Office_Account__c WHERE Id = :sa.Back_Office_Account__c];
              if ( !boa.isEmpty() ) {
                 sa.End_User_Account__c = boa[0].End_User_Account__c;
                 sa.Sold_To_Account__c = boa[0].Sold_To_Account__c;
                 sa.Unique_Boa_Contact_Combination__c = (Id) boa[0].Id + '_' + (Id) sa.Contact__c;
              }
           }
        }
    }    

}