objects/Back_Office_Account__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>BOA Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>BOA Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts</relationshipLabel>
        <relationshipName>Back_Office_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>BOA Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Premise</fullName>
                </value>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Back Office Accounts (Sold To Account)</relationshipLabel>
        <relationshipName>Back_Office_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_STEU__c</fullName>
        <externalId>true</externalId>
        <label>Unique STEU</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Back Office Account</label>
    <nameField>
        <displayFormat>BOA-{000000}</displayFormat>
        <label>Back Office Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Back Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BoaDuplicateReportController_Test.cls
@isTest
public class BoaDuplicateReportController_Test {
    
    static testMethod void dupReportTest () {
	
	     Util.Bypass_Trigger_Chk = true;    
        List<Account> testAccounts = TestUtil.createAccounts(2, true);
  
        Account accnt1 = testAccounts[0];
        Account accnt2 = testAccounts[1];
 
		Back_Office_Account__c boa1 = new Back_Office_Account__c();
		boa1.Contract_Status__c = 'Active';
	   	boa1.Service_Type__c = 'Premise';
	   	boa1.Approval_Status__c = 'Active';
	   	boa1.Sold_To_Account__c = accnt1.id;
	   	boa1.End_User_Account__c = accnt1.id;
	   	boa1.Unique_STEU__c = accnt1.id + '_' + accnt1.id ;
        insert boa1;
        
        Back_Office_Account__c boa2 = new Back_Office_Account__c();
		boa2.Contract_Status__c = 'Active';
	   	boa2.Service_Type__c = 'Premise';
	   	boa2.Approval_Status__c = 'Active';
	   	boa2.Sold_To_Account__c = accnt1.id;
	   	boa2.End_User_Account__c = accnt1.id;
	   	boa2.Unique_STEU__c = accnt2.id + '_' + accnt2.id ;
        insert boa2;
        
        Test.startTest();  
    	BoaDuplicateReportController repContrl = new BoaDuplicateReportController();
        Test.stopTest();     
    
    } 
}