objects/Blog_Post__c.object
<CustomObject>
    <description>Primary content for a blog post.</description>
    <fields>
        <fullName>Blog_Content__c</fullName>
        <description>The rich text content of the blog post.</description>
        <label>Blog Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>The date and  time at which the blog post will no longer be displayed and available.  If omitted, the blog post will remain until it is removed.</description>
        <label>Blog Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Home_Page_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>check to display this post on the partner portal home page blog spotlight section</description>
        <label>Blog Used on Home Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication_Date__c</fullName>
        <description>The date and time at which this blog post should become visible.  If omitted, the blog post will become immediately visible.</description>
        <label>Blog Publication Date</label>
        <type>DateTime</type>
    </fields>
    <label>Blog Post</label>
    <nameField>
        <label>Blog Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blog Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Partner_Portal_Events__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Header__c</fullName>
        <label>Header</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Portal Events</label>
    <nameField>
        <displayFormat>PEN - {00000}</displayFormat>
        <label>Partner Portal Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Portal Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Portal_Events_Webinars__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to record the links visible in the Events and Webinars section of the Partner Portal Home Page</description>
    <fields>
        <fullName>Event_Id__c</fullName>
        <description>Event and Webinar identifier.</description>
        <label>Event Id</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Numeric value determining the order in which Events &amp; Webinars links are displayed, sorted lowest to highest.</description>
        <label>Order</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Partner Portal Events &amp; Webinars</label>
</CustomObject>

objects/Partner_Portal_Hot_Content__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to enter the links displayed in the Hot Content section of the Partner Portal Home Page.</description>
    <fields>
        <fullName>Content_Id__c</fullName>
        <description>The identifier of the linked content record.</description>
        <label>Content Id</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Numeric value determining the order in which content links are displayed.  It sorts from lowest to highest.</description>
        <label>Order</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Partner Portal Hot Content</label>
</CustomObject>

objects/Partner_Portal_Video__c.object
<CustomObject>
    <description>Used to store the links to videos to display in the partner portal.</description>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>The date and time the video will be removed from displays.  If omitted, the video will be visible until it is deleted.</description>
        <label>Video Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Home_Page_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the video is eligible for display on the Partner Portal Home Page.</description>
        <inlineHelpText>If this box is checked, the video will be eligible for display on the Partner Portal Home Page.  The video chosen for display will be selected at random from videos currently visible and flagged with this checkbox.</inlineHelpText>
        <label>Video Used on Home Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication_Date__c</fullName>
        <description>The date and time the video will become visible on displays.  If omitted, the video will be published immediately.</description>
        <label>Video Publication Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of the video for display purposes.</description>
        <label>Video Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Video_Link__c</fullName>
        <description>URL or *other* identifier for videos.  It must contain enough information for the video handler to determine the type of video (i.e., YouTube vs. Video Cloud)</description>
        <label>Video Link or ID</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Video_Type__c</fullName>
        <label>Video Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Youtube</fullName>
                    <default>true</default>
                    <label>Youtube</label>
                </value>
                <value>
                    <fullName>Brightcove</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Portal Video</label>
    <nameField>
        <displayFormat>PPV-{000000}</displayFormat>
        <label>Video Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Portal Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PartnerPortalHomeController.cls
public with sharing class PartnerPortalHomeController {

    public List<HotContentWrapper> hotContentLinks { get; set; }
    public Account newAccount {get;set;}
    
    public List<HotContentWrapper> eventContentLinks { get; set; }
    public List<Partner_Portal_Events__c> events{get;set;}

    // we use the HotContentWrapper to manage the list of hot content links
    public class HotContentWrapper {
        Partner_Portal_Hot_Content__c link;
        ContentDocument doc;
        Partner_Portal_Events_Webinars__c EventLink;
        
        public String title { get; set; }
        public String url { get; set; }
        
        public HotContentWrapper(Partner_Portal_Hot_Content__c hc) {
            link = hc;
            String docid = link.Content_Id__c;
            List<ContentDocument> docs = [ SELECT Title 
                                             FROM ContentDocument 
                                            WHERE Id = :docid ];
            if (docs.size()>0) {
                doc = docs[0];
                title = doc.Title;
            } else {
                List<ContentVersion> docVersions = [ SELECT  c.ContentDocumentId,c.ContentDocument.title From ContentVersion c  WHERE Id = :docid ];
                
                if (docVersions.size()>0) {
                    doc = docVersions[0].ContentDocument;
                    title = doc.title;
                } else {
                    title = '[[ content not found ]]';
                }
            }
            url = Site.getCurrentSiteUrl() + docid;
        }
        
        
        public HotContentWrapper(Partner_Portal_Events_Webinars__c hc) {
            EventLink = hc;
            String docid = EventLink.Event_Id__c;
            List<ContentDocument> docs = [ SELECT Title 
                                             FROM ContentDocument 
                                            WHERE Id = :docid ];
                                            
            if (docs.size()>0) {
                doc = docs[0];
                title = doc.Title;
            } else {
                List<ContentVersion> docVersions = [ SELECT  c.ContentDocumentId,c.ContentDocument.title From ContentVersion c  WHERE Id = :docid ];
                
                if (docVersions.size()>0) {
                    doc = docVersions[0].ContentDocument;
                    title = doc.title;
                } else {
                    title = '[[ content not found ]]';
                }
            }
            url = Site.getCurrentSiteUrl() + docid;
        }
        
    }
    
    private void updateHotContentLinks() {
        List<Partner_Portal_Hot_Content__c> settings = [ SELECT Content_Id__c, Order__c 
                                                           FROM Partner_Portal_Hot_Content__c 
                                                                ORDER BY Order__c ASC NULLS LAST ];
                  
        Integer upperBound = settings.size()<5 ? settings.size() : 5;
        hotContentLinks = new List<HotContentWrapper>();
        for (Integer i=0; i<upperBound && i<settings.size(); i++) {
            // skip those that are not found by incrementing upper bound, we won't exceed size so that works
            HotContentWrapper hc = new HotContentWrapper(settings[i]);
            if (hc.title != '[[ content not found ]]') {
                hotContentLinks.add(hc);
            } else {
                upperBound++;
            }
        }
                
    }   
    
    
    
    private void updateEventContentLinks() {
        List<Partner_Portal_Events_Webinars__c> settings = [ SELECT Event_Id__c, Order__c 
                                                               FROM Partner_Portal_Events_Webinars__c 
                                                                ORDER BY Order__c ASC NULLS LAST ];
                                                                
        Integer upperBound = settings.size()<5 ? settings.size() : 5;
        eventContentLinks = new List<HotContentWrapper>();
        for (Integer i=0; i<upperBound && i<settings.size(); i++) {
            // skip those that are not found by incrementing upper bound, we won't exceed size so that works
            HotContentWrapper hc = new HotContentWrapper(settings[i]);
            if (hc.title != '[[ content not found ]]') {
                eventContentLinks.add(hc);
            } else {
                upperBound++;
            }
        }
    }
    
    ////// END:   HOT CONTENT COMPONENT DATA


    /*public List<EventWebinarWrapper> eventLinks { get; set; }
    
    // we use the EventWebinarWrapper to manage the list of event/webinar links
    public class EventWebinarWrapper {
        Partner_Portal_Events_Webinars__c link;
        Event ev;
        
        public String title { get; set; }
        public String location { get; set; }
        public String description { get; set; }
        public String eventtype { get; set; }
        public String startdate { get; set; }
        public String url { get; set; }
        
        public EventWebinarWrapper(Partner_Portal_Events_Webinars__c ew) {
            link = ew;
            String eventid = link.Event_Id__c;
            List<Event> events = [ SELECT Subject, StartDateTime, Location, Description, Activity_Type__c 
                                      FROM Event 
                                     WHERE Id = :eventid ];
            if (events.size()>0) {
                ev = events[0];
                title = ev.Subject;
                location = ev.location;
                description = ev.Description;
                eventtype = ev.Activity_Type__c;
                startdate = String.valueOf(ev.StartDateTime);
            } else {
                title = '[[ event not found ]]';
                location = '';
                description = '';
                eventtype = '';
                startdate = '';
            }
            url = Site.getCurrentSiteUrl() + eventid;
        }
        
    }*/
    
    /*private void updateEventWebinarLinks() {
        List<Partner_Portal_Events_Webinars__c> settings = [ SELECT Event_Id__c, Order__c 
                                                               FROM Partner_Portal_Events_Webinars__c 
                                                                ORDER BY Order__c ASC NULLS LAST ];
        Integer upperBound = settings.size()<5 ? settings.size() : 5;
        eventLinks = new List<EventWebinarWrapper>();
        for (Integer i=0; i<upperBound && i<settings.size(); i++) {
            EventWebinarWrapper ew = new EventWebinarWrapper(settings[i]);
            // skip those that are not found by incrementing upper bound, we won't exceed size so that works
            if (ew.title != '[[ event not found ]]') {
                eventLinks.add(ew);
            } else {
                upperBound++;
            }
        }
    }*/

    ////// END:   EVENT/WEBINAR LINKS COMPONENT DATA
    
    ////// START: get a Blog post
    public Blog_Post__c selected_blog_post {get; set;}
    //// Get blog prefix
    public String blog_obj_prefix {get;set;}
        
    private void updateBlogPost() {
        blog_obj_prefix = (String)Blog_Post__c.SObjectType.getDescribe().getKeyPrefix();
        Blog_Post__c post;
        List<Blog_Post__c> blogpost = [ SELECT Id, Name, Blog_Content__c, Publication_Date__c, Expiration_Date__c, OwnerId 
                                        FROM Blog_Post__c 
                                        WHERE Home_Page_Flag__c=true ];
        if (blogpost.size()>0) {
            post = blogpost[0];
        } else {
            post=null;
        }
        if(post!=null){
            //TODO: find better way to get an excerpt i.e. there may be an image(s) inside the content
            // for example on all the sample posts an img tag takes up the first ~80 chars
            // images for the excerpt are hidden by css in the blog block on the partner portal home page
            String excerpt = getExcerpt(post.Blog_Content__c);
            post.Blog_Content__c = excerpt;
            selected_blog_post = post;
        }else{
            selected_blog_post = new Blog_Post__c();
            selected_blog_post.Name = '[[ blog post not found ]]';
            selected_blog_post.Blog_Content__c = '';
        }
    }
    //// END Blog Post Component Code
    
    //// START Video Component
    public Partner_Portal_Video__c spotlight_video {get;set;}
    //// Get Video Prefix
    public String video_obj_prefix {get;set;}
    private void updateVideo(){
        List<Partner_Portal_Video__c> videoSpotlight = [ SELECT Id, Video_Link__c, Title__c,Video_Type__c  
                                        FROM Partner_Portal_Video__c 
                                        WHERE Home_Page_Flag__c=true
                                         ];
        if (videoSpotlight.size()>0) {
            spotlight_video = videoSpotlight[0];
        }else{
            spotlight_video = new Partner_Portal_Video__c();
            spotlight_video.Title__c = 'No Videos Please click Link to go to Video Page';
            spotlight_video.Video_Link__c = '';
        }
        video_obj_prefix = (String)Partner_Portal_Video__c.SObjectType.getDescribe().getKeyPrefix();
    }
    
        
    private static String getExcerpt(String fullTest){
        if(fullTest == null) return '';
        String returnedExcerpt = fullTest.trim();
        
        if(returnedExcerpt.length() > 380){
            returnedExcerpt = returnedExcerpt.substring(0,380).trim();
        }
        
        return returnedExcerpt +'&hellip;' ;
    }
        
    //// END Video Component
    
    // CONTROLLER CONSTRUCTOR
 
    public PartnerPortalHomeController() {
        
        updateHotContentLinks();
        updateEventContentLinks();
        //updateEventWebinarLinks();
        updateBlogPost();
        updateVideo();
        
         events =  new List<Partner_Portal_Events__c>();
         events = [Select id,Name,Description__c,Header__c from Partner_Portal_Events__c where Active__c = true  order by Order__c];

    }
    

}