objects/Business_Consulting__c.object
<CustomObject>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Consulting</relationshipLabel>
        <relationshipName>Business_Consulting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>account__c</fullName>
        <label>Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Business Consulting</label>
    <nameField>
        <label>Business Consulting Assessment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Consulting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Integration_Inbound__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>inbound survey integration settings</description>
    <fields>
        <fullName>Security_Token__c</fullName>
        <label>Security Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Survey Integration Inbound</label>
</CustomObject>

objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Consulting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Consulting</label>
        <referenceTo>Business_Consulting__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Casetext__c</fullName>
        <label>External Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Care</fullName>
                    <default>true</default>
                    <label>Customer Care</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Easiness_of_doing_business_with_Genesys__c</fullName>
        <label>Easiness of doing business with Genesys</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Future_Business_Consulting_NPS_Rating__c</fullName>
        <label>Future Business Consulting NPS Rating</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPS_Cloud_Offer__c</fullName>
        <label>NPS Cloud Offer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPS_Deployment_Type__c</fullName>
        <label>NPS Deployment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPS_Rating__c</fullName>
        <label>NPS Rating</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPS_Tier__c</fullName>
        <label>NPS Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_of_Organization__c</fullName>
        <label>Part of Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Respondent_ID__c</fullName>
        <externalId>true</externalId>
        <label>Respondent ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_in_Organization__c</fullName>
        <label>Role in Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_id__c</fullName>
        <label>Salesforce_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Type__c</fullName>
        <label>Survey Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transactional</fullName>
                    <default>true</default>
                    <label>Transactional</label>
                </value>
                <value>
                    <fullName>Relationship</fullName>
                </value>
                <value>
                    <fullName>NPS Interview</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>SMART</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verbatim2__c</fullName>
        <label>Future Use Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Verbatim__c</fullName>
        <label>Verbatim</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Verbatim_on_doing_business_with_Genesys__c</fullName>
        <label>Verbatim on doing business with Genesys</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <recordTypes>
        <fullName>Relationship</fullName>
        <active>true</active>
        <label>Relationship</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyRespRespondentIdCheckRelation.cls
@RestResource(urlMapping='/SurveyRespRespondentIdCheckRelation/v1/*')
global without sharing class SurveyRespRespondentIdCheckRelation {

    @HttpPost
    global static String checkExtId(String ContactId, String AccountId, String External_ID,String First_name,
                                    String security_token,String Last_name, String Verbatim,String Verbatim1,String Verbatim2, 
                                    String NPS_Rating, String Salesforce_Id, String CaseId, String Future_Use_Rating, String Contact_Email,
                                    String PartOfOrg, String RoleInOrg, String EaseOfBus, String VerbatimOnEaseOfBus,
                                    String 	NPS_CloudOffer, String NPS_DeplType, String NPS_Tier ) {
        
       String LogName = 'Survey Response';
       String LogSource = 'SurveyRespRespondentIdCheckRelation'; 
       String baseLogMsg = External_ID;
       String retValue='';  
        
       if ( NPS_Rating == '' ) {
       	   String logMsg = baseLogMsg + ': NPS Rating Blank';
           ErrorLogUtil.insertLog(LogName, logMsg, LogSource);          
           return logMsg;
      	}
        
        if ( !verifyToken(security_token) ) {
           String logMsg = baseLogMsg + ': Invalid Security Token.';
           ErrorLogUtil.insertLog(LogName, logMsg, LogSource);         
           return logMsg;
        }       
      

      List<Business_Consulting__c> bc = [Select End_User_Account__c from Business_Consulting__c where id = :CaseId];
                
      try {
	            Survey_Response__c surveyResp_inst = new Survey_Response__c(Respondent_ID__c = External_ID, CaseText__c = CaseId,
	                                               NPS_Rating__c = NPS_Rating,First_Name__c = First_name, Last_Name__c = Last_name, 
	                                               Email_Address__c = Contact_Email, Salesforce_id__c = Salesforce_id, 
	                                               Verbatim__c = Verbatim,  Verbatim2__c = Verbatim2,
	                                               Business_Consulting__c = CaseId,
	                                               Future_Business_Consulting_NPS_Rating__c = Future_Use_Rating,
	                                               Department__c ='Customer Care', Survey_Type__c ='Relationship',
	                                               Account__c = AccountId, Contact__c = ContactId,
	                                               Part_of_Organization__c = PartOfOrg, Role_in_Organization__c = RoleInOrg,
	                                               Easiness_of_doing_business_with_Genesys__c = EaseOfBus,
	                                               Verbatim_on_doing_business_with_Genesys__c = VerbatimOnEaseOfBus,
	                                               NPS_Cloud_Offer__c = NPS_CloudOffer, NPS_Deployment_Type__c = NPS_DeplType, NPS_Tier__c = NPS_Tier );
	
	            if(!bc.isEmpty())
	                surveyResp_inst.Account__c = bc[0].End_User_Account__c;
	            insert surveyResp_inst;
	            retValue = surveyResp_inst.id;
      }
      catch (Exception ex) {
	   	    String logMsg = baseLogMsg + ': ' + ex.getMessage();
	   	    ErrorLogUtil.insertLog(LogName, logMsg, LogSource);  
        	return ex.getMessage();
       } 
        
       return retValue;  
    }
                                       
    private static Boolean verifyToken(String token)  {
   	    Survey_Integration_Inbound__c custConf = Survey_Integration_Inbound__c.getOrgDefaults();    	     
        return ( custConf.Security_Token__c == null || custConf.Security_Token__c !=  token ) ? false : true;    			 			    	
   	}

}