objects/BusinessPartner__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CORE Model</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Business Partners</relationshipLabel>
        <relationshipName>R00N200000036pXoEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Partner</label>
    <nameField>
        <label>Business Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/DSR_Attachments__c.object
<CustomObject>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <label>Attachment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectType__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DSR Attachments</label>
    <nameField>
        <label>DSR Attachments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DSR Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DSR_Attachments_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <label>Attachment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectType__c</fullName>
        <label>Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Design Attachment</fullName>
                </value>
                <value>
                    <fullName>Technical Design Attachment</fullName>
                </value>
                <value>
                    <fullName>Vision Activity</fullName>
                </value>
                <value>
                    <fullName>Discovery Activity</fullName>
                </value>
                <value>
                    <fullName>Delivery Requirements</fullName>
                </value>
                <value>
                    <fullName>Service Transition Activity</fullName>
                </value>
                <value>
                    <fullName>Design Activity</fullName>
                </value>
                <value>
                    <fullName>Technical Design</fullName>
                </value>
                <value>
                    <fullName>Business Design</fullName>
                </value>
                <value>
                    <fullName>Partner Delivery Requirements</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URLRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>URL Required</label>
        <type>Checkbox</type>
    </fields>
    <label>DSR Attachments Definition</label>
    <nameField>
        <label>DSR Attachments Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DSR Attachments Definition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DSR_SCE_Design__c.object
<CustomObject>
    <fields>
        <fullName>DSR_SCEngagement__c</fullName>
        <label>DSR SCEngagement</label>
        <referenceTo>DSR_SCEngagement__c</referenceTo>
        <relationshipLabel>DSR SCE Designs</relationshipLabel>
        <relationshipName>DSR_SCE_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DSR SCE Design</label>
    <nameField>
        <displayFormat>SCEDES - {000000}</displayFormat>
        <label>Design ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR SCE Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DSR_SCEngagement__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>DSR_SCEngagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity ID</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>DSR_SCEngagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DSR SC Engagement or Partner SMART DSR</label>
    <nameField>
        <displayFormat>SCE - {00000}</displayFormat>
        <label>SC DSR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR SC Engagements or Partner SMART DSRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DSR_Use_Case_Blueprints__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShortCode__c</fullName>
        <label>Short Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Use Case</fullName>
                </value>
                <value>
                    <fullName>Blueprint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DSR Use Case &amp; Blueprints</label>
    <nameField>
        <label>DSR Use Case &amp; Blueprints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DSR Use Case &amp; Blueprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DSR_UseCase_BluePrint_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShortCode__c</fullName>
        <label>Short Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Use Case</fullName>
                </value>
                <value>
                    <fullName>Blueprint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DSR UseCase&amp;BluePrint Definition</label>
    <nameField>
        <label>DSR UseCase&amp;BluePrint Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DSR UseCase&amp;BluePrint Definition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DSRDataDefinition__c.object
<CustomObject>
    <fields>
        <fullName>Header__c</fullName>
        <label>Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <label>Module</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Virtual User</fullName>
                </value>
                <value>
                    <fullName>Common</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Deliver</fullName>
                </value>
                <value>
                    <fullName>Overview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubModule__c</fullName>
        <label>Sub Module</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vision Activity</fullName>
                </value>
                <value>
                    <fullName>Delivery Requirements</fullName>
                </value>
                <value>
                    <fullName>Service Transition</fullName>
                </value>
                <value>
                    <fullName>Virtual User Type</fullName>
                </value>
                <value>
                    <fullName>Process</fullName>
                </value>
                <value>
                    <fullName>Document Source</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Discovery Activity</fullName>
                </value>
                <value>
                    <fullName>Design Activity</fullName>
                </value>
                <value>
                    <fullName>Design General Background</fullName>
                </value>
                <value>
                    <fullName>Offer Type</fullName>
                </value>
                <value>
                    <fullName>Platform Type</fullName>
                </value>
                <value>
                    <fullName>Design Specific Attachment</fullName>
                </value>
                <value>
                    <fullName>Technical Design Activities</fullName>
                </value>
                <value>
                    <fullName>Business Design - Fit%</fullName>
                </value>
                <value>
                    <fullName>Technical Design - Fit%</fullName>
                </value>
                <value>
                    <fullName>Technical Design - Deployment Topology</fullName>
                </value>
                <value>
                    <fullName>Technical Design - Architectural Blue Print</fullName>
                </value>
                <value>
                    <fullName>Functional Use Case</fullName>
                </value>
                <value>
                    <fullName>Service Transition Activity</fullName>
                </value>
                <value>
                    <fullName>Vision Link</fullName>
                </value>
                <value>
                    <fullName>Discovery Link</fullName>
                </value>
                <value>
                    <fullName>Design Link</fullName>
                </value>
                <value>
                    <fullName>Delivery Link</fullName>
                </value>
                <value>
                    <fullName>Business Design Fit%</fullName>
                </value>
                <value>
                    <fullName>Technical Design Fit%</fullName>
                </value>
                <value>
                    <fullName>Business Design Fit Categeory</fullName>
                </value>
                <value>
                    <fullName>Technical Design Fit Category</fullName>
                </value>
                <value>
                    <fullName>Region/Sub Region</fullName>
                </value>
                <value>
                    <fullName>Template</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DSR Data Definition</label>
    <nameField>
        <displayFormat>DSR-DDF-{000000}</displayFormat>
        <label>DSR Data Definition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR Data Definition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Platform__c.object
<CustomObject>
    <description>What it does?  Object holding information about platforms associated with demo requests.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>What it does?  Indicates whether or not the platform is active.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DSRDesignBusinessController_Test.cls
@isTest
public class DSRDesignBusinessController_Test {
    static testmethod void test1()
    {
        try
        {
            Util.Bypass_Trigger_Chk = true;
            
            List<DSRDataDefinition__c>list_DD = new List<DSRDataDefinition__c>();

            DSRDataDefinition__c objDataDef = new DSRDataDefinition__c();
            objDataDef.Module__c = 'Common';
            objDataDef.SubModule__c = 'Access';
            objDataDef.Header__c = 'A1';
            objDataDef.IsActive__c = true;
            list_DD.add(objDataDef);
            
            DSRDataDefinition__c objDataDef1 = new DSRDataDefinition__c();
            objDataDef1.Module__c = 'Design';
            objDataDef1.SubModule__c = 'Business Design Fit%';
            objDataDef1.Header__c = '60';
            objDataDef1.IsActive__c = true;
            list_DD.add(objDataDef1);
            
            DSRDataDefinition__c objDataDef2 = new DSRDataDefinition__c();
            objDataDef2.Module__c = 'Common';
            objDataDef2.SubModule__c = 'Offer Type';
            objDataDef2.Header__c = 'A1';
            objDataDef2.IsActive__c = true;
            list_DD.add(objDataDef2);
            
            DSRDataDefinition__c objDataDef3 = new DSRDataDefinition__c();
            objDataDef3.Module__c = 'Common';
            objDataDef3.SubModule__c = 'Platform Type';
            objDataDef3.Header__c = 'A1';
            objDataDef3.IsActive__c = true;
            list_DD.add(objDataDef3);
            
            insert list_DD;
            
            DSR_UseCase_BluePrint_Definition__c objDataDef_Fn = new DSR_UseCase_BluePrint_Definition__c();
            objDataDef_Fn.Active__c = true;
            objDataDef_Fn.Name__c = 'B01';
            //objDataDef_Fn.OfferingType__c = 'PureCloud';
            //objDataDef_Fn.Platform__c = 'Premise';
            objDataDef_Fn.ShortCode__c = 'B01';
            objDataDef_Fn.Type__c = 'Use Case';
            insert objDataDef_Fn;
            
            DSR_Attachments_Definition__c objDataDef_Attch = new DSR_Attachments_Definition__c();
            objDataDef_Attch.Active__c = true;
            objDataDef_Attch.AttachmentType__c = 'Bill of Material';
            objDataDef_Attch.ObjectType__c = 'Business Design Attachment';
            //objDataDef_Attch.OfferingType__c = 'PureCloud';
            //objDataDef_Attch.Platform__c = 'Cloud';
            objDataDef_Attch.URLRequired__c = false;
            insert objDataDef_Attch;
            
            
            Account objTestAccount = new Account( Name='Test Account', Status__c = 'Active' );
            //objTestAccount.Country__c = [SELECT Id FROM Country__c WHERE Name =: 'United States' LIMIT 1].Id;
            insert objTestAccount;
            
            //List<Account> lstAcc=TestUtil.createAccounts(1,true);
            
            Opportunity objTestOppty = new Opportunity(Name = 'Test Opp', AccountId = objTestAccount.Id);
            objTestOppty.CloseDate = Date.today().addMonths(1);
            objTestOppty.StageName = '1.Recognize Needs';     
            objTestOppty.CurrencyIsoCode = 'BRL';
            objTestOppty.Previous_Maintenance_Rate__c = 0;
            objTestOppty.BusinessPartner__c = objTestAccount.Id;
            objTestOppty.Gene_Care_Specialist__c = UserInfo.getUserId();
            objTestOppty.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' 
                                        AND DeveloperName = 'Genesys_Renewal'].Id;
            insert objTestOppty;
            
            DSR_SCEngagement__c objSCE = new DSR_SCEngagement__c();
            objSCE.Account_ID__c = objTestAccount.id;
            objSCE.Opportunity_ID__c = objTestOppty.id;
            objSCE.SC_Engagement_Status__c = 'Open and Not Assigned';
            objSCE.Design_Start_Date__c = Date.Today().addDays(-10);
            objSCE.Design_End_Date__c = Date.Today().addDays(10);
            
            insert objSCE;

            DSR_SCE_Design__c objSCDesign = new DSR_SCE_Design__c();
            objSCDesign.DSR_SCEngagement__c = objSCE.id;
            //objSCDesign.OfferPlatformType__c = 'aa';
            //objSCDesign.PlatformType__c = 'aa';
            objSCDesign.HAType__c = 'aa';
            objSCDesign.DataCenters__c = 'aa';
            insert objSCDesign ;
       
            DSR_Use_Case_Blueprints__c objFnUseCase = new DSR_Use_Case_Blueprints__c();
            objFnUseCase.DSRSCEDesign__c = objSCDesign.id;
            objFnUseCase.DSRSCEngagement__c = objSCE.id;
            objFnUseCase.ShortCode__c = 'B01';
            objFnUseCase.Type__c = 'Use Case';
            objFnUseCase.Name__c = 'aa';
            
            DSR_Attachments__c objActivity = new DSR_Attachments__c();
            objActivity.DSRSCEDesign__c = objSCDesign.id;
            objActivity.DSRSCEngagement__c = objSCE.id;
            objActivity.ObjectType__c = 'Business Design Attachment';
            objActivity.AttachmentType__c = 'Bill of Material';

            objActivity.Description__c ='aa';
            objActivity.DateofAttachment__c = Date.Today();
            //objActivity.strSelectedAccess = 'aa';
            //objActivity.strSelectedSource = 'aa';
            insert objActivity;
            Test.startTest();
            
            /*For Design controller*/
            Test.setCurrentPageReference(new PageReference('/apex/SC_Engagement_Design_Business?id=' + objSCDesign.Id));
            DSRDesignBusinessController objDesign = new DSRDesignBusinessController();
            objDesign.strSelectedAccess = 'aa';
            objDesign.strSelectedSource = 'aa';
            //objDesign.strSelectedVisionType = 'aa';
            objDesign.strSelectedAttachmentType = 'aa';
            objDesign.objDSRActivity = objActivity;
            objDesign.strURLReq = 'NO';
            objDesign.InsertAndUpdateActivity();
            objDesign.strVisionActId = objActivity.id;
            objDesign.EditActivity();
            objDesign.Cancel();
            objDesign.RemoveVisionActivity();
            objDesign.SaveSCE();
            DSRDesignBusinessController.GetDescription('Bill of Material');
            /*Save for Functional Use Case*/
            objDesign.strSelectedShortCode = 'B01';
            objDesign.strSelectedFit = '100';
            objDesign.strSelectedFitCategory = 'aa';
            objDesign.objFnUseCase = objFnUseCase ;
            objDesign.SaveAndUpdateFnUseCase();
            objDesign.strVisionActId = objFnUseCase.id;
            objDesign.EditFnUseCase();
            objDesign.AddAct();
            DSRDesignBusinessController.GetFitCategoryDtl('B01','PureCloud');
            
            objDesign.strFnId = objFnUseCase.id;
            objDesign.RemoveFnUseCase();
            
            objDesign.strDesignId = objSCDesign.id;
            objDesign.RemoveDesign();
            
            Test.stopTest();
        }
        catch(CalloutException ex)
        {}
    }
}