objects/BusinessPartner__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CORE Model</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Business Partners</relationshipLabel>
        <relationshipName>R00N200000036pXoEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Partner</label>
    <nameField>
        <label>Business Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Bypass_Triggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Bypass flags for triggers</description>
    <label>Bypass Triggers</label>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CORE Model</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/POC_Engagement_Request__c.object
<CustomObject>
    <fields>
        <fullName>AssignTo__c</fullName>
        <label>AssignTo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Partner__c</fullName>
        <label>Business Partner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Closed_Date__c</fullName>
        <label>Expected Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Id</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Engagement Request</relationshipLabel>
        <relationshipName>POC_Engagement_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Status__c</fullName>
        <label>POC Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open and Not Assigned</fullName>
                </value>
                <value>
                    <fullName>Open and Assigned</fullName>
                </value>
                <value>
                    <fullName>POC Status Submitted for Completion</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platform_Type__c</fullName>
        <label>Platform Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Solution_Category__c</fullName>
        <label>Primary Solution Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Contact Center</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Process Automation (EWM)</fullName>
                </value>
                <value>
                    <fullName>Self Service</fullName>
                </value>
                <value>
                    <fullName>Workforce Optimization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Solution__c</fullName>
        <label>Primary Solution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                    <default>true</default>
                    <label>Digital</label>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Omnichannel Desktop</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Platform</fullName>
                </value>
                <value>
                    <fullName>Self Service</fullName>
                </value>
                <value>
                    <fullName>Workforce Optimization</fullName>
                </value>
                <value>
                    <fullName>Workload Management</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>POC Engagement Request</label>
    <nameField>
        <displayFormat>POC-{00000}</displayFormat>
        <label>POC Engagement Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Engagement Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/POCRequestUserAccess_Test.cls
/*
Created By:    Mahesh Varde -Rsystems(10/10/2017)
Function:      Test Class for Class  POCRequestUserAccess
*/
@isTest(seealldata=true)
public class POCRequestUserAccess_Test{
      public static testmethod void testmethod1(){       
            test.starttest(); 
            //Create Account
            List<Account> lstAcc=TestUtil.createAccounts(1,true);
               
            //find current user
            user objUser=[SELECT Id,Bypass_Triggers__c FROM User WHERE Id=:UserInfo.getUserId()];  
            objUser.Bypass_Triggers__c = true;
            update objUser;
            
            //find  country
            country__c objCountry=[SELECT ID,Region__c FROM country__c WHERE Name=:'Anguilla'] ;   
            //Create opportunity
            Opportunity ObjOpp=new Opportunity();
            ObjOpp.Name='Test';
            ObjOpp.CurrencyIsoCode='USD';
            ObjOpp.StageName='Test Stage';
            ObjOpp.Owner=objUser;
            ObjOpp.Primary_Line_of_Business__c='On Premise';
            ObjOpp.Account=lstAcc[0];
            ObjOpp.BusinessPartner__c=lstAcc[0].Id;
            ObjOpp.Primary_Solution_Category__c='Analytics';
            ObjOpp.CloseDate=date.today();
            ObjOpp.CurrencyISOCode='USD';
            ObjOpp.Country__c=objCountry.Id;
            insert ObjOpp;
            
            LIST<User> lstUsr= [Select Id From User WHERE Profile.Name='System Administrator' LIMIT 2];
            
           
            
             POC_Engagement_Request__c objPOC=new POC_Engagement_Request__c();
            objPOC.POC_Status__c='Open and Not Assigned';            
            objPOC.Opportunity_Id__c=ObjOpp.Id;
            objPOC.AssignTo__c='';  
            objPOC.Total_Amount__c=100.00;
            objPOC.Platform_Type__c='Test Platform';
            objPOC.Customer_Name__c='Test Customer';
            objPOC.Business_Partner__c='Test BusinessPartner';
            objPOC.Primary_Solution__c='Test PrimarySolution';
            objPOC.Expected_Closed_Date__c=Date.Today();
            insert objPOC;    
          
            
            //Set Page and Query string
            PageReference pageRef = Page.WowRequestUser;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', ObjOpp.Id);
            ApexPages.currentPage().getParameters().put('view', 'Yes'); 
            ApexPages.StandardController sc = new ApexPages.standardController(objPOC);            
            POCRequestUserAccess objWow=new POCRequestUserAccess(sc); 
           //objWow.pageSize=10;
            objWow.FilterUsers();
            objWow.previous();
            objWow.next();
            //objWow.pageN=2;           
            objWow.last();
            objWow.last();
            objWow.previous();
            //objWow.LastPage();                      
            test.stoptest();          
               
    }
}