objects/Bypass_Triggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Bypass flags for triggers</description>
    <label>Bypass Triggers</label>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Offering_Type__c</fullName>
        <formula>IF(CONTAINS(Quote__r.Offering_Type__c,&apos;Subscription&apos;), Quote__r.Offering_Type__c,

IF(Text(Opportunity__r.Lines_of_Businesses__c) == &apos;Business Edition&apos; &amp;&amp; 
(RecordType.Name == &apos;Cloud Billing Master Order&apos; || RecordType.Name == &apos;Cloud Monthly Billing Order&apos;),
&apos;PureEngage&apos;,  TEXT(Opportunity__r.Lines_of_Businesses__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offering Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <defaultValue>IF($RecordType.Id =&apos;012U0000000M2Tw&apos;, &apos;Non-Revenue&apos;, &apos;Revenue&apos;)

/*IF($RecordType.Id =&apos;012U0000000MGoM&apos;, &apos;Revenue&apos;, null))*/</defaultValue>
        <label>Order Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Product</label>
        <referenceTo>BigMachines__Quote_Product__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Add-On</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Subscription__c.object
<CustomObject>
    <description>To store subscription for different offering types</description>
    <fields>
        <fullName>Amendment_For__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Stores previous subscription which is amended
Downstream Impact? Effects reporting and billing integration
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Previous CCDB/Subscription record that this CCDB/Subscription amended.</inlineHelpText>
        <label>Amendment For</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>CCDBs/Subscriptions (Amendment For)</relationshipLabel>
        <relationshipName>NewSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offering_Type__c</fullName>
        <description>What it Does? Stores different types of offering
Downstream Impact? Effects reporting and quote amendment/creation
Which department is owner? IT/PureCloud Team</description>
        <label>Offering Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PureConnect Cloud</fullName>
                    <default>true</default>
                    <label>PureConnect Cloud</label>
                </value>
                <value>
                    <fullName>PureCloud</fullName>
                </value>
                <value>
                    <fullName>PureEngage Cloud</fullName>
                </value>
                <value>
                    <fullName>PureEngage Subscription</fullName>
                </value>
                <value>
                    <fullName>PureConnect Subscription</fullName>
                </value>
                <value>
                    <fullName>Premier Edition Cloud</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Stores order
Downstream Impact? Effects reporting and billing
Which department is owner? Billing/PureCloud Team</description>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Lookup to quote object which is approved
Downstream Impact? Effects reporting and quote amendment
Which department is owner? IT/PureCloud Team</description>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CCDB/Subscription</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>CCDB/Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCDBs/Subscriptions</pluralLabel>
    <recordTypes>
        <fullName>Cloud</fullName>
        <active>true</active>
        <description>For PC, PCC and PEC</description>
        <label>Cloud</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Subscription_Product__c.object
<CustomObject>
    <fields>
        <fullName>Amendment_For__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Stores previous subscription product from amended subscription
Downstream Impact? Effects reporting and billing integration 
Which department is owner? IT/PureCloud Team</description>
        <label>Amendment For</label>
        <referenceTo>Subscription_Product__c</referenceTo>
        <relationshipLabel>Amended To</relationshipLabel>
        <relationshipName>Amendment_For</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>What it Does?Line number of the line item
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>Line #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Stores the relation to quote product of the associated quote
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>Quote Product</label>
        <referenceTo>BigMachines__Quote_Product__c</referenceTo>
        <relationshipLabel>Subscription Products</relationshipLabel>
        <relationshipName>Subscription_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <description>What it Does? Stores parent subscription
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscription Products</relationshipLabel>
        <relationshipName>Subscription_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Product</label>
    <nameField>
        <displayFormat>SP-{000000000}</displayFormat>
        <label>Subscription Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateQuoteLineNumberforAmendment.cls
global class UpdateQuoteLineNumberforAmendment implements Database.Batchable<SObject>, Database.Stateful {
    DateTime dtRunDate;
    global UpdateQuoteLineNumberforAmendment(Date dtCreatedate){
        dtRunDate = dtCreatedate;
    }
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {   
        
        Util.Bypass_Trigger_Chk = true;
        User objUser = [SELECT BypassValidationRules__c,Bypass_Triggers__c,BypassWorkflows__c FROM User WHERE Id =: userinfo.getUserId()];
        objuser.Bypass_Triggers__c = true;
        objuser.BypassValidationRules__c = true;
        objuser.BypassWorkflows__c = true;
        update objuser;
        String strQuery = 'select id,Amendment_For__r.quote__c from BigMachines__Quote__c where order_type__C = \'Amend Subscription\' and createddate > :dtRunDate order by createddate desc';
        If(Test.isRunningTest()){
            strQuery = 'select id,(select id,BigMachines__Quote__r.Name,Line_Number__c,createddate from BigMachines__BigMachines_Quote_Products__r order by createddate asc) from BigMachines__Quote__c where order_type__C  = \'New Subscription\' and offering_type__c in (\'PureCloud\',\'PureConnect Cloud\',\'PureEngage Cloud\')and createddate > 2019-09-01T00:00:00z order by createddate desc limit 1';
        }
        return Database.getQueryLocator(strQuery);
    }    
    //*****Main Method***
    global void execute(Database.BatchableContext BC, List<SObject> sObjects) 
    {
        Set<Id> set_QPId = new Set<Id>();
        Util.Bypass_Trigger_Chk = true;
        User objUser = [SELECT BypassValidationRules__c,Bypass_Triggers__c,BypassWorkflows__c FROM User WHERE Id =: userinfo.getUserId()];
        objuser.Bypass_Triggers__c = true;
        objuser.BypassValidationRules__c = true;
        objuser.BypassWorkflows__c = true;
        update objuser;
        BigMachines__Quote__c objQuote = (BigMachines__Quote__c)sObjects[0];
        System.debug('objQuote:'+objQuote);
        List<BigMachines__Quote_Product__c> list_QPtoretrive = [select id,Line_Number__c,Subscription_Product__r.Quote_Product__r.Line_Number__c from BigMachines__Quote_Product__c where BigMachines__Quote__c =:objQuote.Id   order by createddate asc ];
        List<BigMachines__Quote_Product__c> list_OriginalQPtoretrive = [select id,Line_Number__c,Subscription_Product__r.Quote_Product__r.Line_Number__c from BigMachines__Quote_Product__c where BigMachines__Quote__c =:objQuote.Amendment_For__r.quote__c order by createddate asc ];
        Decimal decLineNumber = 1;
        List<BigMachines__Quote_Product__c> list_QPtoUpdate = new list<BigMachines__Quote_Product__c>();
        Map<Decimal,BigMachines__Quote_Product__c> map_lntoQP  = new Map<Decimal,BigMachines__Quote_Product__c>();
        for(BigMachines__Quote_Product__c objQP:list_OriginalQPtoretrive){
            if(objQP.Line_Number__c != null){map_lntoQP.put(objQP.Line_Number__c,objQP);}
            if(objQP.Subscription_Product__r.Quote_Product__r.Line_Number__c != null){map_lntoQP.put(objQP.Subscription_Product__r.Quote_Product__r.Line_Number__c,objQP);}
        }
        for(BigMachines__Quote_Product__c objQP:list_QPtoretrive){
            if(objQP.Line_Number__c != null && !map_lntoQP.containsKey(objQP.Line_Number__c)){map_lntoQP.put(objQP.Line_Number__c,objQP);}
            if(objQP.Subscription_Product__r.Quote_Product__r.Line_Number__c != null && !map_lntoQP.containsKey(objQP.Subscription_Product__r.Quote_Product__r.Line_Number__c)){map_lntoQP.put(objQP.Subscription_Product__r.Quote_Product__r.Line_Number__c,objQP);}
        }	
        
        for(BigMachines__Quote_Product__c objQP:list_QPtoretrive){
            System.debug('objQP:'+objQP);
            System.debug('decLinenumber:'+decLinenumber);
            System.debug('map_lntoQP.containsKey(decLinenumber):'+map_lntoQP.containsKey(decLinenumber));
            System.debug('objQP.Line_Number__c:'+objQP.Line_Number__c);
            System.debug('objQP.Subscription_Product__r.Quote_Product__r.Line_Number__c:'+objQP.Subscription_Product__r.Quote_Product__r.Line_Number__c);
            if(objQP.Line_Number__c !=  null || (objQP.Line_Number__c == null && objQP.Subscription_Product__r.Quote_Product__r.Line_Number__c != null)){
                if(objQP.Line_Number__c == null && objQP.Subscription_Product__r.Quote_Product__r.Line_Number__c != null){
                    objQP.Line_Number__c = objQP.Subscription_Product__r.Quote_Product__r.Line_Number__c;
                    list_QPtoUpdate.add(objQP);
                }
            }
            else
            {
                if(objQP.Line_Number__c == null ){
                    do{
                        decLinenumber++;
                    }while(map_lntoQP.containsKey(decLinenumber));
                    objQP.Line_Number__c = decLinenumber;
                    list_QPtoUpdate.add(objQP);
                }    
            }
            set_QPId.add(objQP.Id);
            
        }	
        
        System.debug('list_QPtoUpdate.size():'+list_QPtoUpdate.size());
        System.debug('list_QPtoUpdate'+list_QPtoUpdate);    
        Database.update(list_QPtoUpdate,false);
        list<Order_line_item__c> list_OLI=[select id,name,Line_Number__c,Quote_Product__r.Line_Number__c,createddate from Order_Line_Item__c where Quote_Product__c in :set_QPId and Quote_Product__r.Line_Number__c !=null and ORder__r.recordtypeid = '012U0000000MqMG'];
        for(Order_line_item__c objOLI:list_OLI){
            objOLI.Line_Number__c = objOLI.Quote_Product__r.Line_Number__c;
        }
        Database.update(list_OLI,false);
        list<Subscription_Product__c> list_SP=[select id,name,Line_Number__c,Quote_Product__r.Line_Number__c,createddate from Subscription_Product__c where Quote_Product__c in :set_QPId and Quote_Product__r.Line_Number__c !=null  and Subscription__r.offering_type__C in ('PureCloud','PureConnect Cloud','PureEngage Cloud')];
        for(Subscription_Product__c objSP:list_SP){
            objSP.Line_Number__c = objSP.Quote_Product__r.Line_Number__c;
        }
        Database.update(list_SP,false);
    }
    
    // *** Finish Method : Post Processing Logic ***
    global void finish(Database.BatchableContext BC) 
    {
        
    }     
    
    
}