objects/Bypass_Triggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Bypass flags for triggers</description>
    <label>Bypass Triggers</label>
</CustomObject>

objects/Global_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Information__c</fullName>
        <label>Information</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

objects/partner_portal_prospect__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Manager_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Channel Manager Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Portal Opportunity Registration (End User Account)</relationshipLabel>
        <relationshipName>Partner_Portal_Opportunity_Registration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Offer__c</fullName>
        <description>What it Does? Stores list of lead offers.
Downstream Impact? N/A 
Which department is owner? IT
DL 1/16/19 Requested to update label only to Lead Platform</description>
        <inlineHelpText>The combination of previous platform type &amp; offering type selections made to classify a deal registration</inlineHelpText>
        <label>Lead Platform</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Lead_Offer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Channel_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Filtered lookup based on region to User object to be used as Channel Manager for Opportunity Registration approval process in partner portal</description>
        <inlineHelpText>Please select Region before selecting Channel Manager</inlineHelpText>
        <label>Opportunity Channel Manager</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Employee_Region__c</field>
                <operation>equals</operation>
                <valueField>$Source.Regions__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Partner_Portal_Opportunity_Registration1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request Submitted</fullName>
                    <default>true</default>
                    <label>Request Submitted</label>
                </value>
                <value>
                    <fullName>Request Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Logo</fullName>
                </value>
                <value>
                    <fullName>Existing Business - Cross Sell</fullName>
                </value>
                <value>
                    <fullName>Existing Business - New Line of Business</fullName>
                </value>
                <value>
                    <fullName>Existing Business - Platform Migration</fullName>
                </value>
                <value>
                    <fullName>Existing Business - Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Existing Business - Expansion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_is_the_Expected_Close_Date__c</fullName>
        <label>What is the Expected Close Date?</label>
        <type>Date</type>
    </fields>
    <label>Partner Portal Opportunity Registration</label>
    <nameField>
        <label>Customer Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Opportunity Registration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Lead_Offer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PureCloud</fullName>
    </customValue>
    <customValue>
        <fullName>PureConnect Premise</fullName>
    </customValue>
    <customValue>
        <fullName>PureEngage Premise</fullName>
    </customValue>
    <customValue>
        <fullName>PureConnect Premise Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>PureEngage Premise Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>PureConnect Premise Rental</fullName>
    </customValue>
    <customValue>
        <fullName>PureEngage Premise Rental</fullName>
    </customValue>
    <customValue>
        <fullName>PureConnect Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>PureEngage Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>PureEngage Cloud Partner PPU</fullName>
    </customValue>
    <customValue>
        <fullName>PureConnect Cloud Partner PPU</fullName>
    </customValue>
    <customValue>
        <fullName>Premier Edition Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound Engagement Cloud</fullName>
    </customValue>
    <description>List of lead offers.</description>
    <masterLabel>Lead Offer</masterLabel>
</GlobalValueSet>

classes/PartnerPortalOptyRegUtilTest.cls
/*
Created By: Mukunthan Koothan
Created On: 23-APR-2018
Purpose: Test class for PartnerPortalOptyRegUtil class
*/
@isTest
public class PartnerPortalOptyRegUtilTest{

    public static testmethod void fetchSalesLeadTest(){

        Test.startTest();
        
            User currUser = [Select Id, Name, Bypass_Triggers__c from User where ID=:userinfo.getuserid()];
            currUser.Bypass_Triggers__c = true;
            System.runAs(currUser){
                recordtype rc = [select id from recordtype where developername = 'EMGBusinessPartnerRecordType' limit 1];
                
                Account a1 = new Account (Name = 'Holding Account', RecordTypeId=rc.id, Status__c='Active', PartnerType__c='Cloud Reseller;VAR' , Partner_Tier__c = 'Gold', Partner_Business_Size__c = 'MAJ'); 
                insert a1;
                
                partner_portal_prospect__c ppp = new partner_portal_prospect__c();
                ppp.Name = 'TestRec';
                ppp.Status__c = 'Request Submitted';
                ppp.End_User_Account__c = a1.Id;
                ppp.What_is_the_Expected_Close_Date__c = Date.Today() + 30;
                ppp.Opportunity_Channel_Manager__c = currUser.Id;
                insert ppp;
                
                Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                req.setObjectId(ppp.Id);
                Approval.ProcessResult processResult = Approval.process(req);
                System.assertEquals('Pending', processResult.getInstanceStatus());
                
                List<ProcessInstanceWorkitem> workItems = [SELECT Id, ProcessInstanceId 
                                                            FROM ProcessInstanceWorkitem 
                                                            WHERE ProcessInstance.TargetObjectId = :ppp.Id];
                List<Approval.ProcessWorkitemRequest> requests = new List<Approval.ProcessWorkitemRequest>();
                for(ProcessInstanceWorkitem workItem : workItems){
                Approval.ProcessWorkitemRequest req1 = new Approval.ProcessWorkitemRequest();
                req1.setWorkitemId(workItem.Id);
                req1.setAction('Approve');
                req1.setNextApproverIds(new Id[] {currUser.Id});
                req1.setComments('Your Comment.');
                requests.add(req1);
                }
                Approval.ProcessResult[] processResults = Approval.process(requests);
                
                //if(ppp.Status__c == 'Request Submitted' && ppp.Channel_Manager_Approved__c ==true){
                    PartnerPortalOptyRegUtil.fetchSalesLead(new string[] {ppp.Id});
                //}
            }
        Test.stopTest();
    
    }
    
    
    
public static testmethod void fetchoppsTest(){
        Test.startTest();
        
            User currUser = [Select Id, Name, Bypass_Triggers__c from User where ID=:userinfo.getuserid()];
            currUser.Bypass_Triggers__c = true;
            System.runAs(currUser){
                recordtype rc = [select id from recordtype where developername = 'EMGBusinessPartnerRecordType' limit 1];
                
                Account a1 = new Account (Name = 'Holding Account', RecordTypeId=rc.id, Status__c='Active', PartnerType__c='Cloud Reseller;VAR' , Partner_Tier__c = 'Gold', Partner_Business_Size__c = 'MAJ',Ownerid = userinfo.getuserid()); 
                insert a1;
                
                recordtype rc1 = [select id, Name from recordtype where name = 'Cloud Renewal'  limit 1];
                
                Opportunity  oppt = new Opportunity();
                oppt.Name = 'TestRec';               
                oppt.Accountid =  a1.id; 
                oppt.ownerid = userinfo.getuserid();
                oppt.CSM_GA_Opportunity_Owner__c =   userinfo.getuserid();            
                oppt.CloseDate  = Date.Today() + 30;
                oppt.StageName = '6.Closed';
                oppt.ForecastStatus__c = '0.Booked';
                oppt.RecordTypeid  = rc1.id;
                oppt.Lead_Offer__c ='PureEngage Premise';
                insert oppt;     
                list<opportunity> lstop = new list<opportunity> ();
                lstop.add(oppt);
                oppt.ForecastStatus__c = '1.In Hand';
                oppt.ownerid = userinfo.getuserid();
                update oppt;
                Map<id, Opportunity> mapop = new Map<id, Opportunity>();
                mapop.put(oppt.id,oppt );
                
                    global_setting__c cs = new global_setting__c();
                    cs.ID__c= rc1.id;
                    cs.Information__c= 'test';
                    cs.Type__c = 'test';
                    cs.Name = 'Cloud Renewal Opty recordtype';
                    insert cs;
                
                OpportunityTeamMember opptm = new OpportunityTeamMember();
                opptm.OpportunityId = oppt.id;
                opptm.UserId = oppt.ownerid;
                opptm.OpportunityAccessLevel = 'Edit';
                opptm.TeamMemberRole = 'Opportunity Owner';
                insert opptm;
                
               // PartnerPortalOptyRegUtil.updateopportunityclosedate(lstop , mapop );    
                PartnerPortalOptyRegUtil.updateopportunityteammember(lstop , mapop, 'insert' );
                
                PartnerPortalOptyRegUtil.updateopportunityteammember(lstop , mapop, 'update' );
                
                
                
            }
        Test.stopTest();
    } 
    }