objects/Bypass_Triggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Bypass flags for triggers</description>
    <label>Bypass Triggers</label>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CORE Model</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/DSR_Attachments__c.object
<CustomObject>
    <fields>
        <fullName>Access__c</fullName>
        <label>Access</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <label>Attachment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DSRSCEDesign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSR SCE Design</label>
        <referenceTo>DSR_SCE_Design__c</referenceTo>
        <relationshipLabel>DSR Attachments</relationshipLabel>
        <relationshipName>DSR_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DSRSCEngagement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSR SC Engagement</label>
        <referenceTo>DSR_SCEngagement__c</referenceTo>
        <relationshipLabel>DSR Attachments</relationshipLabel>
        <relationshipName>DSR_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateofAttachment__c</fullName>
        <label>Date of Attachment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ObjectType__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DSR Attachments</label>
    <nameField>
        <label>DSR Attachments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DSR Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DSR_Attachments_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <label>Attachment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ObjectType__c</fullName>
        <label>Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Design Attachment</fullName>
                </value>
                <value>
                    <fullName>Technical Design Attachment</fullName>
                </value>
                <value>
                    <fullName>Vision Activity</fullName>
                </value>
                <value>
                    <fullName>Discovery Activity</fullName>
                </value>
                <value>
                    <fullName>Delivery Requirements</fullName>
                </value>
                <value>
                    <fullName>Service Transition Activity</fullName>
                </value>
                <value>
                    <fullName>Design Activity</fullName>
                </value>
                <value>
                    <fullName>Technical Design</fullName>
                </value>
                <value>
                    <fullName>Business Design</fullName>
                </value>
                <value>
                    <fullName>Partner Delivery Requirements</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URLRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>URL Required</label>
        <type>Checkbox</type>
    </fields>
    <label>DSR Attachments Definition</label>
    <nameField>
        <label>DSR Attachments Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DSR Attachments Definition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DSR_SCE_Design__c.object
<CustomObject>
    <fields>
        <fullName>DSR_SCEngagement__c</fullName>
        <label>DSR SCEngagement</label>
        <referenceTo>DSR_SCEngagement__c</referenceTo>
        <relationshipLabel>DSR SCE Designs</relationshipLabel>
        <relationshipName>DSR_SCE_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DSR SCE Design</label>
    <nameField>
        <displayFormat>SCEDES - {000000}</displayFormat>
        <label>Design ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR SCE Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DSR_SCEngagement__c.object
<CustomObject>
    <fields>
        <fullName>AE_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DSR_SCEngagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>DSR_SCEngagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AssignTo__c</fullName>
        <label>AssignTo</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity ID</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>DSR_SCEngagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SC_Engagement_Status__c</fullName>
        <label>SC Engagement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open and Assigned</fullName>
                </value>
                <value>
                    <fullName>Open and Not Assigned</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted for Completion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DSR SC Engagement or Partner SMART DSR</label>
    <nameField>
        <displayFormat>SCE - {00000}</displayFormat>
        <label>SC DSR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR SC Engagements or Partner SMART DSRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DSR_Virtual_Team__c.object
<CustomObject>
    <fields>
        <fullName>IsPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPrimary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCE_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SCE ID</label>
        <referenceTo>DSR_SCEngagement__c</referenceTo>
        <relationshipLabel>DSR Virtual Teams</relationshipLabel>
        <relationshipName>DSR_Virtual_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <label>Sub Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Virtual_Team_Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Team Member Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DSR_Virtual_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Virtual_User_Role__c</fullName>
        <label>Virtual User Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sub Regional Leader</fullName>
                </value>
                <value>
                    <fullName>Virtual Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DSR Virtual Team</label>
    <nameField>
        <displayFormat>SCVT - {00000}</displayFormat>
        <label>SC Virtual Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR Virtual Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DSRSolutioOverviewCtlrTest.cls
/***************************************************************************************************
* 
*  Class Name      :   DSRSolutioOverviewCtlrTest
*  Description     :   This class is used to unit test the DSRSolutioOverviewCtlr
*  Auther          :   R Systems
* 
****************************************************************************************************/
@isTest(seealldata=true)
private class DSRSolutioOverviewCtlrTest {

    private static testMethod void testFirst() {
        //Create Account          
        List<Account> lstAcc=TestUtil.createAccounts(1,true);
           
        //find current user          
        user objUser=[SELECT Id,Bypass_Triggers__c FROM User WHERE Id=:userinfo.getUserId()];  
        objUser.Bypass_Triggers__c = true;
        update objUser;  
        //find  country
        country__c objCountry=[SELECT ID,Region__c FROM country__c WHERE Name=:'New Zealand'] ;   
       
        DSR_Attachments_Definition__c objDataDef_Attch = new DSR_Attachments_Definition__c();
        objDataDef_Attch.Active__c = true;
        objDataDef_Attch.AttachmentType__c = 'Bill of Material';
        objDataDef_Attch.ObjectType__c = 'Technical Design Attachment';
        objDataDef_Attch.URLRequired__c = false;
        insert objDataDef_Attch;
        
        Opportunity ObjOpp  = TestUtil.createOpportunities(1,lstAcc[0].id, false)[0];
        ObjOpp.Lines_of_Businesses__c = 'PureCloud';
        insert ObjOpp;
        
        DSR_SCEngagement__c dsr = new DSR_SCEngagement__c();
        dsr.Account_ID__c = lstAcc[0].Id;
        dsr.AE_Name__c = objUser.Id;
        dsr.AssignTo__c = 'Lead Assign';
        dsr.Opportunity_ID__c = ObjOpp.Id;
        dsr.SC_Engagement_Status__c = 'Open and Not Assigned';
        
        insert dsr;
        
        
        DSR_Virtual_Team__c dsrvT = new DSR_Virtual_Team__c();
        dsrvT.SCE_ID__c = dsr.Id;
        dsrvT.Virtual_Team_Member_Name__c = objUser.Id;
        dsrvT.Region__c = 'Region';
        dsrvT.Sub_Region__c = 'Sub Region';
        dsrvT.Segment__c = 'Segment';
        dsrvT.Virtual_User_Role__c = 'Sub Regional Leader';
        
        insert dsrvT;
        
        DSR_Virtual_Team__c dsrvT1 = new DSR_Virtual_Team__c();
        dsrvT1.SCE_ID__c = dsr.Id;
        dsrvT1.Virtual_Team_Member_Name__c = objUser.Id;
        dsrvT1.Region__c = 'Region';
        dsrvT1.Sub_Region__c = 'Sub Region';
        dsrvT1.Segment__c = 'Segment';
        dsrvT1.Virtual_User_Role__c = 'Virtual Team';
        
        insert dsrvT1;
        
        /*DSR_Activity__c dsrA = new DSR_Activity__c();
        dsrA.SubModule__c = 'Service Transition Activity';
        dsrA.header__c = 'Test';
        dsrA.Module__c = 'Deliver';
        dsrA.ActivityDate__c = date.today();
        dsrA.Access__c = 'Partner';
        dsrA.SCEID__c = dsr.Id;
        
        insert dsrA;

        DSR_Activity__c dsrA1 = new DSR_Activity__c();
        dsrA1.SubModule__c = 'Delivery Requirements';
        dsrA1.header__c = 'Test';
        dsrA1.Module__c = 'Deliver';
        dsrA1.ActivityDate__c = date.today();
        dsrA1.Access__c = 'Partner';
        dsrA1.SCEID__c = dsr.Id;
        insert dsrA1;
        
        DSR_Activity__c dsrA2 = new DSR_Activity__c();
        dsrA2.SubModule__c = 'Delivery Requirements';
        dsrA2.header__c = 'Test';
        dsrA2.Module__c = 'Discovery';
        dsrA2.ActivityDate__c = date.today();
        dsrA2.Access__c = 'Partner';
        dsrA2.SCEID__c = dsr.Id;
        insert dsrA2;
        
        DSR_Activity__c dsrA3 = new DSR_Activity__c();
        dsrA3.SubModule__c = 'Delivery Requirements';
        dsrA3.header__c = 'Test';
        dsrA3.Module__c = 'Design';
        dsrA3.ActivityDate__c = date.today();
        dsrA3.Access__c = 'Partner';
        dsrA3.SCEID__c = dsr.Id;
        insert dsrA3;
        
        DSR_Activity__c dsrA4 = new DSR_Activity__c();
        dsrA4.SubModule__c = 'Delivery Requirements';
        dsrA4.header__c = 'Test';
        dsrA4.Module__c = 'Vision';
        dsrA4.ActivityDate__c = date.today();
        dsrA4.Access__c = 'Partner';
        dsrA4.SCEID__c = dsr.Id;
        
        insert dsrA4;*/
        
        DSR_SCE_Design__c design = new DSR_SCE_Design__c();
        design.DSR_SCEngagement__c = dsr.Id;
        design.Name__C = 'Test';
        design.IsPrimary__c = true;
        insert design;
        
        List<DSR_Attachments__c>lst_Act = new List<DSR_Attachments__c>();
        
        DSR_Attachments__c objActivity1 = new DSR_Attachments__c();
        objActivity1.DSRSCEDesign__c = design.id;
        objActivity1.DSRSCEngagement__c = dsr.id;
        objActivity1.ObjectType__c = 'Vision Activity';
        objActivity1.AttachmentType__c = 'aa';
        objActivity1.Description__c ='aa';
        objActivity1.DateofAttachment__c = Date.Today();
        lst_Act.add(objActivity1);
        
        DSR_Attachments__c objActivity2 = new DSR_Attachments__c();
        objActivity2.DSRSCEDesign__c = design.id;
        objActivity2.DSRSCEngagement__c = dsr.id;
        objActivity2.ObjectType__c = 'Delivery Requirements';
        objActivity2.AttachmentType__c = 'aa';
        objActivity2.Description__c ='aa';
        objActivity2.DateofAttachment__c = Date.Today();
        lst_Act.add(objActivity2);
        
        DSR_Attachments__c objActivity3 = new DSR_Attachments__c();
        objActivity3.DSRSCEDesign__c = design.id;
        objActivity3.DSRSCEngagement__c = dsr.id;
        objActivity3.ObjectType__c = 'Design Activity';
        objActivity3.AttachmentType__c = 'aa';
        objActivity3.Description__c ='aa';
        objActivity3.DateofAttachment__c = Date.Today();
        lst_Act.add(objActivity3);
        
        DSR_Attachments__c objActivity4 = new DSR_Attachments__c();
        objActivity4.DSRSCEDesign__c = design.id;
        objActivity4.DSRSCEngagement__c = dsr.id;
        objActivity4.ObjectType__c = 'Discovery Activity';
        objActivity4.AttachmentType__c = 'aa';
        objActivity4.Description__c ='aa';
        objActivity4.DateofAttachment__c = Date.Today();
        lst_Act.add(objActivity4);
        
        insert lst_Act;
        
        ApexPages.currentPage().getParameters().put('id', dsr.Id);
        
        DSRSolutioOverviewCtlr dsrCtlr = new DSRSolutioOverviewCtlr();
        dsrCtlr.postSolutionOverview();
    }

}