objects/ca2cq_categories_To_Topic__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>DataCategoryName__c</fullName>
        <label>DataCategoryName</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TopicName__c</fullName>
        <label>Topic Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Categories To Topic</label>
</CustomObject>

objects/ca2cq_config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Batch_size__c</fullName>
        <defaultValue>200</defaultValue>
        <description>Number of questions the batch process will retrieve per batch execution</description>
        <inlineHelpText>This number delimits the number of questions, have in mind that we estimate 2Q + 2x500Q</inlineHelpText>
        <label>Batch Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exclude_this_Ids__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Comma separated list of the record ids to exclude from migration</description>
        <label>Exclude this Ids</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_this_Ids__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Id of the question records to migrate</description>
        <inlineHelpText>Comma separated list of the record ids to include in the migration</inlineHelpText>
        <label>Include this Ids</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_email__c</fullName>
        <description>Email address for receiving notifications after each execution</description>
        <inlineHelpText>Email address for receiving notifications after each execution</inlineHelpText>
        <label>Notification</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Question_Ids__c</fullName>
        <inlineHelpText>Id of questions to include or exclude from migration</inlineHelpText>
        <label>Question Ids</label>
        <type>TextArea</type>
    </fields>
    <label>Migration Config</label>
</CustomObject>

objects/ca2cq_Zone_community__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds mapping between original Zone id and final community Id</description>
    <fields>
        <fullName>Active_for_Migration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active for Migration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Community_Id__c</fullName>
        <description>Id of the community that will host new Question Feeds</description>
        <inlineHelpText>Id of the community that will host new Question Feeds</inlineHelpText>
        <label>Community Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zoneId__c</fullName>
        <description>ID of the original Chatter Answers Zone</description>
        <inlineHelpText>ID of the original Chatter Answers Zone</inlineHelpText>
        <label>Original Chatter Zone Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Zone to Community</label>
</CustomObject>

classes/ca2cq_setupCtr_Test.cls
@isTest
private class  ca2cq_setupCtr_Test {

	static void populateSettings(){
		ca2cq_config__c obj = ca2cq_util.getAppSettings();
		obj.Notification_email__c = 'SOMe@test.org';
		upsert obj;

		Map<Id,Community> comm =  ca2cq_util.allCommunities();
		list<ca2cq_Zone_community__c> lista =  ca2cq_util.getAppCommunityMappings();
		for(ca2cq_Zone_community__c c : lista){
			c.Active_for_Migration__c = true;
			ID tmp = c.zoneId__c;
			if (comm.containsKey(tmp)){
				c.Community_Id__c = comm.get(tmp).NetworkId;
				if (!String.isNotBlank(c.Community_Id__c)){
					c.Community_Id__c = 'null';
				}
			}
		}
		upsert lista;
        
        //map dc to topics
        List<ca2cq_categories_To_Topic__c> dc2t = new List<ca2cq_categories_To_Topic__c>();
        for(Integer h = 0; h<3 ; h++){
           dc2t.add(new ca2cq_categories_To_Topic__c(
                            Name = 'dc_t_'+h,
                            DataCategoryName__c = 'dc_'+h,
                            TopicName__c = 't_'+h
           ));
        }
		insert dc2t;
	}

	static testMethod void test_ca2cq_setupCtr(){

		populateSettings();

		ca2cq_setupCtr ctr = new ca2cq_setupCtr();
		System.assertNotEquals(ctr.setupObj, null);
		System.assertNotEquals(ctr.setupObj.Notification_email__c, 'SOMe@test.org');

		System.assertNotEquals(ca2cq_setupCtr.allCommunities, null);
		System.assertNotEquals(ca2cq_setupCtr.allNetworkList, null);
		System.assertNotEquals(ca2cq_setupCtr.lastLog, null);
		System.assertNotEquals(ca2cq_setupCtr.topicsMaps, null);

		System.assertNotEquals(ctr.zonesMap, null);

		System.assertEquals(ctr.getCanStartProcess(), true);
		System.assertEquals(ctr.getIsProcessRunning(), false);
		System.assertNotEquals('XXX',ca2cq_setupCtr.questionIDPrefix);

	}

	@isTest(SeeAllData=true)
	static  void test_save(){

		populateSettings();

		System.Test.startTest();


		PageReference pageRef = Page.ca2cq_setup;
		// populate mapd from Zone to Community        
		String allC ='';
		for (Community c : [SELECT Id FROM Community  ]){
			allC +=','+c.Id+':'+c.Id+':1';
		}
		pageRef.getParameters().put('zonesMap',allC);
		
		// populate mapd from DataCategory to Topic        
		String dcTop ='';
        for(Integer h = 0; h<5 ; h++){
            dcTop +=',dc'+h+':topic'+h;
        }
		pageRef.getParameters().put('topicsMaps',dcTop);
        
        System.Test.setCurrentPage(pageRef);

		ca2cq_setupCtr ctr = new ca2cq_setupCtr();
		ctr.setupObj.Batch_size__c = 53;
		ctr.save();

		System.Test.stopTest();

		list<ca2cq_Zone_community__c> mapps = ca2cq_Zone_community__c.getAll().values();
		for(ca2cq_Zone_community__c ca : mapps){
			System.assertEquals(ca.zoneId__c,ca.Community_Id__c);
		}

		system.assertEquals(53,ca2cq_util.getBatchSize());
	}


	@isTest(SeeAllData=true)
	static  void test_save_questionId(){

			populateSettings();
			System.Test.startTest();

			//add ids to include
			List<Question> qL = [Select Id,CommunityId from Question ORDER BY Id limit 2];

			if (qL.size() > 0) {
					List<String> idL = new List<String>();
					List<Id> selZones = new List<Id>();
					for(Question q : qL){
						idL.add(q.Id);
						selZones.add(q.CommunityId);
					}
					Set<String> setIdL = new Set<String>(idL);

					String idString = String.join(idL,',');
                	String zonesString ='';
					for(String zId : selZones){
						zonesString+=zId+':null:1,';
					}
                	System.debug('idString:' + idString);

					PageReference pageRef = Page.ca2cq_setup;

					pageRef.getParameters().put('zonesMap',zonesString);
					system.debug('\n zonesString: '+zonesString);
					pageRef.getParameters().put('questionIdList',idString);
					pageRef.getParameters().put('whichQuestions','includeThis');
					System.Test.setCurrentPage(pageRef);

					ca2cq_setupCtr ctr = new ca2cq_setupCtr();
					ctr.save();

					System.Test.stopTest();

					ca2cq_config__c obj = ca2cq_util.getAppSettings();
					system.assert(!obj.Exclude_this_Ids__c , 'Exclude Ids should be false');
					system.assert(obj.Include_this_Ids__c , 'Include Ids should be false');

					system.assertEquals(obj.Question_Ids__c ,idString, 'List of Ids should match');
			}
	}

	static testMethod void test_launchBatch_noSetup(){

		 System.Test.startTest();

		ca2cq_setupCtr ctr = new ca2cq_setupCtr();
		ctr.launchBatch();
		System.assertEquals(ctr.getCanStartProcess(), false);
		System.assertEquals(ctr.getIsProcessRunning(), false);

		System.Test.stopTest();
	}

	static testMethod void test_launchBatch (){
		populateSettings();

		System.Test.startTest();

		ca2cq_setupCtr ctr = new ca2cq_setupCtr();
		ctr.launchBatch();

		System.assertEquals(ctr.getCanStartProcess(), false);
		System.assertEquals(ctr.getIsProcessRunning(), true);

		System.Test.stopTest();
	}

}