objects/Cases_Closed_By_Default_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <externalId>true</externalId>
        <label>Case Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Owner__c</fullName>
        <label>Case Owner</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases Closed By Default Details</relationshipLabel>
        <relationshipName>Cases_Closed_By_Default_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <externalId>true</externalId>
        <label>Period</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Cases Closed By Default Detail</label>
    <nameField>
        <label>Cases Closed By Default Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases Closed By Default Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CasesClosedByDefaultController.cls
public class CasesClosedByDefaultController {
	
    public List<CCBDDetail> CCBDDetails {get; set;}
    public String period {get; set;}
    public String accountId {get; set;}
    public CasesClosedByDefaultController(){
        period = ApexPages.currentPage().getParameters().get('period');
        accountId = ApexPages.currentPage().getParameters().get('aId');

        CCBDDetails = new List<CCBDDetail>();
        for(Cases_Closed_By_Default_Detail__c cdetails : [SELECT id, Name, Case_Number__c, Contact_Name__c, Case_Owner__c FROM Cases_Closed_By_Default_Detail__c WHERE Partner_Account__c = :accountId AND Period__c = :period Order By Contact_Name__c,Case_Number__c]){
            CCBDDetails.add(new CCBDDetail(cdetails.Case_Number__c, cdetails.Contact_Name__c, cdetails.Case_Owner__c));
        }    
    }
    
    public class CCBDDetail{
        public String caseNumber { get; set; }
        public String contactName { get; set; }
        public String ownerName { get; set; }
        public CCBDDetail(String caseNumber, String contactName, String ownerName) {
            this.caseNumber = caseNumber;
            this.contactName = contactName;
            this.ownerName = ownerName;
        }
    }
}