objects/Case_Escalation__c.object
<CustomObject>
    <fields>
        <fullName>Account_Escalation_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escalation Owner</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Email</field>
                <operation>contains</operation>
                <value>@genesys.com</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>AccntOwner_Escalations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Escalations</relationshipLabel>
        <relationshipName>Case_Escalations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Escalations</relationshipLabel>
        <relationshipName>Account_Case_Escalations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TAM/Manager</fullName>
                </value>
                <value>
                    <fullName>Leader/Director</fullName>
                </value>
                <value>
                    <fullName>VP</fullName>
                </value>
                <value>
                    <fullName>EVP</fullName>
                </value>
                <value>
                    <fullName>CSO</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Analyst Soft Skills Issue</fullName>
                </value>
                <value>
                    <fullName>Internal Genesys Delays</fullName>
                </value>
                <value>
                    <fullName>No Action Required</fullName>
                </value>
                <value>
                    <fullName>Priority Change Request</fullName>
                </value>
                <value>
                    <fullName>Product Issue/Limitation</fullName>
                </value>
                <value>
                    <fullName>Project Blocker</fullName>
                </value>
                <value>
                    <fullName>Recurring Issue</fullName>
                </value>
                <value>
                    <fullName>Require Update</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Security/Stability Issue</fullName>
                </value>
                <value>
                    <fullName>SLT</fullName>
                </value>
                <value>
                    <fullName>Timezone Concern</fullName>
                </value>
                <value>
                    <fullName>Urgent Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Escalation</label>
    <nameField>
        <displayFormat>ESC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Escalations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CaseMngrAttentionController.cls
public class CaseMngrAttentionController {
        
        public Integer esclNum {get; set;}
        public List<Case_Escalation__c> EsclRec {get; set;}
        public List<Case_Escalation__c> escls  {get; set;}
        
        public CaseMngrAttentionController(ApexPages.StandardController stdController)  {
                String csId = Apexpages.currentPage().getParameters().get('Id');
                
                esclNum = 0;

                                
                if ( csId != null && String.isNotBlank(csId) ) {
                    escls = [SELECT Id,Name,Account_Escalation_Owner__r.Name,Level__c,Reason__c,Status__c
                                 FROM Case_Escalation__c WHERE Status__c = 'Open'
                                 AND End_User_Account__c IN (SELECT End_User_Account__c FROM Case WHERE id = :csId )];                                                         
                        esclNum = escls.size(); 
                    
                    EsclRec    = [SELECT Id,Name,Account_Escalation_Owner__r.Name,Level__c,Reason__c,Status__c
                                  FROM Case_Escalation__c WHERE Case__c=:csId AND  Status__c != 'Closed']; 
                }
                
        }
    
}