objects/Cloud_Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Downstream Impact: CM and Cloud Billing
Department Owner: CM
Help Text: Used to reference the Account for this Cloud Deployment</description>
        <inlineHelpText>Used to reference the Account for this Cloud Deployment</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cloud Deployments (Account)</relationshipLabel>
        <relationshipName>Account_Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cloud_Platform__c</fullName>
        <label>Cloud Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PureEngage Cloud</fullName>
                </value>
                <value>
                    <fullName>PureConnect Cloud</fullName>
                </value>
                <value>
                    <fullName>PureCloud</fullName>
                </value>
                <value>
                    <fullName>Outbound Engagement</fullName>
                </value>
                <value>
                    <fullName>Premier Edition</fullName>
                </value>
                <value>
                    <fullName>SpeechStorm</fullName>
                </value>
                <value>
                    <fullName>PureEngage Subscription</fullName>
                </value>
                <value>
                    <fullName>PureConnect Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offering_Type__c</fullName>
        <formula>Text(Opportunity__r.Lines_of_Businesses__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offering Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cloud Deployments</relationshipLabel>
        <relationshipName>Cloud_Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Same as Account in case of direct relationship.</inlineHelpText>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cloud Deployments (Sold To Account)</relationshipLabel>
        <relationshipName>Cloud_Deployments_ST</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Implementation Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deployment</fullName>
                </value>
                <value>
                    <fullName>UAT</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                    <default>true</default>
                    <label>Production</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Status__c</fullName>
        <label>Support Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Billing Only</fullName>
                </value>
                <value>
                    <fullName>Order Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cloud Deployment</label>
    <nameField>
        <label>Cloud Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cloud Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders(Revenue/Non-Revenue)</relationshipLabel>
        <relationshipName>End_User_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offering_Type__c</fullName>
        <formula>IF(CONTAINS(Quote__r.Offering_Type__c,&apos;Subscription&apos;), Quote__r.Offering_Type__c,

IF(Text(Opportunity__r.Lines_of_Businesses__c) == &apos;Business Edition&apos; &amp;&amp; 
(RecordType.Name == &apos;Cloud Billing Master Order&apos; || RecordType.Name == &apos;Cloud Monthly Billing Order&apos;),
&apos;PureEngage&apos;,  TEXT(Opportunity__r.Lines_of_Businesses__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offering Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order (Sold To)</relationshipLabel>
        <relationshipName>Sold_To_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BatchUpdateAccountOfferingType_Test.cls
@isTest
public class BatchUpdateAccountOfferingType_Test{

    static testMethod void BatchUpdateAccountOfferingType_unitTest(){
        
        Id emgRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('EMG - Customer Record Type').getRecordTypeId();
        
        Account acc = new Account();
        acc.name = 'Test';
        acc.recordTypeId = emgRecordTypeId;
        insert acc;
        
        Account acc1 = new Account();
        acc1.name = 'Test';
        acc1.recordTypeId = emgRecordTypeId;
        insert acc1;
        
        Contact con = new Contact();
        con.lastname = 'test contact';
        con.accountId = acc.id;
        insert con;
        
        Opportunity testOpp = TestUtil.createOpportunities(1, true)[0];
        BigMachines__Quote__c testQuote = TestUtil.createQuotes(1, true)[0];
        Order__c testOrder = TestUtil.createOrders(1, testQuote.id, testOpp.id, true)[0];
        
        List<ServiceContract> list_SC = new List<ServiceContract>();
        
        ServiceContract testSC = TestUtil.createServiceContracts(1, false)[0];
        testSC.Agreement_Status__c = 'Active';
        testSC.Override_Offering_Type__c = 'PureEngage';
        testSC.End_User_Name__c = acc.id;
        testSC.Sold_To_Name__c =acc1.id;
        testSC.AccountId = acc.id;
        list_SC.add(testSC);
        
        ServiceContract testSC1 = TestUtil.createServiceContracts(1, false)[0];
        testSC1.Agreement_Status__c = 'Active';
        testSC1.Override_Offering_Type__c = 'PureEngage';
        testSC1.End_User_Name__c = acc.id;
        testSC1.Sold_To_Name__c =acc.id;
        testSC1.AccountId = acc.id;
        list_SC.add(testSC1);
        
        ServiceContract testSC2 = TestUtil.createServiceContracts(1, false)[0];
        testSC2.Agreement_Status__c = 'Closed';
        testSC2.Override_Offering_Type__c = 'PureEngage';
        testSC2.End_User_Name__c = acc.id;
        testSC2.AccountId = acc.id;
        testSC2.Sold_To_Name__c =acc.id;
        list_SC.add(testSC2);
        
        ServiceContract testSC3 = TestUtil.createServiceContracts(1, false)[0];
        testSC3.Agreement_Status__c = 'Closed';
        testSC3.Override_Offering_Type__c = 'PureEngage';
        testSC3.End_User_Name__c = acc.id;
        testSC3.Sold_To_Name__c =acc1.id;
        testSC3.AccountId = acc.id;
        list_SC.add(testSC3);
        
        insert list_SC;
        
        List<Cloud_Deployment__c> list_CD = new List<Cloud_Deployment__c>();
        Cloud_Deployment__c deplTo = new Cloud_Deployment__c();
        deplTo.Support_Status__c = 'Active';
        deplTo.Account__c = acc.id;
        deplTo.Sold_To_Account__c = acc.id;
        deplTo.Status__c = 'Production';
        deplTo.Cloud_Platform__c = 'PureConnect Subscription';   
        list_CD.add(deplTo); 
        
        Cloud_Deployment__c deplTo1 = new Cloud_Deployment__c();
        deplTo1.Support_Status__c = 'Active';
        deplTo1.Account__c = acc1.id;
        deplTo1.Sold_To_Account__c = acc.id;
        deplTo1.Status__c = 'Production';
        deplTo1.Cloud_Platform__c = 'Outbound Engagement';   
        list_CD.add(deplTo1);
        
        Cloud_Deployment__c deplTo2 = new Cloud_Deployment__c();
        deplTo2.Support_Status__c = 'InActive';
        deplTo2.Account__c = acc.id;
        deplTo2.Sold_To_Account__c = acc.id;
        deplTo2.Status__c = 'Production';
        deplTo2.Cloud_Platform__c = 'PureEngage Subscription';   
        list_CD.add(deplTo2); 
        
        Cloud_Deployment__c deplTo3 = new Cloud_Deployment__c();
        deplTo3.Support_Status__c = 'InActive';
        deplTo3.Account__c = acc1.id;
        deplTo3.Sold_To_Account__c = acc.id;
        deplTo3.Status__c = 'Production';
        deplTo3.Cloud_Platform__c = 'Premier Edition';   
        list_CD.add(deplTo3);
        
        insert list_CD;
        
        
        Test.startTest();
        BatchUpdateAccountOfferingType bc = new BatchUpdateAccountOfferingType();
        Database.executeBatch(bc);
        Test.stopTest();
        
        Contact newCon = [SELECT Id, Primary_offering__c, Additional_Offering__c, Account.Offering_Type__c FROM Contact WHERE Id =: con.Id];
        System.assert(newCon.Primary_offering__c != null);
    }
}