objects/Cloud_Billing_Log__c.object
<CustomObject>
    <description>Logs related to Billing (Formerly Cloud Billing)</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>GCR_Content_Document_Detail__c</referenceTo>
        <relationshipName>Cloud_Billing_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Billing Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Billing Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract_Tier_Set__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>GCR_Content_Document_Detail__c</referenceTo>
        <relationshipLabel>Contract Tier Sets</relationshipLabel>
        <relationshipName>Contract_Tier_Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Tier Set</label>
    <nameField>
        <label>Contract Tier Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Tier Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract_Tier_Set_Month__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Tier_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Tier Set</label>
        <referenceTo>Contract_Tier_Set__c</referenceTo>
        <relationshipLabel>Contract Tier Set Month</relationshipLabel>
        <relationshipName>Contract_Tier_Set_Month</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Contract Tier Set Month</label>
    <nameField>
        <displayFormat>CTM-{000000}</displayFormat>
        <label>Contract Tier Set Month Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Tier Set Month</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Tier_Set_Month__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Cloud Billing. If this Order Line Item was created from a Contract Tier Set Month, store its reference here</description>
        <inlineHelpText>Cloud Billing. If this Order Line Item was created from a Contract Tier Set Month, store its reference here</inlineHelpText>
        <label>Contract Tier Set Month</label>
        <referenceTo>Contract_Tier_Set_Month__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Downstream Impact: Only used for Cloud Billing
Department Owner: Cloud Billing
Help Text: Used to store and bill for the number of gigabytes in usage data
Used to store and bill for the quantity of items in the Order Line</description>
        <inlineHelpText>Used to store and bill for the quantity of items in the Order Line (Quantity__c)</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Status__c</fullName>
        <description>Cloud Billing.flag to indicate that this Order Line Item requires taxation through a taxation service</description>
        <inlineHelpText>Cloud Billing.flag to indicate that this Order Line Item requires taxation through a taxation service</inlineHelpText>
        <label>Tax Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SureTax Needed</fullName>
                </value>
                <value>
                    <fullName>Tax Complete</fullName>
                </value>
                <value>
                    <fullName>No Tax Returned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Rolled_Up_Usage_Data__c.object
<CustomObject>
    <fields>
        <fullName>Billable_60__c</fullName>
        <description>Number of billable seconds (rounded up to 60 seconds)</description>
        <label>Billable 60</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <description>Number of messages included in this rollup</description>
        <label>Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>Service Type of activity</description>
        <label>Service Type</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Rolled Up Usage Data</label>
    <nameField>
        <displayFormat>RUD-{0000000}</displayFormat>
        <label>Rolled Up Usage Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rolled Up Usage Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Tier_Set_Month__c</fullName>
        <label>Contract Tier Set Month</label>
        <referenceTo>Contract_Tier_Set_Month__c</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <description>Cost of outbound call</description>
        <label>Cost</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <description>Directly Stored values from RUUD.Count</description>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Number of units - either messages or minutes</description>
        <label>Quantity</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rolled_Up_Usage_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rolled Up Usage Data</label>
        <referenceTo>Rolled_Up_Usage_Data__c</referenceTo>
        <relationshipLabel>Service Usage</relationshipLabel>
        <relationshipName>Service_Usage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax_Status__c</fullName>
        <description>If the record needs to be taxed a series of status information to assist tax processing
Downstream Impact: Used under the assumption of SureTax, may need to add new picklist values if additional taxing software is implemented.
Department Owner: Cloud Billing</description>
        <inlineHelpText>If the record needs to be taxed a series of status information to assist tax processing</inlineHelpText>
        <label>Tax Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rollup Tax Needed</fullName>
                </value>
                <value>
                    <fullName>Rollup Tax Completed</fullName>
                </value>
                <value>
                    <fullName>Tax Calculated</fullName>
                </value>
                <value>
                    <fullName>Tax Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Usage</label>
    <nameField>
        <displayFormat>SU-{000000}</displayFormat>
        <label>Service Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Usage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Usage_Tax__c.object
<CustomObject>
    <description>Tax records related to the service usage.</description>
    <fields>
        <fullName>Rolled_Up_Usage_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Owner: Cloud Billing
Parent Relationship to Rolled Up Usage Data</description>
        <inlineHelpText>Owner: Cloud Billing
Parent Relationship to Rolled Up Usage Data</inlineHelpText>
        <label>Rolled Up Usage Data</label>
        <referenceTo>Rolled_Up_Usage_Data__c</referenceTo>
        <relationshipLabel>Service Usage Taxes</relationshipLabel>
        <relationshipName>Rolled_Up_Usage_Data_Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Usage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Usage</label>
        <referenceTo>Service_Usage__c</referenceTo>
        <relationshipLabel>Service Usage Taxes</relationshipLabel>
        <relationshipName>Service_Usage_Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Type_Code__c</fullName>
        <description>The tax type code</description>
        <inlineHelpText>The tax type code</inlineHelpText>
        <label>Tax Type Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Service Usage Tax</label>
    <nameField>
        <displayFormat>SUT-{000000000}</displayFormat>
        <label>Service Usage Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Usage Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchTaxCloudUsageDataTest.cls
@isTest
public class BatchTaxCloudUsageDataTest {
    @testSetup
    public static void setUpData() {
        List<SureTax_Settings__c> list_SureTaxSettings = SureTaxSettingsFactory.createDefaultSureTaxSettings();//BatchCreateCloudMonthlySalesOrdersTest.setupSureTaxSettings();
		insert list_SureTaxSettings;

        Util.Bypass_Trigger_Chk = true;
        GCR_Content_Document_Detail__c objContract = CloudBillingTestUtil.createAndInsertCloudBillingContract(new List<Rolled_Up_Usage_Data__c>());
        CloudBillingTestUtil.insertRuud();
        List<Rolled_Up_Usage_Data__c> listRUUD = [select Id, Count__c, Billable_60__c, Service_Type__c from Rolled_Up_Usage_Data__c];
        if (listRUUD.size() > 1) {
            
            Rolled_Up_Usage_Data__c objRUUD = listRUUD[0];
            System.Debug('First Rudd ' + objRUUD);
            
            List<Contract_Tier_Set__c> listCTS = new List<Contract_Tier_Set__c>();
            Contract_Tier_Set__c objCTS = new Contract_Tier_Set__c(Contract__c = objContract.Id);
            insert objCTS;
            listCTS.add(objCTS);
            
            TestCloudBilling.getListTierSetMonth(1);
            // Above method inserts 2 SU's Contract Tier Set Month and Contract Tier Set
            List<Service_Usage__c> listSU = [select Count__c,
                                             Quantity__c,
                                             Cost__c,
                                             Service_Type__c,
                                             Contract_Tier_Set_Month__c
                                             from Service_Usage__c];
            if (listSU == null && listSU.size() == 0) {
                System.Assert(false);
            }
            Service_Usage__c objSU = listSU[0];
            objSU.Rolled_Up_Usage_Data__c = objRUUD.Id;
            objSU.Tax_Status__c = BatchTaxCloudUsageData.TAX_STATUS_ROLLUP_TAX_NEEDED;
            update objSU;
            
			List<Service_Usage_Tax__c> listServiceUsageTaxToInsert = new List<Service_Usage_Tax__c>();
            Service_Usage_Tax__c objServiceUsageTax = new Service_Usage_Tax__c(Rolled_Up_Usage_Data__c = objRUUD.Id,
                                                                               Service_Usage__c = objSU.id,
                                                                               Tax_Type_Code__c = '106',
                                                                               Tax_Amount__c = 3.33);
            listServiceUsageTaxToInsert.add(objServiceUsageTax);
            Service_Usage_Tax__c objServiceUsageTax2 = new Service_Usage_Tax__c(Rolled_Up_Usage_Data__c = objRUUD.Id,
                                                                                Service_Usage__c = objSU.id,
                                                                                Tax_Type_Code__c = '035',
                                                                                Tax_Amount__c = 6.66);
            listServiceUsageTaxToInsert.add(objServiceUsageTax2);
            insert listServiceUsageTaxToInsert;
        } else {
            System.assert(false);
        }

        {
        // These products in SureTaxSettingsFactory
        List<Product2> listProducts = TestUtil.createProducts(3, false);
        Product2 prod1 = listProducts[0];
        prod1.APN_Number__c = 'PEC-100-TAX-SL911';
        Product2 prod2 = listProducts[1];
        prod2.APN_Number__c = 'PEC-100-TAX-FUSFC';
        Product2 prod3 = listProducts[2];
        prod3.Name = 'Cloud Contact Center -Outbound Call (Blended Rate)';
        prod3.APN_Number__c = '3GP21171ABAA';
        prod3.SureTax_Code_Undetermined__c = '050155';
        insert listProducts;
        
        Util.Bypass_Trigger_Chk = true;
        //GCR_Content_Document_Detail__c objContract = CloudBillingTestUtil.createAndInsertCloudBillingContract(new List<Rolled_Up_Usage_Data__c>());

        Subsidary__c objSubsidiary = new Subsidary__c(Name = '8100', Active__C = true);
        insert objSubsidiary;

        Util.Bypass_Trigger_Chk = true;
        Order__c objOrder = CloudBillingTestUtil.setupOrder(objContract);
        objOrder.Subsidaries__c = objSubsidiary.Id;
        objOrder.Maintenance_Start__c = Date.newInstance(2018, 02, 01);
        insert objOrder;

		Account_Order_Address__c objAddress = new Account_Order_Address__c(
            Order__c = objOrder.Id,
            Country__c = 'US',
            Zip_Code__c = '02176',
            State__c = 'MA',
            Address_Type__c = 'Bill To');
        insert objAddress;

        list<Order_Line_Item__c> listOLIinsert = new List<Order_Line_Item__c>();
        Order_Line_Item__c objOLI = new Order_Line_Item__c(
            Product__c = prod3.id,
            Order__c = objOrder.Id,
            Sales_Price__c = 300,
            Quantity__c = 1,
            BigMachines_Quantity__c = 1,
            Tax_Status__c = BatchTaxCloudUsageData.TAX_STATUS_ORDER_LINE_SURETAX_NEEDED
        );
        listOLIinsert.add(objOLI);
        Order_Line_Item__c objOLItax = new Order_Line_Item__c(
            Product__c = prod1.Id,
            Order__c = objOrder.Id,
            Sales_Price__c = 300,
            Quantity__c = 1,
            BigMachines_Quantity__c = 1
        );
        listOLIinsert.add(objOLItax);
		insert listOLIinsert;
        }

    }
    @isTest
    public static void testBatchRolledTax(){
        Test.startTest();
        BatchTaxCloudUsageData objBatch = new BatchTaxCloudUsageData(BatchTaxCloudUsageData.PROCESS_ROLLUP_TAX_NEEDED);
        Database.executeBatch(objBatch, 100);
        Test.stopTest();
    }
    
    @isTest
    public static void testBatchOrderLineSureTax(){
        Test.startTest();

        GCR_Content_Document_Detail__c objContract = [select id from GCR_Content_Document_Detail__c];
        Order_Line_Item__c objOLI = [select Id from Order_Line_Item__c where Tax_Status__c = :BatchTaxCloudUsageData.TAX_STATUS_ORDER_LINE_SURETAX_NEEDED];
        TaxCalculatorTest.idOrderLineItem = objOLI.Id;

        CloudBillingData objCloudBillingData = new CloudBillingData();
        // This is set in CloudBillingTestUtil.setupOrder()
        objCloudBillingData.month = '6';
        objCloudBillingData.year = '2017';
        //objCloudBillingData.subsidiary = '8100';
        objCloudBillingData.contractId = objContract.Id;
        //objCloudBillingData.region = 'North America';
        //Skip this for testing
        //objCloudBillingData.edition = 'PureEngage';

		Cloud_Billing_Log__c objJobLog = new Cloud_Billing_Log__c(
            Month__c = objCloudBillingData.month,
            Year__c = objCloudBillingData.year
        );
        BatchTaxCloudUsageData objBatch = new BatchTaxCloudUsageData(BatchTaxCloudUsageData.PROCESS_ORDER_LINE_SURETAX, objCloudBillingData);
        objBatch.objJobLog = objJobLog;
        Util.Bypass_Trigger_Chk = true;
        Database.executeBatch(objBatch, 1);
        Test.stopTest();
    }
    
}