objects/Cloud_Billing_Information__c.object
<CustomObject>
    <label>Cloud Forecast Information</label>
    <nameField>
        <displayFormat>CBI-{00000}</displayFormat>
        <label>Cloud Forecast</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cloud Forecast Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cloud_Billing_Phase__c.object
<CustomObject>
    <fields>
        <fullName>Cloud_Billing_Information__c</fullName>
        <label>Cloud Billing Information</label>
        <referenceTo>Cloud_Billing_Information__c</referenceTo>
        <relationshipLabel>Cloud Billing Phases</relationshipLabel>
        <relationshipName>Cloud_Billing_Phases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cloud Billing Phase</label>
    <nameField>
        <displayFormat>CBP-{00000}</displayFormat>
        <label>Cloud Billing Phase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cloud Billing Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cloud_Phase_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cloud Phase Line Items</relationshipLabel>
        <relationshipName>Cloud_Phase_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>April_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-4-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-4-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 

Quantity__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>April 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Aug_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-8-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-8-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 

Quantity__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aug 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cloud_Billing_Phase__c</fullName>
        <label>Cloud Billing Phase</label>
        <referenceTo>Cloud_Billing_Phase__c</referenceTo>
        <relationshipLabel>Cloud Phase Line Items</relationshipLabel>
        <relationshipName>Cloud_Phase_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dec_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-12-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-12-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 

Quantity__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dec 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Feb_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-2-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-2-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 

Quantity__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Feb 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jan_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-1-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-1-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 
 Quantity__c,  0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Jan 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-7-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-7-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 

Quantity__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>July 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-6-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-6-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 

Quantity__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>June 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-3-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-3-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 

Quantity__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>March 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-5-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-5-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 

Quantity__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>May 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nov_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-11-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-11-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 

Quantity__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nov 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Oct_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-10-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-10-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 

Quantity__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Oct 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Cloud_Billing_Phase__r.Cloud_Billing_Information__r.Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Product2.BE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product2.Product_Category__c</field>
                <operation>equals</operation>
                <value>Business Edition, Business Edition Cloud, Enterprise Edition Cloud</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cloud Phase Line Items</relationshipLabel>
        <relationshipName>Cloud_Phase_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sep_2016__c</fullName>
        <formula>if( 
AND 
( 
MONTH( DateValue(&apos;2017-9-1&apos;) ) == MONTH(Phase_Go_Live_Date__c ), 
YEAR( DateValue(&apos;2017-9-1&apos;) ) == YEAR(Phase_Go_Live_Date__c ) 
) 
, 

Quantity__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sep 2017</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Cloud Phase Line Item</label>
    <nameField>
        <label>Cloud Phase Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cloud Phase Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CloudBillingPhasesAgentReport.cls
//Naresh Kumar  01/12/2016
public without sharing class CloudBillingPhasesAgentReport {
  public List<wrapperLines> records {get;set;}
  public CloudBillingPhasesAgentReport(){
    List<Cloud_Phase_Line_Items__c> cloudPhaseLines;
    AggregateResult[] groupedResults = [SELECT Cloud_Billing_Phase__r.Cloud_Billing_Information__r.Opportunity__r.Account.Name accName, Product__r.Name pName, Sum(Quantity__c) quantity, SUM(Jan_2016__c) jan2016,
      SUM(Feb_2016__c) feb2016, SUM(March_2016__c) mar2016, SUM(April_2016__c) apr2016, SUM(May_2016__c) may2016, SUM(June_2016__c) june2016, 
      SUM(July_2016__c) july2016, SUM(Aug_2016__c) aug2016, SUM(Sep_2016__c) sep2016, SUM(Oct_2016__c) oct2016, 
      SUM(Nov_2016__c) nov2016, SUM(Dec_2016__c) dec2016 FROM Cloud_Phase_Line_Items__c 
      GROUP BY Cloud_Billing_Phase__r.Cloud_Billing_Information__r.Opportunity__r.Account.Name, Product__r.Name ORDER BY Cloud_Billing_Phase__r.Cloud_Billing_Information__r.Opportunity__r.Account.Name];
    records = new List<wrapperLines>();
    for(AggregateResult ar : groupedResults){
      wrapperLines newRecord = new wrapperLines();
      newRecord.accountName = (String)ar.get('accName');
      newRecord.productName = (String)ar.get('pName');
      newRecord.quantity = (Decimal)ar.get('quantity');
      newRecord.jan2016 = (Decimal)ar.get('jan2016');
      newRecord.feb2016 = (Decimal)ar.get('feb2016');
      newRecord.mar2016 = (Decimal)ar.get('mar2016');
      newRecord.apr2016 = (Decimal)ar.get('apr2016');
      newRecord.may2016 = (Decimal)ar.get('may2016');
      newRecord.june2016 = (Decimal)ar.get('june2016');
      newRecord.july2016 = (Decimal)ar.get('july2016');
      newRecord.aug2016 = (Decimal)ar.get('aug2016');
      newRecord.sep2016 = (Decimal)ar.get('sep2016');
      newRecord.oct2016 = (Decimal)ar.get('oct2016');
      newRecord.nov2016 = (Decimal)ar.get('nov2016');
      newRecord.dec2016 = (Decimal)ar.get('dec2016');      
      records.add(newRecord);  
    }
    //SELECT Account__r.Name, Product__r.Name a, SUM(Jan_2016__c) FROM Cloud_Phase_Line_Items__c GROUP BY Account__r.Name, Product__r.Name
  }
  
  public class wrapperLines{
    public transient String accountName {get;set;}
    public transient String productName {get;set;}
    public transient Decimal quantity {get;set;}
    public transient Decimal jan2016 {get;set;}
    public transient Decimal feb2016 {get;set;}
    public transient Decimal mar2016 {get;set;}
    public transient Decimal apr2016 {get;set;}
    public transient Decimal may2016 {get;set;}
    public transient Decimal june2016 {get;set;}
    public transient Decimal july2016 {get;set;}
    public transient Decimal aug2016 {get;set;}
    public transient Decimal sep2016 {get;set;}
    public transient Decimal oct2016 {get;set;}
    public transient Decimal nov2016 {get;set;}
    public transient Decimal dec2016 {get;set;}    
    public transient String headerString {get;set;}
    public transient Boolean isHeader {get;set;}    
  }
}