objects/Cloud_Billing_Log__c.object
<CustomObject>
    <description>Logs related to Billing (Formerly Cloud Billing)</description>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Downstream Impact: Only used for Cloud Billing
Department Owner: Cloud Billing 
Status of the activity if appropriate</description>
        <inlineHelpText>Status of the activity if appropriate</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Billing Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Billing Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GCR_Content_Document_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GCR_Content_Document_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Date_Option__c</fullName>
        <inlineHelpText>Order date to be populated on Monthly Billing Order.</inlineHelpText>
        <label>Order Date Option</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current Date</fullName>
                </value>
                <value>
                    <fullName>Last Day of Usage Month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Start_Date__c</fullName>
        <label>Pricing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>Contracts - {000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Attached</fullName>
                </value>
                <value>
                    <fullName>Send Email</fullName>
                </value>
                <value>
                    <fullName>Email Sent</fullName>
                </value>
                <value>
                    <fullName>Invoice or Order Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Account_Code__c</fullName>
        <externalId>true</externalId>
        <label>SAP Account Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BatchSendInvoicesTest.cls
@isTest
public class BatchSendInvoicesTest {
    
    @testSetup
    static void setUpData() {
        Util.Bypass_Trigger_Chk = true;
/*
        List<Account> list_Accounts = TestUtil.createAccounts(1,false);
        list_Accounts[0].SAP_Account_Code__c = 'GARN TEST';
        insert list_Accounts;

        GCR_Content_Document_Detail__c objContract = new GCR_Content_Document_Detail__c();
        objContract.Account_Name__c = list_Accounts[0].Id;
        objContract.Document_Name__c = 'Cloud Billing Contract';
        objContract.Order_Date_Option__c = 'Last Day of Usage Month';
        objContract.Status__c = 'New';
        objContract.Active__c = true;
        objContract.Status__c = 'Approved';
        objContract.Pricing_Start_Date__c = System.today() - 730 ;
*/
        Id idCloudMonthlyBillingOrder = Schema.SObjectType.Order__c.getRecordTypeInfosByName().get('Cloud Monthly Billing Order').getRecordTypeId();
        Order__c objOrder = new Order__c(Sales_Org__c = 'PureConnect',
                                     Month__c = '7',
                                     Year__c = '2017',
                                     Status__c = 'Completed',
                                     RecordTypeId = idCloudMonthlyBillingOrder);
        insert objOrder;
        Invoice__c objInvoice = new Invoice__c(
            Status__c = 'Invoice Attached',
            Order__c = objOrder.Id
        );
        insert objInvoice;
        
        
    }
    
    static testmethod void testSend() {
        CloudBillingData objCloudBillingData = new CloudBillingData();
        Cloud_Billing_Log__c objCloudBillingLog = new Cloud_Billing_Log__c(Month__c = '7',
                                                                          Year__c = '2017');
		BatchSendInvoices objBatchSendInvoices = new BatchSendInvoices(objCloudBillingData, objCloudBillingLog);
        Test.startTest();
        Database.executeBatch(objBatchSendInvoices, 50);
        Test.stopTest();
    }
    static testmethod void testSendPureCloud() {
        CloudBillingData objCloudBillingData = new CloudBillingData();
        objCloudBillingData.edition = 'PureCloud';
        Cloud_Billing_Log__c objCloudBillingLog = new Cloud_Billing_Log__c(Month__c = '7',
                                                                          Year__c = '2017');
		BatchSendInvoices objBatchSendInvoices = new BatchSendInvoices(objCloudBillingData, objCloudBillingLog);
        Test.startTest();
        Database.executeBatch(objBatchSendInvoices, 50);
        Test.stopTest();
    }
    static testmethod void testSendPureConnect() {
        CloudBillingData objCloudBillingData = new CloudBillingData();
        objCloudBillingData.edition = 'PureConnect';
        Cloud_Billing_Log__c objCloudBillingLog = new Cloud_Billing_Log__c(Month__c = '7',
                                                                          Year__c = '2017');
		BatchSendInvoices objBatchSendInvoices = new BatchSendInvoices(objCloudBillingData, objCloudBillingLog);
        Test.startTest();
        Database.executeBatch(objBatchSendInvoices, 50);
        Test.stopTest();
    }

    static testmethod void testSendNullLog() {
        CloudBillingData objCloudBillingData = new CloudBillingData();
		BatchSendInvoices objBatchSendInvoices = new BatchSendInvoices(objCloudBillingData, null);
        Test.startTest();
        Database.executeBatch(objBatchSendInvoices, 50);
        Test.stopTest();
    }

}