objects/Cloud_Deployment_To_Contract_Junction__c.object
<CustomObject>
    <description>This object is owned by Cloud Billing. It is an intermediate object between Cloud Deployment and Contracts (GCR_Content_Document_Detail__c) to allow assignment of a Cloud Deployment to  multiple Cloud Billing Contracts.</description>
    <label>Cloud Deployment To Billing Junction</label>
    <nameField>
        <displayFormat>CDCJ-{00000}</displayFormat>
        <label>Cloud Deployment To Billing Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cloud Deployment To Billing Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GCR_Content_Document_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_End_Date__c</fullName>
        <label>Pricing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pricing_Start_Date__c</fullName>
        <label>Pricing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>Downstream Impact: All
Department Owner: All
Help Text: Formula to display the Offering Type for this Contract</description>
        <formula>IF (NOT(ISBLANK(Quote__c)),(IF(TEXT(Quote__r.BigMachines__Opportunity__r.Offering_Detail__c) == &apos;Subscription&apos;&amp;&amp;Document_Name__c == &apos;Cloud Billing Contract&apos;,Quote__r.Offering_Type__c,IF (Document_Name__c == &apos;Cloud Billing Contract&apos;, 
TEXT(Quote__r.BigMachines__Opportunity__r.Lines_of_Businesses__c), Quote__r.Offering_Type__c))),&apos;PureCloud&apos;)</formula>
        <inlineHelpText>Formula to display the Offering Type for this Contract based off of Quote. PureCloud if not Quote and a Zoura Quote.</inlineHelpText>
        <label>Product Group/Edition</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>Contracts - {000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Group__c.object
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CloudBillingPureCloudRRSchedulerTest.cls
@isTest(SeeAllData=false)
public class CloudBillingPureCloudRRSchedulerTest {

    @TestSetup
    static void setupData() {
        Util.Bypass_Trigger_Chk = true;
        GCR_Content_Document_Detail__c objContract = CloudBillingTestUtil.insertPureCloudContract();
        
        List<GCR_Content_Document_Detail__c> list_contracts = [
            select Id, Status__c, Product_Group__c, Document_Name__c, Pricing_Start_Date__c, Pricing_End_Date__c
            from GCR_Content_Document_Detail__c
        ];
        for (GCR_Content_Document_Detail__c objContractView : list_contracts) {
            System.debug('Test Contract ' + objContractView);
        }

        List<Cloud_Deployment_To_Contract_Junction__c> list_junctions = CloudBillingTestUtil.setupInsertCloudDeploymentsAndJunctions(objContract);
        for (Cloud_Deployment_To_Contract_Junction__c objJunction : list_junctions) {
            System.debug ('Junction ' + objJunction);
        }
    }

    @isTest
    public static void testRequestContractsToday() {
        // Find all of the PureCloud Contracts and set their start date to today minus a year. Should fire all of the records.
        List<GCR_Content_Document_Detail__c> list_Contracts = [
            select Id from GCR_Content_Document_Detail__c where Product_Group__c = 'PureCloud'
        ];
        for (GCR_Content_Document_Detail__c objContract : list_Contracts) {
            objContract.Pricing_Start_Date__c = Date.today().addYears(-1);
        }
        update list_Contracts;
        Test.startTest();
        CloudBillingPureCloudRRScheduler objSched = new CloudBillingPureCloudRRScheduler();
        //System.schedule('Schedule', '0 0 0 0 ?', objSched);
        CloudBillingPureCloudRRScheduler.runProcess();
        Test.stopTest();
    }

    @isTest
    public static void testRequestAllContractsLastMonth() {
        CloudBillingPureCloudRRScheduler.addAllPureCloudLastMonth(true);
    }
}