objects/Community__c.object
<CustomObject>
    <fields>
        <fullName>EventDate__c</fullName>
        <label>Event Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hyperlink__c</fullName>
        <label>Hyperlink</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Community</label>
    <nameField>
        <displayFormat>CN-{00000}</displayFormat>
        <label>CN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communitys</pluralLabel>
    <recordTypes>
        <fullName>Events</fullName>
        <active>true</active>
        <description>Events</description>
        <label>Events</label>
    </recordTypes>
    <recordTypes>
        <fullName>Webinars</fullName>
        <active>true</active>
        <description>Webinars</description>
        <label>Webinars</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/GenesysConsuCommunityLoginController.cls
global class GenesysConsuCommunityLoginController
{
    public String username {get; set;}
    public String password {get; set;}
    public Boolean err {get; set;}
    public static String SESSION_ID {get; set;}
    public static Boolean auth {get; set;}
    public list<Community__c> evnt_comm {get;set;}
    public list<Community__c> webnr_comm {get;set;}
    public list<Community__c> rfp_comm {get;set;}


    global PageReference forwardToAuthPage() {
        String startURL = System.currentPageReference().getParameters().get('startURL');
 
        if(Userinfo.getUserType() != 'Guest'){
           if(startURL == null || startURL == ''){
                startURL = '/ConsultantPortal/';
         } 
          return new PageReference(startURL);
         }
        
        return null;
   }
    
     static{
         SESSION_ID = userInfo.getSessionId();
         if(SESSION_ID!=null){
         auth = true;
         }else auth = false;
     }
    
    global PageReference loginCheck() 
    {
        String startURL = System.currentPageReference().getParameters().get('startURL');

        System.debug(' startURL>>>>>>>>>>>>>>>>>>>>>>> ' +startURL);

        if(startURL == null || startURL == ''){
           startURL = System.currentPageReference().getParameters().get('refURL');
           
           if(startURL == null || startURL == ''){
               //startURL = '/ConsultantPortal/CommunityPureCloudDev';
               startURL = '/CommunityPureCloudDev';
           }
           
        }
       
       System.debug(' startURL>>>>>>>>>>>>>>>>>>>>>>> 3' +startURL);
        
       PageReference communityLoginPage = Site.login(username, password, startURL);
       
       System.debug(' startURL>>>>>>>>>>>>>>>>>>>>>>> 4' +startURL);
       
       if (communityLoginPage == null)
            err=true;
            
       return communityLoginPage;
    }
    
    global GenesysConsuCommunityLoginController() {
          err = false; 
          evnt_comm  = [Select Name, Year__c, EventDate__c, Hyperlink__c, Location__c, Title__c  From Community__c where RecordType.Name='Events' and isActive__c= true order by Order__c asc Limit 100];
          webnr_comm = [Select Name, Year__c, EventDate__c, Hyperlink__c, Location__c, Title__c  From Community__c where RecordType.Name='Webinars' and isActive__c= true  order by Order__c asc  Limit 100];
          rfp_comm    = [Select Name, Year__c, EventDate__c, Hyperlink__c, Location__c, Title__c  From Community__c where RecordType.Name='RFP Templates' and isActive__c= true  order by Order__c asc  Limit 100];
    }

}