objects/Contract_Tier_Set__c.object
<CustomObject>
    <fields>
        <fullName>Aggregation_Model__c</fullName>
        <description>Downstream Impact: Only used for Cloud Billing
Department Owner: Cloud Billing
Help Text: How to summarize usage data for this Tier Set for billing purposes</description>
        <inlineHelpText>How to summarize usage data for this Tier Set for billing purposes</inlineHelpText>
        <label>Aggregation Model</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Step</fullName>
                    <default>true</default>
                    <label>Step</label>
                </value>
                <value>
                    <fullName>Lookback</fullName>
                </value>
                <value>
                    <fullName>Max Per Month</fullName>
                </value>
                <value>
                    <fullName>Sum of Max Per Region Per Month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>GCR_Content_Document_Detail__c</referenceTo>
        <relationshipLabel>Contract Tier Sets</relationshipLabel>
        <relationshipName>Contract_Tier_Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Period_In_Months__c</fullName>
        <description>Period over which quantities are calculated. Default of 1 is billing only over the course of a month. Quarterly: 3 Annual: 12</description>
        <inlineHelpText>Period over which quantities are calculated.
Monthly: 1
Quarterly: 3
Annual: 12</inlineHelpText>
        <label>Period In Months</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>36</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RC_Period__c</fullName>
        <description>Recurring Charge Period in Months. This can be different</description>
        <label>RC_Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>36</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Units_Type__c</fullName>
        <description>Downstream Impact: Only used for Cloud Billing
Department Owner: Cloud Billing
Help Text: Determine which field from the Rolled Up Usage Data to pull data for billing</description>
        <inlineHelpText>Determine which field from the Rolled Up Usage Data to pull data for billing</inlineHelpText>
        <label>Units Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gigabytes</fullName>
                </value>
                <value>
                    <fullName>Messages/Seats/Ports</fullName>
                </value>
                <value>
                    <fullName>Minutes(12s/message)</fullName>
                </value>
                <value>
                    <fullName>Minutes(6s ceiling)</fullName>
                </value>
                <value>
                    <fullName>Minutes(30s ceiling)</fullName>
                </value>
                <value>
                    <fullName>Minutes(60s ceiling)</fullName>
                </value>
                <value>
                    <fullName>Minutes(6s/message)</fullName>
                </value>
                <value>
                    <fullName>Minutes(Actual)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Tier Set</label>
    <nameField>
        <label>Contract Tier Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Tier Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractTierSetFactory.cls
@isTest
public class ContractTierSetFactory {

    public static Contract_Tier_Set__c createContractTierSet(String name, Id contractId, String aggregationModel, String period, String rcPeriod, String unitType)
    {
        return new Contract_Tier_Set__c(
            Name = name,
            Contract__c = contractId,
            Aggregation_Model__c = aggregationModel,
            Period_In_Months__c = period,
            RC_Period__c = rcPeriod,
            Units_Type__c = unitType,
            Is_Deleted__c = false
        );
    }
}