objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>selling_entity__c</fullName>
        <label>Selling Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/GCR_Content_Document_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name_Formula__c</fullName>
        <formula>Account_Name__r.Name</formula>
        <label>Account Name Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Account_Name__r.Street1__c &amp; BR() &amp; Account_Name__r.City__c &amp; &apos; &apos; &amp; Account_Name__r.ZipCode__c &amp; &apos;, &apos; &amp; Account_Name__r.Country__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Genesys_Entity__c</fullName>
        <label>Genesys Entity</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Genesys Telecommunications Laboratories, Inc.</fullName>
                </value>
                <value>
                    <fullName>Genesys Telecommunications Laboratories B.V.</fullName>
                </value>
                <value>
                    <fullName>Genesys University B.V. (Netherlands)</fullName>
                </value>
                <value>
                    <fullName>Genesys Laboratories Canada Inc.</fullName>
                </value>
                <value>
                    <fullName>Genesys Laboratories Australasia Pty Ltd</fullName>
                </value>
                <value>
                    <fullName>Genesys Lab de Telecom Ltd. (Brazil)</fullName>
                </value>
                <value>
                    <fullName>Genesys Japan Co. Ltd</fullName>
                </value>
                <value>
                    <fullName>Genesys Tele Comm Lab, Inc. (US) - Premier &amp; Outbound</fullName>
                </value>
                <value>
                    <fullName>Genesys Europe B.V.</fullName>
                </value>
                <value>
                    <fullName>Other (with a Text Box)</fullName>
                </value>
                <value>
                    <fullName>Echopass</fullName>
                </value>
                <value>
                    <fullName>Angel</fullName>
                </value>
                <value>
                    <fullName>SoundBite</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Footer_Text__c</fullName>
        <inlineHelpText>Needed if footer is overriden</inlineHelpText>
        <label>Invoice Footer Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BEEEC</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Standard with Part Number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Override_Invoice_Footer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this flag to override with footer text specified on Contract.</inlineHelpText>
        <label>Override Invoice Footer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <inlineHelpText>PO # from Quote. Can be overridden on Billing Contract. Appears on Invoice.</inlineHelpText>
        <label>PO #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Net30</fullName>
                </value>
                <value>
                    <fullName>Net45</fullName>
                </value>
                <value>
                    <fullName>Net60</fullName>
                </value>
                <value>
                    <fullName>Net90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>Contracts - {000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Genesys_Entity__c.object
<CustomObject>
    <fields>
        <fullName>Selling_Entity__c</fullName>
        <label>Selling Entity</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Genesys Entity</label>
    <nameField>
        <label>Genesys Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genesys Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>GCR_Content_Document_Detail__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Tax_Id__c</fullName>
        <description>Customer Tax Id Maintained in NetSuite. this is brought over from NetSuite for a Cloud Billing Invoice</description>
        <inlineHelpText>Customer Tax Id Maintained in NetSuite. this is brought over from NetSuite for a Cloud Billing Invoice</inlineHelpText>
        <label>Customer Tax Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_User_ID__c</fullName>
        <formula>End_User_Name__r.SAP_Account_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End User ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <defaultValue>IF($RecordType.Id =&apos;012U0000000M2Tw&apos;, TODAY(), null)</defaultValue>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Number__c</fullName>
        <defaultValue>IF($RecordType.Id =&apos;012U0000000M2Tw&apos;, text(0), null)</defaultValue>
        <label>PO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Account_Code__c</fullName>
        <externalId>true</externalId>
        <label>SAP Account Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order (Sold To)</relationshipLabel>
        <relationshipName>Sold_To_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subsidaries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subsidary</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Subsidary__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subsidary__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zero_Tax_Wording__c</fullName>
        <description>If there is zero tax for the invoice and there needs to be verbiage indicating this on the invoice, please it here. Leaving null will not print a message on the invoice.</description>
        <inlineHelpText>If there is zero tax for the invoice and there needs to be verbiage indicating this on the invoice, please it here. Leaving null will not print a message on the invoice.</inlineHelpText>
        <label>Zero Tax Wording</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <description>What it Does?  Object holding states available in a country.  Downstream Impact? None. Which Department is Owner? Sales Ops.

Part of the DEMO REQUEST process.</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>What it Does?  Holds the country to which this state belongs.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Subsidary__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Invoice_Footer__c</fullName>
        <label>Billing Invoice Footer</label>
        <length>10000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Store the country related to Subsidiary
Downstream Impact? To be used by PureCloud Billing
Which department is owner? IT/PureCloud Team</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Subsidaries</relationshipLabel>
        <relationshipName>Subsidaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subsidary</label>
    <nameField>
        <label>Subsidary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CloudAccountBillingComponentController.cls
public class CloudAccountBillingComponentController
{
    public Id idAccountBilling {get; set;}
    public Boolean blnIsExcel {get; set;}
    public Order__c objOrder {get; private set;}
    public List<ProductDetail> list_ProductDetails {get; private set;}
    public Decimal decTotalInvoiceAmount {get; private set;}
    public String strDateRange {get; private set;}
    public String strCurrencyCode {get; private set;}
    public String strPaymentTerms {get; private set;}
    public String strFooterText {get; private set;}
    // Billing Address selected on related quote
    public Account_Order_Address__c objBillingAddress {get; private set;}
    public Account_Billing_Info__c objAccountBillingInfo {get; private set;}
    public List<Account_Billing_Info_Line__c> list_accountBillingInfoLine {get; private set;}
    
    public Genesys_Entity__c objGenesysEntityInternal;
    
    public String strMainTitle {get; private set;}
    
    public class ProductDetail
    {
        public String strProductName {get; set;}
        public Decimal decTotalQuantity {get; set;}
        public String strUOM {get; set;}
        public Decimal decTotalAmount {get; set;}
        public List<UsageDetail> list_UsageDetails {get; set;}
        public String strDateRange {get; private set;}
        public Decimal decTaxRate {get; private set;}
        
        public ProductDetail()
        {
            decTotalAmount = 0;
            list_UsageDetails = new List<UsageDetail>();
        }
    }
    
    public class UsageDetail
    {
        public String strMemo {get; set;}
        public Decimal decQuantity {get; set;}
        public Decimal decRate {get; set;}
        public Decimal decAmount {get; set;}
    }
    
    public CloudAccountBillingComponentController()
    {
        blnIsExcel = false;
    }
    
    public Genesys_Entity__c getObjGenesysEntity()
    {
        init();
        return objGenesysEntityInternal;
    }
    
    void init()
    {
        // Put the period strDateRange in the header by default
        list_ProductDetails = new List<ProductDetail>();
        objGenesysEntityInternal = new Genesys_Entity__c();
        objOrder = new Order__c();
        
        List<Account_Billing_Info__c> list_AccountBillingInfo = [SELECT Order__c,
                                                                 Document_Type__c,
                                                                 Date__c,
                                                                 Name,
                                                                 Tax_Number__c,
                                                                 Payment_Terms__c,
                                                                 PO__c,
                                                                 Sales_Rep__c,
                                                                 Sold_To_NS_Bill_To__r.Name,
                                                                 Sold_To_NS_Bill_To__r.SAP_Account_Code__c,
                                                                 Sold_To_NS_Bill_To__r.Subsidary__r.Name,
                                                                 End_User__r.Name,
                                                                 End_User__r.SAP_Account_Code__c,
                                                                 End_User__r.Subsidary__r.Name,
                                                                 Account_Billing_Info_Line_Total__c,
                                                                 Memo_Text__c,
                                                                 (select Units__c,
                                                                  Item__c,
                                                                  Description__c,
                                                                  Memo__c,
                                                                  Start_Date__c,
                                                                  End_Date__c,
                                                                  Quantity__c,
                                                                  UOM__c,
                                                                  Rate__c,
                                                                  Amount__c
                                                                  from Account_Billing_Info_Lines__r)
                                                                 FROM Account_Billing_Info__c WHERE Id = :idAccountBilling];
        
        if(!list_AccountBillingInfo.isEmpty())
            objAccountBillingInfo = list_AccountBillingInfo[0];
        
        strMainTitle = objAccountBillingInfo.Document_Type__c;
        strMainTitle = strMainTitle.replace(' Memo', '');
        
        if(objAccountBillingInfo != null)
        {
            // Gathering a bit too much here due to code copying.
            objOrder = [SELECT Id,Quote__c, Month__c, Year__c,
                        Contract_Lookup__c,Contract_Lookup__r.Quote__c,Contract_Lookup__r.Account_Name_Formula__c,
                        Contract_Lookup__r.Genesys_Entity__c,Invoice_Number__c,Invoice_Date__c,Order_Number__c,PO_Number__c,Order_Date__c,
                        Contract_Lookup__r.Quote__r.CurrencyISOCode,Payment_Terms__c,
                        Contract_Lookup__r.Override_Invoice_Footer__c,Contract_Lookup__r.Invoice_Footer_Text__c,
                        Sold_To_Name__r.SAP_Account_Code__c,Subsidaries__r.Billing_Invoice_Footer__c,
                        Contract_Lookup__r.Quote__r.Name,Due_Date__c,Tax_Amount__c,Customer_Tax_Id__c,Zero_Tax_Wording__c,
                        Contract_Lookup__r.Quote__r.End_User_ID__r.Name, Contract_Lookup__r.Invoice_Type__c
                        FROM Order__c WHERE Id = :objAccountBillingInfo.Order__c];
            
            // If Service Period in the Order Line Items also calculate its String
            Integer intMonth = Integer.valueOf(objOrder.Month__c);
			Integer intYear = Integer.valueOf(objOrder.Year__c);
            strDateRange = Date.newInstance(intYear,intMonth,1).format() + ' - ' + Date.newInstance(intYear,intMonth,Date.daysInMonth(intYear,intMonth)).format();
            
            list_accountBillingInfoLine = new List<Account_Billing_Info_Line__c>();
            for (Account_Billing_Info_Line__c abil : objAccountBillingInfo.Account_Billing_Info_Lines__r) {
                list_accountBillingInfoLine.add(abil);
            }
            
            if(objOrder.Contract_Lookup__r.Quote__c != null)
            {
                List<Account_Order_Address__c> list_BillingAddress = [SELECT Address__c, Address2__c, City__c,State__c, Country__c,Zip_Code__c,
                                                                      Attention_To__c FROM Account_Order_Address__c WHERE Quote__c = :objOrder.Contract_Lookup__r.Quote__c LIMIT 1];
                
                if(!list_BillingAddress.isEmpty())
                    objBillingAddress = list_BillingAddress[0];
            }
            
            if(String.isNotBlank(objOrder.Contract_Lookup__r.Genesys_Entity__c) && objBillingAddress != null)
            {
                List<Genesys_Entity__c> list_Entities = [SELECT Selling_Entity__c,Remit_To__c FROM Genesys_Entity__c 
                                                         WHERE CurrencyISOCode = :objOrder.Contract_Lookup__r.Quote__r.CurrencyISOCode AND 
                                                         Name = :objOrder.Contract_Lookup__r.Genesys_Entity__c.substringBefore(';') LIMIT 1];
                
                if(!list_Entities.isEmpty())
                    objGenesysEntityInternal = list_Entities[0];
            }
            
            // Getting default Invoice footer from Subsidiary record
            strFooterText = objOrder.Subsidaries__r.Billing_Invoice_Footer__c;
            
        }
        if (objBillingAddress == null) {
            objBillingAddress = new Account_Order_Address__c();
        }
        
    }
}