objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DAP_Region__c</fullName>
        <label>DAP Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_DAP_Region__c</fullName>
        <label>New DAP Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Price_Book__c</fullName>
        <label>New Price Book</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Price_Book__c</fullName>
        <label>Old Price Book</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RU__c</fullName>
        <description>CORE Model</description>
        <label>Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ANZ</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>DACH</fullName>
                </value>
                <value>
                    <fullName>France &amp; N. Africa</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>Iberia</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>UKI</fullName>
                </value>
                <value>
                    <fullName>Benelux</fullName>
                </value>
                <value>
                    <fullName>ECSEI</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                </value>
                <value>
                    <fullName>Italy &amp; Middle East</fullName>
                </value>
                <value>
                    <fullName>South East Asia</fullName>
                </value>
                <value>
                    <fullName>Andean</fullName>
                </value>
                <value>
                    <fullName>Southern Cone</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CORE Model</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Subscription__c.object
<CustomObject>
    <description>To store subscription for different offering types</description>
    <fields>
        <fullName>ACV__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores annual contract value
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Annual Contract Value.</inlineHelpText>
        <label>ACV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amendment_For__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Stores previous subscription which is amended
Downstream Impact? Effects reporting and billing integration
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Previous CCDB/Subscription record that this CCDB/Subscription amended.</inlineHelpText>
        <label>Amendment For</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>CCDBs/Subscriptions (Amendment For)</relationshipLabel>
        <relationshipName>NewSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMRR__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores monthly committed value
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Committed Monthly Recurring Revenue.</inlineHelpText>
        <label>CMRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Master_Order__r.Region__c</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <description>What it Does? Stores term end date for this subscription
Downstream Impact? Effects reporting and billing
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Date in which the initial term or renewal term ends.</inlineHelpText>
        <label>Subscription Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TCV__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores total contract value
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Total Contract Value.</inlineHelpText>
        <label>TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Education__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores total education amount
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <label>Total Education</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Hardware__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores total hardware amount
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <label>Total Hardware</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Non_Recurring_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores total non recurring amount
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <label>Total Non Recurring Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CCDB/Subscription</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>CCDB/Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCDBs/Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Subscription_Product__c.object
<CustomObject>
    <fields>
        <fullName>Adjustment__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? adjustment discount applied for the line item
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amendment_For__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Stores previous subscription product from amended subscription
Downstream Impact? Effects reporting and billing integration 
Which department is owner? IT/PureCloud Team</description>
        <label>Amendment For</label>
        <referenceTo>Subscription_Product__c</referenceTo>
        <relationshipLabel>Amended To</relationshipLabel>
        <relationshipName>Amendment_For</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disc__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Discount for line item
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>What it Does? Stores proposal group number of the line item
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? List price of the line item
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>List Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Unit_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Net unit price of the line item
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>Net Unit Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Partner price of the line item if the opportunity is based on partner
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>Partner Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores the quantity of the line item
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <description>What it Does? Stores parent subscription
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscription Products</relationshipLabel>
        <relationshipName>Subscription_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>or_Amount__c</fullName>
        <description>What it Does? type of discount applied for the line item
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>% or Amount</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Subscription Product</label>
    <nameField>
        <displayFormat>SP-{000000000}</displayFormat>
        <label>Subscription Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateRenewalOppAndQuoteforM2MSubsTest.cls
/************************************************************************************
Purpose : Unit test class for CreateRenewalOppAndQuoteforM2MSubs
Written By : Rony Joseph
Test Classes : N/A
*************************************************************************************/
@isTest(seealldata=true)
public class CreateRenewalOppAndQuoteforM2MSubsTest {
    @isTest
    public static void TestMethod1(){
        //Skipping all triggers as we do not need any updates from triggers for the purposes of this unit test
        Util.Bypass_Trigger_Chk = true;
        
        //Create account, opp and quote
        List<Account> list_NewAccts = TestDataFactoryForQuoteTool.createAccounts(1);
        System.assertEquals(list_NewAccts.size(), 1);
        List<Opportunity> list_NewOpps = TestDataFactoryForQuoteTool.createOpportunties(list_NewAccts[0].Id, 1);
        System.assertEquals(list_NewOpps.size(), 1);
        List<BigMachines__Quote__c> list_NewQuotes = TestDataFactoryForQuoteTool.createPCQuotes(list_NewOpps[0].Id, list_NewAccts[0].Id, 1);
        System.assertEquals(list_NewQuotes.size(), 1);          
        List<Account_Order_Address__c> list_NewQtAddrs = TestDataFactoryForQuoteTool.createAOAs(list_NewQuotes[0].Id);
        System.assertEquals(list_NewQtAddrs.size(), 4);        
        Country__c objNewCountry = new Country__c(Country__c='United States A', DAP_Region__c='NA', Region__c='NA', RU__c='NA', New_DAP_Region__c = 'NA',        
                                                  New_Price_Book__c='NG5_NA_USD', Old_Price_Book__c='NG5_NA_USD');    
        insert objNewCountry;
        
        list_NewAccts[0].Country__c = objNewCountry.Id;
        update list_NewAccts[0];
        
        list_NewOpps[0].Primary_Quote__c=list_NewQuotes[0].Id;
        list_NewOpps[0].Country__c = objNewCountry.Id;
        update list_NewOpps[0];
        list_NewQuotes[0].Subscription_End_Date__c = Date.today().addDays(120);
        update list_NewQuotes[0];
        
        //Add quote line items         
        List<BigMachines__Quote_Product__c> list_NewQuoteProds = TestDataFactoryForQuoteTool.createPCQuoteProducts(list_NewQuotes[0].Id);
        
        
        list_NewQuoteProds = [SELECT Id, Adjustment__c, Disc__c, or_Amount__c, BigMachines__Quote__c,BigMachines__Product__c,Quantity__c,List_Price__c,Partner_Price__c,Net_Unit_Price__c
                              FROM BigMachines__Quote_Product__c 
                              WHERE BigMachines__Quote__c =: list_NewQuotes[0].Id];
        
        for(BigMachines__Quote_Product__c objQP : list_NewQuoteProds) {
            //objQP.Quantity__c = 100;
            objQP.Adjustment__c=10;
            objQP.Disc__c=10;
            objQP.or_Amount__c='%';
            objQP.Group_Number__c='PG1';
            objQP.List_Price__c = objQP.List_Price__c !=null?objQP.List_Price__c:0.00;
            objQP.Partner_Price__c = objQP.Partner_Price__c !=null?objQP.Partner_Price__c:0.00;
            objQP.Net_Unit_Price__c  = objQP.Net_Unit_Price__c  !=null?objQP.Net_Unit_Price__c :0.00;
            
        }    
        list_NewQuoteProds[1].or_Amount__c='Amt';
        update list_NewQuoteProds;
        
        Product2 objProd = new Product2(Id=list_NewQuoteProds[0].BigMachines__Product__c, ProductShippable__c='Yes', Include_in_CMMR_Total__c=true );      
        update objProd;
        
        //Create subscription & products        
        List<Subscription_Product__c> list_NewSubscriptionProds = new List<Subscription_Product__c>();
        Subscription__c objNewSubscription = SubscriptionUtil.buildSubscrFromQuote(list_NewQuotes[0]);  
        objNewSubscription.CMRR__c = objNewSubscription.ACV__c = objNewSubscription.TCV__c = objNewSubscription.Total_Education__c= objNewSubscription.Total_Hardware__c = objNewSubscription.Total_Non_Recurring_Fees__c = 0;
        insert objNewSubscription;
        for(BigMachines__Quote_Product__c objQtProd: list_NewQuoteProds) {                    
            Subscription_Product__c objNewSubscriptionProd = SubscriptionUtil.buildSubscrProdFromQuoteProd(objQtProd);             
            objNewSubscriptionProd.Subscription__c = objNewSubscription.Id;
            list_NewSubscriptionProds.add(objNewSubscriptionProd);
        }  
        insert list_NewSubscriptionProds;
        list_NewQuotes[0].Amendment_For__c = objNewSubscription.Id;
        update list_NewQuotes[0];
        Test.startTest();
        CreateRenewalOppAndQuoteforM2MSubs.createRenewalOppandQuote(objNewSubscription.Id);
        Test.stopTest();
    }
    
    
}