objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Recordtypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Recordtypes</label>
</CustomObject>

objects/Sales_Aid__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Aids</relationshipLabel>
        <relationshipName>Sales_Aids</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Aid</label>
    <nameField>
        <label>Sales Aid Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Aids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Aid_Question__c.object
<CustomObject>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>category__c</fullName>
        <label>category</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>options__c</fullName>
        <defaultValue>false</defaultValue>
        <label>options</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Aid Question</label>
    <nameField>
        <displayFormat>SAQ-{000}</displayFormat>
        <label>Sales Aid Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Aid Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sales_aid_response__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Competitor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Genesys__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Genesys</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Neither__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Neither</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Aid Responses</relationshipLabel>
        <relationshipName>Sales_Aid_Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_number__c</fullName>
        <label>Question number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>This is linked with option in sales aid question</description>
        <label>Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Aid_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Aid Question</label>
        <referenceTo>Sales_Aid_Question__c</referenceTo>
        <relationshipLabel>Sales Aid Responses</relationshipLabel>
        <relationshipName>Sales_Aid_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Aid_Question_txt__c</fullName>
        <label>Sales Aid Question txt</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Aid__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Aid</label>
        <referenceTo>Sales_Aid__c</referenceTo>
        <relationshipLabel>Sales Aid Responses</relationshipLabel>
        <relationshipName>Sales_Aid_Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>category__c</fullName>
        <label>category</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Sales Aid Response</label>
    <nameField>
        <displayFormat>SAR-{000}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Aid Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesaid_Action_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Salesaid Action Plans</relationshipLabel>
        <relationshipName>Salesaid_Action_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <label>Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_Activity__c</fullName>
        <label>Proposed Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>rownumber__c</fullName>
        <label>#</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sales_aid__c</fullName>
        <label>Sales Aid</label>
        <referenceTo>Sales_Aid__c</referenceTo>
        <relationshipLabel>Salesaid Action Plans</relationshipLabel>
        <relationshipName>Salesaid_Action_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Salesaid Action Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Salesaid Action Plan  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesaid Action Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testSalesaidApexClass.cls
//Ravi V - Sales Aid -  12/06/2013
@isTest(SEEALLDATA=TRUE)

public class testSalesaidApexClass
{  
 
 static testMethod void testClassMethod()
    
    { 
list<Recordtypes__c> lstrecordtype=new   list<Recordtypes__c>();//bulk List of custom setting object for bulk insert

 
     String firstcheck;
     String RecordTypeId;
     List<Responsewrapper> saqWrapperedit;
     String st;
     List<SelectOption> temp = new List<SelectOption>();
     RecordType rt = [select id,Name from RecordType where name='Success Plan'];
     Country__c cc = [select id,Name from Country__c where name='United States'];
     Account a = new Account( Name='Test Account', Status__c = 'Active',Country__c=cc.id); 
     insert a;
     Opportunity opp = new Opportunity( Name='Test Opp',Direct_sales__c=true,accountId=a.id,StageName='3.Evaluate Options',CloseDate=date.today(),Competitor__c='NONE');
     insert opp;
     PageReference pageRef = Page.Salesaid_SuccessPlan;
     pageRef.getParameters().put('retURL','/'+opp.id);
     pageRef.getParameters().put('RecordType',rt.id);
     Test.setCurrentPageReference(pageRef); 
    
     Sales_Aid__c sa = new Sales_Aid__c(name='test sa',RecordTypeId=rt.id);
     insert sa;
     ApexPages.StandardController sc = new ApexPages.StandardController(sa);
    
     Sales_Aid_extension sad = new Sales_Aid_extension(sc);
     
     firstcheck=sad.getParametersNew();
     
     Sales_Aid_Question__c saq = new Sales_Aid_Question__c(category__c='first',options__c=true,Questions__c='this is for testing',Sequence_Number__c=1,Stage__c='one');
     insert saq;
     RecordType rt2 = [select id,Name from RecordType where name='Call Plan'];
      Sales_Aid__c sa1 = new Sales_Aid__c(name='test sac',RecordTypeId=rt2.id);
     insert sa1;
     Questionwrapper qw = new Questionwrapper(saq);
     temp=qw.getOptionsall();
     pageReference pfsave =sad.savequestions();
       pageReference pfsave2 =sad.savecallplan();
       sad.saqWrapperedit=sad.getupdatequestions();
       pageReference pfsave3=sad.updatequestions();
         
           string[] starray=sad.getheaders();
           //List<String> editfieldss=sad.editableFields;
        PageReference pfsave7=sad.redirectNew();
          List<Salesaid_Action_Plan__c>  sapeditluist=sad.getActionplaneditlist();
        List<Salesaid_Action_Plan__c>  sapluist=sad.getActionplanlist();
     saqWrapperedit = sad.getupdatequestions();
      sad.Obj=sa1;
     Salesaid_Action_Plan__c sap = new Salesaid_Action_Plan__c(rownumber__c=1,Complete__c=true,Description__c='testing',Opportunity__c=opp.id,Owner__c='RaviV',Proposed_Activity__c='Sales aid project',sales_aid__c=sa1.id,Target_Date__c=system.today());
     insert sap;
     
     sad.SAPlist=sapeditluist;
         
     Actionplanwrapper aw1 = new Actionplanwrapper(1);
     Actionplanwrapper aw2 = new Actionplanwrapper(sap);
     
     sa1=[select id,recordtypeid from Sales_Aid__c where id=:sa1.id limit 1]; 
     
     System.currentPageReference().getParameters().put('id', sa1.id);
     System.currentPageReference().getParameters().put('RecordType', rt.id);
     System.currentPageReference().getParameters().put('retURL', opp.id);
     
     pageReference pfsave4=sad.saveActionplan();
     PageReference pfsave5=sad.updateActionplan();
     PageReference pfsave6=sad.redirectEdit();
     List<Salesaid_Action_Plan__c> sapeditlist=sad.getEditActionplan();
     st=sad.getParametersEdit();
     
     sales_aid_response__c sar = new sales_aid_response__c (stage__c='testing',Sales_Aid__c=sa.id, Opportunity__c=opp.id,Sales_Aid_Question_txt__c='testing 1',category__c='first',Question_number__c=1,Competitor__c=true,Genesys__c=true,Neither__c=true,Partner__c=true,Response__c='Yes',Comments__c='xyz');
     insert sar;
     sar =[select id,stage__c,Sales_Aid__c,Opportunity__c,Sales_Aid_Question_txt__c,category__c,Question_number__c,Competitor__c,Genesys__c,Neither__c,Partner__c,Response__c,Comments__c from sales_aid_response__c where stage__c='testing' limit 1];
     Responsewrapper rw = new Responsewrapper(sar);
    List<SelectOption> ls2 =rw.getOptionsall();
     
     //pageReference pfupdate =sad.updatequestions();
    }
    }