objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CORE Model</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/GCR__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Legal Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GCRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attorney_Name__c</fullName>
        <label>Attorney Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Bill Dummett</fullName>
                </value>
                <value>
                    <fullName>Carin Mastrolia</fullName>
                </value>
                <value>
                    <fullName>Catherine Ewings</fullName>
                </value>
                <value>
                    <fullName>Daniel Benavides</fullName>
                </value>
                <value>
                    <fullName>Devyn Rangiah</fullName>
                </value>
                <value>
                    <fullName>Elizabeth Vincent</fullName>
                </value>
                <value>
                    <fullName>Geoffrey Castronovo</fullName>
                </value>
                <value>
                    <fullName>Giselle Dalan</fullName>
                </value>
                <value>
                    <fullName>Harry Mak</fullName>
                </value>
                <value>
                    <fullName>Jaime Borja-Lascurain</fullName>
                </value>
                <value>
                    <fullName>Jason Klavon</fullName>
                </value>
                <value>
                    <fullName>Joe Hynes</fullName>
                </value>
                <value>
                    <fullName>John Garcia</fullName>
                </value>
                <value>
                    <fullName>Jyl Obozbekova</fullName>
                </value>
                <value>
                    <fullName>Laura Arsenault</fullName>
                </value>
                <value>
                    <fullName>Mark Rosine</fullName>
                </value>
                <value>
                    <fullName>Paul Collins</fullName>
                </value>
                <value>
                    <fullName>Reception Netherlands</fullName>
                </value>
                <value>
                    <fullName>Scott Wolfe</fullName>
                </value>
                <value>
                    <fullName>Shahzad Ahmad</fullName>
                </value>
                <value>
                    <fullName>Stephanie Meckler</fullName>
                </value>
                <value>
                    <fullName>Tamsen Bhachech</fullName>
                </value>
                <value>
                    <fullName>Tomasz Sztyber</fullName>
                </value>
                <value>
                    <fullName>Victor Buzinari</fullName>
                </value>
                <value>
                    <fullName>Vikram Sharma</fullName>
                </value>
                <value>
                    <fullName>Vincent Lim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>GCRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GCR_Content_Document_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCR Content Document Detail</label>
        <referenceTo>GCR_Content_Document_Detail__c</referenceTo>
        <relationshipName>GCRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>GCRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Application</label>
        <referenceTo>Partner_Application__c</referenceTo>
        <relationshipLabel>Legal Contract Requests</relationshipLabel>
        <relationshipName>Legal_Contract_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Legal Region Contacts</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APAC (Vincent Lim)</fullName>
                    <label>APAC</label>
                </value>
                <value>
                    <fullName>LATAM (Jaime Borja)</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>North America (John Garcia/Tracey McAllister)</fullName>
                    <default>true</default>
                    <label>North America (John Garcia/Tracey McAllister)</label>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                    <default>true</default>
                    <label>Sales</label>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                </value>
                <value>
                    <fullName>Data Privacy / Information Security</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requestor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GCRs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Sub_Type__c</fullName>
        <description>What it does? Stores the Subscription Sub Type. Downstream Impact?Reporting. Which Department is Owner? Finance</description>
        <label>Subscription Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Amend Existing Subscription</fullName>
                </value>
                <value>
                    <fullName>New Org &amp; Subscription</fullName>
                </value>
                <value>
                    <fullName>Renew Existing Subscription</fullName>
                </value>
                <value>
                    <fullName>Replace Existing Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Legal Contract Request</label>
    <nameField>
        <displayFormat>Legal Request -{000000}</displayFormat>
        <label>Legal Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legal Contract Requests(New)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/GCR_Content_Document_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GCR_Content_Document_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Renewal_Date__c</fullName>
        <label>Expiration/Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>GCR_Content_Document_Folder__c</referenceTo>
        <relationshipName>GCR_Content_Document_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GCR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCR</label>
        <referenceTo>GCR__c</referenceTo>
        <relationshipName>GCR_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>Contracts - {000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GCR_Content_Document_Folder__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GCR_Content_Document_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GCR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCR</label>
        <referenceTo>GCR__c</referenceTo>
        <relationshipName>GCR_Content_Document_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contracts Folders</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GCR Content Document Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Application__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Applications</relationshipLabel>
        <relationshipName>Partner_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Partner Applications (Contact)</relationshipLabel>
        <relationshipName>Partner_Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Account__r.Country__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>Partner Application</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Partner Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Application_Category_and_Country__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Partner App Categories and Countries</relationshipLabel>
        <relationshipName>Partner_App_Categories_and_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Application__c</fullName>
        <label>Partner Application</label>
        <referenceTo>Partner_Application__c</referenceTo>
        <relationshipLabel>Partner App Categories and Countries</relationshipLabel>
        <relationshipName>Partner_App_Categories_and_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Application Category and Country</label>
    <nameField>
        <displayFormat>PACC-{000000}</displayFormat>
        <label>Partner Application Category and Country</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner App Categories and Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GCRContentDocumentDetailsControllerTest.cls
@isTest(seeAllData = true)
private class GCRContentDocumentDetailsControllerTest {
    public static String gcrId;
    public static String documentId;
    public static String accountId;
    public static String folderId;
    public static String attachmentId;
    public static String docusignStatusId;
    
    static void insertTestData(){
        Country__c testCountry = [SELECT Id, Name, Country__c, Region__c FROM Country__c WHERE Name = 'United States'];
        /*testCountry.Name = 'Test Country';
        testCountry.Country__c = 'Test Country';
        testCountry.Region__c = 'APAC';
        insert testCountry;*/
        
        Account acct = new Account();
        acct.Name = 'Test Account';
        acct.Country__c = testCountry.id;
        insert acct;
      
        Opportunity opp = new Opportunity();
        opp.AccountId = acct.Id;
        opp.Name = 'Test Opportunity';
        acct.Country__c = testCountry.id;
        opp.StageName = 'Prospect';
        opp.CloseDate = Date.Today();        
        insert opp;
             
        Contact con = new Contact();
        con.AccountId = acct.Id;
        con.LastName = 'Test Contact';
        con.Email = 'test@test.com';        
        insert con;
        
        String paID = [SELECT Partner_Application__c FROM Partner_Application_Category_and_Country__c WHERE Country__r.Name = 'United States' LIMIT 1][0].Partner_Application__c;
        
        List<GCR__c> gcrList = new List<GCR__c>();   
        
        GCR__c gcr = new GCR__c();
        gcr.Contact__c = con.id;
        gcr.Account__c = acct.Id;
        gcr.Region__c = acct.Country__r.Region__c;
        gcr.Request_Type__c = 'Sales';
        gcr.Contact_Name__c = con.Name;
        gcr.Contact_Phone__c = con.ContactPhone__c;
        gcr.Requestor_Name__c = UserInfo.getUserId();
        gcr.Attorney_Name__c = UserInfo.getUserId();
        gcr.Opportunity__c = opp.Id;
        gcr.Subscription_Sub_Type__c = 'Amend Existing Subscription';
        gcr.Partner_Application__c = paID;
        gcrList.add(gcr);
        insert gcrList;
        
        GCR_Content_Document_Detail__c document = new GCR_Content_Document_Detail__c();        
        document.Account_Name__c = acct.Id;
        document.GCR__c = gcrList[0].id;       
        document.Active__c = true;
        insert document;
        
        GCR_Content_Document_Folder__c folder = new GCR_Content_Document_Folder__c();
        folder.Active__c = true;
        folder.Account__c = acct.id;
        folder.Name = 'Test Folder';
        folder.GCR__c = gcrList[0].id;
        insert folder;
        
        dsfs__DocuSign_Status__c docStatus = new dsfs__DocuSign_Status__c();
        docStatus.GCR_Content_Document__c = document.id;
        insert docStatus;
        
        Attachment attach=new Attachment();     
        attach.Name = 'Unit Test Attachment';
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        attach.body = bodyBlob;
        attach.parentId = docStatus.id;
        insert attach;
        
        folderId = folder.id;
        gcrId = gcrList[0].id;
        documentId = document.id;       
        accountId = acct.id;
        attachmentId = attach.id;
        docusignStatusId = docStatus.id;
    }
    static testMethod void myUnitTest1() {  
        insertTestData();   
        ApexPages.currentPage().getParameters().put('id', gcrId);
        String documentRecordId = ApexPages.currentPage().getParameters().put('documentRecordId', documentId);
        
        GCRContentDocumentDetailsController objPg = new GCRContentDocumentDetailsController(new ApexPages.StandardController(new GCR_Content_Document_Detail__c()));
    }
    static testMethod void myUnitTest2() {  
        insertTestData(); 
        
        ApexPages.currentPage().getParameters().put('id', gcrId);
        ApexPages.currentPage().getParameters().put('gcrId', gcrId);
        ApexPages.currentPage().getParameters().put('hideHeader','true');
        ApexPages.currentPage().getParameters().put('embedded', 'true');
        ApexPages.currentPage().getParameters().put('showAll', 'true');
        ApexPages.currentPage().getParameters().put('addNewDocument', 'true');
        ApexPages.currentPage().getParameters().put('accId', accountId);        
        ApexPages.currentPage().getParameters().put('folderId', folderId);
        ApexPages.currentPage().getParameters().put('addNewFolder', 'true');
        
        String documentRecordId = ApexPages.currentPage().getParameters().put('documentRecordId', documentId);
        GCRContentDocumentDetailsController objPg = new GCRContentDocumentDetailsController(new ApexPages.StandardController(new GCR_Content_Document_Detail__c()));
        objPg.addNewDocument();        
        objPg.refresh();
        objPg.edit();
        objPg.setAccountId();
        objPg.resetAccount();
        objPg.currentRecord.Effective_Date__c = System.today();
        objPg.currentRecord.Expiration_Renewal_Date__c = System.today().addDays(7);
        objPg.currentRecord.Legal_Exceptions__c = 'None;Background Checks';
        objPg.save();
        objPg.currentRecord.Legal_Exceptions__c = 'Background Checks';
        objPg.save();
        objPg.showAll();
        objPg.saveFolder();
        objPg.editFolder();
        objPg.cancel();
        objPg.sendToFinanceDirectly();
        objPg.sendToFinanceViaDocusign();
        objPg.approve();
        objPg.getDocusignRecpDisplay();
        objPg.attachmentIdToBeDeleted = attachmentId;
        objPg.delAttachment();
        objPg.deleteFolder();  
    }
    
    static testMethod void myUnitTest3() {  
        insertTestData();   
        ApexPages.currentPage().getParameters().put('id', gcrId);
        ApexPages.currentPage().getParameters().put('gcrId', gcrId);
        ApexPages.currentPage().getParameters().put('hideHeader','true');
        ApexPages.currentPage().getParameters().put('embedded', 'true');
        ApexPages.currentPage().getParameters().put('showAll', 'true');
        ApexPages.currentPage().getParameters().put('addNewDocument', 'true');
        ApexPages.currentPage().getParameters().put('accId', accountId);        
        ApexPages.currentPage().getParameters().put('folderId', folderId);
        ApexPages.currentPage().getParameters().put('addNewFolder', 'true');
        
        GCR_Content_Document_Folder__c folder = new GCR_Content_Document_Folder__c();
        folder.Active__c = true;
        folder.Account__c = accountId;
        folder.Name = 'Test Folder 1';
        folder.GCR__c = gcrId;
        folder.Parent_Folder__c = folderId;
        insert folder;
        
        GCR_Content_Document_Detail__c document = new GCR_Content_Document_Detail__c();        
        document.Account_Name__c = accountId;
        document.Contract_Category__c = 'Amend';
        document.GCR__c = gcrId;       
        document.Active__c = true;
        document.Folder__c = folder.id;
        insert document;
        
        String documentRecordId = ApexPages.currentPage().getParameters().put('documentRecordId', documentId);
        GCRContentDocumentDetailsController objPg = new GCRContentDocumentDetailsController(new ApexPages.StandardController(new GCR_Content_Document_Detail__c()));
        objPg.addNewDocument();        
        objPg.refresh();
        objPg.edit();
        objPg.setAccountId();
        objPg.resetAccount();
        objPg.currentRecord.Legal_Exceptions__c = 'None';
        objPg.currentRecord.Effective_Date__c = System.today();
        objPg.save();
        objPg.currentRecord.Expiration_Renewal_Date__c = System.today().addDays(7);
        objPg.save();
        objPg.currentRecord.Contract_Category__c = 'Amend';
        objPg.save();
        objPg.showAll();
        objPg.saveFolder();
        objPg.editFolder();
        objPg.cancel();
        objPg.sendToFinanceDirectly();
        objPg.sendToFinanceViaDocusign();
        objPg.getDocusignRecpDisplay();
        objPg.getDocusignStatusRecordId();
        objPg.showFromCurrentGCR();
        objPg.attachmentIdToBeDeleted = attachmentId;
        objPg.delAttachment();
        objPg.deleteFolder();  
    }
    
    static testMethod void testDocuSignRecipientStatusTrigger(){
        insertTestData();
        dsfs__DocuSign_Recipient_Status__c newRecipientStatus = new dsfs__DocuSign_Recipient_Status__c();
        newRecipientStatus.dsfs__Recipient_Status__c = 'Test';  
        newRecipientStatus.dsfs__DocuSign_Recipient_Id__c = 'test'; 
        newRecipientStatus.dsfs__Parent_Status_Record__c = docusignStatusId;
        insert newRecipientStatus;
        newRecipientStatus.dsfs__Date_Signed__c = System.today();
        newRecipientStatus.dsfs__DocuSign_Recipient_Email__c = 'test@genesys.com';
        update newRecipientStatus;
        newRecipientStatus.dsfs__Date_Signed__c = System.today().addDays(1);
        newRecipientStatus.dsfs__DocuSign_Recipient_Email__c = 'test@test.com';         
        update newRecipientStatus;
        
    }   
    
    
    static testmethod void TestGCRequestController2(){
                   
        Account acct = new Account();
        acct.Name = 'Test Account';
        insert acct;

        Opportunity opp = new Opportunity();
        opp.AccountId = acct.Id;
        opp.Name = 'Test Opportunity';
        opp.StageName = 'Prospect';
        opp.CloseDate = Date.Today();        
        insert opp;  
        
        Contact con = new Contact();
        con.AccountId = acct.Id;
        con.LastName = 'Test Contact';
        con.Email = 'standarduser@testorg.com';        
        insert con;
        
        GCR__c gcr = new GCR__c();
        gcr.Contact__c = con.id;
        gcr.Account__c = acct.Id;
        gcr.Region__c = acct.Country__r.Region__c;
        gcr.Request_Type__c = 'Sales';
        gcr.Contact_Name__c = con.Name;
        gcr.Contact_Phone__c = con.ContactPhone__c;
        gcr.Requestor_Name__c = UserInfo.getUserId();
        gcr.Attorney_Name__c = UserInfo.getUserId();
        gcr.Contract_Type__c = 'Amendment';
        gcr.Offering_Type__c = 'PureCloud';
        insert gcr;
        
        List<GCR_Content_Document_Folder__c> gcrFolderList = new List<GCR_Content_Document_Folder__c>();        
        GCR_Content_Document_Folder__c gcrFolder = new GCR_Content_Document_Folder__c();
        gcrFolder.Name = gcr.Name;
        gcrFolder.Account__c = gcr.Account__c;
        gcrFolder.GCR__c = gcr.id;
        gcrFolder.Active__c = true;
        gcrFolderList.add(gcrFolder);
        insert gcrFolderList;
        
             
        GCR_Content_Document_Detail__c  gcrDocDetail = new GCR_Content_Document_Detail__c();
        gcrDocDetail.Folder__c = gcrFolder.id;
        gcrDocDetail.Legal_Exceptions__c = 'Billing Period';
        gcrDocDetail.IsGoverningContract__c = true;
        gcrDocDetail.Contract_Category__c = 'Amend';
        gcrDocDetail.Expiration_Renewal_Date__c = System.today().addDays(5);
        gcrDocDetail.Contract_Type__c = 'Service Order';
        gcrDocDetail.Account_Name__c = gcr.Account__c;
        gcrDocDetail.GCR__c = gcr.id;
        gcrDocDetail.Document_Name__c = gcr.Name;
        gcrDocDetail.Active__c = true;        
        insert gcrDocDetail;
        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('documentRecordId', gcrDocDetail.Id);
        ApexPages.currentPage().getParameters().put('gcrId', gcr.Id);
        GCRContentDocumentDetailsController objPg = new GCRContentDocumentDetailsController(new ApexPages.StandardController(gcrDocDetail));
        objPg.checkRequiredField();
        objPg.currentRecord.Contract_Type__c = 'PureCloud T&C';
        objPg.checkRequiredField();
        objPg.currentRecord.Is_Governing_Contract__c = true;
        objPg.checkRequiredField();
        objPg.enableGoveringFields();
        objPg.currentRecord.Contract_Category__c = 'New';
        objPg.currentRecord.Contract_Type__c = 'Service Order';
        objPg.checkRequiredField();
        objPg.checkGoverningType();
        objPg.currentRecord.Contract_Category__c = 'New';
        objPg.currentRecord.Contract_Type__c = 'PureCloud T&C';
        objPg.checkRequiredField();
        objPg.checkGoverningType();
        objPg.currentRecord.Is_Governing_Contract__c = false;
        objPg.enableGoveringFields();
        objPg.deleteDocument();
        objPg.pageMode = 'edit';
        objPg.intializeCountryList();
        Test.stopTest();
    }
}