objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>What it Does?  Holds the country&apos;s ISO Code.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
        <externalId>true</externalId>
        <label>ISO Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LegacyId__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Country Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Legacy_EMG_Id__c</fullName>
        <externalId>true</externalId>
        <label>Legacy EMG Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PSRDP_Region__c</fullName>
        <label>PSRDP Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RU__c</fullName>
        <description>CORE Model</description>
        <label>Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ANZ</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>DACH</fullName>
                </value>
                <value>
                    <fullName>France &amp; N. Africa</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>Iberia</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>UKI</fullName>
                </value>
                <value>
                    <fullName>Benelux</fullName>
                </value>
                <value>
                    <fullName>ECSEI</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                </value>
                <value>
                    <fullName>Italy &amp; Middle East</fullName>
                </value>
                <value>
                    <fullName>South East Asia</fullName>
                </value>
                <value>
                    <fullName>Andean</fullName>
                </value>
                <value>
                    <fullName>Southern Cone</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CORE Model</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubRU__c</fullName>
        <description>CORE Model</description>
        <label>Sub-Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andean &amp; Central</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belux</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Central, South East Europe and Israel (CSEI)</fullName>
                </value>
                <value>
                    <fullName>CIS</fullName>
                </value>
                <value>
                    <fullName>CIS &amp; Central/Eastern Europe</fullName>
                </value>
                <value>
                    <fullName>CS Europe</fullName>
                </value>
                <value>
                    <fullName>France Pacific</fullName>
                </value>
                <value>
                    <fullName>France Reg.</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece Reg.</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>Italy Reg.</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Mainland China</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Maldives</fullName>
                </value>
                <value>
                    <fullName>Malta</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                </value>
                <value>
                    <fullName>N&amp;B</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <description>Champ créé le 9/09/11 suite à réorganisation des Regions pour EMEA</description>
        <label>Sub Region Old</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>AMERICAS</fullName>
                </value>
                <value>
                    <fullName>EUNO</fullName>
                </value>
                <value>
                    <fullName>EUSO</fullName>
                </value>
                <value>
                    <fullName>MEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Global_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Information__c</fullName>
        <label>Information</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

objects/Partner_Directory_Approved__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Directory Approveds</relationshipLabel>
        <relationshipName>Partner_Directory_Approveds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Channel Manager Approved</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Final Approval Done</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HQ_Address__c</fullName>
        <label>HQ Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Directory_Staging__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Directory-Staging</label>
        <referenceTo>Partner_Directory_Staging__c</referenceTo>
        <relationshipLabel>Partner Directory Approveds</relationshipLabel>
        <relationshipName>Partner_Directory_Approveds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>text(Account__r.Country__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMART_Qualified__c</fullName>
        <formula>Account__r.SMART_Qualified__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SMART Qualified</label>
        <type>Checkbox</type>
    </fields>
    <label>Partner Directory Approved</label>
    <nameField>
        <label>Partner Directory Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Directory Approveds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Directory_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account object lookup for partner directory.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Directory-Stagings</relationshipLabel>
        <relationshipName>Partner_Directory_Stagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Channel Manager Approved</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Channel Manager Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>text(Account__r.Country__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMART_Qualified__c</fullName>
        <formula>Account__r.SMART_Qualified__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SMART Qualified</label>
        <type>Checkbox</type>
    </fields>
    <label>Partner Directory-Staging</label>
    <nameField>
        <label>Partner Directory-Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Directory-Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidary__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Store the country related to Subsidiary
Downstream Impact? To be used by PureCloud Billing
Which department is owner? IT/PureCloud Team</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Subsidaries</relationshipLabel>
        <relationshipName>Subsidaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subsidary</label>
    <nameField>
        <label>Subsidary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PartnerDirectoryControllertest.cls
@isTest

public class PartnerDirectoryControllertest {
    
    static testmethod void init(){
        test.startTest();        
       
        
        
        country__c country = new country__C(Name='United States',
                                              RU__c = 'North America', 
                                              SubRegion__c = 'AMERICAS',
                                              SubRU__c='USA', 
                                              Region__c='North America',
                                              PSRDP_Region__c='NA',
                                              Country__c ='United States1',
                                              ISO_Code__c='911' , 
                                              LegacyId__c = 'test',
                                              Legacy_EMG_Id__c = 'test' );
        insert country;
        list<String> region = new list<string>();
        region.add(country.Region__c);
        
   recordtype recTp = [Select Id,DeveloperName from recordtype where DeveloperName = 'EMGBusinessPartnerRecordType'];
    Global_Setting__c setting = new Global_Setting__c();
        setting.Name = 'United States';
        setting.ID__c = 'a24U00000004XlJ';
        setting.Type__c = 'Subsidary';
        setting.Information__c = '8100 United States';
        insert setting;
       
        
    account testaccount = new Account(Name='Test Account',Subsidary__c = setting.ID__c,Country__c = country.id,Partner_Tier__c = 'gold',SMART_Qualified__c = true,Screening_Checklist_Completed__c=true, isDirect__c= true, PartnerType__c = 'VAR',recordtypeid=recTp.Id );
    insert testaccount;
  
        list<String> ptypes = new list<string>();
        ptypes.add(testaccount.PartnerType__c);    
        list<String> ptiers = new list<string>();
        ptiers.add(testaccount.Partner_Tier__c);
    
    Partner_Directory_Staging__c  testpartnerdirectoryadmin = new Partner_Directory_Staging__c (Account__C = testaccount.id, Approval_Status__c = 'Published', 
                                                                                           HQ_Address__c = 'Colonia 968, 11100 Montevideo Montevideo Department, Uruguay',Latitude__c = '-34.90541109999999',
                                                                                           Longitude__c = '56.19571840000003', Phone__c = '123123123123', Website__c = 'www.google.com',
                                                                                           Company_Description__c = 'test');
  insert testpartnerdirectoryadmin;
        
  Partner_Directory_Approved__c testpartnerdirapproved = new Partner_Directory_Approved__c(Account__C = testaccount.id, Approval_Status__c = 'Published', 
                                                                                           HQ_Address__c = 'Colonia 968, 11100 Montevideo Montevideo Department, Uruguay',Latitude__c = '-34.90541109999999',
                                                                                           Longitude__c = '56.19571840000003', Phone__c = '123123123123', Website__c = 'www.google.com',Offering_Type__c = 'PureCloud', Specialization__c = 'PureEngage Core',  TierSupport__c = 'Gold',
                                                                                           Company_Description__c = 'test', Partner_Directory_Staging__c = testpartnerdirectoryadmin.id); 
        
     insert  testpartnerdirapproved;  
        
        list<String> poffer = new list<string>();
        poffer.add(testpartnerdirapproved.Offering_Type__c);
        list<String> pspecial = new list<string>();
        pspecial.add(testpartnerdirapproved.Specialization__c);
        
        PartnerDirectoryController pdc = new PartnerDirectoryController(new ApexPages.StandardController(testpartnerdirapproved));
     PageReference pageRef = Page.Finderloc; 
     Test.setCurrentPage(pageRef);          
    pageRef.getParameters().put('pid', testpartnerdirapproved.id); 
         pdc.searchPartner();
        pdc.filteraction();
     pageRef.getParameters().put('partnerName', testaccount.Name);    
     pageRef.getParameters().put('selectedRegion',  country.Region__c);
      
     
        pdc.init();        
        pdc.clearall();      
        pdc.specficpartnerlink();
        pdc.partnerName =  testaccount.Name;
        pdc.smartQualifieds = true;     
        pdc.selectedRegion = region;
        pdc.selectedPartnerType1 = ptypes;
        pdc.selectedPartnerTiers = ptiers;          
        pdc.selectedOfferingType = poffer;
        pdc.selectedSpecialization = pspecial;      
        pdc.getCloudoff();
        pdc.getOnPremiseoff();
        pdc.getPCloud();
        pdc.getPEngage();
        pdc.getPCSA();    
        pdc.searchPartner();
        pdc.filteraction();
    }
}