objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CORE Model</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Site__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>New_Solution_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Solution Design</label>
        <referenceTo>New_Solution_Design__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>CANADA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
                <value>
                    <fullName>N / A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution_Design__c</fullName>
        <label>Solution Design - Old Reference</label>
        <referenceTo>Solution_Design__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Customer_Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>Site-{00000}</displayFormat>
        <label>**Customer Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DSR_SCE_Design__c.object
<CustomObject>
    <fields>
        <fullName>DSR_SCEngagement__c</fullName>
        <label>DSR SCEngagement</label>
        <referenceTo>DSR_SCEngagement__c</referenceTo>
        <relationshipLabel>DSR SCE Designs</relationshipLabel>
        <relationshipName>DSR_SCE_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DataCenters__c</fullName>
        <label>Data Centers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HAType__c</fullName>
        <label>HA Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DSR SCE Design</label>
    <nameField>
        <displayFormat>SCEDES - {000000}</displayFormat>
        <label>Design ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR SCE Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DSR_SCEngagement__c.object
<CustomObject>
    <fields>
        <fullName>AE_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DSR_SCEngagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>DSR_SCEngagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AssignTo__c</fullName>
        <label>AssignTo</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity ID</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>DSR_SCEngagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SC_Engagement_Status__c</fullName>
        <label>SC Engagement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open and Assigned</fullName>
                </value>
                <value>
                    <fullName>Open and Not Assigned</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted for Completion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DSR SC Engagement or Partner SMART DSR</label>
    <nameField>
        <displayFormat>SCE - {00000}</displayFormat>
        <label>SC DSR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR SC Engagements or Partner SMART DSRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DSR_Use_Case_Blueprints__c.object
<CustomObject>
    <fields>
        <fullName>DSRSCEDesign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSR SCE Design</label>
        <referenceTo>DSR_SCE_Design__c</referenceTo>
        <relationshipLabel>DSR Use Case &amp; Blueprints</relationshipLabel>
        <relationshipName>DSR_Use_Case_Blueprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DSRSCEngagement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSR SC Engagement</label>
        <referenceTo>DSR_SCEngagement__c</referenceTo>
        <relationshipLabel>DSR Use Case &amp; Blueprints</relationshipLabel>
        <relationshipName>DSR_Use_Case_Blueprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShortCode__c</fullName>
        <label>Short Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Use Case</fullName>
                </value>
                <value>
                    <fullName>Blueprint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DSR Use Case &amp; Blueprints</label>
    <nameField>
        <label>DSR Use Case &amp; Blueprints Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DSR Use Case &amp; Blueprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ININ_Applications__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer_Site__c.Solution_Design__c</field>
                <operation>equals</operation>
                <valueField>$Source.Solution_Design__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer_Site__c</referenceTo>
        <relationshipName>ININ_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Solution_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Solution Design</label>
        <referenceTo>New_Solution_Design__c</referenceTo>
        <relationshipLabel>ININ Applications</relationshipLabel>
        <relationshipName>ININ_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution Design</label>
        <referenceTo>Solution_Design__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>ININ_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000000}</displayFormat>
        <label>ININ Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ININ Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ININ_Solution_Components__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer_Site__c.New_Solution_Design__c</field>
                <operation>equals</operation>
                <valueField>$Source.New_Solution_Design__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer_Site__c</referenceTo>
        <relationshipLabel>ININ Solution Components</relationshipLabel>
        <relationshipName>ININ_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Solution_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Solution Design</label>
        <referenceTo>New_Solution_Design__c</referenceTo>
        <relationshipLabel>ININ Solution Components</relationshipLabel>
        <relationshipName>ININ_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution_Design__c</fullName>
        <label>Solution Design</label>
        <referenceTo>Solution_Design__c</referenceTo>
        <relationshipLabel>Solution Components</relationshipLabel>
        <relationshipName>ININ_Solution_Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Solution Component</label>
    <nameField>
        <displayFormat>ISC-{0000000}</displayFormat>
        <label>ININ Solution Components ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ININ Solution Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/New_Solution_Design__c.object
<CustomObject>
    <fields>
        <fullName>DSR_SCE_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DSR SCE Design</label>
        <referenceTo>DSR_SCE_Design__c</referenceTo>
        <relationshipName>New_Solution_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outbound_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Outbound Only</label>
        <type>Checkbox</type>
    </fields>
    <label>Cloud Approval Process</label>
    <nameField>
        <label>New Solution Design Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cloud Approval Processs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wow_Sub_Regional_Users__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Hold the sub regional users</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subregional_Leader__c</fullName>
        <label>Subregional Leader</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Wow Sub Regional Users</label>
</CustomObject>

classes/NewSolutionDesignControllerClone1_Test.cls
/*
* Created By: Ashish Goyal (05/13/2019)
* Desc: Test class for the VF Controller, Trigger, and TriggerHelper created for MDM Functionality
*/
@isTest(seealldata=true)
private class NewSolutionDesignControllerClone1_Test {
    
    static testmethod void test_ValidateTest(){
        //Create Account          
        List<Account> lstAcc=TestUtil.createAccounts(1,true);           
       
        user objUser=[SELECT Id,Bypass_Triggers__c FROM User WHERE Id=:userinfo.getUserId()];  
        objUser.Bypass_Triggers__c = true;
        update objUser;  
        
        country__c objCountry=[SELECT ID,Region__c FROM country__c WHERE Name=:'New Zealand'] ;   
       
        Wow_Sub_Regional_Users__c custSet = new Wow_Sub_Regional_Users__c();
        custSet.Name = 'Test';
        custSet.Subregional_Leader__c = 'amit@rsys.com';
        custSet.User_Name__c = 'Test';
        insert custSet;
        
        Opportunity ObjOpp  = TestUtil.createOpportunities(1,lstAcc[0].id, false)[0];
        ObjOpp.Lines_of_Businesses__c = 'PureCloud';
        insert ObjOpp;
        
        DSR_SCEngagement__c dsr = new DSR_SCEngagement__c();
        dsr.Account_ID__c = lstAcc[0].Id;
        dsr.AE_Name__c = objUser.Id;
        dsr.AssignTo__c = 'Lead Assign';
        dsr.Opportunity_ID__c = ObjOpp.Id;
        dsr.SC_Engagement_Status__c = 'Open and Not Assigned';        
        insert dsr;
        
        DSR_SCE_Design__c objSCDesign = new DSR_SCE_Design__c();
        objSCDesign.DSR_SCEngagement__c = dsr.id;
        objSCDesign.HAType__c = 'aa';
        objSCDesign.DataCenters__c = 'aa';
        insert objSCDesign ;
        
        DSR_Use_Case_Blueprints__c objFnUseCase = new DSR_Use_Case_Blueprints__c();
        objFnUseCase.DSRSCEDesign__c = objSCDesign.id;
        objFnUseCase.DSRSCEngagement__c = dsr.id;
        objFnUseCase.ShortCode__c = 'B01';
        objFnUseCase.Type__c = 'Use Case';
        objFnUseCase.Name__c = 'aa';
        insert objFnUseCase;
        
        DSR_Use_Case_Blueprints__c objFnUseCase1 = new DSR_Use_Case_Blueprints__c();
        objFnUseCase1.DSRSCEDesign__c = objSCDesign.id;
        objFnUseCase1.DSRSCEngagement__c = dsr.id;
        objFnUseCase1.ShortCode__c = 'B01';
        objFnUseCase1.Type__c = 'Use Case';
        objFnUseCase1.Name__c = 'IVR';
        insert objFnUseCase1;
        
        DSR_Use_Case_Blueprints__c objFnUseCase2 = new DSR_Use_Case_Blueprints__c();
        objFnUseCase2.DSRSCEDesign__c = objSCDesign.id;
        objFnUseCase2.DSRSCEngagement__c = dsr.id;
        objFnUseCase2.ShortCode__c = 'B01';
        objFnUseCase2.Type__c = 'Use Case';
        objFnUseCase2.Name__c = 'IVR interaction';
        insert objFnUseCase2;
        
        DSR_Use_Case_Blueprints__c objFnUseCase3 = new DSR_Use_Case_Blueprints__c();
        objFnUseCase3.DSRSCEDesign__c = objSCDesign.id;
        objFnUseCase3.DSRSCEngagement__c = dsr.id;
        objFnUseCase3.ShortCode__c = 'Custom';
        objFnUseCase3.Type__c = 'Use Case';
        objFnUseCase3.Name__c = 'aa';
        insert objFnUseCase3;
        
        Solution_Design__c sdobj = new Solution_Design__c();
        sdobj.name = 'test';
        insert sdobj;       
               
        
        Test.startTest();
        Test.setCurrentPageReference(new PageReference('/apex/NewSolutionDesignVFClone1?dsrId='+dsr.Id+'&dsrSceId='+objSCDesign.Id));
        New_Solution_Design__c nsdObj = new New_Solution_Design__c();
        ApexPages.StandardController sc = new ApexPages.StandardController(nsdObj);
        NewSolutionDesignControllerClone1 controlr = new NewSolutionDesignControllerClone1(sc);
        controlr.nsdObj.Outbound_Only__c = true;
        controlr.saveRecord();        
        controlr.editRecord();
        controlr.reviseRecord();
        controlr.SubmitApproval();
        controlr.backToPage();
        controlr.redirectToClonePage();
        controlr.relaodVoiceSection();
        controlr.relaodStorageSection();
        controlr.relaodDialerSection();
        controlr.sendSoWRequest();
        controlr.backToView();
        
        Customer_Site__c newcSite = new Customer_Site__c();
        newcSite.New_Solution_Design__c = controlr.nsdObj.Id;
        newcSite.Solution_Design__c = sdobj.Id;
        newcSite.Customer_Site_Name__c = 'test';
        insert newcSite;
        ININ_Applications__c appObj = new ININ_Applications__c();
        appObj.New_Solution_Design__c = controlr.nsdObj.Id;
        appObj.Application_Name__c = 'test';
        insert appObj;
        ININ_Solution_Components__c SCObj = new ININ_Solution_Components__c();
        SCObj.New_Solution_Design__c = controlr.nsdObj.Id;
        SCObj.Solution_Design__c = sdobj.Id;        
        insert SCObj; 

/*        String myString = 'StringToBlob';
     	Blob myBlob = Blob.valueof(myString);
        Attachment att = new Attachment(parentid=controlr.nsdObj.Id, Name = 'test Attachment' , Body = myBlob );
        insert att;
        
        controlr.uploadAttachment();*/
        
        
      
		Test.setCurrentPageReference(new PageReference('/apex/NewSolutionDesignVFClone1?dsrId='+dsr.Id+'&Id='+controlr.nsdObj.Id));
        NewSolutionDesignControllerClone1 controlr2 = new NewSolutionDesignControllerClone1();
        
        controlr.nsdObj.Outbound_Only__c = false;
        controlr.nsdObj.Dialer__c = true;        
        controlr.nsdObj.Screen_Storage__c = 'Customer premise (requires local RCS)';
        controlr.nsdObj.Voice_Storage__c = 'Customer premise (requires local RCS)';
        controlr.saveRecord();
        
        Test.setCurrentPageReference(new PageReference('/apex/NewSolutionDesignVFClone1?dsrId='+dsr.Id+'&dsrSceId='+objSCDesign.Id+'&Id='+controlr.nsdObj.Id));
        ApexPages.StandardController sc2 = new ApexPages.StandardController(controlr.nsdObj);
        NewSolutionDesignControllerClone1 controlr3 = new NewSolutionDesignControllerClone1(sc2);
        controlr3.relaodVoiceSection();
        controlr3.relaodStorageSection();
        controlr3.relaodDialerSection();
        controlr3.sendSoWRequest();
        
        Test.setCurrentPageReference(new PageReference('/apex/NewSolutionDesignVFClone1?dsrId='+dsr.Id+'&dsrSceId='+objSCDesign.Id+'&cloneId='+controlr.nsdObj.Id));
        ApexPages.StandardController sc3 = new ApexPages.StandardController(controlr.nsdObj);
        NewSolutionDesignControllerClone1 controlr4 = new NewSolutionDesignControllerClone1(sc3);
        controlr4.saveRecord();
        
        Test.stopTest();
    }
}