objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Deal_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Business_Users_Add_On__c</fullName>
        <label>Business Users &amp; Add-On Functionality</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <label>Competitor</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>[24]7</fullName>
                </value>
                <value>
                    <fullName>8X8</fullName>
                </value>
                <value>
                    <fullName>Adeptra</fullName>
                </value>
                <value>
                    <fullName>Alcatel-Lucent</fullName>
                </value>
                <value>
                    <fullName>Alorica</fullName>
                </value>
                <value>
                    <fullName>Altigen</fullName>
                </value>
                <value>
                    <fullName>Altitude</fullName>
                </value>
                <value>
                    <fullName>Appian</fullName>
                </value>
                <value>
                    <fullName>ASC Telecom</fullName>
                </value>
                <value>
                    <fullName>Aspect (Voxeo)</fullName>
                </value>
                <value>
                    <fullName>Astute Solutions</fullName>
                </value>
                <value>
                    <fullName>AT&amp;T</fullName>
                </value>
                <value>
                    <fullName>Avaya (Nortel)</fullName>
                </value>
                <value>
                    <fullName>Bridgetec</fullName>
                </value>
                <value>
                    <fullName>BT</fullName>
                </value>
                <value>
                    <fullName>Cacti</fullName>
                </value>
                <value>
                    <fullName>Calabrio</fullName>
                </value>
                <value>
                    <fullName>Callcopy</fullName>
                </value>
                <value>
                    <fullName>Call Fire</fullName>
                </value>
                <value>
                    <fullName>Call Miner</fullName>
                </value>
                <value>
                    <fullName>Callray</fullName>
                </value>
                <value>
                    <fullName>Cameo Solutions</fullName>
                </value>
                <value>
                    <fullName>Castel</fullName>
                </value>
                <value>
                    <fullName>CenturyLink</fullName>
                </value>
                <value>
                    <fullName>Cincom</fullName>
                </value>
                <value>
                    <fullName>Cisco</fullName>
                </value>
                <value>
                    <fullName>Clarity Connect</fullName>
                </value>
                <value>
                    <fullName>ClickFox</fullName>
                </value>
                <value>
                    <fullName>Collab9</fullName>
                </value>
                <value>
                    <fullName>Comm100</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deal_Qualification__c</fullName>
        <formula>HYPERLINK(&quot;../apex/DealQualification?oppId=&quot; &amp; Opportunity__c &amp; &quot;&amp;p=&quot; &amp; Text(Pricing_Type__c), Name )</formula>
        <label>Deal Qualification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_On_Quote__c</fullName>
        <label>Discount On Quote</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Number_of_Agents__c</fullName>
        <label>Estimated Number of Agents</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Explanation_for_Telco_Pricing__c</fullName>
        <label>Explanation for Telco Pricing</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>If_Other_Ramp_Period_Requested_Days__c</fullName>
        <label>If Other, Ramp Period Requested (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>If_Other_Term_Months_Requested__c</fullName>
        <label>If Other, Term (Months) Requested</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initial_Subscription_Term_Months_PC__c</fullName>
        <description>PCC &amp; PC</description>
        <label>Initial Subscription Term (Months)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>36</fullName>
                </value>
                <value>
                    <fullName>48</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Telco_Included__c</fullName>
        <label>Is Telco Included ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Telco_Quoted_At_Standard_Rates__c</fullName>
        <description>Is Telco being quoted at the Standard Telco Rates ?</description>
        <label>Is Telco Quoted At Standard Rates ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Justification_for_Discount__c</fullName>
        <inlineHelpText>Why is this discount level required to win? Is this walk-in, walk-out, best, final?</inlineHelpText>
        <label>Justification for Discount</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Less_than_100_Agents__c</fullName>
        <label>Less than 100 Agents?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Monthly_Recurring_Revenue_less_than_14K__c</fullName>
        <label>Monthly Recurring Revenue less than $14K</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>More_than_5_000_Business_Users__c</fullName>
        <label>More than 5,000 Business Users?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offering_Type__c</fullName>
        <description>Offer type for which the deal qualification is being done.</description>
        <label>Offering Type</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal Qualifications</relationshipLabel>
        <relationshipName>Deal_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform_Type__c</fullName>
        <description>Platform type for which the deal qualification is being done.</description>
        <label>Platform Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>On Premise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Type__c</fullName>
        <inlineHelpText>Effective April 1, 2015 select ‘New Simplified Pricing’ for all deals, except if Genesys is contractually obligated to extend a discount that is only feasible with “Old” Pricing</inlineHelpText>
        <label>Pricing Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Old Pricing</fullName>
                </value>
                <value>
                    <fullName>New Pricing</fullName>
                    <default>true</default>
                    <label>New Pricing</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PureCloud_Monthly_Minimum__c</fullName>
        <label>PureCloud Monthly Minimum</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct - $2,000.00 USD</fullName>
                </value>
                <value>
                    <fullName>Velocity - $1,500.00 USD</fullName>
                </value>
                <value>
                    <fullName>Indirect - $1,000.00 USD</fullName>
                </value>
                <value>
                    <fullName>Indirect (PC Approved Billing Partner) - $750.00 USD</fullName>
                </value>
                <value>
                    <fullName>Trial/Dev Org - $0.00</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ramp_Period_Days__c</fullName>
        <label>Ramp Period Days</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
                <value>
                    <fullName>270</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
                <value>
                    <fullName>330</fullName>
                </value>
                <value>
                    <fullName>1 Year</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Req_Revenue_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Revenue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Revision Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Original</fullName>
                    <default>true</default>
                    <label>Original</label>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal Qualification</label>
    <nameField>
        <displayFormat>DQ-{000000}</displayFormat>
        <label>Deal Qualification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Yes_No.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>Yes and No picklist values.</description>
    <masterLabel>Yes/No</masterLabel>
</GlobalValueSet>

classes/DealQualificationCloudControllerTest.cls
//Naresh Kumar    02/17/2017
@isTest(seeAllData=true)
private class DealQualificationCloudControllerTest{ 
    static testMethod void testDealQualificationCloudController1() { 
        Test.starttest();
        Account testAccount = TestUtil.createAccounts(1, false)[0];
        insert testAccount;
        
        map<string, DQ_Special_Offers__c> dqSpecOffersCS = DQ_Special_Offers__c.getAll();
        System.debug('dqSpecOffersCS--->'+dqSpecOffersCS);
        
        country__c ccc = [select id from country__C where name='United States' limit 1];
        
        Opportunity testOpp = TestUtil.createOpportunities(1, testAccount.id, false)[0];
        testOpp.Enablement_Model__c = 'Direct Enablement';
        testOpp.Country__c = ccc.Id;
        insert testOpp;
        
        Deal_Qualification__c testDQ = new Deal_Qualification__c();
        testDQ.Opportunity__c = testOpp.id;
        testDQ.Offering_Type__c = 'Business Edition';
        testDQ.Pricing_Type__c = 'New Pricing';
        testDQ.Type__c = DealQualificationApprovalUtil.DQ_RECORD_ORIGINAL;
        testDQ.Platform_Type__c = 'Cloud';
        testDQ.Is_Telco_Included__c = 'No';
        testDQ.Status__c = DealQualificationApprovalUtil.QUOTE_STATUS_PENDING;
        insert testDQ;
        
        ApexPages.currentPage().getParameters().put('oppId', testOpp.id);
        ApexPages.currentPage().getParameters().put('id', testDQ.id);
        
        ApexPages.StandardController stdCtr = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController = new DealQualificationCloudController(stdCtr);
        objController.telcoIncludedToggleHandler();        
        objController.revise();
        objController.reviseOnLoad();
        objController.save();
        //objController.objDQ.Req_Revenue_Approval__c = true;
        objController.saveFinanceApproval();
        system.debug('dqSpecOffrWrppr--->'+objController.dqSpecOffrWrppr);
        objController.requestSpecOfferSubApproval();
        objController.unlockFinFn = 'revenue';
        objController.unlockSubApprSection();
        objController.unlockFinFn = 'orderMgmt';
        objController.unlockSubApprSection();
        objController.unlockFinFn = 'creditCol';
        objController.unlockSubApprSection();
        objController.unlockFinFn = 'legal';
        objController.unlockSubApprSection();
        //objController.submitForApproval();   
        Test.stoptest();     
    }
    
    static testMethod void testDealQualificationCloudController2() { 
        Test.starttest();
        Account testAccount = TestUtil.createAccounts(1, false)[0];
        insert testAccount;
        
        Opportunity testOpp = TestUtil.createOpportunities(1, testAccount.id, false)[0];
        testOpp.Enablement_Model__c = 'Direct Enablement';
        insert testOpp;
        
        Deal_Qualification__c testDQ = new Deal_Qualification__c();
        testDQ.Opportunity__c = testOpp.id;
        testDQ.Offering_Type__c = 'Business Edition';
        testDQ.Pricing_Type__c = 'New Pricing';
        testDQ.Type__c = DealQualificationApprovalUtil.DQ_RECORD_ORIGINAL;
        testDQ.Platform_Type__c = 'Cloud';
        testDQ.Status__c = 'In Progress';
        insert testDQ;
        
        BigMachines__Quote__c quote = TestUtil.createQuotes(1, testOpp.id, true)[0];
        
        //ApexPages.currentPage().getParameters().put('oppId', testOpp.id);
        ApexPages.currentPage().getParameters().put('id', testDQ.id);
        
        ApexPages.StandardController stdCtr = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController = new DealQualificationCloudController(stdCtr);
        objController.objDQ.Type__c = DealQualificationApprovalUtil.DQ_RECORD_HISTORY;
        objController.reviseOnLoad();
        Test.stoptest();
    }
    
    static testMethod void testDealQualificationCloudController3() { 
        Test.starttest();
        Account testAccount = TestUtil.createAccounts(1, false)[0];
        insert testAccount;
        
        Opportunity testOpp = TestUtil.createOpportunities(1, testAccount.id, false)[0];
        testOpp.Enablement_Model__c = 'Direct Enablement';
        insert testOpp;        
        
        Deal_Qualification__c testDQ = new Deal_Qualification__c();
        testDQ.Opportunity__c = testOpp.id;
        testDQ.Offering_Type__c = 'Business Edition';
        testDQ.Pricing_Type__c = 'New Pricing';
        testDQ.Type__c = DealQualificationApprovalUtil.DQ_RECORD_ORIGINAL;
        testDQ.Platform_Type__c = 'Cloud';
        testDQ.Status__c = 'In Progress';
        testDQ.Type__c = DealQualificationApprovalUtil.DQ_RECORD_HISTORY;
        testDQ.Competitor__c = 'Test Competitor';
        insert testDQ;
        
        BigMachines__Quote__c testQuote = TestUtil.createQuotes(1, testOpp.id, false)[0];
        testQuote.Quote_Business_Type__c = 'Cloud';
        testQuote.Offering_Type__c = 'Business Edition';
        insert testQuote;
        
        ApexPages.currentPage().getParameters().put('id', testDQ.id);
        ApexPages.currentPage().getParameters().put('REVISE', 'true');
        ApexPages.StandardController stdCtr = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController = new DealQualificationCloudController(stdCtr);
        objController.objDQ.id = testDQ.id;
        objController.reviseOnLoad(); 
        Test.stoptest();    
    }
    
    static testMethod void testDealQualificationCloudController4() { 
    
        Test.starttest();
        //Create account, opp and quote
        List<Account> list_NewAccts = TestDataFactoryForQuoteTool.createAccounts(1);
        System.assertEquals(list_NewAccts.size(), 1);
        Opportunity testOpp = TestUtil.createOpportunities(1, list_NewAccts[0].id, false)[0];
        testOpp.Enablement_Model__c = 'Direct Enablement';
        insert testOpp; 
        List<zqu__Quote__c> list_NewQuotes = TestDataFactoryForQuoteTool.createZuoraQuotes(testOpp.Id, list_NewAccts[0].Id, 1);
        System.assertEquals(list_NewQuotes.size(), 1);
        list_NewQuotes[0].zqu__Previewed_MRR__c = 1000;
        update list_NewQuotes[0];
        
        ApexPages.StandardController stdCtr = new ApexPages.StandardController(testOpp);
        ApexPages.currentPage().getParameters().put('oppId',testOpp.id);
        DealQualificationCloudController objController = new DealQualificationCloudController(stdCtr);
        objController.zQuote = list_NewQuotes[0];
        objController.onQuoteChange();
        objController.getZQuotes();
        objController.submitForApproval();
        
        Test.stoptest();
    }
    
    static testMethod void testDealQualificationCloudController5() { 
        Test.starttest();
        Account testAccount = TestUtil.createAccounts(1, false)[0];
        insert testAccount;
        
        Opportunity testOpp = TestUtil.createOpportunities(1, testAccount.id, false)[0];
        testOpp.Enablement_Model__c = 'Direct Enablement';
        insert testOpp;
        
        Deal_Qualification__c testDQ = new Deal_Qualification__c();
        testDQ.Opportunity__c = testOpp.id;
        testDQ.Offering_Type__c = 'PureConnect Cloud';
        testDQ.Pricing_Type__c = 'New Pricing';
        testDQ.Business_Users_Add_On__c = 10;
        testDQ.Justification_for_Discount__c = null;
        testDQ.Initial_Subscription_Term_Months_PC__c = 'Other';
        testDQ.Ramp_Period_Days__c = 'Other';
        testDQ.Type__c = DealQualificationApprovalUtil.DQ_RECORD_ORIGINAL;
        testDQ.Platform_Type__c = 'Cloud';
        testDQ.Status__c = 'In Progress';
        insert testDQ;
        
        BigMachines__Quote__c quote = TestUtil.createQuotes(1, testOpp.id, true)[0];
        
        //ApexPages.currentPage().getParameters().put('oppId', testOpp.id);
        ApexPages.currentPage().getParameters().put('id', testDQ.id);
        
        ApexPages.StandardController stdCtr = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController = new DealQualificationCloudController(stdCtr);
        objController.objDQ.Type__c = DealQualificationApprovalUtil.DQ_RECORD_HISTORY;
        objController.reviseOnLoad();
        objController.save();
        
        testDQ.If_Other_Ramp_Period_Requested_Days__c = 120;
        testDQ.If_Other_Term_Months_Requested__c = 30;
        testDQ.Justification_for_Discount__c = 'test';
        update testDQ;
        ApexPages.currentPage().getParameters().put('id', testDQ.id);
        
        ApexPages.StandardController stdCtr2 = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController2 = new DealQualificationCloudController(stdCtr2);
        objController2.objDQ.Type__c = DealQualificationApprovalUtil.DQ_RECORD_HISTORY;
        objController2.reviseOnLoad();
        objController2.save();
        
        Test.stoptest();
    }
    
    static testMethod void testDealQualificationCloudController6() { 
        Test.starttest();
        Account testAccount = TestUtil.createAccounts(1, false)[0];
        insert testAccount;
        
        Opportunity testOpp = TestUtil.createOpportunities(1, testAccount.id, false)[0];
        testOpp.Enablement_Model__c = 'Direct Enablement';
        insert testOpp;
        
        Deal_Qualification__c testDQ = new Deal_Qualification__c();
        testDQ.Opportunity__c = testOpp.id;
        testDQ.Offering_Type__c = 'PureCloud';
        testDQ.Discount_On_Quote__c = 10;
        testDQ.Justification_for_Discount__c = null;
        testDQ.Is_Telco_Quoted_At_Standard_Rates__c = 'No';
        testDQ.PureCloud_Monthly_Minimum__c = 'Other';
        testDQ.Monthly_Recurring_Revenue_less_than_14K__c = 'Yes';
        testDQ.More_than_5_000_Business_Users__c = 'Yes';
        testDQ.Less_than_100_Agents__c = 'Yes';
        testDQ.Pricing_Type__c = 'New Pricing';
        testDQ.Type__c = DealQualificationApprovalUtil.DQ_RECORD_ORIGINAL;
        testDQ.Platform_Type__c = 'Cloud';
        testDQ.Status__c = 'In Progress';
        insert testDQ;
        
        BigMachines__Quote__c quote = TestUtil.createQuotes(1, testOpp.id, true)[0];
        
        //ApexPages.currentPage().getParameters().put('oppId', testOpp.id);
        ApexPages.currentPage().getParameters().put('id', testDQ.id);
        
        ApexPages.StandardController stdCtr2 = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController = new DealQualificationCloudController(stdCtr2);
        objController.objDQ.Type__c = DealQualificationApprovalUtil.DQ_RECORD_HISTORY;
        objController.reviseOnLoad();
        objController.save();
        
        testDQ.Justification_for_Discount__c = 'test';
        testDQ.Explanation_for_Telco_Pricing__c = 'test';
        testDQ.Estimated_Number_of_Agents__c = 50;
        testDQ.Estimated_Number_of_Business_Users__c = 6000;
        testDQ.Estimated_Monthly_Recurring_Revenue__c = 200;
        testDQ.If_Other_PureCloud_Monthly_Minimum_Req__c = 200;
        update testDQ;
        ApexPages.currentPage().getParameters().put('id', testDQ.id);
        
        ApexPages.StandardController stdCtr = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController2 = new DealQualificationCloudController(stdCtr);
        objController2.objDQ.Type__c = DealQualificationApprovalUtil.DQ_RECORD_HISTORY;
        objController2.reviseOnLoad();
        objController2.save();
        
        Test.stoptest();
    }
    
    static testMethod void testDealQualificationCloudController7() { 
        Test.starttest();
        Account testAccount = TestUtil.createAccounts(1, false)[0];
        insert testAccount;
        
        Opportunity testOpp = TestUtil.createOpportunities(1, testAccount.id, false)[0];
        testOpp.Enablement_Model__c = 'Direct Enablement';
        insert testOpp;
        
         
        ApexPages.currentPage().getParameters().put('oppId', testOpp.id);
        ApexPages.currentPage().getParameters().put('ot', 'PureConnect Cloud');
        ApexPages.currentPage().getParameters().put('p', 'New Pricing');
        ApexPages.currentPage().getParameters().put('pt', 'Cloud');
        
        ApexPages.StandardController stdCtr2 = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController = new DealQualificationCloudController(stdCtr2);
        
        
        ApexPages.currentPage().getParameters().put('oppId', testOpp.id);
        ApexPages.currentPage().getParameters().put('ot', 'PureCloud');
        ApexPages.currentPage().getParameters().put('p', 'New Pricing');
        ApexPages.currentPage().getParameters().put('pt', 'Cloud');
        
        ApexPages.StandardController stdCtr3 = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController3 = new DealQualificationCloudController(stdCtr3);
        
        ApexPages.currentPage().getParameters().put('oppId', testOpp.id);
        ApexPages.currentPage().getParameters().put('ot', 'Business Edition');
        ApexPages.currentPage().getParameters().put('p', 'New Pricing');
        ApexPages.currentPage().getParameters().put('pt', 'Cloud');
        
        ApexPages.StandardController stdCtr4 = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController4 = new DealQualificationCloudController(stdCtr4);
        
        BigMachines__Quote__c quote = TestUtil.createQuotes(1, testOpp.id, true)[0];
        quote.offering_type__c = 'Business Edition';
        quote.Quote_Business_Type__c = 'Cloud';
        quote.Initial_Subscription_Term__c = '3 Years';
        update quote;
        
        ApexPages.currentPage().getParameters().put('oppId', testOpp.id);
        ApexPages.currentPage().getParameters().put('ot', 'Business Edition');
        ApexPages.currentPage().getParameters().put('p', 'New Pricing');
        ApexPages.currentPage().getParameters().put('pt', 'Cloud');
        
        ApexPages.StandardController stdCtr5 = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController5 = new DealQualificationCloudController(stdCtr5);
        
        
        quote.offering_type__c = QuoteUtil.OFFERING_TYPE_CAAS;
        quote.No_Of_Months__c = 46;
        update quote;
        
        ApexPages.currentPage().getParameters().put('oppId', testOpp.id);
        ApexPages.currentPage().getParameters().put('ot', 'PureConnect Cloud');
        ApexPages.currentPage().getParameters().put('p', 'New Pricing');
        ApexPages.currentPage().getParameters().put('pt', 'Cloud');
        
        ApexPages.StandardController stdCtr6 = new ApexPages.StandardController(testOpp);
        DealQualificationCloudController objController6 = new DealQualificationCloudController(stdCtr6);
        
        Test.stoptest();
    }
}