objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SW_Download_Site__c</fullName>
        <description>Site of the software download. Actual URL is stored in Custom Settings.</description>
        <inlineHelpText>This is the location of the software download server.</inlineHelpText>
        <label>SW Download Site</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_SW_Download_History__c.object
<CustomObject>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipLabel>Customer SW Downloads History (Component)</relationshipLabel>
        <relationshipName>Customer_SW_Downloads_History2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer SW Downloads History</relationshipLabel>
        <relationshipName>Customer_SW_Downloads_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DL_Site__c</fullName>
        <label>Download Site</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Download_Type__c</fullName>
        <label>Download Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer SW Downloads History</relationshipLabel>
        <relationshipName>Customer_SW_Downloads_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>Name of Downloadable Item</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Size__c</fullName>
        <label>File Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Release__c</fullName>
        <label>Major Release</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OS__c</fullName>
        <label>OS</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipLabel>Customer SW Downloads History</relationshipLabel>
        <relationshipName>Customer_SW_Downloads_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SWDL_Id__c</fullName>
        <displayFormat>SWDL-{000000}</displayFormat>
        <label>SWDL Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Sold_To_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sold To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer SW Downloads History (Sold To Account)</relationshipLabel>
        <relationshipName>Customer_SW_Downloads_History1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_IP__c</fullName>
        <label>User IP</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_SW_Downloads_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Customer SW Download History</label>
    <nameField>
        <displayFormat>DLH-{000000}</displayFormat>
        <label>SW Download History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer SW Downloads History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product__c.object
<CustomObject>
    <description>What it does?  Object containing information about products associated with a DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Software_Download__c.object
<CustomObject>
    <fields>
        <fullName>Download_Type__c</fullName>
        <description>This field will track the types of downloads available.</description>
        <inlineHelpText>This field will track the types of downloads available.</inlineHelpText>
        <label>Download Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>Installation Package</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Size_KBs__c</fullName>
        <description>This field will display the size of this download in kbs.</description>
        <inlineHelpText>This field will display the size of this download in kbs.</inlineHelpText>
        <label>File Size (KB)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Localization__c</fullName>
        <description>This field will track the language for this download.</description>
        <inlineHelpText>This field will track the language for this download.</inlineHelpText>
        <label>Language</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Release__c</fullName>
        <label>Major Release</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_Systam__c</fullName>
        <label>O/S</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will track the component to which this download is linked to.</description>
        <inlineHelpText>This field will track the component to which this download is linked to.</inlineHelpText>
        <label>Component or CD Name</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipName>Software_Downloads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will track the product to which this download is linked to.</description>
        <inlineHelpText>This field will track the product to which this download is linked to.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipName>Software_Downloads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Software Download</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Downloads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SW_Download__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>settings for software downloads</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SW Download</label>
</CustomObject>

classes/DownloadsControllerExtension.cls
public class DownloadsControllerExtension {
   
    public String siteDest {get;set;}   
    public String swHistId {get;set;}
    public String tokenValue {get;set;}
    public String tokenStatus {get;set;}   
    public String swdLoadId {get;set;}
    public String urlToDl {get; set;}
    public String errMsg {get; set;}
    
    private Customer_SW_Download_History__c cdh;
    private String userIp;
    private String trueClientIP;
    private String xSalesforceSip;
    private String dlSite;
    private String privatePort;
    private String publicPort;
    private String fileName;
    private DownloadsController dc;
    private Software_Download__c sfd;
        
    public DownloadsControllerExtension (DownloadsController dlcon) {
           dc = dlcon;
    }

    public Pagereference gtDload(){  
        
      if(dc.acceptTnc){  
            
          errMsg = '';
          urlToDl = '';
                         
          cdh  = new  Customer_SW_Download_History__c();
          cdh.Contact__c = dc.conId;
          cdh.User__c = UserInfo.getUserId();
          cdh.End_User_Account__c = dc.endUserAccId;
          cdh.Sold_To_Account__c = dc.soldToAccId;
          
          sfd =   [SELECT s.Version__c, s.Operating_Systam__c, s.Name, 
                                           s.Major_Release__c, s.Localization__c,
                                           s.Product__c, s.Product_Component__c, 
                                           s.File_Size_KBs__c, s.File_Name__c, s.Download_Type__c
                                    FROM Software_Download__c s WHERE ID= :swdLoadId];
          fileName = sfd.Name;
          cdh.DL_Site__c = dlSite;
          cdh.File_Name__c = sfd.Name;
          cdh.File_Size__c = sfd.File_Size_KBs__c;
          cdh.Component__c = sfd.Product_Component__c;
          cdh.Product__c = sfd.Product__c;
          cdh.Version__c = sfd.Version__c;
          cdh.OS__c       = sfd.Operating_Systam__c;
          cdh.Download_Type__c = sfd.Download_Type__c;
          cdh.Language__c     = sfd.Localization__c;
          cdh.Major_Release__c = sfd.Major_Release__c;  
       
         /// get download site
          if ( !sdSite() && !Test.isRunningTest() ) {
                  errMsg = 'ERROR: Embargo';
                  return null;
            } 
            /// get user IP
            userIPAddress();
            cdh.User_IP__c = userIp;
                
            /// get security token
             if ( !getSecurityToken() ) {
             	   if ( tokenStatus == '100' )
             	      errMsg = 'ERROR: Not Found';
             	   else
                  	 errMsg = 'ERROR: Service';
                  	 
                   return null;
             }
                
             ///insert swdl history
             if ( !logHistory() ) {
                   errMsg = 'ERROR: Log';
                   return null;
             }
              
              //// download URL  
               urlToDl = siteDest + ':' + publicPort +
                  //  '/FileDownload/GENESYSLAB/servlet/DownloadFile?token=' +
                    '/swdl/download_2.php?token=' + tokenValue + '&swHistId=' +  swHistId;     
        }
        else
              dc.showNTNC();
                
        return null;
    }
        
    private void userIPAddress() {
          
       trueClientIP = ApexPages.currentPage().getHeaders().get('True-Client-IP');       
        // get IP address when no caching (sandbox, dev, secure urls)                       
       xSalesforceSip = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
             
        if (trueClientIP == null) 
             userIp = xSalesforceSip;
        else
             userIp = trueClientIP;
    }
    
    @TestVisible
    private Boolean sdSite() {          
        Country__c cntr;
        siteDest = '';

        try {
                cntr = [SELECT c.SW_Download_Site__c FROM Country__c c WHERE Id in 
                        (SELECT Country__c FROM Account WHERE Id= :dc.endUserAccId)];
            
              System.debug('>>> sdSite ' + cntr.SW_Download_Site__c + ' <<<<<');                         
        }
        catch (Exception e) {
                return false;                   
        }                                  
        if ( cntr.SW_Download_Site__c == null )
            return false;
        else {               
                /// custom setting SW Download  
                dlSite = cntr.SW_Download_Site__c;                 
                SW_Download__c site = SW_Download__c.getInstance(dlSite);
                siteDest = site.Value__c; 
                  
                SW_Download__c prPort = SW_Download__c.getInstance('PrivatePort');
                privatePort = prPort.Value__c;
                
                SW_Download__c pblPort = SW_Download__c.getInstance('PublicPort');
                publicPort = pblPort.Value__c;  
        }
                
        if ( siteDest =='' )  
                return false;
        else
             return true;
    }
    
    @TestVisible
    private Boolean logHistory() {             
        insert cdh;  
             
        cdh = [SELECT SWDL_Id__c FROM Customer_SW_Download_History__c WHERE ID= :cdh.Id];
        swHistId = cdh.SWDL_Id__c;
        
        if ( swHistId != null && swHistId != '' )
              return true;
        else
              return false;
    }
    
    @TestVisible
    private Boolean getSecurityToken() {
        
     try {
        // Build and send HTTP request for the one-time token
        String inputBody = '';
        tokenValue = '';
        tokenStatus = '';

        String urlString = siteDest + ':' + privatePort
                + '/FileDownload/GENESYSLAB/servlet/GenerateToken?' + '&requestedFilename=' + sfd.Name + '&trueClientIp=' + trueClientIP
                + '&xSalesforceSip=' + xSalesforceSip;
        
        System.debug('<<<<< urlString >>> ' + urlString );
                
        Http http = new Http();

        HttpRequest req = new HttpRequest();
        req.setEndpoint(urlString);
        req.setMethod('GET');
        req.setTimeout(2000);

        HttpResponse res = http.send(req);
        inputBody = res.getBody(); 
        
        Integer firstIndex = 0;
        Integer secondIndex = 0;
        String tagString = null;
        tagString = 'name="token" value="';
        firstIndex = inputBody.indexOf(tagString) + tagString.length();
        secondIndex = inputBody.substring(firstIndex).indexOf('"');
        tokenValue = inputBody.substring(firstIndex, firstIndex + secondIndex);
        tagString = 'name="status" value="';
        firstIndex = inputBody.indexOf(tagString) + tagString.length();
        secondIndex = inputBody.substring(firstIndex).indexOf('"');
        tokenStatus = inputBody.substring(firstIndex, firstIndex + secondIndex);
        
        System.debug('<<<< TOKEN >>' + tokenValue);
        System.debug('<<<< tokenStatus >>' + tokenStatus);
        
        if ( tokenStatus != '0' )
                return false;
        else 
                return true;
     }
     catch (CalloutException ex) {
                return false;
     }  
   }
}