objects/Country__c.object
<CustomObject>
    <description>CORE Model</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Licensing_Analyst__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>IMPORTANT!  All UserId fields have to be either Valid USER ID or blank. If User Id is invalid customer facing License Request form will display error message.</description>
    <fields>
        <fullName>APAC_Analyst_UserId__c</fullName>
        <label>APAC Analyst UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Licensing Analyst</label>
</CustomObject>

classes/LicenseRequestWebFormController_Test.cls
@isTest
public class LicenseRequestWebFormController_Test {
	
	static testmethod void tstLisReq() {
		TestUtil.setConfigValues();
		Util.Bypass_Trigger_Chk = true;
		
		Country__c us = new Country__c(Name = 'United States', Country__c = 'United States');
		insert us;
		
		Licensing_Analyst__c la = new Licensing_Analyst__c(APAC_Analyst_UserId__c = UserInfo.getUserId());
		insert la;
		
		List<RecordType> rectp = [SELECT Id FROM RecordType WHERE DeveloperName = 'EMGCustomerRecordType'];
		List<Account> acnt=  TestUtil.createAccounts(1, false);
        acnt[0].name='new test accountt';
        acnt[0].SAP_Account_Code__c = '1234';
        acnt[0].Country__c = us.id;
        acnt[0].Status__c = 'Active';
        acnt[0].RecordTypeId = rectp[0].id;
        insert acnt;
        
		Test.startTest();		
		ApexPages.currentPage().getParameters().put('fnm', 'fst');
		ApexPages.currentPage().getParameters().put('lst', 'lst');
		ApexPages.currentPage().getParameters().put('em', 'em@em.com');
		ApexPages.currentPage().getParameters().put('eusr', 'endusr');
		ApexPages.currentPage().getParameters().put('empl', 'employer');
		ApexPages.currentPage().getParameters().put('garn', '1234');
		ApexPages.currentPage().getParameters().put('src', 'internal');
		ApexPages.currentPage().getParameters().put('reqtp', 'AFR');
		
	    LicenseRequestWebFormController cntr = new LicenseRequestWebFormController(null);
	    
	    cntr.submitRequest();
	    
	    cntr.licReq.Request_Type__c = 'Question';
	    cntr.selectedGenImplType = 'GenImpl';
	    cntr.selectedGenDeplType = 'GenDepl';
	    cntr.selectedImplType = 'Impl';
	    cntr.selectedDeplType = 'Depl';
	    
	    cntr.resetFileType();
	    List<SelectOption> impl = cntr.implOptions;
	    List<SelectOption> depl = cntr.deplOptions;
	    
	    cntr.attName = 'Attachment';
	    cntr.upload();
	    cntr.submitRequest();
	    	    
	    List<Attachment> alst = cntr.attachmList;
	    
	    cntr.startNewReq();
	    cntr.newReqInternal();	
	    Test.stopTest();	
	}
    
}