objects/Deal_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Qualification__c</fullName>
        <formula>HYPERLINK(&quot;../apex/DealQualification?oppId=&quot; &amp; Opportunity__c &amp; &quot;&amp;p=&quot; &amp; Text(Pricing_Type__c), Name )</formula>
        <label>Deal Qualification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Revision Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal Qualification</label>
    <nameField>
        <displayFormat>DQ-{000000}</displayFormat>
        <label>Deal Qualification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DealQualificationStatusController.cls
//Naresh Kumar	06/06/2017 
public without sharing class DealQualificationStatusController {    
    //DQ Status
    public String dqStatus {get; private set;}
    public DealQualificationStatusController(ApexPages.StandardController stdCtrl){
        Id quoteId = stdCtrl.getId();
        // Quote Object
        zqu__Quote__c objQuote = [SELECT zqu__Opportunity__c FROM zqu__Quote__c WHERE id =: quoteId];
        List <Deal_Qualification__c> dqs = DealQualificationApprovalUtil.getDQ(objQuote.zqu__Opportunity__c, 'New Pricing', 'Cloud', 'PureCloud', DealQualificationApprovalUtil.DQ_RECORD_ORIGINAL);
        if (!dqs.isEmpty()) {
            dqStatus = dqs[0].Status__c;
        }
    }
}