objects/Demo_Request__c.object
<CustomObject>
    <description>What it Does? Object used to request a demonstrations from the Technical Sales Team.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>Demo Request</label>
    <nameField>
        <displayFormat>DR-{YYYY}-{00000}</displayFormat>
        <label>Demo Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Demo_Request_Tracking__c.object
<CustomObject>
    <description>What it does?  Object for tracking activities associated with a DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <fields>
        <fullName>Activity_Completed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it does?  Holds name of demonstrator that completed the demo request.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Completed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Demo_Request_Activities_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Date_Time__c</fullName>
        <description>What it does?  Holds the date and time of the DR activity.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Activity Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Activity_Duration__c</fullName>
        <description>What it does?  Holds the duration of the DR activity.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Activity Duration</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <description>What it does?  Shows the type of demo request activity.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Activity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Demo Setup</fullName>
                </value>
                <value>
                    <fullName>Demo Shadow</fullName>
                </value>
                <value>
                    <fullName>Demo Training</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Prep Call</fullName>
                </value>
                <value>
                    <fullName>Tradeshow</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Demo_Request__c</fullName>
        <description>What it does?  Holds a link to the DR associated with the activity.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Demo Request</label>
        <referenceTo>Demo_Request__c</referenceTo>
        <relationshipLabel>Activity Tracking</relationshipLabel>
        <relationshipName>Demo_Request_Activities_Tracking</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GTM_ConfCall__c</fullName>
        <description>What it does?  Holds the GTM conference call info associated with the DR activity.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>GoToMeeting Conference Call Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GoToMeeting_ID__c</fullName>
        <description>What it does?  Holds the GTM meeting ID for the DR activity.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>GoToMeeting ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GoToMeeting_JoinURL__c</fullName>
        <description>What it does?  Holds the join URL for the GTM meeting for the DR activity.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>GoToMeeting JoinURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>hasEvent__c</fullName>
        <defaultValue>true</defaultValue>
        <description>What it Does?  Boolean to indicate if this activity has a calendar event associated.  Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>hasEvent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>What it Does?  Set to true if this activity is a template to create new activities from.  Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>isTemplate</label>
        <type>Checkbox</type>
    </fields>
    <label>Demo Request Activity Tracking</label>
    <nameField>
        <displayFormat>DRT-{YYYY}-{MM}-{0000}</displayFormat>
        <label>Demo Request Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Request Activities Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Demonstration_Presenter__c.object
<CustomObject>
    <description>What it does?  Object holding information about demonstration presenters for demo requests.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <fields>
        <fullName>GTM_Access_Token__c</fullName>
        <description>What it does?  Holds the GTM access token for the demonstration presenter.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>GTM Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTM_Account_Key__c</fullName>
        <description>What it does?  Holds the GTM account key for the demostration presenter.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>GTM Account Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTM_Conference_Preference__c</fullName>
        <description>What it does?  Holds conference preference for the demonstration presenter.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <inlineHelpText>PSTN - Provides GTM conference number only.  No VoIP
Hybrid - Provides both GTM Conference number and VoIP option</inlineHelpText>
        <label>GTM Conference Preference</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PSTN</fullName>
                    <default>true</default>
                    <label>PSTN</label>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GTM_Organizer_Key__c</fullName>
        <description>What it does?  Holds the GTM organizer key for the demonstration presenter.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>GTM Organizer Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTM_Token_Expire_Date__c</fullName>
        <description>What it does?  Holds the GTM token expiration date.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>GTM Token Expire Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Holds the name of the presenter. Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Demonstration_Presenters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Demonstration Presenter</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Demonstration Presenter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demonstration Presenters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DemoRequestGTMActions.cls
public without sharing class DemoRequestGTMActions {
    
    public boolean oauthComplete { get; set; } {oauthComplete = false;}
    public boolean hasValidToken { get; set; } {hasValidToken = false;}
    public DateTime expireDate { get; set; }
    public Decimal meetingId { get; set; }
    public String accessToken { get; set; }
    public String organizerKey { get; set; }
    public String accountKey { get; set; }
    public String responseKey { get; set; }
    public String joinUrl { get; set; }
    public String conferenceCallInfo { get; set; }
    public String consumerKey { get {if(consumerKey == null) consumerKey = getConsumerKey();
        							return consumerKey;}
                              	private set; }
    
    private String citrixOauthUrl = 'https://api.getgo.com/oauth/';
    private String citrixApiUrl = 'https://api.getgo.com/G2M/rest/';
    private String confCallPref = 'PSTN';
    
    public DemoRequestGTMActions(Id userId){
        Demonstration_Presenter__c presenter = [SELECT Id, User_Name__c, GTM_Access_Token__c, GTM_Token_Expire_Date__c, GTM_Conference_Preference__c FROM Demonstration_Presenter__c WHERE User_Name__c = :userId];
        DateTime now = DateTime.now();
        if(presenter.GTM_Access_Token__c == null || presenter.GTM_Token_Expire_Date__c <= now){
            hasValidToken = false;
            oauthComplete = false;
        } else {
            accessToken = presenter.GTM_Access_Token__c;
            hasValidToken = true;
            oauthComplete = true;
        }
        
        if(!String.isEmpty(presenter.GTM_Conference_Preference__c)){
            confCallPref = presenter.GTM_Conference_Preference__c;
        } 
    }
    
    public void updatePresenter(Id userId){
        Demonstration_Presenter__c presenter = [SELECT Id, User_Name__c, GTM_Access_Token__c, GTM_Token_Expire_Date__c FROM Demonstration_Presenter__c WHERE User_Name__c = :userId];
        presenter.GTM_Token_Expire_Date__c = expireDate;
        presenter.GTM_Access_Token__c = accessToken;
        presenter.GTM_Account_Key__c = accountKey;
        presenter.GTM_Organizer_Key__c = organizerKey;
        update presenter;
        
        hasValidToken = true;
    }
    
    public void updateActivity(Id activityId){
        Demo_Request_Tracking__c currentActivity = [SELECT Id, GoToMeeting_ID__c, GoToMeeting_JoinURL__c, GTM_ConfCall__c, Activity_Completed_By__c,
                                                    Activity_Type__c, Activity_Date_Time__c, Activity_Duration__c, Demo_Request__c, hasEvent__c, isTemplate__c
                                                    From Demo_Request_Tracking__c WHERE Id = :activityId];
        Demo_Request_Tracking__c newActivity = currentActivity.clone(true, true, true, true);
        system.debug('cloned activity');
        newActivity = new DemoRequestTrackingBuilder(newActivity)
            .withGTMID(meetingId)
            .withGTMURL(joinUrl)
            .withGTMConfCall(conferenceCallInfo)
            .build();
    }
    
    public PageReference oauthStart(string reqId) {
        PageReference url = new PageReference(citrixOauthUrl + 'authorize?client_id=' + consumerKey + '&state=' + reqId);
        url.setRedirect(true);
        return url;
    }
    
    public HTTPResponse getRequestToken() {
        Http h = new Http();
        
        HttpRequest getToken = new HttpRequest();
        getToken.setEndpoint(citrixOauthUrl + 'access_token');
        getToken.setMethod('POST');
        getToken.setHeader('Accept', 'application/json');
        getToken.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        getToken.setBody('grant_type=authorization_code&code=' + responseKey + '&client_id=' + consumerKey);
        
        return h.send(getToken);        
    }
    
    public HTTPResponse createMeeting(String subject, DateTime startTime, DateTime endTime){
        Http h = new Http();
        
        HttpRequest meeting = buildRequest('POST');
        meeting.setEndpoint(citrixApiUrl + 'meetings');
        String jsonMessage = jsonBodyMap(subject, startTime, endTime);
        meeting.setBody(jsonMessage);
        
        return h.send(meeting);        
    }
    
    public HTTPResponse updateMeeting(String subject, DateTime startTime, DateTime endTime){
        Http h = new Http();
        
        HttpRequest meeting = buildRequest('PUT');
        meeting.setEndpoint(citrixApiUrl + 'meetings/' + meetingId);
		String jsonMessage = jsonBodyMap(subject, startTime, endTime);
        meeting.setBody(jsonMessage);
        
        return h.send(meeting);
    }
    
    public HTTPResponse deleteMeeting(){
        Http h = new Http();
        
        HttpRequest meeting = buildRequest('DELETE');
        meeting.setEndpoint(citrixApiUrl + 'meetings/' + meetingId);
        
        return h.send(meeting);
    }

	public HTTPResponse getMeeting(){
        Http h = new Http();
        
        HttpRequest meeting = buildRequest('GET');
        meeting.setEndpoint(citrixApiUrl + 'meetings/' + meetingId);
        
        return h.send(meeting);
    } 
    
    public static String createMeetingDetails(String joinUrl, String callInfo){
        return '\r\n\r\nPlease join my meeting. \r\n' + joinUrl + '\r\n\r\nJoin the conference call: \r\n \r\n' + callInfo + '\r\nAudio PIN: Shown after joining the meeting \r\n \r\n';
    }
    
    public static String removeMeetingDetails(String messageBody, String joinUrl, String callInfo){
        return messageBody.remove(createMeetingDetails(joinUrl, callInfo).trim());
    }
    
    private HttpRequest buildRequest(String method){
        HttpRequest request = new HttpRequest();
        request.setMethod(method);
        request.setHeader('Accept', 'application/json');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Authorization', accessToken);
        return request;
    }
    
    private String getConsumerKey(){
        Organization thisOrg = [SELECT Id, IsSandBox, InstanceName FROM Organization LIMIT 1];
        
        //Determine which GTM App to use based on environment
        if(thisOrg.IsSandbox){
            if(thisOrg.InstanceName == 'CS8') {
                return '3KdsixG5ShIl4S0Kh23bODNRrpJCGqnj';
            } else {
                return '72W3x7ls4jsGSttzuGPXqdkpKQuNAQ7k';
            }
        } else {
            return '70AdbGZ3hBcrMTthZYP5DR8UbbqDjqMs';
        }
    }
    
    private String jsonBodyMap(String subject, DateTime startTime, DateTime endTime){
        Map<String, object> bodyMap = new Map<String, object>();
        bodyMap.put('subject', subject);
        bodyMap.put('starttime', startTime);
        bodyMap.put('endtime', endTime);
        bodyMap.put('passwordrequired', false);
        bodyMap.put('conferencecallinfo', confCallPref);
        bodyMap.put('timezonekey', '');
        bodyMap.put('meetingtype', 'scheduled');
        return JSON.serialize(bodyMap);
    }

}