objects/Demo_Request__c.object
<CustomObject>
    <description>What it Does? Object used to request a demonstrations from the Technical Sales Team.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <fields>
        <fullName>Chatter_Feed_ID__c</fullName>
        <description>What it does?  Holds the chatter feed ID for the DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Chatter Feed ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Demo_Date_Time__c</fullName>
        <description>What it does?  Holds the date and time of the DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Demo Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Demo_Location__c</fullName>
        <description>What it does?  Holds the requested location of the DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Demo Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Web Based</fullName>
                </value>
                <value>
                    <fullName>HQ Simulation Room</fullName>
                </value>
                <value>
                    <fullName>On-site (Requires Approval)</fullName>
                </value>
                <value>
                    <fullName>ININ HQ Campus</fullName>
                </value>
                <value>
                    <fullName>Tradeshow</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Demo_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it does?  Holds the owner of the DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Demo Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Demo_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Demo_Time_Length__c</fullName>
        <defaultValue>0.5</defaultValue>
        <description>What it Does? Decimal representation of demo length, round to the closest 15 minutes mark. ex. 2.15.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Demo Length</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HQ_Meeting_Room__c</fullName>
        <description>What it does?  Holds the room number for the DR meeting.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>HQ Meeting Room</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OnSite_Justification__c</fullName>
        <description>What it does?  Holds the justification for an on-site demo.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>On-Site Justification</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>On_site_Location__c</fullName>
        <description>What it does?  Holds the location for the on-site demo.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>On-site Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Org_URL__c</fullName>
        <description>What it does?  Holds org URL attached to the DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Org URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>QueueName__c</fullName>
        <description>What it does?  Holds name of queue associated with the DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>QueueName</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Sales</fullName>
                    <default>true</default>
                    <label>Technical Sales</label>
                </value>
                <value>
                    <fullName>Velocity Sales</fullName>
                    <isActive>false</isActive>
                    <label>Velocity Sales</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Timezone__c</fullName>
        <defaultValue>&quot;America/New_York&quot;</defaultValue>
        <description>What it does? Holds the timezone of the DR.  Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>Requested Timezone</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_Email_Addr__c</fullName>
        <description>What it does? Holds the requester&apos;s email address.  Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>Requester E-mail</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Requester_Name__c</fullName>
        <defaultValue>$User.FirstName + &apos; &apos; + $User.LastName</defaultValue>
        <description>What it does? Holds name of demo requester.  Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>Requester Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reschedule_Reason__c</fullName>
        <description>What it does? Holds the reason for rescheduling the DR. Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>Reschedule Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requester Reschedule</fullName>
                </value>
                <value>
                    <fullName>Submission Error</fullName>
                </value>
                <value>
                    <fullName>Technical Sales Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>What it does? Holds the state of the DR.  Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rescheduled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Approval Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SuppressNotification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>What it Does? Stop emails and chatter from going out.  Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>Suppress Notification</label>
        <type>Checkbox</type>
    </fields>
    <label>Demo Request</label>
    <nameField>
        <displayFormat>DR-{YYYY}-{00000}</displayFormat>
        <label>Demo Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Demo_Request_Decline__c.object
<CustomObject>
    <description>What it does? Object holding information about declining a DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>Demo Request Decline</label>
    <nameField>
        <displayFormat>DR-DL-{YYYY}-{MM}-{0000}</displayFormat>
        <label>Demo Request Decline Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Request Declines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <description>What it Does?  Object holding states available in a country.  Downstream Impact? None. Which Department is Owner? Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestDemoReschedule.cls
@isTest
public class TestDemoReschedule {
    
    @testSetup
    static void setup() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        List<User> tsc = new List<User>();
        List<User> tsm = new List<User>();
		System.runAs(thisUser) {
            tsc = DemoRequestFactory.CreateTscTestUsers(7);
            tsm = DemoRequestFactory.CreateTsmTestUsers(1);
        }
        
        DemoRequestFactory.CreateDemonstrationPresenters(tsc, tsm);
        DemoRequestFactory.InitializeData();
    }
    
    static testMethod void validateDemoRequestReschedule(){
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        
        //Testing Variables
        Map<Id, DateTime> currentDateTimeMap = new Map<Id, DateTime>();
        //Get List of platform IDs to create a request for each
        
        //Create Requests
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(6, null);
        //Get Id and Date/Time after workflow and triggers have run.
        request = [Select State__c, SuppressNotification__c, Org_URL__c, Demo_Date_Time__c, Requested_Timezone__c, 
                   Demo_Time_Length__c, Chatter_Feed_ID__c, Reschedule_Reason__c, Requester_Email_Addr__c, Demo_Owner__c,
                   Requester_Name__c, OnSite_Justification__c, On_site_Location__c, Demo_Location__c, HQ_Meeting_Room__c, QueueName__c from Demo_Request__c];
        List<Id> requestIds = new List<Id>();
        for(Demo_Request__c dr : request){
            requestIds.add(dr.Id);
            currentDateTimeMap.put(dr.Id, dr.Demo_Date_Time__c);
        }
        
        Test.startTest();
        System.debug('Reschedule Request');        
        TestDemoRequestClass.RescheduleRequest(request);
        Test.stopTest();
        
        //Compare the DateTime value before and after reschedule and make sure the DateTime value has changed.
        for(Demo_Request__c dr : [SELECT Id, Demo_Date_Time__c FROM Demo_Request__c WHERE ID IN :requestIds]){
            DateTime currentDateTime = currentDateTimeMap.get(dr.Id);
            DateTime rescheduleDateTime = dr.Demo_Date_Time__c;
            System.assertNotEquals(currentDateTime, rescheduleDateTime, 'The request was not correctly rescheduled');
        }
    }
    
    static testMethod void validateRescheduleEscalation() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        
        //Testing Variables
        Map<Id, DateTime> currentDateTimeMap = new Map<Id, DateTime>();
        //Get List of platform IDs to create a request for each
        
        //Create Requests
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(6, null);
        //Get Id and Date/Time after workflow and triggers have run.
        request = [Select State__c, SuppressNotification__c, Org_URL__c, Demo_Date_Time__c, Requested_Timezone__c, 
                   Demo_Time_Length__c, Chatter_Feed_ID__c, Reschedule_Reason__c, Requester_Email_Addr__c, Demo_Owner__c,
                   Requester_Name__c, OnSite_Justification__c, On_site_Location__c, Demo_Location__c, HQ_Meeting_Room__c, QueueName__c from Demo_Request__c];
        List<Id> requestIds = new List<Id>();
        for(Demo_Request__c dr : request){
            requestIds.add(dr.Id);
            currentDateTimeMap.put(dr.Id, dr.Demo_Date_Time__c);
        }
        
        Test.startTest();
        System.debug('Reschedule Request');        
        TestDemoRequestClass.RescheduleRequestEscalated(request);
        Test.stopTest();
        
        //Compare the DateTime value before and after reschedule and make sure the DateTime value has changed.
        for(Demo_Request__c dr : [SELECT Id, State__c, Demo_Date_Time__c, Requested_Timezone__c, Demo_Time_Length__c, Chatter_Feed_ID__c, Reschedule_Reason__c, SuppressNotification__c, QueueName__c FROM Demo_Request__c WHERE ID IN :requestIds]){
            DateTime currentDateTime = currentDateTimeMap.get(dr.Id);
            DateTime rescheduleDateTime = dr.Demo_Date_Time__c;
            //System.assertNotEquals(currentDateTime, rescheduleDateTime, 'The request was not correctly rescheduled');
            //System.assertEquals('Escalated', dr.State__c, 'The request did not escalate when rescheduled on a weekend');
        }
    }   
    
    static testMethod void validateCannotReschedule(){
        //Initalize Test Data
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        
        //Create Test User
        User tscTest = TestDemoRequestClass.GetTscTestUser(0);
        
        //Create Test Request
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(3, null);        
        List<Id> requestIds = new List<Id>();
        for(Demo_Request__c r : request){
            requestIds.add(r.Id);
        }
        
        TestDemoRequestClass.AcceptRequest(request, tscTest);
        TestDemoRequestClass.completeRequest(request);
        
        Test.startTest();
        
        request = [Select State__c, SuppressNotification__c, Org_URL__c, Demo_Date_Time__c, Requested_Timezone__c, 
                   Demo_Time_Length__c, Chatter_Feed_ID__c, Reschedule_Reason__c, Requester_Email_Addr__c, Demo_Owner__c,
                   Requester_Name__c, OnSite_Justification__c, On_site_Location__c, Demo_Location__c, HQ_Meeting_Room__c, QueueName__c from Demo_Request__c where Id in :requestIds];
        System.runAs(tscTest){
            for(Demo_Request__c d : request) {
                ApexPages.StandardController stdRequest = new ApexPages.StandardController(d);
                DemoRequestRescheduleExtension ext = new DemoRequestRescheduleExtension(stdRequest);
                System.AssertEquals(true, ext.cannotReschedule, 'Demo could be rescheduled after being completed');
            }
        }
        
        Test.stopTest();
    }
    
    static testMethod void validateRescheduleBadDateInput(){
        //Initalize Test Data
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
       
        //Create Test User
        User tscTest = TestDemoRequestClass.GetTscTestUser(0);
        
        //Create Test Request
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(3, null);        
        List<Id> requestIds = new List<Id>();
        for(Demo_Request__c r : request){
            requestIds.add(r.Id);
        }
        
        TestDemoRequestClass.AcceptRequest(request, tscTest);
        
        Test.startTest();
        
        request = [Select State__c, SuppressNotification__c, Org_URL__c, Demo_Date_Time__c, Requested_Timezone__c, 
                   Demo_Time_Length__c, Chatter_Feed_ID__c, Reschedule_Reason__c, Requester_Email_Addr__c, Demo_Owner__c,
                   Requester_Name__c, OnSite_Justification__c, On_site_Location__c, Demo_Location__c, HQ_Meeting_Room__c, QueueName__c from Demo_Request__c where Id in :requestIds];
        System.runAs(tscTest){
            for(Demo_Request__c d : request) {
                ApexPages.StandardController stdRequest = new ApexPages.StandardController(d);
                DemoRequestRescheduleExtension ext = new DemoRequestRescheduleExtension(stdRequest);
                ext.rescheduleReason = ext.rescheduleReasons[2].getValue(); 
                ext.rDate = 'blarg';
                ext.checkAvail();
                ApexPages.Message[] pageMessages = ApexPages.getMessages();
                System.assertEquals(1, pageMessages.size());
                ext.resetTime();
            }
        }
        
        Test.stopTest();
    }
    
    static testMethod void validateRescheduleEmptyOnSiteLocationInput(){
        //Initalize Test Data
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        
        //Create Test User
        User tscTest = TestDemoRequestClass.GetTscTestUser(0);
        
        //Create Test Request
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(1, null);        
        List<Id> requestIds = new List<Id>();
        for(Demo_Request__c r : request){
            requestIds.add(r.Id);
        }
        
        TestDemoRequestClass.AcceptRequest(request, tscTest);
        
        Test.startTest();
        
        request = [Select State__c, SuppressNotification__c, Org_URL__c, Demo_Date_Time__c, Requested_Timezone__c, 
                   Demo_Time_Length__c, Chatter_Feed_ID__c, Reschedule_Reason__c, Requester_Email_Addr__c, Demo_Owner__c,
                   Requester_Name__c, OnSite_Justification__c, On_site_Location__c, Demo_Location__c, HQ_Meeting_Room__c, QueueName__c from Demo_Request__c where Id in :requestIds];
        System.runAs(tscTest){
            for(Demo_Request__c d : request) {
                ApexPages.StandardController stdRequest = new ApexPages.StandardController(d);
                DemoRequestRescheduleExtension ext = new DemoRequestRescheduleExtension(stdRequest);
                ext.rescheduleReason = ext.rescheduleReasons[2].getValue(); 
                ext.rDate = '2020-02-14';
                ext.rTime = '11:11';
                ext.timezone = 'America/New_York';
                ext.demoLocation = 'On-site (Requires Approval)';
                ext.checkAvail();
                System.assertEquals(1, ApexPages.getMessages().size(), 'Reschedule did not require justify and onsite location to be included');
            }
        }
        
        Test.stopTest();
    }

    static testMethod void validateRescheduleGoodOnSiteLocationInput(){
        //Initalize Test Data
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        //Create Test User
        User tscTest = TestDemoRequestClass.GetTscTestUser(0);
        
        //Create Test Request
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(1, null);        
        List<Id> requestIds = new List<Id>();
        for(Demo_Request__c r : request){
            requestIds.add(r.Id);
        }
        
        TestDemoRequestClass.AcceptRequest(request, tscTest);
        
        Test.startTest();
        
        request = [Select State__c, SuppressNotification__c, Org_URL__c, Demo_Date_Time__c, Requested_Timezone__c, 
                   Demo_Time_Length__c, Chatter_Feed_ID__c, Reschedule_Reason__c, Requester_Email_Addr__c, Demo_Owner__c,
                   Requester_Name__c, OnSite_Justification__c, On_site_Location__c, Demo_Location__c, HQ_Meeting_Room__c, QueueName__c from Demo_Request__c where Id in :requestIds];
        System.runAs(tscTest){
            for(Demo_Request__c d : request) {
                ApexPages.StandardController stdRequest = new ApexPages.StandardController(d);
                DemoRequestRescheduleExtension ext = new DemoRequestRescheduleExtension(stdRequest);
                ext.rescheduleReason = ext.rescheduleReasons[2].getValue(); 
                ext.rDate = '2020-02-14';
                ext.rTime = '11:11';
                ext.timezone = 'America/New_York';
                ext.demoLocation = 'On-site (Requires Approval)';
                ext.onsiteDemoLocation = 'blah';
                ext.onsiteJustify = 'blah';
                ext.checkAvail();
                system.assertEquals(0, ApexPages.getMessages().size(), 'Reschedule gave a page message, when it shouldnt have');
            }
        }
        
        Test.stopTest();
    }
    
    static testMethod void validateRescheduleBadHqLocationInput(){
        //Initalize Test Data
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        
        //Create Test User
        User tscTest = TestDemoRequestClass.GetTscTestUser(0);
        
        //Create Test Request
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(1, null);        
        List<Id> requestIds = new List<Id>();
        for(Demo_Request__c r : request){
            requestIds.add(r.Id);
        }
        
        TestDemoRequestClass.AcceptRequest(request, tscTest);
        
        Test.startTest();
        
        request = [Select State__c, SuppressNotification__c, Org_URL__c, Demo_Date_Time__c, Requested_Timezone__c, 
                   Demo_Time_Length__c, Chatter_Feed_ID__c, Reschedule_Reason__c, Requester_Email_Addr__c, Demo_Owner__c,
                   Requester_Name__c, OnSite_Justification__c, On_site_Location__c, Demo_Location__c, HQ_Meeting_Room__c, QueueName__c from Demo_Request__c where Id in :requestIds];
        System.runAs(tscTest){
            for(Demo_Request__c d : request) {
                ApexPages.StandardController stdRequest = new ApexPages.StandardController(d);
                DemoRequestRescheduleExtension ext = new DemoRequestRescheduleExtension(stdRequest);
                ext.rescheduleReason = ext.rescheduleReasons[2].getValue(); 
                ext.rDate = '2020-02-14';
                ext.rTime = '11:11';
                ext.timezone = 'America/New_York';
                ext.demoLocation = 'ININ HQ Campus';
                ext.checkAvail();
                System.assertEquals(1, ApexPages.getMessages().size(), 'Reschedule did not require onsiteMeetingRoom ' + ApexPages.getMessages()[0]);
            }
        }
        
        Test.stopTest();
    }
    
    static testMethod void validateRescheduleGoodHqLocationInput(){
        //Initalize Test Data
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        
        //Create Test User
        User tscTest = TestDemoRequestClass.GetTscTestUser(0);
        
        //Create Test Request
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(1, null);        
        List<Id> requestIds = new List<Id>();
        for(Demo_Request__c r : request){
            requestIds.add(r.Id);
        }
        
        TestDemoRequestClass.AcceptRequest(request, tscTest);
        
        Test.startTest();
        
        request = [Select State__c, SuppressNotification__c, Org_URL__c, Demo_Date_Time__c, Requested_Timezone__c, 
                   Demo_Time_Length__c, Chatter_Feed_ID__c, Reschedule_Reason__c, Requester_Email_Addr__c, Demo_Owner__c,
                   Requester_Name__c, OnSite_Justification__c, On_site_Location__c, Demo_Location__c, HQ_Meeting_Room__c, QueueName__c from Demo_Request__c where Id in :requestIds];
        System.runAs(tscTest){
            for(Demo_Request__c d : request) {
                ApexPages.StandardController stdRequest = new ApexPages.StandardController(d);
                DemoRequestRescheduleExtension ext = new DemoRequestRescheduleExtension(stdRequest);
                ext.rescheduleReason = ext.rescheduleReasons[2].getValue(); 
                ext.rDate = '2020-02-14';
                ext.rTime = '11:11';
                ext.timezone = 'America/New_York';
                ext.demoLocation = 'ININ HQ Campus';
                ext.onsiteMeetingRoom = 'blah';
                ext.checkAvail();
                System.assertEquals(0, ApexPages.getMessages().size(), 'Reschedule gave a page message, when it shouldnt have');
            }
        }
        
        Test.stopTest();
    }
    
    static testMethod void validateRescheduleBadReasonInput(){
        //Initalize Test Data
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        
        //Create Test User
        User tscTest = TestDemoRequestClass.GetTscTestUser(0);
        
        //Create Test Request
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(1, null);        
        List<Id> requestIds = new List<Id>();
        for(Demo_Request__c r : request){
            requestIds.add(r.Id);
        }
        
        TestDemoRequestClass.AcceptRequest(request, tscTest);
        
        Test.startTest();
        
        request = [Select State__c, SuppressNotification__c, Org_URL__c, Demo_Date_Time__c, Requested_Timezone__c, 
                   Demo_Time_Length__c, Chatter_Feed_ID__c, Reschedule_Reason__c, Requester_Email_Addr__c, Demo_Owner__c,
                   Requester_Name__c, OnSite_Justification__c, On_site_Location__c, Demo_Location__c, HQ_Meeting_Room__c, QueueName__c from Demo_Request__c where Id in :requestIds];
        System.runAs(tscTest){
            for(Demo_Request__c d : request) {
                ApexPages.StandardController stdRequest = new ApexPages.StandardController(d);
                DemoRequestRescheduleExtension ext = new DemoRequestRescheduleExtension(stdRequest);
                ext.rDate = '2020-02-14';
                ext.rTime = '11:11';
                ext.timezone = 'America/New_York';
                ext.demoLocation = 'ININ HQ Campus';
                ext.checkAvail();
                System.assertEquals(1, ApexPages.getMessages().size(), 'Reschedule did not require a reason ' + ApexPages.getMessages()[0]);
            }
        }
        
        Test.stopTest();
    }
    
    static testMethod void validateRescheduleAndAccept() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        User tscTest = TestDemoRequestClass.GetTscTestUser(0);
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(3, null);  
        
        System.runAs(tscTest) {
            for(Demo_Request__c d : request) {
                ApexPages.currentPage().getParameters().put('id',d.Id);
                ApexPages.StandardController stdRequest = new ApexPages.StandardController(d);
                DemoRequestRescheduleExtension ext = new DemoRequestRescheduleExtension(stdRequest);
                //Covert the time from GMT
                TimeZone tz = TimeZone.getTimeZone(d.Requested_Timezone__c);
                Integer tzOffset = tz.getOffset(d.Demo_Date_Time__c); //offset in milliseconds
                tzOffset /= 1000; //offset in seconds
                DateTime dtOffset = d.Demo_Date_Time__c.addSeconds(tzOffset);
                DateTime newDt = dtOffset.addDays(1);
                ext.timezone = 'America/New_York';
                ext.rDate = d.Demo_Date_Time__c.format('yyyy-MM-dd');
                ext.rTime = '11:30';
                ext.rescheduleReason = ext.rescheduleReasons[2].getValue(); 
                ext.submitAccept();
            }
        }
        request = [Select Id, State__c, Demo_Owner__c from Demo_Request__c];
        for(Demo_Request__c d : request) {
            System.assertEquals('Accepted', d.State__c, 'State was not accepted');
            System.assertEquals(tscTest.Id, d.Demo_Owner__c, 'Different demo owner than expected');
        }
    }
    
    static testMethod void validateRescheduleAndAcceptNewOwner() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        User tscTest = TestDemoRequestClass.GetTscTestUser(0);
        User tscTest2 = TestDemoRequestClass.GetTscTestUser(1);
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(1, null);  
        
        TestDemoRequestClass.AcceptRequest(request, tscTest);
        
        System.runAs(tscTest2) {
            for(Demo_Request__c d : request) {
                ApexPages.currentPage().getParameters().put('id',d.Id);
                ApexPages.StandardController stdRequest = new ApexPages.StandardController(d);
                DemoRequestRescheduleExtension ext = new DemoRequestRescheduleExtension(stdRequest);
                //Covert the time from GMT
                TimeZone tz = TimeZone.getTimeZone(d.Requested_Timezone__c);
                Integer tzOffset = tz.getOffset(d.Demo_Date_Time__c); //offset in milliseconds
                tzOffset /= 1000; //offset in seconds
                DateTime dtOffset = d.Demo_Date_Time__c.addSeconds(tzOffset);
                DateTime newDt = dtOffset.addDays(1);
                ext.timezone = 'America/New_York';
                ext.rDate = d.Demo_Date_Time__c.format('yyyy-MM-dd');
                ext.rTime = '11:30';
                ext.rescheduleReason = ext.rescheduleReasons[2].getValue(); 
                ext.submitAccept();
            }
        }
        request = [Select Id, State__c, Demo_Owner__c from Demo_Request__c];
        for(Demo_Request__c d : request) {
            System.assertEquals('Accepted', d.State__c, 'State was not accepted');
            System.assertEquals(tscTest2.Id, d.Demo_Owner__c, 'Different demo owner than expected');
        }
    }
    
    static testMethod void validateRescheduleAndDecline() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        User tscTest = TestDemoRequestClass.GetTscTestUser(0);
        Integer demoCount = 3;
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(demoCount, null);  
        
        System.runAs(tscTest) {
            for(Demo_Request__c d : request) {
                ApexPages.currentPage().getParameters().put('id',d.Id);
                ApexPages.StandardController stdRequest = new ApexPages.StandardController(d);
                DemoRequestRescheduleExtension ext = new DemoRequestRescheduleExtension(stdRequest);
                Boolean b = ext.isTSMember;
                String user = ext.userName;
                //Covert the time from GMT
                TimeZone tz = TimeZone.getTimeZone(d.Requested_Timezone__c);
                Integer tzOffset = tz.getOffset(d.Demo_Date_Time__c); //offset in milliseconds
                tzOffset /= 1000; //offset in seconds
                DateTime dtOffset = d.Demo_Date_Time__c.addSeconds(tzOffset);
                DateTime newDt = dtOffset.addDays(1);
                ext.timezone = 'America/New_York';
                ext.rDate = d.Demo_Date_Time__c.format('yyyy-MM-dd');
                ext.rTime = '11:30';
                ext.rescheduleReason = ext.rescheduleReasons[2].getValue(); 
                ext.submitDecline();
                ext.declineReason = 'Demo Prep';
                ext.declineComments = 'Comment Comments';
                ext.declineDate = '';
                ext.declineTime = '';
                ext.submitDeclineFinal();
            }
        }
        request = [Select Id, State__c, Demo_Owner__c from Demo_Request__c];
        List<Demo_Request_Decline__c> declines = [Select Id from Demo_Request_Decline__c];
        for(Demo_Request__c d : request) {
            System.assertEquals('Rescheduled', d.State__c, 'State was not rescheduled');
        }
        
        System.assertEquals(demoCount, declines.size(), 'Incorrect number of declines'); 
    }
    
    static testMethod void validateRescheduleAndDeclineDateTime() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        User tscTest = TestDemoRequestClass.GetTscTestUser(0);
        Integer demoCount = 3;
        List<Demo_Request__c> request = TestDemoRequestClass.CreateRequest(demoCount, null);  
        
        System.runAs(tscTest) {
            for(Demo_Request__c d : request) {
                ApexPages.currentPage().getParameters().put('id',d.Id);
                ApexPages.StandardController stdRequest = new ApexPages.StandardController(d);
                DemoRequestRescheduleExtension ext = new DemoRequestRescheduleExtension(stdRequest);
                //Covert the time from GMT
                TimeZone tz = TimeZone.getTimeZone(d.Requested_Timezone__c);
                Integer tzOffset = tz.getOffset(d.Demo_Date_Time__c); //offset in milliseconds
                tzOffset /= 1000; //offset in seconds
                DateTime dtOffset = d.Demo_Date_Time__c.addSeconds(tzOffset);
                DateTime newDt = dtOffset.addDays(1);
                ext.timezone = 'America/New_York';
                ext.rDate = d.Demo_Date_Time__c.format('yyyy-MM-dd');
                ext.rTime = '11:30';
                ext.rescheduleReason = ext.rescheduleReasons[2].getValue(); 
                ext.submitDecline();
                ext.declineReason = 'Demo Prep';
                ext.declineComments = 'Comment Comments';
                DateTime dt = d.Demo_Date_Time__c;
                ext.declineDate = dt.addDays(1).format('MM/dd/yyyy');
                ext.declineTime = '12:00 PM';
                ext.submitDeclineFinal();
            }
        }
        request = [Select Id, State__c, Demo_Owner__c from Demo_Request__c];
        List<Demo_Request_Decline__c> declines = [Select Id from Demo_Request_Decline__c];
        for(Demo_Request__c d : request) {
            System.assertEquals('Rescheduled', d.State__c, 'State was not rescheduled');
        }
        
        System.assertEquals(demoCount, declines.size(), 'Incorrect number of declines'); 
    }
    
}