objects/Demo_Request__c.object
<CustomObject>
    <description>What it Does? Object used to request a demonstrations from the Technical Sales Team.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it does?  Holds name of Account associated with the DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Demo Requests</relationshipLabel>
        <relationshipName>Demo_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AudienceType__c</fullName>
        <description>What it Does?  Holds the type of Audience for the DR.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Audience Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Tradeshow</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Demo_Date_Time__c</fullName>
        <description>What it does?  Holds the date and time of the DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Demo Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Demo_Location__c</fullName>
        <description>What it does?  Holds the requested location of the DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Demo Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Web Based</fullName>
                </value>
                <value>
                    <fullName>HQ Simulation Room</fullName>
                </value>
                <value>
                    <fullName>On-site (Requires Approval)</fullName>
                </value>
                <value>
                    <fullName>ININ HQ Campus</fullName>
                </value>
                <value>
                    <fullName>Tradeshow</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Demo_Time_Length__c</fullName>
        <defaultValue>0.5</defaultValue>
        <description>What it Does? Decimal representation of demo length, round to the closest 15 minutes mark. ex. 2.15.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Demo Length</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it does?  Holds a link to the opportunity associated with the DR.  Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <inlineHelpText>Enter the Opportunity for which you would like a demonstration performed.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Demo Requests</relationshipLabel>
        <relationshipName>Demo_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QueueName__c</fullName>
        <description>What it does?  Holds name of queue associated with the DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>QueueName</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Sales</fullName>
                    <default>true</default>
                    <label>Technical Sales</label>
                </value>
                <value>
                    <fullName>Velocity Sales</fullName>
                    <isActive>false</isActive>
                    <label>Velocity Sales</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <description>What it does? Holds the type of demo requested. Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Existing Customer (Add-On Revenue)</fullName>
                </value>
                <value>
                    <fullName>New Customer (Implementation / Training)</fullName>
                </value>
                <value>
                    <fullName>Prospect (New Revenue)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>New Revenue</fullName>
                </value>
                <value>
                    <fullName>Additional Revenue</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tradeshow</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requester_Company__c</fullName>
        <defaultValue>$User.CompanyName</defaultValue>
        <description>What it does? Holds the name of the requester&apos;s company.  Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>Requester Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_Name__c</fullName>
        <defaultValue>$User.FirstName + &apos; &apos; + $User.LastName</defaultValue>
        <description>What it does? Holds name of demo requester.  Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>Requester Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>What it does? Holds the state of the DR.  Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rescheduled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Approval Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Demo Request</label>
    <nameField>
        <displayFormat>DR-{YYYY}-{00000}</displayFormat>
        <label>Demo Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Demo_Request_Decline__c.object
<CustomObject>
    <description>What it does? Object holding information about declining a DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <fields>
        <fullName>Decline_Reason__c</fullName>
        <description>What it does?  Holds the reason for declining the DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Decline Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Demo Prep</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Personal Appointment</fullName>
                </value>
                <value>
                    <fullName>Product Knowledge</fullName>
                </value>
                <value>
                    <fullName>Scheduled Demo</fullName>
                </value>
                <value>
                    <fullName>Scheduled Meeting</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>PTO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Demo_Request_ID__c</fullName>
        <description>What it does?  Holds the ID of the DR that was declined.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.</description>
        <label>Demo Request ID</label>
        <referenceTo>Demo_Request__c</referenceTo>
        <relationshipLabel>Request Declines</relationshipLabel>
        <relationshipName>Demo_Request_Declines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Holds the name of the user that declined the DR. Downstream Impact? None. Which Department is Owner? Sales Ops.</description>
        <label>User Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>equals</operation>
                <valueField>User.UserRole.Name</valueField>
            </filterItems>
            <infoMessage>By default, your search is restricted to users within your same role.  To search all users, click &quot;Show all results.&quot;</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Demo_Request_Declines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Demo Request Decline</label>
    <nameField>
        <displayFormat>DR-DL-{YYYY}-{MM}-{0000}</displayFormat>
        <label>Demo Request Decline Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Request Declines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <description>What it Does?  Object holding states available in a country.  Downstream Impact? None. Which Department is Owner? Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DemoRequestAvailableController.cls
public class DemoRequestAvailableController {
    public List<DemoRequestWrapper> reqWithRelated { get {if(reqWithRelated == null) reqWithRelated = getRequests();
        													return reqWithRelated;}
                                                    set; }
	public List<SelectOption> statusFilter { get; set; } 
    public String selectedState { get; set; } {selectedState = 'My Queue';}
    private List<String> filterStates = new List<String>{'My Queue', 'Escalated', 'Rescheduled', 'Pending Approval', 'Auto-Declined', 'Active'};
    public List<SelectOption> sortBy { get; set;}
    public String selectedSort { get; set; } { selectedSort = 'Demo Date/Time';}
    public Boolean requery { get; set; } {requery = true;}
    private List<Id> requestsToDisplay = new List<Id>();
    private List<Id> autoDeclinedIds = new List<Id>();
    private List<Id> allRequestIds = new List<Id>();
    private List<Demo_Request__c> availableRequests = new List<Demo_Request__c>();
    private List<DemoRequestWrapper> reqToDisplay = new List<DemoRequestWrapper>();  
    private Map<String, String> sortStrings = new Map<String, String>{'Demo Date/Time' => 'Demo_Date_Time__c ASC', 'Request ID (Ascending)' => 'Name ASC', 'Request ID (Descending)' => 'Name DESC', 'Request Type (Ascending)' => 'Request_Type__c ASC', 'Request Type (Descending)' => 'Request_Type__c DESC'};  
    private Map<Id, List<String>> req2Plats = new Map<Id, List<String>>();
    private Map<Id, List<String>> req2Prods = new Map<Id, List<String>>();
    private Map<Id, List<String>> req2GenCons = new Map<Id, List<String>>();
    private Map<Id, List<String>> req2Ints = new Map<Id, List<String>>();
    private Map<Id, Integer> leftToDecline = new Map<Id, Integer>();
    private Boolean viewingAutoDecline = false;
    private String queue { get; set; }

    
    public DemoRequestAvailableController() {        
        statusFilter = new List<SelectOption>();
        for(string i : filterStates){
            statusFilter.add(new SelectOption(i,i));
        }
        sortBy = new List<SelectOption>();
        for(String s : sortStrings.keySet()){
            sortBy.add(new SelectOption(s,s));
        }

        queue = DemoRequestUtility.getPresentersQueue(UserInfo.getUserId());
        
    }    
    
    public List<DemoRequestWrapper> getRequests(){
        if(selectedState == 'My Queue') return getAvailableRequests();
        if(selectedState == 'Auto-Declined') return getAutoDeclines();
        if(selectedState == 'Active') return getAllRequests();
        List<DemoRequestWrapper> filteredRequests = new List<DemoRequestWrapper>();        
        for(DemoRequestWrapper d : getAvailableRequests()){
            if(selectedState == d.request.State__c){
                filteredRequests.add(new DemoRequestWrapper(d.request, req2Plats.get(d.request.Id), req2Prods.get(d.request.Id), req2GenCons.get(d.request.Id), req2Ints.get(d.request.Id), leftToDecline.get(d.request.Id)));
            }
        }
        return filteredRequests;
    }
    
    public void filter(){
        reqWithRelated = getRequests();
    }
    
    public void resort(){
        requery = false;
        availableRequests.clear();
        reqWithRelated = getRequests();
    }
    
    public void refresh(){
        requery = true;
        availableRequests.clear();
        reqWithRelated = getRequests();
    }
    
    private List<DemoRequestWrapper> getAvailableRequests(){		       
        if(availableRequests.isEmpty() && requery){            
            reqToDisplay.clear();
            requestsToDisplay.clear();
            autoDeclinedIds.clear();            
            buildIdLists();            
            buildWrappers(requestsToDisplay);            
        } else if (availableRequests.isEmpty() || viewingAutoDecline){
            reqToDisplay.clear();
            buildWrappers(requestsToDisplay);
        }
        viewingAutoDecline = false;
        return reqToDisplay;
    }
    
    private List<DemoRequestWrapper> getAutoDeclines(){
        if(autoDeclinedIds.isEmpty()) buildIdLists();
        reqToDisplay.clear();
        buildWrappers(autoDeclinedIds);
        viewingAutoDecline = true;
        return reqToDisplay;
    }
    
    private List<DemoRequestWrapper> getAllRequests() {
        reqToDisplay.clear();
        buildIdLists();
        buildWrappers(allRequestIds);
        return reqToDisplay;
    }
    
    private void buildWrappers(List<Id> displayIds){
        String queryString = 'SELECT Id, Name, QueueName__c, State__c, Requester_Name__c, Requester_Company__c, Demo_Date_Time__c, ' + 
            'Demo_Time_Length__c, Demo_Location__c, Opportunity__c, Account__c, Opportunity__r.Name, Request_Type__c, Account__r.Name, ' +
            'AudienceType__c FROM Demo_Request__c WHERE Id IN :displayIds ORDER BY ';
        queryString += sortStrings.get(selectedSort);
        availableRequests = Database.query(queryString);
        
        req2Plats = DemoRequestClass.GetRequestRelatedPlatforms(displayIds);
        req2Prods = DemoRequestClass.GetRequestRelatedProducts(displayIds);
        req2GenCons = DemoRequestClass.GetRequestRelatedGenCons(displayIds);
        req2Ints = DemoRequestClass.GetRequestRelatedIntegrations(displayIds);
        leftToDecline = DemoRequestUtility.GetNumLeftToDecline(availableRequests, queue);
        
        for(Demo_Request__c r : availableRequests){
            reqToDisplay.add(new DemoRequestWrapper(r, req2Plats.get(r.Id), req2Prods.get(r.Id), req2GenCons.get(r.Id), req2Ints.get(r.Id), leftToDecline.get(r.Id)));
        }
    }
    
    private void buildIdLists(){
        Set<String> activeState = DemoRequestUtility.activeDemoStates;
        allRequestIds.clear();
        
        List<Demo_Request__c> allRequests = [SELECT Id, Name FROM Demo_Request__c WHERE State__c IN :activeState and QueueName__c = :queue]; //get all demos in an active state
            
        //Get all IDs for demos in an active state
        for(Demo_Request__c d : allRequests){
            allRequestIds.add(d.Id);
        }
        
        //Get all declines records for the active demos
        List<Demo_Request_Decline__c> allDeclines = [SELECT Demo_Request_ID__c, Id, User_Name__c, Decline_Reason__c FROM Demo_Request_Decline__c WHERE Demo_Request_ID__c IN : allRequestIds];
        
        Set<Id> userDeclinedRequest = new Set<Id>();
        Set<Id> declinedRequestIds = new Set<Id>();            
        for(Demo_Request_Decline__c dec: allDeclines){
            //if the current user matches a decline add the demo request ID to the set
            if(dec.User_Name__c == userinfo.getUserId()){
                userDeclinedRequest.add(dec.Demo_Request_ID__c);
                if(dec.Decline_Reason__c == 'Auto-Declined by Calendar'){
                    autoDeclinedIds.add(dec.Demo_Request_ID__c);
                }
            }
            //get all of the Request ID that have declines
            declinedRequestIds.add(dec.Demo_Request_ID__c);
        }                
        
        for(Id i : allRequestIds){
            //If user has not declined request or there are no declines for the request, add it to list to display
            if(!userDeclinedRequest.contains(i) || !declinedRequestIds.contains(i)){
                requestsToDisplay.add(i);
            }
        }
    }
}