objects/DSR_SCEngagement__c.object
<CustomObject>
    <fields>
        <fullName>AE_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DSR_SCEngagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DSR SC Engagement or Partner SMART DSR</label>
    <nameField>
        <displayFormat>SCE - {00000}</displayFormat>
        <label>SC DSR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR SC Engagements or Partner SMART DSRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DSR_Virtual_Team__c.object
<CustomObject>
    <fields>
        <fullName>SCE_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SCE ID</label>
        <referenceTo>DSR_SCEngagement__c</referenceTo>
        <relationshipLabel>DSR Virtual Teams</relationshipLabel>
        <relationshipName>DSR_Virtual_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Virtual_Team_Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Team Member Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DSR_Virtual_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Virtual_User_Role__c</fullName>
        <label>Virtual User Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sub Regional Leader</fullName>
                </value>
                <value>
                    <fullName>Virtual Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DSR Virtual Team</label>
    <nameField>
        <displayFormat>SCVT - {00000}</displayFormat>
        <label>SC Virtual Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR Virtual Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wow_Sub_Regional_Users__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Hold the sub regional users</description>
    <fields>
        <fullName>Sales_COE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales COE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subregional_Leader__c</fullName>
        <label>Subregional Leader</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Wow Sub Regional Users</label>
</CustomObject>

classes/DSR_SC_Engage_Utility.cls
public class DSR_SC_Engage_Utility {
    
    /**
    *   Class Name  :   CheckSubregionalUser()
    *   Description :   This method is used to check the current user status
    *   Parameters  :  
    **/
    public static Boolean CheckSubregionalUser(String userId, String dsrId){
        Boolean isRegional = false;
        Integer count = [Select count() from DSR_Virtual_Team__c where SCE_ID__c=:dsrID and Virtual_Team_Member_Name__c=:userId and Virtual_User_Role__c=:'Sub Regional Leader'];        
        if(count > 0){
            isRegional = true;
        }
        return isRegional;
    }
    
    
    
    /**
    *   Class Name  :   CheckSalesCOE()
    *   Description :   This method is used to check the current user as SalesCOE
    *   Parameters  : 
    *   Requested By : Debora Lane 16/April/2018
    **/
    public static Boolean CheckSalesCOE(String userEmail){
        Boolean isCOE = false;
        List<Wow_Sub_Regional_Users__c> list_SubRegion= Wow_Sub_Regional_Users__c.getall().values();
        for(Wow_Sub_Regional_Users__c obj : list_SubRegion)
        {
           if(obj.Subregional_Leader__c == userEmail && obj.Sales_COE__c)
            isCOE = true;
        }
        return isCOE;
    }
    
    
    
    /**
    *   Class Name  :   CheckVTUser()
    *   Description :   This method is used to check the current user status
    *   Parameters  :  
    **/
    public static Boolean CheckVTUser(String userId, String dsrId){
        Boolean isVT = false;        
        Integer count = [Select count() from DSR_Virtual_Team__c where SCE_ID__c=:dsrID and Virtual_Team_Member_Name__c=:userId and Virtual_User_Role__c=:'Virtual Team'];        
        if(count > 0){
            isVT = true;
        }
        return isVT;
    }
    
    
    
    /**
    *   Class Name  :   CheckAEUser()
    *   Description :   This method is used to check the current user status
    *   Parameters  :  
    **/
    public static Boolean CheckAEUser(String userId, String dsrId){
        Boolean isAE = false;
        Integer count = [Select count() from DSR_SCEngagement__c where ID=:dsrID and AE_Name__c=:userId];        
        if(count > 0){
            isAE = true;
        }
        return isAE;
    }
    
    
    
    /**
    *   Class Name  :   CheckAdminUser()
    *   Description :   This method is used to check the current user status
    *   Parameters  :  
    **/
    public static Boolean CheckAdminUser(String userId, String dsrId){
        Boolean isAdmin = false;        
        Integer count = [Select count() from User where Id=:UserId and Profile.Name =: 'System Administrator'];
        if(count > 0){
            isAdmin = true;
        }
        return isAdmin;
    }
    
    
    /**
    *   Class Name  :   checkReadOnly()
    *   Description :   This method is used to check the current user access on DSR
    *   Parameters  :  
    **/
    public static boolean checkReadOnly(String userId, String dsrId, String userEmail){
        boolean isReadOnly = false;        
        if(!CheckAEUser(userId, dsrId) && !CheckSalesCOE(userEmail) && !CheckSubregionalUser(userId, dsrId) && !CheckVTUser(userId, dsrId) && !CheckAdminUser(userId, dsrId)){
            isReadOnly = true;
        }
        return isReadOnly;
    }
}