objects/DSR_SCEngagement__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity ID</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>DSR_SCEngagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SC_Engagement_Status__c</fullName>
        <label>SC Engagement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open and Assigned</fullName>
                </value>
                <value>
                    <fullName>Open and Not Assigned</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted for Completion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DSR SC Engagement or Partner SMART DSR</label>
    <nameField>
        <displayFormat>SCE - {00000}</displayFormat>
        <label>SC DSR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR SC Engagements or Partner SMART DSRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DSR_Virtual_Team__c.object
<CustomObject>
    <fields>
        <fullName>IsPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPrimary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SCE_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SCE ID</label>
        <referenceTo>DSR_SCEngagement__c</referenceTo>
        <relationshipLabel>DSR Virtual Teams</relationshipLabel>
        <relationshipName>DSR_Virtual_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Virtual_Team_Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Team Member Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DSR_Virtual_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Virtual_User_Role__c</fullName>
        <label>Virtual User Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sub Regional Leader</fullName>
                </value>
                <value>
                    <fullName>Virtual Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Virtual_User_type__c</fullName>
        <label>Virtual User type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Solution Consultant</fullName>
                </value>
                <value>
                    <fullName>Business Consultant</fullName>
                </value>
                <value>
                    <fullName>PS Consulting Sales Director</fullName>
                </value>
                <value>
                    <fullName>Solution Lead</fullName>
                </value>
                <value>
                    <fullName>Solution Architect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DSR Virtual Team</label>
    <nameField>
        <displayFormat>SCVT - {00000}</displayFormat>
        <label>SC Virtual Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DSR Virtual Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RFP_Support_Request__c.object
<CustomObject>
    <fields>
        <fullName>Direct_Sales__c</fullName>
        <defaultValue>false</defaultValue>
        <label>XDirect Sales</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Clarifying Questions</fullName>
                </value>
                <value>
                    <fullName>Down select questions</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>RFQ</fullName>
                </value>
                <value>
                    <fullName>Vendor Questionnaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Extension_Due_Date__c</fullName>
        <label>Extension Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Amount__c</fullName>
        <formula>Opportunity__r.License_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>License Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RFP Support Requests</relationshipLabel>
        <relationshipName>RPF_Support_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposal_Manager__c</fullName>
        <label>Proposal Manager</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andrew Frye</fullName>
                </value>
                <value>
                    <fullName>Ashley Norman</fullName>
                </value>
                <value>
                    <fullName>Elizabeth Murphy</fullName>
                </value>
                <value>
                    <fullName>Ella Deduque</fullName>
                </value>
                <value>
                    <fullName>Jefferson Saraiva</fullName>
                </value>
                <value>
                    <fullName>Jen Hernandez</fullName>
                </value>
                <value>
                    <fullName>Joslin Vethakumar</fullName>
                </value>
                <value>
                    <fullName>Matt Armstrong</fullName>
                </value>
                <value>
                    <fullName>Melina Basak</fullName>
                </value>
                <value>
                    <fullName>Pam Villa-Real</fullName>
                </value>
                <value>
                    <fullName>Rebecca Loro</fullName>
                </value>
                <value>
                    <fullName>Sharon Salcedo</fullName>
                </value>
                <value>
                    <fullName>Sherri Robinson</fullName>
                </value>
                <value>
                    <fullName>Susan Terheide</fullName>
                </value>
                <value>
                    <fullName>Yogie De Leon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposal_Outcome_1__c</fullName>
        <formula>if( OR( ISNULL(text(Override_Proposal_Outcome__c)), ISBLANK(text(Override_Proposal_Outcome__c)) ), text(Opportunity__r.RFP_Proposal__c),text(Override_Proposal_Outcome__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Proposal Outcome</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal_Status__c</fullName>
        <label>Proposal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request For Support</fullName>
                    <default>true</default>
                    <label>Request For Support</label>
                </value>
                <value>
                    <fullName>Response In Process</fullName>
                </value>
                <value>
                    <fullName>Response Complete</fullName>
                </value>
                <value>
                    <fullName>No Bid</fullName>
                </value>
                <value>
                    <fullName>Declined Due To Bandwidth</fullName>
                </value>
                <value>
                    <fullName>Partner Direct</fullName>
                </value>
                <value>
                    <fullName>No Support Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Business_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To/Business Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RFP Support Requests (Sold To/Business Partner)</relationshipLabel>
        <relationshipName>RFP_Support_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution_Engineer_Name__c</fullName>
        <label>Solution Consultant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution_Type__c</fullName>
        <label>Solution Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Edition Cloud</fullName>
                </value>
                <value>
                    <fullName>Business Edition Premise</fullName>
                </value>
                <value>
                    <fullName>Enterprise Edition Cloud</fullName>
                </value>
                <value>
                    <fullName>Enterprise Edition Premise</fullName>
                </value>
                <value>
                    <fullName>Premier Edition Cloud</fullName>
                </value>
                <value>
                    <fullName>Proactive Customer Communications</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
                <value>
                    <fullName>Self Service</fullName>
                </value>
                <value>
                    <fullName>WFO-Workforce Management</fullName>
                </value>
                <value>
                    <fullName>WFO-Call Recording</fullName>
                </value>
                <value>
                    <fullName>WFO-Quality Management</fullName>
                </value>
                <value>
                    <fullName>WFO-Analytics</fullName>
                </value>
                <value>
                    <fullName>Omnichannel Desktop</fullName>
                </value>
                <value>
                    <fullName>Workload Management</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Integrations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>XTotal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <formula>Existing_Customer_Score__c + Genesys_Influence_Score__c + How_do_we_rate_vs_competition_score__c + Percentage_Solution_Fit_Score__c + Deal_Age_Score__c + Deal_Stage_Score__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Score (Out of 100)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RFP Support Request</label>
    <nameField>
        <displayFormat>RFP-{0000}</displayFormat>
        <label>RFP Support Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFP Support Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RFPReportController.cls
/* @Class Name   : RFPReportController 
 * @Description  : This is a controller class for preparing the Vf template which needs to be sent as RFP weekly support table.
 * @Created On   : 26/11/2014 
 */
public without sharing class RFPReportController {  
    // sfdc URL of the instance
    public String sfdcURL {get;set;}
    public String virtualTeamMemberName {get;set;}
    public string reportRegion{get;set;}
    
    /**    
    * @Description: Getter method to populate the records from RFP records as per the report. This is used to prepare the data table 
    * @Param: none
    * @Return: List<wrapperResult>
    */
    public List<wrapperResult> getRFPRecords(){
        sfdcURL = URL.getSalesforceBaseUrl().toExternalForm();
        String query;
        System.Debug('reportRegion--->'+reportRegion);
        if(reportRegion == 'Global'){
            query = Label.RFP_Support_Req_Weekly_Query + Label.RFP_Query_Second;
        }
        else if(reportRegion == 'APAC'){
            query = Label.RFP_Support_Req_Weekly_Query + Label.RFP_Query_Second_APAC;
        }
        else if(reportRegion == 'LATAM'){
            query = Label.RFP_Support_Req_Weekly_Query + Label.RFP_Query_Second_LATAM;
        }
        else if(reportRegion == 'EMEA'){
            query = Label.RFP_Support_Req_Weekly_Query + Label.RFP_Query_Second_EMEA;
        }
        else if(reportRegion == 'NA'){
            query = Label.RFP_Support_Req_Weekly_Query + Label.RFP_Query_Second_NA;
        }
        
        /*'SELECT Id,Name,Extension_Due_Date__c,Due_Date__c, Proposal_Outcome_1__c,'+
                       'Opportunity__r.AccountId, Opportunity__r.Account.Name, Document_Type__c,'+
                       'Proposal_Manager__c, Opportunity__r.OwnerId, Opportunity__r.Owner.Name,'+
                       'Solution_Engineer_Name__c, Direct_Sales__c, Total_Score__c, Total_Amount__c,'+
                       'Opportunity__r.License_Amount__c, Solution_Type__c, Sold_To_Business_Partner__r.Name,'+
                       'Opportunity__r.Country_Sub_Region__c,Proposal_Status__c, Sold_To_Business_Partner__r.Id'+
                       ' FROM RFP_Support_Request__c'+
                       ' WHERE Proposal_Status__c =\'Response Complete\' ORDER BY Opportunity__r.Country_Sub_Region__c ASC';*/
                       
        
        List<RFP_Support_Request__c> rfpRecords = (List<RFP_Support_Request__c>)Database.query(query);
        List<wrapperResult> wrapperResults = new List<wrapperResult>();     
        Set<String> setOfSubRegions = new Set<String>();
        Set<String> setOfRegions = new Set<String>();
        
        //Below Code Added by Priyank
        Set<String> oppId = new Set<String>();
        for(RFP_Support_Request__c eachRec : rfpRecords){
            oppId.add(eachRec.Opportunity__c);  
        }
        Map<String,String> mapOppUserName = new Map<String,String>();
        for(DSR_Virtual_Team__c dsrName : [SELECT Virtual_Team_Member_Name__r.Name, SCE_ID__r.Opportunity_ID__c FROM DSR_Virtual_Team__c
                        WHERE Virtual_User_Role__c = 'Virtual Team' AND IsPrimary__c = TRUE 
                        AND Virtual_User_type__c = 'Solution Consultant' AND SCE_ID__r.Opportunity_ID__c IN: oppId AND SCE_ID__r.SC_Engagement_Status__c != 'Rejected']){
            mapOppUserName.put(dsrName.SCE_ID__r.Opportunity_ID__c, dsrName.Virtual_Team_Member_Name__r.Name);                   
        }
        //Priyank Code Ended
        //Looping over each record
        for(RFP_Support_Request__c eachRec : rfpRecords){
           
           if(!setOfRegions.contains(eachRec.Opportunity__r.Country_Region__c)){
                wrapperResult headerRecord = new wrapperResult();
                headerRecord.isHeader= true;
                headerRecord.isHeaderRecord = false;
                headerRecord.headerName = eachRec.Opportunity__r.Country_Region__c;
                wrapperResults.add(headerRecord);
                setOfRegions.add(eachRec.Opportunity__r.Country_Region__c);
            }   
          
            if(!setOfSubRegions.contains(eachRec.Opportunity__r.Country_Sub_Region__c)){
                wrapperResult headerRecord = new wrapperResult();
                headerRecord.isHeaderRecord = true;
                 headerRecord.isHeader= false;
                
                headerRecord.headerName = eachRec.Opportunity__r.Country_Sub_Region__c;
                wrapperResults.add(headerRecord);
                setOfSubRegions.add(eachRec.Opportunity__r.Country_Sub_Region__c);
            }
                       
              
            wrapperResult newRecord = new wrapperResult();
            //Below Code Added by Priyank
            if(mapOppUserName.containsKey(eachRec.Opportunity__c)){
                newRecord.solutionConsultant = mapOppUserName.get(eachRec.Opportunity__c);
            }
            else if(!string.isBlank(eachRec.Solution_Engineer_Name__c)){
                newRecord.solutionConsultant = eachRec.Solution_Engineer_Name__c;
            }
            else{
                newRecord.solutionConsultant = '';
            }
            //Priyank Code Ended
            newRecord.record = eachRec;
            newRecord.isHeaderRecord = false;
            newRecord.isHeader= false;
            wrapperResults.add(newRecord);         
             
        }
        if(wrapperResults.isEmpty()){
            wrapperResult headerRecord = new wrapperResult();
            headerRecord.isHeaderRecord = true;
            headerRecord.isHeader = true;
            headerRecord.headerName = 'No RFP Support Requests found.'; // Use Custom Label
            wrapperResults.add(headerRecord);
        }
        return wrapperResults;
    }
    
    /**    
    * @Description: wrapper class to display the records in a format that will be sent in email
    
    */
    public class wrapperResult{
        public RFP_Support_Request__c record {get;set;}
        public String headerName {get;set;}
        public String solutionConsultant {get;set;}
        public Boolean isHeaderRecord {get;set;}
        public Boolean isHeader {get;set;}
    
    }
}