objects/Dynamic_Query__c.object
<CustomObject>
    <fields>
        <fullName>Process_Name__c</fullName>
        <label>Process Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_type__c</fullName>
        <label>Where Condition</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Report_Name__c</fullName>
        <label>Report Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dynamic Query</label>
    <nameField>
        <displayFormat>QRID-{00000}</displayFormat>
        <label>Query ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Maintenance_End__c</fullName>
        <label>Maint. End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maintenance_Start__c</fullName>
        <label>Maint. Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Numb_of_Maint_Months__c</fullName>
        <label># of Maint Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>Text( Opportunity__r.Type )</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>APN_Number__c</fullName>
        <label>APN Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Base Item</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PublicGroupReportController_Test.cls
@istest(seeAllData = true)
public class PublicGroupReportController_Test{
    
    static testMethod void PublicGroupReportController_TestMethod() { 
        
        Opportunity testOpp = TestUtil.createOpportunities(1, true)[0];
        BigMachines__Quote__c testQuote = TestUtil.createQuotes(1, true)[0];   
        Order__c ord_1 = new Order__c();
        ord_1.Maintenance_Start__c = Date.today();
        ord_1.Maintenance_End__c = Date.today().addYears(1);
        ord_1.Numb_of_Maint_Months__c = 12;
        ord_1.status__c = 'In Progress';
        ord_1.Opportunity__c = testOpp.id;
        ord_1.Quote__c = testQuote.id;
        insert ord_1;
        
        List<RecordType> rtypes = [Select Id from RecordType where SobjectType = 'Product2' and DeveloperName= 'COREProductRecordType'];
        Product2 objTestProd1 = new Product2();
        objTestProd1.Name='Test Prod1';
        objTestProd1.recordTypeId = rtypes[0].Id;
        objTestProd1.Type__c = 'Token';
        objTestProd1.End_of_Support__c = String.valueOf(Date.today());
        objTestProd1.IsActive = true;
        objTestProd1.Description = 'test 1';
        objTestProd1.OfferingType__c = 'PureSuccess';
        objTestProd1.APN_Number__c = 'Tokens1';
        objTestProd1.zqu__SKU__c = 'testAshosh12121';
        Test.startTest();
        insert objTestProd1;
        
        /*Dynamic_Query__c dq = new Dynamic_Query__c();
        dq.Process_Name__c = 'Default';
        dq.Report_Name__c = 'eMite_Closed Won_FY2018_MW';
        string queryType = 'where Order__r.Quote__r.BigMachines__Opportunity__r.Lines_of_Businesses__c =' + 'Pure Cloud' + ' and Order__r.Quote__r.BigMachines__Opportunity__r.StageName =' + 'Closed' +' and Order__r.Quote__r.BigMachines__Opportunity__r.Win_Loss_Status__c =' + 'Won' + ' and Order__r.Quote__r.BigMachines__Is_Primary__c =' + 'true' + 'and (Product__r.APN_Number__c like'+ '%pureins%' + ' OR Product__r.Name like'+ '%pureins%';
        dq.Query_type__c = queryType;
        insert dq;*/
        
        //Dynamic_Query__c dq1 = new Dynamic_Query__c();
        //dq1.Process_Name__c = 'eMite_Closed Won_FY2018_MW';
        //dq1.Report_Name__c = 'eMite_Closed Won_FY2018_MW';
        //string queryType1 = 'where Order__r.Quote__r.BigMachines__Opportunity__r.Lines_of_Businesses__c =' + 'Pure Cloud' + ' and Order__r.Quote__r.BigMachines__Opportunity__r.StageName =' + 'Closed' +' and Order__r.Quote__r.BigMachines__Opportunity__r.Win_Loss_Status__c =' + 'Won' + ' and Order__r.Quote__r.BigMachines__Is_Primary__c =' + 'true' + 'and (Product__r.APN_Number__c like'+ '%pureins%' + ' OR Product__r.Name like'+ '%pureins%';
        //dq1.Query_type__c = queryType1;
        //insert dq1;
        
        List<Order_Line_Item__c> list_oli = TestUtil.createOrderLines(new List<Product2>{objTestProd1}, ord_1.Id, true);
        
        PublicGroupReportController publicGroup = new PublicGroupReportController();
        publicGroup.loadReport();
        Test.stopTest();
    }
}