objects/Entitlement_Transfer__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Entitlement Transfer</label>
</CustomObject>

objects/Product__c.object
<CustomObject>
    <description>What it does?  Object containing information about products associated with a DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Products_To_Exclude_In_New_SC__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List all the product names that can not be transferred in Transfer Tool and should not be Auto Transferred to New Service Contracts</description>
    <fields>
        <fullName>ProductName__c</fullName>
        <label>ProductName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Products To Exclude In New SC</label>
</CustomObject>

objects/Products_To_Include_In_New_SC__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List all the product names that need to be transferred Auto Transferred to New Service Contracts in Transfer Tool; No need to include if this is categorized as Genesys Care, Flex Care or Maintenance</description>
    <fields>
        <fullName>ProductName__c</fullName>
        <label>ProductName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Products To Include In New SC</label>
</CustomObject>

objects/Regional_Controller_List__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regional_Controller_User__c</fullName>
        <label>Regional Controller User</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Genesys Care Regional Controller List</label>
</CustomObject>

objects/Transfer_Tool__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Transfer_Tools1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Line Item</label>
        <referenceTo>ContractLineItem</referenceTo>
        <relationshipName>Transfer_Tools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Transfer_Tools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Entitlement Transfer Detail (Service Contract)</relationshipLabel>
        <relationshipName>Transfer_Tools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transfer_Quantity__c</fullName>
        <label>Transfer Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Status__c</fullName>
        <label>Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Awaiting for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transfer_Tool_Approval__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer Tool Approval</label>
        <referenceTo>Transfer_Tool_Approval__c</referenceTo>
        <relationshipName>Transfer_Tools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transfer_to_ST_EU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer to End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>equals</operation>
                <value>Active, Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entitlement Transfer Detail (Transfer to End User)</relationshipLabel>
        <relationshipName>Transfer_Tools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transfer_to_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer to Sold To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entitlement Transfer Detail (Transfer to Sold To)</relationshipLabel>
        <relationshipName>Transfer_Tools2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entitlement Transfer Detail</label>
    <nameField>
        <displayFormat>T{0000}</displayFormat>
        <label>Transfer Tool Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entitlement Transfer Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Transfer_Tool_Approval__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Transfer_Tool_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attachments_Linked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attachments Linked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Account__r.Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regional_Controller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional Controller</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Transfer_Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Transfer Entitlements (Service Contract)</relationshipLabel>
        <relationshipName>Transfer_Tool_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transfer Entitlements</label>
    <nameField>
        <displayFormat>TTA{0000}</displayFormat>
        <label>Transfer Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transfer Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TransferToolTest.cls
/*
    Description     : This Test Class covers all the Classes, Triggers, Pages related to Transfer Tool.
                      The following is the list of artifacts covered for tested using this test class. 
    Apex Classes    :   TransferToolController, TransferEntitlementsAttMsgController
    Apex Triggers   :   trgAfterApprovedEntitlement on Transfer_Tool_Approval__c
                        TransferEntitlementsAttachmentTrigger on Attachment
 
*/
@isTest(seeAllData=True)
private class TransferToolTest {

    @isTest
    static void transferToolTestCase(){
        
        List<Products_To_Exclude_In_New_SC__c> productsToExcludeConfig = new List<Products_To_Exclude_In_New_SC__c>();
        
        List<Products_To_Exclude_In_New_SC__c> productsToExclude = Products_To_Exclude_In_New_SC__c.getall().values();
        if(productsToExclude.isEmpty()){
            productsToExcludeConfig.add(new Products_To_Exclude_In_New_SC__c(Name = 'Dummy', ProductName__c = 'Dummy'));
            Insert productsToExcludeConfig;
        }
        
        List<Products_To_Include_In_New_SC__c> productsToIncludeConfig = new List<Products_To_Include_In_New_SC__c>();
        List<Products_To_Include_In_New_SC__c> productsToInclude = Products_To_Include_In_New_SC__c.getall().values();
        if(productsToInclude.isEmpty()){
            productsToIncludeConfig.add(new Products_To_Include_In_New_SC__c(Name = 'Dummy', ProductName__c = 'Dummy'));
            Insert productsToIncludeConfig;
        }        

        List<Entitlement_Transfer__c> etcs = new List<Entitlement_Transfer__c>();
        List<Entitlement_Transfer__c> etcsList = Entitlement_Transfer__c.getall().values();
        if(etcsList.isEmpty()){
            etcs.add(new Entitlement_Transfer__c(Name = UserInfo.getName(), Email__c = UserInfo.getUserEmail()));
            Insert etcs;
        }
        
        List<Regional_Controller_List__c> rccs = new List<Regional_Controller_List__c>();
        List<Regional_Controller_List__c> rccsList = Regional_Controller_List__c.getall().values();
        if(rccsList.isEmpty()){
            rccs.add(new Regional_Controller_List__c(Name = 'APAC', Region__c = 'APAC', Regional_Controller_User__c = UserInfo.getUserName()));
            rccs.add(new Regional_Controller_List__c(Name = 'EMEA', Region__c = 'EMEA', Regional_Controller_User__c = UserInfo.getUserName()));
            rccs.add(new Regional_Controller_List__c(Name = 'LATAM', Region__c = 'LATAM', Regional_Controller_User__c = UserInfo.getUserName()));
            rccs.add(new Regional_Controller_List__c(Name = 'North America', Region__c = 'North America', Regional_Controller_User__c = UserInfo.getUserName()));
            Insert rccs;
        }
        
        //Util.Bypass_Trigger_Chk = true;
        PageReference pageRef = Page.TransferToolPage;
        Test.setCurrentPageReference(pageRef);
        
        TransferToolController ttController = new TransferToolController();
        // Fetch any ContractLineItem which has Active Contract and Current_Quantity__c greater than 5  
        List<ContractLineItem> cLineItem = [SELECT Id, ServiceContractId, ServiceContract.Name, ServiceContract.AccountId, ServiceContract.Account.Name, Service_Contract_Status__c, Current_Quantity__c  FROM ContractLineItem WHERE ServiceContract.Offering_Type__c = 'PureEngage' AND ServiceContract.Service_Contract_Type__c = 'Perpetual' AND Service_Contract_Status__c ='Active' AND Current_Quantity__c > 5 LIMIT 1];
        // Set the Transfer Tool Selected Account
        ttController.transferTool.Account__c = cLineItem[0].ServiceContract.AccountId;
        // Retrieve Service Contracts for Selected Account
        ttController.getServiceContracts();
        // Set the Transfer Tool Selected Service Contract
        ttController.selectServiceContractId = cLineItem[0].ServiceContractId;
        // Retrieve Service Contract Line Items for Selected Service Contract
        ttController.getContractLineItems();
        
        // SELECT Random Custom to Transfer the Licenses To
        List<Account> customerAccounts = [Select Id, Name FROM Account WHERE Account_Status__c = 'Active' AND Type = 'Customer' LIMIT 2];
        
        // Select one Contract Line to be Transferred to Random Customer 
        for(TransferToolController.TransferLineItemsWrapper tliw : ttController.transferCliWrapperList){
            if(tliw.cli.id == cLineItem[0].Id){
                tliw.isSelect  = True;
                tliw.transferQty = 2;
                if(customerAccounts[0].Id != cLineItem[0].ServiceContract.AccountId)
                    tliw.toolForAccTransfer.Transfer_to_ST_EU__c = customerAccounts[0].Id;
                else 
                    tliw.toolForAccTransfer.Transfer_to_ST_EU__c = customerAccounts[1].Id;
            }
        }
        ttController.clickedTransferStr = 'true';
        ttController.displayTransferredRows();
        // Update the quantity 
        for(TransferToolController.TransferLineItemsWrapper tliw : ttController.transferCliWrapperList){
            if(tliw.cli.id == cLineItem[0].Id){
                tliw.isSelect  = True;
                tliw.transferQty = 4;
                if(customerAccounts[0].Id != cLineItem[0].ServiceContract.AccountId)
                    tliw.toolForAccTransfer.Transfer_to_ST_EU__c = customerAccounts[0].Id;
                else 
                    tliw.toolForAccTransfer.Transfer_to_ST_EU__c = customerAccounts[1].Id;
            }
        }
        ttController.clickedTransferStr = 'true';
        ttController.displayTransferredRows();

        // Remove the Item from the List to Transfer
        ttController.removeTransferId = ttController.newTransferToolList[0].Id;
        ttController.removeNonApprovedRows();
        
        // Select one Contract Line to be Transferred to Random Customer 
        for(TransferToolController.TransferLineItemsWrapper tliw : ttController.transferCliWrapperList){
            if(tliw.cli.id == cLineItem[0].Id){
                tliw.isSelect  = True;
                tliw.transferQty = 2;
                if(customerAccounts[0].Id != cLineItem[0].ServiceContract.AccountId)
                    tliw.toolForAccTransfer.Transfer_to_ST_EU__c = customerAccounts[0].Id;
                else 
                    tliw.toolForAccTransfer.Transfer_to_ST_EU__c = customerAccounts[1].Id;
            }
        }
        ttController.clickedTransferStr = 'true';
        ttController.displayTransferredRows();
        
        // Set the Status to Approved on the Transfer Tool Requests         
        List<Transfer_Tool_Approval__c> ttRequests = [SELECT id, Account__c, Service_Contract__c, Status__c FROM Transfer_Tool_Approval__c WHERE Status__c  = 'New'];
        for(Transfer_Tool_Approval__c tta: ttRequests){
            tta.Status__c = 'Submitted';
        }
        update ttRequests;
        
        for(Transfer_Tool_Approval__c tta: ttRequests){
            tta.Status__c = 'Rejected';
        }
        update ttRequests;
        
        ttController.reinstateTransfer();
        
        for(Transfer_Tool_Approval__c tta: ttRequests){
            tta.Status__c = 'Submitted';
        }
        update ttRequests;
        
        for(Transfer_Tool_Approval__c tta: ttRequests){
            tta.Status__c = 'Approved';
        }
        update ttRequests;

        // Dummy calls .... 
        ttController.refreshCurrentPage();
        
        // Test Cases for TransferEntitlementsAttMsgController & TransferEntitlementsAttachmentTrigger on Attachment
        ApexPages.StandardController sc = new ApexPages.StandardController(ttRequests[0]);
        TransferEntitlementsAttMsgController teamc = new TransferEntitlementsAttMsgController(sc);
        PageReference teamcPageRef = Page.TransferToolApprovalAttachmentsMessage;
        Test.setCurrentPage(teamcPageRef);
        
        // Insert Attachment for 
        Attachment attachment = new Attachment();
        attachment.body = Blob.valueOf('This is an Attachment Test ...');
        attachment.name = 'fake-attachment';
        attachment.parentId = ttRequests[0].id;
        insert attachment;
        
    }

    
    @isTest
    static void transferToolTriggersTestCase(){
        List<ContractLineItem> cLineItem = [SELECT Id, ServiceContractId, ServiceContract.Name, ServiceContract.AccountId, ServiceContract.Account.Name, 
                                            PricebookEntry.Product2.Id, Service_Contract_Status__c, Current_Quantity__c  
                                            FROM ContractLineItem 
                                            WHERE 
                                            	ServiceContract.Offering_Type__c = 'PureEngage' AND ServiceContract.Service_Contract_Type__c = 'Perpetual' AND
                                            	Service_Contract_Status__c ='Active' AND Current_Quantity__c > 5 
                                            LIMIT 1];
        
        // SELECT Random Custom to Transfer the Licenses To
        List<Account> customerAccounts = [Select Id, Name FROM Account WHERE Account_Status__c = 'Active' AND Type = 'Customer' LIMIT 2];
        
        Transfer_Tool_Approval__c ttRequest = new Transfer_Tool_Approval__c(Account__c = cLineItem[0].ServiceContract.AccountId, 
                                                                            Service_Contract__c = cLineItem[0].ServiceContractId, 
                                                                            Status__c = 'New', Attachments_Linked__c = true, 
                                                                            Regional_Controller__c = UserInfo.getUserId());  
        insert ttRequest;
        
         Transfer_Tool__c ttRequestLineItem1 = new Transfer_Tool__c(Contract_Line_Item__c = cLineItem[0].Id, 
                                                                  Service_Contract__c = cLineItem[0].ServiceContractId, 
                                                                  Product__c = cLineItem[0].PricebookEntry.Product2.Id, 
                                                                  Transfer_Quantity__c = 2,
                                                                  Transfer_to_ST_EU__c = customerAccounts[0].Id,
                                                                  Transfer_to_Sold_To__c = customerAccounts[1].Id, 
                                                                  Transfer_Status__c = 'New',
                                                                    Transfer_Tool_Approval__c = ttRequest.Id
                                                                 );
        insert ttRequestLineItem1;
        
        Transfer_Tool__c ttRequestLineItem = new Transfer_Tool__c(Contract_Line_Item__c = cLineItem[0].Id, 
                                                                  Service_Contract__c = cLineItem[0].ServiceContractId, 
                                                                  Product__c = cLineItem[0].PricebookEntry.Product2.Id, 
                                                                  Transfer_Quantity__c = 0,
                                                                  Transfer_Status__c = 'New',
                                                                    Transfer_Tool_Approval__c = ttRequest.Id
                                                                 );
        try{
            insert ttRequestLineItem;
        } catch(Exception e){
            // do nothing
        }
        
        ttRequestLineItem.Transfer_Quantity__c = cLineItem[0].Current_Quantity__c + 1;
        try{
            insert ttRequestLineItem;
        } catch(Exception e){
            // do nothing
        }

        ttRequestLineItem.Transfer_Quantity__c = cLineItem[0].Current_Quantity__c + 1;
        try{
            insert ttRequestLineItem;
        } catch(Exception e){
            // do nothing
        }
        
       ttRequestLineItem.Transfer_Quantity__c = 4;
        try{
            insert ttRequestLineItem;
        } catch(Exception e){
            // do nothing
        }

        ttRequestLineItem.Transfer_to_ST_EU__c = customerAccounts[0].Id; 
        try{
            insert ttRequestLineItem;
        } catch(Exception e){
            // do nothing
        }
        
        ttRequestLineItem.Transfer_to_Sold_To__c = customerAccounts[1].Id;
        try{
            insert ttRequestLineItem;
        } catch(Exception e){
            // do nothing
        }
        
        ttRequest.Status__c = 'Submitted';
        update ttRequest;
        ttRequest.Status__c = 'Approved';
        update ttRequest;
    }
    // 
}