objects/ERP_Currency_Daily_Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FROM_CURRENCY_CODE__c</fullName>
        <label>From Currency</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TO_CURRENCY_CODE__c</fullName>
        <label>To Currency</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Currency Exchange Rate</label>
    <nameField>
        <label>SFDC Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currency Exchange Rate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>ERP_Currency_Daily_Exchange_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the daily USD currency rates from the ERP.</description>
        <label>ERP Currency Daily Exchange Rate</label>
        <referenceTo>ERP_Currency_Daily_Exchange_Rate__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders(Revenue/Non-Revenue)</relationshipLabel>
        <relationshipName>End_User_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>Text( Opportunity__r.Type )</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <label>End User Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OrderFieldPopulationHelper_Test.cls
//Naresh Kumar  09/14/2017
@isTest(seeAllData=true)
private class OrderFieldPopulationHelper_Test {
    
    static testMethod void testOrderFieldPopulationHelper(){
        
        Account testAccount = TestUtil.createAccounts(1, true)[0];        
        
        Order__c testOrder = TestUtil.createOrders(1, false)[0];    
        testOrder.End_User_Name__c = testAccount.id;
        insert testOrder;
        
        Product2 testProduct = TestUtil.createProducts(1, false)[0];
        testProduct.Type__c = 'GU';
        insert testProduct;
        Test.startTest();
        List<Product2> list_ofProduct2 = new List<Product2>();
        list_ofProduct2.add(testProduct);
        
        Order_Line_Item__c testOLI = TestUtil.createOrderLines(list_ofProduct2, testOrder.id, false)[0];
        insert testOLI;
        Test.stopTest();
    }
    
    static testMethod void testPopulateCurrnecyRateLookup(){
        ERP_Currency_Daily_Exchange_Rate__c testRate = new ERP_Currency_Daily_Exchange_Rate__c();
        testRate.Effective_Date__c = System.today().addDays(-1);
        testRate.FROM_CURRENCY_CODE__c = 'CAD';
        testRate.TO_CURRENCY_CODE__c = 'USD';
        Util.Bypass_Trigger_Chk = true;
        insert testRate;
        Util.Bypass_Trigger_Chk = false;
        
        Account testAccount = TestUtil.createAccounts(1, true)[0];        
        Opportunity testOpportunity = TestUtil.createOpportunities(1, testAccount.id, false)[0];
        testOpportunity.CloseDate = System.today().addYears(1);
        testOpportunity.CurrencyIsoCode = 'CAD';
        insert testOpportunity;
        
        Order__c testOrder = TestUtil.createOrders(1, false)[0];    
        testOrder.End_User_Name__c = testAccount.id;
        testOrder.Status__c = 'In Progress';
        testOrder.CurrencyIsoCode = 'CAD';
        testOrder.Invoice_Date__c = System.today();
        testOrder.Opportunity__c = testOpportunity.id;
        insert testOrder;
        
        Test.startTest();
        //testOrder.Status__c = 'Approved';
        //update testOrder;
        testOrder.Status__c = 'Completed';
        TriggerFlowManager.ORDER_BEFORE_UPDATE_TRIGGER = true;
        update testOrder;
        Test.stopTest();
       
    }
    
}