objects/Error_Log__c.object
<CustomObject>
    <description>This object is for storing exceptions while users are doing any DML/Data operations.</description>
    <fields>
        <fullName>Code_Type__c</fullName>
        <description>It will differentiate about apex code type</description>
        <label>Code Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Description__c</fullName>
        <label>Error Description</label>
        <length>16384</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Object name on where code is executing logic.</description>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ErrorLogUtil.cls
//Naresh Kumar	03/13/2014
public with sharing class ErrorLogUtil {	
	public static void insertLog(String recordName, String logDetails, String source){
		try{
			Error_Log__c newLog = new Error_Log__c();
			newLog.Code_Type__c = recordName;
			newLog.Error_Description__c = logDetails;
			newLog.User_Name__c = UserInfo.getUserId();
			newLog.Object_Name__c = source;
			insert newLog;
			//String html = 'https://na12.salesforce.com/' + newLog.id;
			//if(recordName != null)
			//SendEmail.sendSingleEmail('nareshk.it@gmail.com', 'New Order Completed', html);
		}
		catch(Exception ex){
			//SendEmail.sendSingleEmail('nareshk.it@gmail.com', 'Error in ErrorLogUtil', ex.getMessage());
		}
	}
}