objects/ExecInitiativeGroup__c.object
<CustomObject>
    <description>The master Executive Group under which initiatives are collected and managed</description>
    <fields>
        <fullName>Exec_Group_Additional_Information__c</fullName>
        <description>Additional information relating to the Executive Group overall and all of its Initiatives</description>
        <inlineHelpText>Additional information relating to the Executive Group overall and all of its Initiatives</inlineHelpText>
        <label>Exec Group Additional Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Group_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary business manager for the group</description>
        <inlineHelpText>The primary business manager for the group</inlineHelpText>
        <label>Group Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Executive_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Executive Group</label>
    <nameField>
        <label>Executive Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Executive Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Initiative__c.object
<CustomObject>
    <description>An Executive Initiative Item</description>
    <fields>
        <fullName>Applicable_Year__c</fullName>
        <description>The year in which the Initiative item is applicable</description>
        <inlineHelpText>The year in which the Initiative item is applicable</inlineHelpText>
        <label>Applicable Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2015</fullName>
                    <default>true</default>
                    <label>2015</label>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DeadlinesSummary__c</fullName>
        <description>Deadlines Summary Information</description>
        <label>DeadlinesSummary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Executive_Group__c</fullName>
        <description>The Executive Group to which this initiative item belongs</description>
        <inlineHelpText>The Executive Group to which this initiative item belongs</inlineHelpText>
        <label>Executive Group</label>
        <referenceTo>ExecInitiativeGroup__c</referenceTo>
        <relationshipLabel>Initiatives</relationshipLabel>
        <relationshipName>Initiatives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Initiative_Name__c</fullName>
        <description>The name of the Initiative Item</description>
        <inlineHelpText>The name of the Initiative Item</inlineHelpText>
        <label>Initiative Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Initiative_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The business owner of the initiative item</description>
        <inlineHelpText>The business owner of the initiative item</inlineHelpText>
        <label>Initiative Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Initiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initiative_Rank__c</fullName>
        <description>The rank / order of the initiative - 1 being the highest ranked</description>
        <inlineHelpText>The rank / order of the initiative - 1 being the highest ranked</inlineHelpText>
        <label>Initiative Rank</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ObjectivesSummary__c</fullName>
        <description>Objectives Summary text information</description>
        <label>ObjectivesSummary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Overall_Status_Summary__c</fullName>
        <description>The overall summary status of the initiative</description>
        <inlineHelpText>The overall summary status of the initiative</inlineHelpText>
        <label>Overall Status Summary</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the executive initiative item</description>
        <inlineHelpText>The status of the executive initiative item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On-Track</fullName>
                    <color>#009900</color>
                    <default>true</default>
                    <label>On-Track</label>
                </value>
                <value>
                    <fullName>Attention Required</fullName>
                    <color>#FF6600</color>
                    <label>Attention Required</label>
                </value>
                <value>
                    <fullName>Major Deviation</fullName>
                    <color>#FF0000</color>
                    <label>Major Deviation</label>
                </value>
                <value>
                    <fullName>Complete</fullName>
                    <color>#3366FF</color>
                    <label>Complete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Initiative</label>
    <nameField>
        <displayFormat>EI-{00000}</displayFormat>
        <label>Initiative ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Initiative_Deadline__c.object
<CustomObject>
    <description>A deadline associated with an Executive Initiative</description>
    <fields>
        <fullName>Deadline_Name__c</fullName>
        <description>The name of the Initiative Deadline item</description>
        <inlineHelpText>The name of the Initiative Deadline item</inlineHelpText>
        <label>Deadline Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Deadline_completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the deadline was met and completed</description>
        <inlineHelpText>Indicates whether the deadline was met and completed</inlineHelpText>
        <label>Deadline completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The date that this Initiative Deadline is required to be completed</description>
        <inlineHelpText>The date that this Initiative Deadline is required to be completed</inlineHelpText>
        <label>Due Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiative__c</fullName>
        <description>The Initiative to which this Deadline item belongs</description>
        <inlineHelpText>The Initiative to which this Deadline item belongs</inlineHelpText>
        <label>Initiative</label>
        <referenceTo>Initiative__c</referenceTo>
        <relationshipLabel>Initiative Deadlines</relationshipLabel>
        <relationshipName>Initiative_Deadlines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Overdue__c</fullName>
        <formula>IF (  Deadline_completed__c  = False,
      IF ( ISBLANK ( Due_Date__c ),
           False,
           IF ( ( Due_Date__c  - TODAY() ) &lt; 0, True, False) 
         )
      , False
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Overdue</label>
        <type>Checkbox</type>
    </fields>
    <label>Initiative Deadline</label>
    <nameField>
        <displayFormat>EID-{00000}</displayFormat>
        <label>Deadline ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Initiative Deadlines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Initiative_Objective__c.object
<CustomObject>
    <description>An Objective related to an Executive Initiative</description>
    <fields>
        <fullName>Initiative__c</fullName>
        <description>The Initiative to which this Objective belongs</description>
        <inlineHelpText>The Initiative to which this Objective belongs</inlineHelpText>
        <label>Initiative</label>
        <referenceTo>Initiative__c</referenceTo>
        <relationshipLabel>Initiative Objectives</relationshipLabel>
        <relationshipName>Initiative_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Objective_Name__c</fullName>
        <description>The name of the Initiative Objective</description>
        <inlineHelpText>The name of the Initiative Objective</inlineHelpText>
        <label>Objective Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Initiative Objective</label>
    <nameField>
        <displayFormat>EIO-{00000}</displayFormat>
        <label>Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Initiative Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ExecInitiativeController.cls
public class ExecInitiativeController {
    public String StatusColor;
    private String UpdatesData;
    private String DeadlinesData;
    private String DeadlineSuffix;
    
    public ExecInitiativeController() {
    
    }
    
    public String getExecGroupNameAndOwner() {
        String ExecGroupId = ApexPages.currentPage().getParameters().get('id');
        String NameAndOwner='';
        List<ExecInitiativeGroup__c> listExecGroups=[SELECT Name, Group_Manager__r.Name FROM ExecInitiativeGroup__c WHERE Id = :ExecGroupId];
        if (listExecGroups != null) {
            NameAndOwner = listExecGroups[0].Name + '-' + listExecGroups[0].Group_Manager__r.Name;
        }
        return NameAndOwner;
    }
    
    public String getExecGroupAdditionalInfo() {
        String ExecGroupId = ApexPages.currentPage().getParameters().get('id');
        String AdditionalInfo='';
        List<ExecInitiativeGroup__c> listExecGroups=[SELECT Exec_Group_Additional_Information__c FROM ExecInitiativeGroup__c WHERE Id = :ExecGroupId];
        if (listExecGroups != null) {
            AdditionalInfo = listExecGroups[0].Exec_Group_Additional_Information__c;
        }
        return AdditionalInfo;
    }
        
    public List<Initiative__c> getInitiatives() {
        String ExecGroupId = ApexPages.currentPage().getParameters().get('id');
        String CurrYear = String.valueOf(system.today().year());
        List<Initiative__c> listInitiative=[SELECT Id, Name, Initiative_Name__c, Initiative_Owner__r.Name, Status__c, Overall_Status_Summary__c, ObjectivesSummary__c, DeadlinesSummary__c FROM Initiative__c WHERE Executive_Group__r.Id =:ExecGroupId AND Applicable_Year__c = :CurrYear ORDER BY Initiative_Rank__c];
        for (Initiative__c i : listInitiative) {
            if(i.Status__c=='On-Track')
                i.Status__c='green'; 
            if(i.Status__c=='Attention Required')
                i.Status__c='orange'; 
            if(i.Status__c=='Major Deviation')
                i.Status__c='red';
            if(i.Status__c=='Complete')
                i.Status__c='blue';
         
            // get the latest updates from the Objectives
            //UpdatesData = '<b>Accomplishments this past month</b>';
            UpdatesData = '';

            date d = system.today().addDays(-30);
            List<Initiative_Objective__c> listObjectives=[SELECT Id, Name, Objective_Name__c FROM Initiative_Objective__c WHERE Initiative__r.Id = :i.Id];
            for (Initiative_Objective__c eIO : listObjectives) {
                UpdatesData += '<li>' + eIO.Objective_Name__c + '</li>';
                UpdatesData += '<ul>';
                List<Task> tasks=[select subject, description from Task where (status='Completed' or status='Done') and lastModifiedDate >= :d and WhatId = :eIO.Id];
                for (Task t : tasks) {
                    if (t.description != null) {
                        UpdatesData += '<li type="Square">' + t.subject + ':(' + t.description + ')</li>';
                    } else {
                        UpdatesData += '<li type="Square">' + t.subject + '</li>';
                    }
                }   
                UpdatesData += '</ul>';
            }             
        
            // get the overall status if available
            if(i.Overall_Status_Summary__c != null) {
                // Substitute the new line characters for html breaks for output in the VF dashboards
                String OSS = i.Overall_Status_Summary__c;
                OSS = OSS.replaceAll('\n', '<br/>');
                UpdatesData += '<br><br><b>Overall Status</b><br>' + OSS;
                }
                
                
            // get the deadline information from the Deadlines related object
            //DeadlinesData = '<b>Initiative Deadlines</b>';
            DeadlinesData = '';
            List<Initiative_Deadline__c> listDeadlines=[SELECT Id, Name, Deadline_Name__c, Due_Date__c, Deadline_completed__c, Is_Overdue__c FROM Initiative_Deadline__c WHERE Initiative__r.Id = :i.Id ORDER BY Due_Date__c];
            for (Initiative_Deadline__c eID : listDeadlines) {
                DeadlineSuffix = '';
                if (eID.Deadline_completed__c == true)
                {
                    DeadlineSuffix = '<span style="color:green"> <b> (completed)</b></span>';
                }
                else
                {
                    if (eID.Is_Overdue__c == true)
                    {
                        DeadlineSuffix = '<span style="color:red"> <b>(overdue)</b></span>';
                    }
                }
                
                DeadlinesData += '<li>' + eID.Due_Date__c.format() + '&nbsp-' + eID.Deadline_Name__c + DeadlineSuffix +'</li>';
            }             
            
            i.ObjectivesSummary__c = UpdatesData;
            i.DeadlinesSummary__c = DeadlinesData;
        }
        return listInitiative;
    }    

}