objects/Export_Screening_Checklist__c.object
<CustomObject>
    <customHelpPage>ECC_help</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Export Screening Checklists</relationshipLabel>
        <relationshipName>Export_Screening_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Checklist_expiration_date__c</fullName>
        <label>Checklist expiration date</label>
        <type>Date</type>
    </fields>
    <label>Export Screening Checklist</label>
    <nameField>
        <label>Export Screening Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Export Screening Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ChecklistIterator.cls
global class ChecklistIterator implements Iterator<Export_Screening_Checklist__c>
{
   List<Export_Screening_Checklist__c> memList{get; set;}
   Integer i {get; set;}

   public ChecklistIterator()
   {
       memList = [SELECT id,name,Account__c,Checklist_expiration_date__c,owner.email,Account__r.name,Account__r.owner.email FROM Export_Screening_Checklist__c where Checklist_expiration_date__c!=null];
       i = 0;
   }

   global boolean hasNext()
   {
       if(i >= memList.size())
       {
           return false;
       
       } else 
       {
           return true;
       }
   }

   global Export_Screening_Checklist__c next()
   {
       if(i > memList.size())
       {
           return null;
       }
       i++;
       return memList[i-1];
   }
}