objects/Failed_Operation_Recovery__c.object
<CustomObject>
    <description>stores details of failed operations and resubmit for retry.
Currently capture error on the Order status update, but can be extended to other events.</description>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <label>Object Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Failed Operation Recovery</label>
    <nameField>
        <displayFormat>FOR-{00000000}</displayFormat>
        <label>Failed Operation Recovery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Failed Operation Recovery</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Failed_Operation_Recovery_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>specifies max number of retry attempts and time between the attempts in minutes
used in trigger FailedOperationRecovery_After</description>
    <fields>
        <fullName>Max_Retry_Attempts__c</fullName>
        <label>Max Retry Attempts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wait_Minutes__c</fullName>
        <label>Wait Minutes</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Failed Operation Recovery Settings</label>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FailedOperationRecovery_Test.cls
@isTest
public class FailedOperationRecovery_Test {
    
    static TestMethod void myUnitTest0(){
        util.Bypass_Trigger_Chk=true;
        Order__c ordr = TestUtil.createOrders(1, true)[0];
        util.Bypass_Trigger_Chk=false;
        Failed_Operation_Recovery__c rec = new Failed_Operation_Recovery__c(
            Object_Name__c = ordr.Name,
            Object_Id__c = String.valueOf(ordr.Id),
            Error_Message__c = 'Error updatingcreating CCDB for Order:');                   
        insert rec;
        
        Failed_Operation_Recovery_Settings__c FORS = new Failed_Operation_Recovery_Settings__c();
        FORS.Max_Retry_Attempts__c=10;
        FORS.Wait_Minutes__c=0;
        //FORS.Max_Retry_Attempts__c=60;
        insert FORS;
        
        util.Bypass_Trigger_Chk=true;
        //Order__c ordr1 = TestUtil.createOrders(1, true)[0];
        util.Bypass_Trigger_Chk=false;
        Failed_Operation_Recovery__c rec1 = new Failed_Operation_Recovery__c(
            Object_Name__c = ordr.Name,
            Object_Id__c = String.valueOf(ordr.Id),
            Error_Message__c = 'Error updatingcreating CCDB for Order:');                   
        insert rec1;
        
        util.Bypass_Trigger_Chk=true;
        //Order__c ordr1 = TestUtil.createOrders(1, true)[0];
        //util.Bypass_Trigger_Chk=false;
        Failed_Operation_Recovery__c rec2 = new Failed_Operation_Recovery__c(
            Object_Name__c = ordr.Name,
            Object_Id__c = String.valueOf(ordr.Id),
            Error_Message__c = 'Error updatingcreating CCDB for Order:');                   
        insert rec2;
    }

}