objects/Finance_Notifications__c.object
<CustomObject>
    <description>Notifications as requested by Ankit</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Notifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notification_Type__c</fullName>
        <label>Notification Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collection Letter</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
                <value>
                    <fullName>Shipping Notifications</fullName>
                </value>
                <value>
                    <fullName>Invoices-Maintenance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Finance Notifications</label>
    <nameField>
        <displayFormat>FN-{000000}</displayFormat>
        <label>Finance Notifications Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OrderAcknowledgeSchedularTest1.cls
@isTest(seeAllData = false)
public class OrderAcknowledgeSchedularTest1{
     
    
    public static testMethod void testOrderAcknowledgeEmailTemplateController1(){
        Test.StartTest();
        Account testAcc = TestUtil.createAccounts(1, true)[0];
        Contact testContact = new Contact(AccountId = testAcc.id, LastName = 'Test');
        insert testContact;
        Opportunity testOpp = TestUtil.createOpportunities(1, testAcc.id, false)[0];
        testOpp.Contact__c = testContact.id;
        insert testOpp;
        
        List<Account_Order_Address__c> orderAddress = [SELECT Order__c FROM Account_Order_Address__c WHERE Order__c != null LIMIT 5];         
        Order__c testOrder = TestUtil.createOrders(1, true)[0];
        Test.StopTest();
        BigMachines__Quote__c objQuote = new BigMachines__Quote__c(id = testOrder.Quote__c, BigMachines__Is_Primary__c = true);
        update objQuote;
        List<Account_Order_Address__c> listOfOrderAddresses = new List<Account_Order_Address__c>();
        Account_Order_Address__c testAddress = new Account_Order_Address__c(Order__c = testOrder.id, Address_Type__c = 'Bill To');
        listOfOrderAddresses.add(testAddress);
        testAddress = new Account_Order_Address__c(Order__c = testOrder.id,Address_Type__c = 'Ship To');
        listOfOrderAddresses.add(testAddress);
        testAddress = new Account_Order_Address__c(Order__c = testOrder.id,Address_Type__c = 'Sold To');
        listOfOrderAddresses.add(testAddress);
        insert listOfOrderAddresses;
        
        OrderAcknowledgeEmailTemplateController objContTest = new OrderAcknowledgeEmailTemplateController();
        objContTest.orderId = testOrder.id;
        objContTest.getOrderLineItems();
        objContTest.getOrderAddreses();
        objContTest.getContractEmails();
        //objContTest.isRunningTest();
        OrderAcknowledgeEmailTemplateController.resendEmail(testOrder.id);
        
        Account testAccount = TestUtil.createAccounts(1, true)[0];
        Finance_Notifications__c objFin = new Finance_Notifications__c(Active__c = true, Email__c = 'test@asdf.com1');
        objFin.Account__c = testAccount.id;
        objFin.Notification_Type__c = 'Invoice';
        insert objFin;
        
        testOrder.Status__c = 'Order Submitted';
        update testOrder;
        objContTest.accountId = testAccount.id;
        objContTest.getContractEmails();
        Map<Id, Order__c> newMap = new Map<Id, Order__c>();
        newMap.put(testOrder.id, testOrder);
        
        OrderUtil.sendAcknowledgeEmail(newMap, null);
    }
}