objects/FR_Commitment__c.object
<CustomObject>
    <fields>
        <fullName>Commitment_Progress__c</fullName>
        <label>Commitment Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Under Evaluation</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Field Customer Commit Request</label>
    <nameField>
        <displayFormat>FCCR-{0000}</displayFormat>
        <label>Commitment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Customer Commit Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FRCommitmentRequestController.cls
public without sharing class FRCommitmentRequestController {

    public String presentState {get; set;}
    private ID commId; 
    private FR_Commitment__c comm;

    public FRCommitmentRequestController (ApexPages.StandardController stdController) {
        commId = stdController.getId();
   
        if ( String.isNotBlank(commId) ) {
        	
           List<FR_Commitment__c> commlst = [SELECT Commitment_Progress__c FROM FR_Commitment__c WHERE Id = :commId];
           comm = commlst[0];
           presentState = comm.Commitment_Progress__c;    
        }   
    }
 
    public PageReference withdraw() {
    	comm.Commitment_Progress__c = 'Withdrawn';
    	update comm;
    	return new PageReference('/' + commId);
    }
}