objects/GCF_NetSuite_Data__c.object
<CustomObject>
    <fields>
        <fullName>End_User_GARN_Code__c</fullName>
        <label>End User GARN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <label>End User Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Subsidiary_ID__c</fullName>
        <label>End User Subsidiary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maintenance_End_Date__c</fullName>
        <label>Maintenance End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maintenance_Start_Date__c</fullName>
        <label>Maintenance Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offering_Type_Formula__c</fullName>
        <formula>CASE(Offering_Type__c, 
&apos;PureConnect&apos;, &apos;PureConnect&apos;, 
&apos;PureConnect - On Premise&apos;, &apos;PureConnect&apos;, 
&apos;PureEngage&apos;, &apos;PureEngage&apos;, 
&apos;PureEngage - On Premise&apos;, &apos;PureEngage&apos;, 
&apos;PureEngage - Renewal&apos;, &apos;PureEngage&apos;, 
&apos;Legacy Deferred Upload&apos;, &apos;Legacy Deferred Upload&apos;, 
&apos;PureConnect - Cloud&apos;, &apos;PureConnect - Cloud&apos;, 
&apos;PureEngage - Cloud&apos;, &apos;PureEngage - Cloud&apos;, 
&apos;PureCloud&apos;, &apos;PureCloud&apos;, 
&apos;PureEngage&apos; 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offering Type (Formula)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offering_Type__c</fullName>
        <externalId>true</externalId>
        <label>Offering Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Posting_Amount_USD__c</fullName>
        <label>Posting Amount USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Posting_Amount__c</fullName>
        <label>Posting Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Posting_Date__c</fullName>
        <label>Posting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posting_Month_Formula__c</fullName>
        <formula>MONTH(Posting_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Posting Month Formula</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Posting_Quarter_Formula__c</fullName>
        <formula>CASE(MONTH(Posting_Date__c), 
       1, 1, 
       2, 1,
       3, 1,
       4, 2, 
       5, 2,
       6, 2,
       7, 3, 
       8, 3,
       9, 3,
       10, 4, 
       11, 4,
       12, 4,
       0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Posting Quarter Formula</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Posting_Year_Formula__c</fullName>
        <formula>YEAR(Posting_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Posting Year Formula</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <label>Quote Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Schedule</fullName>
                </value>
                <value>
                    <fullName>Deferred Revenue</fullName>
                </value>
                <value>
                    <fullName>Incremental Revenue</fullName>
                </value>
                <value>
                    <fullName>First Year Maintenance</fullName>
                </value>
                <value>
                    <fullName>Recognized Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_GARN_Code__c</fullName>
        <label>Sold To GARN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <label>Sold To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Subsidiary_ID__c</fullName>
        <label>Sold To Subsidiary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GCF NetSuite Data</label>
    <nameField>
        <displayFormat>GCFN-{00000000}</displayFormat>
        <label>Genesys Care Forecasting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCF NetSuite Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GCF_Report_Data__c.object
<CustomObject>
    <fields>
        <fullName>BillingPlan_E__c</fullName>
        <label>BillingPlan (Expected)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BillingPlan_R__c</fullName>
        <label>BillingPlan (Recoginized)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BillingPlan_TIV__c</fullName>
        <label>BillingPlan (Total Invoice Value)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deferred__c</fullName>
        <label>Deferred</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_User_GARN__c</fullName>
        <label>End User GARN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <label>End User Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Subsidiary_ID__c</fullName>
        <label>End User Subsidiary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FYM_R__c</fullName>
        <label>FYM (Recognized)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FYM_TIV__c</fullName>
        <label>FYM (Total Invoice Value)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FYM_U__c</fullName>
        <label>FYM (Upside)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Forecast_Status__c</fullName>
        <label>Forecast Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incremental_E__c</fullName>
        <label>Incremental (Expected)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incremental_R__c</fullName>
        <label>Incremental (Recognized)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incremental_TIV__c</fullName>
        <label>Incremental (Total Invoice Value)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incremental_U__c</fullName>
        <label>Incremental (Upside)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maintenance_End_Date__c</fullName>
        <label>Maintenance End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maintenance_Start_Date__c</fullName>
        <label>Maintenance Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Month_Text__c</fullName>
        <externalId>true</externalId>
        <label>Month Text</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <externalId>true</externalId>
        <label>Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offering_Type__c</fullName>
        <externalId>true</externalId>
        <label>Offering Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Posting_Date__c</fullName>
        <label>Posting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quarter_Text__c</fullName>
        <externalId>true</externalId>
        <label>Quarter Text</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <externalId>true</externalId>
        <label>Quarter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recognized__c</fullName>
        <label>Recognized</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reference_Opportunity__c</fullName>
        <label>Reference Opportunity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Order__c</fullName>
        <label>Reference Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Quote__c</fullName>
        <label>Reference Quote</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Service_Contract__c</fullName>
        <label>Reference Service Contract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <externalId>true</externalId>
        <label>Revenue Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_GARN__c</fullName>
        <label>Sold To GARN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <label>Sold To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Subsidiary_ID__c</fullName>
        <label>Sold To Subsidiary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Booking_Forecast_E__c</fullName>
        <label>Total_Booking_Forecast (Expected)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Booking_Forecast_U__c</fullName>
        <label>Total_Booking_Forecast (Upside)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_Text__c</fullName>
        <externalId>true</externalId>
        <label>Year Text</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <externalId>true</externalId>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GCF Report Data</label>
    <nameField>
        <displayFormat>CGF#{0000000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCF Report Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NetSuite_Report_Data_Last_Imported__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to store when is the last time NetSuite Report Data is Imported</description>
    <fields>
        <fullName>Imported_Date__c</fullName>
        <label>Imported Date</label>
        <type>Date</type>
    </fields>
    <label>NetSuite Report Data Last Imported</label>
</CustomObject>

classes/GCFCopyNetSuiteReportData.cls
global class GCFCopyNetSuiteReportData implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT End_User_Name__c, End_User_GARN_Code__c, End_User_Subsidiary_ID__c, Sold_To_Name__c, Sold_To_GARN_Code__c, Sold_To_Subsidiary_ID__c, '
					 + 'Revenue_Type__c, Region__c, Quote_Number__c, Order_Number__c, Posting_Amount__c, Posting_Amount_USD__c, Posting_Date__c, Status__c, '
					 + 'Posting_Month_Formula__c, Posting_Quarter_Formula__c, Posting_Year_Formula__c, Maintenance_Start_Date__c, Maintenance_End_Date__c, Offering_Type__c, Offering_Type_Formula__c '
        			 + 'FROM GCF_NetSuite_Data__c WHERE Offering_Type_Formula__c IN (\'PureEngage\', \'PureConnect\') ';
     
        if(Test.isRunningTest())
            query = query + ' LIMIT 10';
        return Database.getQueryLocator(query);
    }
	
	global void execute (Database.BatchableContext bc , List<sObject> scope){
    	List<GCF_Report_Data__c> gcfReportData = new List<GCF_Report_Data__c>();
    	for(sObject so : scope){
    		GCF_NetSuite_Data__c inputObj = (GCF_NetSuite_Data__c)so;
    		GCF_Report_Data__c outputObj = new GCF_Report_Data__c();
    		
    		outputObj.Incremental_R__c = 0.0;
    		outputObj.Incremental_E__c = 0.0;
    		outputObj.Incremental_U__c = 0.0;
    		outputObj.Incremental_TIV__c = 0.0;
    		outputObj.FYM_R__c = 0.0;
    		outputObj.FYM_U__c = 0.0;
    		outputObj.FYM_TIV__c = 0.0;
    		outputObj.BillingPlan_R__c = 0.0;
    		outputObj.BillingPlan_E__c = 0.0;
    		outputObj.BillingPlan_TIV__c = 0.0;
    		outputObj.Total_Booking_Forecast_E__c = 0.0;
    		outputObj.Total_Booking_Forecast_U__c = 0.0;
			outputObj.Deferred__c = inputObj.Revenue_Type__c == 'Deferred Revenue' ? inputObj.Posting_Amount__c : 0.0;
			outputObj.Recognized__c = inputObj.Revenue_Type__c == 'Recognized Revenue' ? inputObj.Posting_Amount__c : 0.0;

    		outputObj.Revenue_Type__c = inputObj.Revenue_Type__c;
    		outputObj.Region__c = inputObj.Region__c;
    		outputObj.Posting_Date__c = inputObj.Posting_Date__c;
    		outputObj.Maintenance_Start_Date__c = inputObj.Maintenance_Start_Date__c;
    		outputObj.Maintenance_End_Date__c = inputObj.Maintenance_End_Date__c;
    		outputObj.Month__c = Integer.valueOf(inputObj.Posting_Month_Formula__c);
    		outputObj.Month_Text__c = ''+Integer.valueOf(inputObj.Posting_Month_Formula__c);
    		outputObj.Quarter__c = Integer.valueOf(inputObj.Posting_Quarter_Formula__c);
    		outputObj.Quarter_Text__c = ''+Integer.valueOf(inputObj.Posting_Quarter_Formula__c);
    		outputObj.Year__c = Integer.valueOf(inputObj.Posting_Year_Formula__c);
    		outputObj.Year_Text__c = ''+Integer.valueOf(inputObj.Posting_Year_Formula__c);
    		outputObj.Reference_Opportunity__c = null;
    		outputObj.Reference_Service_Contract__c = null;
    		outputObj.Reference_Quote__c = inputObj.Quote_Number__c;
    		outputObj.Reference_Order__c = inputObj.Order_Number__c;
    		outputObj.End_User_Name__c  = inputObj.End_User_Name__c;
    		outputObj.End_User_GARN__c = inputObj.End_User_GARN_Code__c;
    		outputObj.End_User_Subsidiary_ID__c = inputObj.End_User_Subsidiary_ID__c;
    		outputObj.Sold_To_Name__c = inputObj.Sold_To_Name__c;
    		outputObj.Sold_To_GARN__c = inputObj.Sold_To_GARN_Code__c;
    		outputObj.Sold_To_Subsidiary_ID__c = inputObj.Sold_To_Subsidiary_ID__c;
    		outputObj.Forecast_Status__c = inputObj.Status__c;
    		outputObj.Offering_Type__c = inputObj.Offering_Type_Formula__c;
    		gcfReportData.add(outputObj);
    	}
    	Database.insert(gcfReportData);
    }
    
    global void finish(Database.BatchableContext bc){
    	GCF_NetSuite_Data__c netSuiteData = [SELECT CreatedDate FROM GCF_NetSuite_Data__c ORDER BY ID DESC LIMIT 1];
		Date maxDate = netSuiteData != NULL ? netSuiteData.CreatedDate.date() : Date.Today();
		List<NetSuite_Report_Data_Last_Imported__c> lastImportedDateList = [SELECT id, Name, Imported_Date__c FROM NetSuite_Report_Data_Last_Imported__c];
		
		if(lastImportedDateList.isEmpty()){
		    lastImportedDateList.add(new NetSuite_Report_Data_Last_Imported__c(Name='LastImported',Imported_Date__c = maxDate));
		} else {
		    lastImportedDateList[0].Imported_Date__c = maxDate;
		}
		Database.upsert(lastImportedDateList);
    }
}