objects/GCR__c.object
<CustomObject>
    <fields>
        <fullName>GCR_Content_Document_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCR Content Document Detail</label>
        <referenceTo>GCR_Content_Document_Detail__c</referenceTo>
        <relationshipName>GCRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-New</fullName>
                </value>
                <value>
                    <fullName>2-Assigned to Attorney</fullName>
                </value>
                <value>
                    <fullName>3-In Progress</fullName>
                </value>
                <value>
                    <fullName>4-Approved By Legal</fullName>
                </value>
                <value>
                    <fullName>5-Pending Finance Approval</fullName>
                </value>
                <value>
                    <fullName>6-Approved by Finance</fullName>
                </value>
                <value>
                    <fullName>7-Rejected by Finance</fullName>
                </value>
                <value>
                    <fullName>8-Metadata Complete</fullName>
                </value>
                <value>
                    <fullName>9-Signed by Genesys</fullName>
                </value>
                <value>
                    <fullName>10-Completed</fullName>
                </value>
                <value>
                    <fullName>12-Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Legal Contract Request</label>
    <nameField>
        <displayFormat>Legal Request -{000000}</displayFormat>
        <label>Legal Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legal Contract Requests(New)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/GCR_Content_Document_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>GCR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCR</label>
        <referenceTo>GCR__c</referenceTo>
        <relationshipName>GCR_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>Contracts - {000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GCR_Content_Document_Detail_Approval__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Add_Approvers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Add Approvers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Submission_Counter__c</fullName>
        <label>Approval Submission Counter</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Rejected_Date__c</fullName>
        <label>Approved/Rejected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GCR_Content_Document_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCR Content Document Detail</label>
        <referenceTo>GCR_Content_Document_Detail__c</referenceTo>
        <relationshipLabel>GCR Content Document Detail Approvals</relationshipLabel>
        <relationshipName>GCR_Content_Document_Detail_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GCR__c</fullName>
        <formula>GCR_Content_Document_Detail__r.GCR__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GCR</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In-Active</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>DateTime</type>
    </fields>
    <label>GCR Content Document Detail Approval</label>
    <nameField>
        <displayFormat>GCRA-{00000}</displayFormat>
        <label>GCR Content Document Detail Approval Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCR Content Document Detail Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/GCRVFEmailRelatedListsController.cls
//Naresh Kumar  01/04/2015
public without sharing class GCRVFEmailRelatedListsController {

  public Boolean showNotes {get;set;}
  public Boolean showAttachments {get;set;}
  public Boolean showDocStatus {get;set;}
  public String gcrId {get;set;}
  public String currentOrgURL {get;set;}
  public Boolean isApprovalTemplate {get;set;}
  public String approvalDocumentId {get;set;}
  public Boolean showApprovalHistory {get;set;}
  List<GCR_Content_Document_Detail__c> lastestDocument;
  public String overAllStatus {get;set;}
  public GCRVFEmailRelatedListsController(){
    showNotes = true;
    showAttachments = true;
    showDocStatus = true;
    showApprovalHistory = true;
    currentOrgURL = URL.getSalesforceBaseUrl().toExternalForm();
  }
  
  public List<Note> getNotes(){
    List<Note> notes = [SELECT id, body, title, createdDate FROM Note WHERE parentId =: gcrId Order BY CreatedDate DESC];
    if(notes.isEmpty())
      showNotes = false;
    return notes;
  }
  
  public List<wrapperDocuments> getDocuments(){
    if(lastestDocument == null)
      lastestDocument = [SELECT id FROM GCR_Content_Document_Detail__c WHERE GCR__c =: gcrId ORDER BY CreatedDate DESC LIMIT 1];
    List<wrapperDocuments> attachments = new List<wrapperDocuments>();
    if(!lastestDocument.isEmpty()){
      Map<Id, dsfs__DocuSign_Status__c> mapIdVsDocusignStatus = new Map<Id, dsfs__DocuSign_Status__c>([SELECT id FROM dsfs__DocuSign_Status__c 
      WHERE GCR_Content_Document__c =: lastestDocument[0].id]); 
      List<Attachment> atts = [SELECT Name, CreatedBy.Name, CreatedDate, parentId FROM Attachment 
        WHERE parentId =: lastestDocument[0].id OR parentId IN : mapIdVsDocusignStatus.keyset()
        ORDER BY CreatedDate DESC];
      Integer counter = 1;
          for(Attachment eachAtt : atts){
              wrapperDocuments newAtt = new wrapperDocuments();
              newAtt.att = eachAtt;
              if(mapIdVsDocusignStatus.keyset().contains(eachAtt.parentId) && counter == 1)
                  newAtt.isFinal = true;
              else
                  newAtt.isFinal = false;         
              attachments.add(newAtt);
              counter ++;
          }          
    }
    if(attachments.isEmpty())
        showAttachments = false;
    return attachments;
  }
  
  public List<dsfs__DocuSign_Recipient_Status__c> getDocusignRecpDisplay() {
    if(lastestDocument == null)
      lastestDocument = [SELECT id FROM GCR_Content_Document_Detail__c WHERE GCR__c =: gcrId ORDER BY CreatedDate DESC LIMIT 1];
    List<dsfs__DocuSign_Recipient_Status__c> docusignRecp  = new List<dsfs__DocuSign_Recipient_Status__c>();
       List <dsfs__DocuSign_Status__c>  docusignStatus = new List <dsfs__DocuSign_Status__c>();
       
       if(!lastestDocument.isEmpty()) {
          docusignStatus = [SELECT id FROM dsfs__DocuSign_Status__c WHERE GCR_Content_Document__c= : lastestDocument[0].id ];
         if( docusignStatus.isEmpty()) {
             showDocStatus = false;    
          }
          else { 
             docusignRecp = [SELECT id,dsfs__DocuSign_Recipient_Email__c,dsfs__Date_Sent__c,dsfs__Date_Delivered__c,
               dsfs__Recipient_Status__c,dsfs__Date_Signed__c FROM dsfs__DocuSign_Recipient_Status__c WHERE dsfs__Parent_Status_Record__c in : docusignStatus];
          }
       }
       if(docusignRecp.isEmpty())
          showDocStatus = false;
       
        return docusignRecp ;
   }
   
   public List<GCRContentDocApprovalHistoryController.historyWrapper> getApprovals(){
     if(approvalDocumentId == null)
       return null;
     GCR_Content_Document_Detail__c gcrDocument = [SELECT Approval_Status__c, GCR__c FROM GCR_Content_Document_Detail__c WHERE id =: approvalDocumentId];
    gcrId = gcrDocument.GCR__c;
    if(gcrDocument.Approval_Status__c == GCRContentDocumentApprovalUtil.STATUS_PENDING)
      overAllStatus = GCRContentDocumentApprovalUtil.STATUS_PENDING;
    else if(gcrDocument.Approval_Status__c == GCRContentDocumentApprovalUtil.STATUS_PENDING)
      overAllStatus = GCRContentDocumentApprovalUtil.STATUS_REJECTED;
    else 
      overAllStatus = GCRContentDocumentApprovalUtil.STATUS_APPROVED;
    
    //Getting quote approval records with related fields
    List<GCR_Content_Document_Detail_Approval__c>  gcrDocumentApprovals = [SELECT id, Status__c, Approved_Rejected_Date__c,
    Comments__c,Owner.Name, GCR_Content_Document_Detail__r.Approval_Status__c, Submitted_Date__c, Order__c,
    Allow_Add_Approvers__c, Approval_Submission_Counter__c  FROM GCR_Content_Document_Detail_Approval__c
    WHERE GCR_Content_Document_Detail__c =: approvalDocumentId ORDER BY Order__c DESC];
    
    //Making sure of hiding section if there is no approval record
    if(gcrDocumentApprovals.isEmpty())
      showApprovalHistory = false;
    else
      showApprovalHistory = true;
    //Initializing wrapper list  
    List<GCRContentDocApprovalHistoryController.historyWrapper> approvals = new List<GCRContentDocApprovalHistoryController.historyWrapper>();  
    Integer counter = 1;  
    //Looping over all quote approval record 
    for(GCR_Content_Document_Detail_Approval__c eachGCRDocumentApproval : gcrDocumentApprovals){      
      GCRContentDocApprovalHistoryController.historyWrapper newRecord = new GCRContentDocApprovalHistoryController.historyWrapper();
      if(eachGCRDocumentApproval.Submitted_Date__c != null)
        newRecord.submittedDate = eachGCRDocumentApproval.Submitted_Date__c.format();
      if(eachGCRDocumentApproval.Approved_Rejected_Date__c != null)
        newRecord.approvalRejectDate = eachGCRDocumentApproval.Approved_Rejected_Date__c.format();
      newRecord.approvalRecord = eachGCRDocumentApproval;   
      //Applying css style depending on status
      if(eachGCRDocumentApproval.Status__c == GCRContentDocumentApprovalUtil.STATUS_APPROVED)
        newRecord.statusClass = 'approved';
      else if(eachGCRDocumentApproval.Status__c == GCRContentDocumentApprovalUtil.STATUS_REJECTED)
        newRecord.statusClass = 'rejected';
      newRecord.showAction = false;
      newRecord.rowType = 'detail';
      approvals.add(newRecord);
      counter ++;
    }  
    /*
    if(overAllStatus == null)
      overAllStatus = GCRContentDocumentApprovalUtil.STATUS_APPROVED;  
    */
    return approvals;
   }
   
   
  
  public class wrapperDocuments {
    public Attachment att {get;set;}
    public Boolean isFinal {get;set;}  
  }
}