objects/GCR__c.object
<CustomObject>
    <fields>
        <fullName>CCDB_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? CCDB - Store the Original CCDB for Amend requests 
Downstream Impact? CCDB 
Which department is owner? IT/CSM</description>
        <label>CCDB/Subscription</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select Subscriptions related to the Account selected.</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Legal Contract Requests(New)</relationshipLabel>
        <relationshipName>Legal_Contract_Requests_New</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Expiration_Date__c</fullName>
        <label>Contract Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Request_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>Self-Service</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>New Contract</fullName>
                </value>
                <value>
                    <fullName>General Inquiry</fullName>
                </value>
                <value>
                    <fullName>Standard NDA/MSLSA</fullName>
                </value>
                <value>
                    <fullName>Self Service MSLA</fullName>
                </value>
                <value>
                    <fullName>Partner Contract</fullName>
                </value>
                <value>
                    <fullName>Privacy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GCR_Content_Document_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCR Content Document Detail</label>
        <referenceTo>GCR_Content_Document_Detail__c</referenceTo>
        <relationshipName>GCRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Exceptions__c</fullName>
        <description>What it does? Stores the legal exceptions of the contract . Downstream Impact?Reporting. Which Department is Owner? Finance</description>
        <label>Legal Exceptions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legal_Deal_Review</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>GCRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                    <default>true</default>
                    <label>Sales</label>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                </value>
                <value>
                    <fullName>Data Privacy / Information Security</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-New</fullName>
                </value>
                <value>
                    <fullName>2-Assigned to Attorney</fullName>
                </value>
                <value>
                    <fullName>3-In Progress</fullName>
                </value>
                <value>
                    <fullName>4-Approved By Legal</fullName>
                </value>
                <value>
                    <fullName>5-Pending Finance Approval</fullName>
                </value>
                <value>
                    <fullName>6-Approved by Finance</fullName>
                </value>
                <value>
                    <fullName>7-Rejected by Finance</fullName>
                </value>
                <value>
                    <fullName>8-Metadata Complete</fullName>
                </value>
                <value>
                    <fullName>9-Signed by Genesys</fullName>
                </value>
                <value>
                    <fullName>10-Completed</fullName>
                </value>
                <value>
                    <fullName>12-Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Legal Contract Request</label>
    <nameField>
        <displayFormat>Legal Request -{000000}</displayFormat>
        <label>Legal Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legal Contract Requests(New)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/GCR_Content_Document_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Category__c</fullName>
        <label>Contract Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Amend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Renewal_Date__c</fullName>
        <label>Expiration/Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GCR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCR</label>
        <referenceTo>GCR__c</referenceTo>
        <relationshipName>GCR_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Governing_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Governing Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Exceptions__c</fullName>
        <description>What it Does? Review components for legal team 
Downstream Impact? Effects legal review process 
Which department is owner? Legal</description>
        <label>Legal Exceptions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legal_Deal_Review</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>Contracts - {000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subscription__c.object
<CustomObject>
    <description>To store subscription for different offering types</description>
    <fields>
        <fullName>Contract_Effective_Date__c</fullName>
        <description>What it does? Stores the contract effective date . Downstream Impact?Reporting. Which Department is Owner? Finance</description>
        <inlineHelpText>Date the agreement is considered to take effect.</inlineHelpText>
        <label>Governing Contract Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Expiration_Date__c</fullName>
        <description>What it does? Stores Contract Expiration Dates. Downstream Impact? Reporting. Which Department is Owner? Finance.</description>
        <inlineHelpText>Date the agreement is set to expire.</inlineHelpText>
        <label>Governing Contract Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Exceptions__c</fullName>
        <description>What it Does? Review components for legal team 
Downstream Impact? Effects legal review process 
Which department is owner? Legal</description>
        <inlineHelpText>Nonstandard or negotiated sections in the legal agreement.</inlineHelpText>
        <label>Governing Contract Legal Exceptions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legal_Deal_Review</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>What it Does? Stores opportunity sfdc id
Downstream Impact? Effects cloud deployment creation
Which department is owner? IT/PureCloud Team</description>
        <formula>IF(NOT(ISBLANK(Quote__c)), Quote__r.BigMachines__Opportunity__c, &quot;&quot;)</formula>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>What it Does? Captures the current status of this subscription
Downstream Impact? Effects reporting and integration with billing
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Current state of this CCDB/Subscription record.  NOTE: Only active CCDB/Subscription records can be amended or renewed.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Pending Product Deactivation</fullName>
                </value>
                <value>
                    <fullName>Do Not Use</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CCDB/Subscription</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>CCDB/Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCDBs/Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Legal_Deal_Review.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Anonymized Data Sharing Opt Out</fullName>
    </customValue>
    <customValue>
        <fullName>Background Checks</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Period</fullName>
    </customValue>
    <customValue>
        <fullName>Change in pricing, support guide, or user documentation notification</fullName>
    </customValue>
    <customValue>
        <fullName>Confidentiality</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Price Increases</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Specific Purchase Schedule</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Term Renewal Clause</fullName>
    </customValue>
    <customValue>
        <fullName>Conversion Rights</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Paper</fullName>
    </customValue>
    <customValue>
        <fullName>Custom Operating Model</fullName>
    </customValue>
    <customValue>
        <fullName>Discounts</fullName>
    </customValue>
    <customValue>
        <fullName>Free Product/Service Offered</fullName>
    </customValue>
    <customValue>
        <fullName>Future Product Discounts</fullName>
    </customValue>
    <customValue>
        <fullName>Includes Non-Material Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Information Security and Data Privacy</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance Requirements</fullName>
    </customValue>
    <customValue>
        <fullName>Language Support Requirement Exceptions</fullName>
    </customValue>
    <customValue>
        <fullName>Limit of Liability</fullName>
    </customValue>
    <customValue>
        <fullName>Outage Notifications</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Terms</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Change Management Notifications</fullName>
    </customValue>
    <customValue>
        <fullName>Ramp Period</fullName>
    </customValue>
    <customValue>
        <fullName>Rebates</fullName>
    </customValue>
    <customValue>
        <fullName>Record Retention Exceptions</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstatement Fees</fullName>
    </customValue>
    <customValue>
        <fullName>Right of Refund on Prepaid Amounts</fullName>
    </customValue>
    <customValue>
        <fullName>Root Cause Analysis Report Notifications</fullName>
    </customValue>
    <customValue>
        <fullName>SLA Exceptions</fullName>
    </customValue>
    <description>Review components for legal team. Used in Opportunity and CCDB</description>
    <masterLabel>Legal Deal Review</masterLabel>
</GlobalValueSet>

classes/ContractTtriggerHandler.cls
public class ContractTtriggerHandler{   
    
    /*
    * @author: Ashish Goyal (09/28/2018)
    * @desc: To Update the Prmiary Quote's Contract Type for the Governing Contract
    */
    
    public static void updateOpportunityDetails(List<GCR__c> newGCRList, Map<Id, GCR__c> oldMap){
        
        Set<Id> set_GCRIds = new Set<Id>();
        for(GCR__C objGCR : newGCRList){
            if(objGCR.status__C == '10-Completed' && (oldMap == null || oldMap.get(objGCR.Id).Status__c != objGCR.Status__c) && objGCR.Opportunity__c != null && objGCR.Request_Type__c== 'Sales')
                set_GCRIds.add(objGCR.Id);
        }
        
        Map<Id, List<GCR_Content_Document_Detail__c>> map_OpptyIdListContract = new Map<id, List<GCR_Content_Document_Detail__c>>();
        Map<Id, Set<String>> map_OpptyIdLegalExc = new Map<id, Set<String>>();
        Map<Id, String> map_OpptyIdContractType = new Map<id, String>();
        Map<Id, Opportunity> map_OpportunityToUpdate = new Map<Id, Opportunity>();
        
        if(set_GCRIds.size() > 0){
            Set<Id> set_OppIds = new Set<Id>();            
            for(GCR_Content_Document_Detail__c contractDetails : [SELECT Id, GCR__r.CCDB_Subscription__c, GCR__r.Opportunity__c, Is_Governing_Contract__c, Contract_Category__c, Legal_Exceptions__c, 
                                                                    GCR__r.CCDB_Subscription__r.Contract_Effective_Date__c, GCR__r.CCDB_Subscription__r.Contract_Expiration_Date__c, Effective_Date__c, Expiration_Renewal_Date__c, Contract_Type__c 
                                                                    FROM GCR_Content_Document_Detail__c 
                                                                    WHERE IsGoverningContract__c = true 
                                                                    AND (Contract_Category__c = 'New' OR Contract_Category__c = 'Amend')
                                                                    AND GCR__c IN: set_GCRIds]){
                if(contractDetails.Contract_Category__c == 'Amend' && contractDetails.GCR__r.CCDB_Subscription__c != null && contractDetails.Is_Governing_Contract__c){
                    Opportunity oppTemp = new Opportunity(id = contractDetails.GCR__r.Opportunity__c);
                    String legalEc = '';
                    legalEc = contractDetails.Legal_Exceptions__c;
                    if(legalEc != ''){
                        oppTemp.Legal_Exceptions__c = legalEc;
                        if(!legalEc.contains('None')){
                            oppTemp.MSA_Link__c = '';
                            oppTemp.MSA_Link_Type__c = 'Custom';
                        }
                        else{
                            oppTemp.MSA_Link_Type__c = 'Standard';
                        }
                    }  
                    oppTemp.Contract_Type__c = contractDetails.Contract_Type__c;
                    oppTemp.Contract_Expiration_Date__c = contractDetails.GCR__r.CCDB_Subscription__r.Contract_Expiration_Date__c;
                    oppTemp.Contract_Effective_Date__c = contractDetails.GCR__r.CCDB_Subscription__r.Contract_Effective_Date__c;
                    oppTemp.Is_Governing_Contract__c = true;
                    map_OpportunityToUpdate.put(contractDetails.GCR__r.Opportunity__c, oppTemp);
                }
                else{
                    if(!contractDetails.Is_Governing_Contract__c){
                        if(!map_OpptyIdListContract.containsKey(contractDetails.GCR__r.Opportunity__c)){
                            map_OpptyIdListContract.put(contractDetails.GCR__r.Opportunity__c, new List<GCR_Content_Document_Detail__c>());
                        }
                        map_OpptyIdListContract.get(contractDetails.GCR__r.Opportunity__c).add(contractDetails);
                    }
                    else{
                        if(!map_OpptyIdLegalExc.containsKey(contractDetails.GCR__r.Opportunity__c)){
                            map_OpptyIdLegalExc.put(contractDetails.GCR__r.Opportunity__c, new Set<String>());
                        }
                        map_OpptyIdLegalExc.get(contractDetails.GCR__r.Opportunity__c).add(contractDetails.Legal_Exceptions__c);
                    }
                    
                    if(!map_OpptyIdContractType.containsKey(contractDetails.GCR__r.Opportunity__c)){
                        map_OpptyIdContractType.put(contractDetails.GCR__r.Opportunity__c, contractDetails.Contract_Type__c);
                    }
                }
            }
        }
        
        if(map_OpptyIdListContract.size() > 0){   
            System.debug('---map_OpportunityToUpdate- before if--'+map_OpportunityToUpdate);         
            map_OpportunityToUpdate.putAll(updateOpportunity(map_OpptyIdListContract, map_OpptyIdContractType, true));
            System.debug('---map_OpportunityToUpdate---after if--'+map_OpportunityToUpdate);
        }
        
        if(map_OpptyIdLegalExc.size() > 0){
            
            // Appropriate field needs to be mapped for the Quote for the Effective and Expiration Date. 
            
            for(Id opptyId : map_OpptyIdLegalExc.keySet()){
                Opportunity tempOpp = new Opportunity(Id = opptyId);
                tempOpp.Contract_Type__c = map_OpptyIdContractType.get(opptyId);
                String legalEc = '';
                
                if(map_OpportunityToUpdate.containsKey(opptyId)){
                    legalEc = map_OpportunityToUpdate.get(opptyId).Legal_Exceptions__c + ';';
                }
                
                for(String legalExc : map_OpptyIdLegalExc.get(opptyId)){
                    for(String legal : legalExc.split(';')){
                        if(!legalEc.contains(legal)){
                            legalEc += legal + ';';
                        }                    
                    }
                }
                if(legalEc != ''){
                    legalEc = legalEc.removeEnd(';');
                    tempOpp.Legal_Exceptions__c = legalEc;
                    if(!legalEc.contains('None')){
                        tempOpp.MSA_Link__c = '';
                        tempOpp.MSA_Link_Type__c = 'Custom';
                    }
                    else{
                        tempOpp.MSA_Link_Type__c = 'Standard';
                    }
                }                
                tempOpp.Is_Governing_Contract__c = true;
                if(map_OpportunityToUpdate.containsKey(opptyId)){
                    map_OpportunityToUpdate.get(opptyId).Legal_Exceptions__c = tempOpp.Legal_Exceptions__c;
                }
                else{
                    map_OpportunityToUpdate.put(opptyId, tempOpp);
                }
            }
            
            for(BigMachines__Quote__c quoteObj : [SELECT Id, BigMachines__Opportunity__c, Contract_Signature_Date__c, Subscription_End_Date__c 
                                                    FROM BigMachines__Quote__c 
                                                    WHERE BigMachines__Is_Primary__c = true AND BigMachines__Opportunity__c IN: map_OpptyIdLegalExc.keySet()]){
                
                Opportunity tempOpp = new Opportunity(Id = quoteObj.BigMachines__Opportunity__c);
                tempOpp.Contract_Effective_Date__c = Date.valueOf(quoteObj.Contract_Signature_Date__c);
                tempOpp.Contract_Expiration_Date__c = quoteObj.Subscription_End_Date__c;
                
                if(map_OpportunityToUpdate.containsKey(quoteObj.BigMachines__Opportunity__c)){
                    if(map_OpportunityToUpdate.get(quoteObj.BigMachines__Opportunity__c).Contract_Effective_Date__c  == null || 
                            map_OpportunityToUpdate.get(quoteObj.BigMachines__Opportunity__c).Contract_Effective_Date__c < tempOpp.Contract_Effective_Date__c){
                        map_OpportunityToUpdate.get(quoteObj.BigMachines__Opportunity__c).Contract_Effective_Date__c = tempOpp.Contract_Effective_Date__c;
                    }
                    if(map_OpportunityToUpdate.get(quoteObj.BigMachines__Opportunity__c).Contract_Expiration_Date__c == null ||
                            map_OpportunityToUpdate.get(quoteObj.BigMachines__Opportunity__c).Contract_Expiration_Date__c < tempOpp.Contract_Expiration_Date__c){
                        map_OpportunityToUpdate.get(quoteObj.BigMachines__Opportunity__c).Contract_Expiration_Date__c = tempOpp.Contract_Expiration_Date__c;
                    }
                }else{
                    map_OpportunityToUpdate.put(quoteObj.BigMachines__Opportunity__c, tempOpp);
                }
            }
        }
            
        if(map_OpportunityToUpdate.size() > 0){
            System.debug('---map_OpportunityToUpdate---'+map_OpportunityToUpdate);
            update map_OpportunityToUpdate.values();
        }
        
        if(set_GCRIds.size() > 0){
            Map<Id, Opportunity> map_OpportunityToUp = new Map<Id, Opportunity>();
            Set<Id> set_OppIds = new Set<Id>(); 
            Set<Id> set_RampGCR = new Set<Id>();
            for(GCR__c objGCR : [SELECT Id, (SELECT Id FROM GCR_Details__r WHERE Contract_Category__c = 'Amend' AND Contract_Type__c = 'Service Order' AND Legal_Exceptions__c INCLUDES ('Ramp Period')) FROM GCR__C WHERE Id IN :set_GCRIds ]){
                if(objGCR.GCR_Details__r.size() > 0){
                    set_RampGCR.add(objGCR.Id);
                }
            }
            if(set_RampGCR.size() > 0){
                Map<Id, List<GCR_Content_Document_Detail__c>> map_OpptyIdListContractOthr = new Map<Id, List<GCR_Content_Document_Detail__c>>();
                for(GCR_Content_Document_Detail__c contractDetails : [SELECT Id, GCR__r.Opportunity__c, Legal_Exceptions__c, Expiration_Renewal_Date__c 
                                                                        FROM GCR_Content_Document_Detail__c 
                                                                        WHERE GCR__c IN: set_RampGCR]){
                    if(!map_OpptyIdListContractOthr.containsKey(contractDetails.GCR__r.Opportunity__c)){
                        map_OpptyIdListContractOthr.put(contractDetails.GCR__r.Opportunity__c, new List<GCR_Content_Document_Detail__c>());
                    }
                    map_OpptyIdListContractOthr.get(contractDetails.GCR__r.Opportunity__c).add(contractDetails);
                }
                if(map_OpptyIdListContractOthr.size() > 0){                    
                    map_OpportunityToUp = updateOpportunity(map_OpptyIdListContractOthr, new Map<Id, String>(), false);
                }
            }
            if(map_OpportunityToUp.size() > 0){
                update map_OpportunityToUp.values();
            }
        }
    }
    
    
    private static Map<Id, Opportunity> updateOpportunity(Map<Id, List<GCR_Content_Document_Detail__c>> map_OpptyIdListContract, Map<Id, String> map_OpptyIdContractType, boolean isAll){
        Map<Id, Opportunity> list_OpportunityToUpdate = new Map<Id, Opportunity>();
        for(Id oppId : map_OpptyIdListContract.keySet()){
            Opportunity tempOpp = new Opportunity(Id = oppId);
            String legalEc = '';
            for(GCR_Content_Document_Detail__c contrct : map_OpptyIdListContract.get(oppId)){
                if(isAll && (tempOpp.Contract_Effective_Date__c == null || tempOpp.Contract_Effective_Date__c <= contrct.Effective_Date__c)){
                    tempOpp.Contract_Effective_Date__c = contrct.Effective_Date__c;
                }
                if(tempOpp.Contract_Expiration_Date__c == null || tempOpp.Contract_Expiration_Date__c <= contrct.Expiration_Renewal_Date__c){
                    tempOpp.Contract_Expiration_Date__c = contrct.Expiration_Renewal_Date__c;
                }
                
                if(contrct.Legal_Exceptions__c != null){
                    for(String legal : contrct.Legal_Exceptions__c.split(';')){
                        if(!legalEc.contains(legal)){
                            legalEc += legal + ';';
                        }
                    }
                    legalEc = legalEc.removeEnd(';');
                }                
            }
            if(legalEc != ''){
                tempOpp.Legal_Exceptions__c = legalEc;
                if(!legalEc.contains('None')){
                    tempOpp.MSA_Link__c = '';
                    tempOpp.MSA_Link_Type__c = 'Custom';
                }
                else{
                    tempOpp.MSA_Link_Type__c = 'Standard';
                }
            }
            tempOpp.Is_Governing_Contract__c = true;
            
            if(isAll){
                tempOpp.Contract_Type__c = map_OpptyIdContractType.get(oppId);
            }
            list_OpportunityToUpdate.put(oppId, tempOpp);
        }
        return list_OpportunityToUpdate;
    }
}