objects/GCR_Content_Document_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GCR_Content_Document_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adoption Agreement</fullName>
                </value>
                <value>
                    <fullName>Alliance Agreement</fullName>
                </value>
                <value>
                    <fullName>Assignment Agreement</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Business Associate Agreement</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Consulting Agreement</fullName>
                </value>
                <value>
                    <fullName>Correspondence</fullName>
                </value>
                <value>
                    <fullName>Distribution Agreement</fullName>
                </value>
                <value>
                    <fullName>Escrow Agreement</fullName>
                </value>
                <value>
                    <fullName>Evaluation Agreement</fullName>
                </value>
                <value>
                    <fullName>Interoperability Agreement</fullName>
                </value>
                <value>
                    <fullName>Joint Development Agreement</fullName>
                </value>
                <value>
                    <fullName>Joint Marketing Agreement</fullName>
                </value>
                <value>
                    <fullName>Letter of Engagement</fullName>
                </value>
                <value>
                    <fullName>Letter of Intent</fullName>
                </value>
                <value>
                    <fullName>Maintenance Agreement</fullName>
                </value>
                <value>
                    <fullName>Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>Master Subscription Agreement</fullName>
                </value>
                <value>
                    <fullName>Memorandum of Understanding</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Agreement</fullName>
                </value>
                <value>
                    <fullName>OEM (Original Equipment Manufacturer)</fullName>
                </value>
                <value>
                    <fullName>Participation Agreement</fullName>
                </value>
                <value>
                    <fullName>Pre-Release</fullName>
                </value>
                <value>
                    <fullName>PS Agreement (for Clients)</fullName>
                </value>
                <value>
                    <fullName>Schedule</fullName>
                </value>
                <value>
                    <fullName>Service Order</fullName>
                </value>
                <value>
                    <fullName>Statement of Work</fullName>
                </value>
                <value>
                    <fullName>Teaming Agreement</fullName>
                </value>
                <value>
                    <fullName>MSLSA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Renewal_Date__c</fullName>
        <label>Expiration/Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Finance_Comments__c</fullName>
        <label>Finance Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>GCR_Content_Document_Folder__c</referenceTo>
        <relationshipName>GCR_Content_Document_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maint_SLA__c</fullName>
        <label>Maintenance SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Non-Standard</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Maintenance_Rate__c</fullName>
        <label>Maintenance Rate</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Maintenance_Type__c</fullName>
        <label>Maintenance Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Care</fullName>
                </value>
                <value>
                    <fullName>Premium Care</fullName>
                </value>
                <value>
                    <fullName>Flex Care</fullName>
                </value>
                <value>
                    <fullName>Cloud Care</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Net30</fullName>
                </value>
                <value>
                    <fullName>Net45</fullName>
                </value>
                <value>
                    <fullName>Net60</fullName>
                </value>
                <value>
                    <fullName>Net90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Penalties__c</fullName>
        <label>Penalties</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Terms__c</fullName>
        <label>Pricing Terms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Services_Covered_by_Contract1__c</fullName>
        <label>Product/Services Covered by Contract</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Cloud/Hosted</fullName>
                </value>
                <value>
                    <fullName>Saas</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>Cloud SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipping_Terms__c</fullName>
        <label>Shipping Terms</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Warranty_Period_Start__c</fullName>
        <label>Warranty Period Start Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Software Delivery</fullName>
                </value>
                <value>
                    <fullName>PS Delivery</fullName>
                </value>
                <value>
                    <fullName>PS Acceptance</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contracts</label>
    <nameField>
        <displayFormat>Contracts - {000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GCR_Content_Document_Folder__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <label>Contracts Folders</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GCR Content Document Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DocuSignMainTriggerHelper.cls
//Naresh Kumar 04/04/2014
public with sharing class DocuSignMainTriggerHelper {
    
    public static void generateServiceContract(Map<id, dsfs__DocuSign_Status__c> newMap, Map<id, dsfs__DocuSign_Status__c> oldMap){
        Set<Id> quoteIds = new Set<Id>();
        for(dsfs__DocuSign_Status__c eachDSStatus : newMap.values()){
            if(eachDSStatus.dsfs__Envelope_Status__c == 'Completed' 
                && (oldMap == null || oldMap.get(eachDSStatus.id).dsfs__Envelope_Status__c != 'Completed')){
                quoteIds.add(eachDSStatus.Quote__c);
            }
        }   
        if(!quoteIds.isEmpty()) {
            //CloudQuoteUtil.createServiceContract(quoteIds); 
           }
    }
    
    public static void updateGCRContentDocument(Attachment newAttachment){
        System.debug('NKC debug newAttachment.Name ['+newAttachment.Name+']');
        if(  newAttachment.Name.startsWith('Services Order') || newAttachment.Name.startsWith(GCRContentDocumentDetailsContHelper.NDA) 
            || newAttachment.Name.startsWith(GCRContentDocumentDetailsContHelper.MSLSA) ){
            Id docuSignStatusRecordId = newAttachment.parentId;
            Schema.SObjectType token = docuSignStatusRecordId.getSObjectType();
            Schema.DescribeSObjectResult dr = token.getDescribe();
            System.debug('NKC debug dr.getName() ['+dr.getName()+']');
            if(dr.getName() == 'dsfs__DocuSign_Status__c'){
                dsfs__DocuSign_Status__c currentDocuSignStatusRecord =  [SELECT dsfs__Company__c,GCR_Content_Document__c, dsfs__Envelope_Status__c FROM dsfs__DocuSign_Status__c WHERE id =: docuSignStatusRecordId ];
                if(currentDocuSignStatusRecord.dsfs__Envelope_Status__c == 'Completed'){
                    List<GCR_Content_Document_Folder__c> masterAgreementFolder = [SELECT id FROM GCR_Content_Document_Folder__c 
                    WHERE Name =: GCRContentDocumentDetailsContHelper.MASTER_AGREEMENT_FOLDER];             
                    GCR_Content_Document_Detail__c gcrDocumentToBeUpdated;
                     dsfs__DocuSign_Status__c currentDocuSignStatusRecordToUpdate;
                    if(currentDocuSignStatusRecord.GCR_Content_Document__c != null && currentDocuSignStatusRecord.GCR_Content_Document__c <>'')  {
                     gcrDocumentToBeUpdated = new GCR_Content_Document_Detail__c(id = currentDocuSignStatusRecord.GCR_Content_Document__c);
                    }
                    else  {
                     gcrDocumentToBeUpdated = new GCR_Content_Document_Detail__c();
                     currentDocuSignStatusRecordToUpdate = new  dsfs__DocuSign_Status__c(id = docuSignStatusRecordId);
                     currentDocuSignStatusRecordToUpdate.GCR_Content_Document__c =  gcrDocumentToBeUpdated.id;
                     System.debug('VIK' + gcrDocumentToBeUpdated.id);
                    }
                   
                    
                    gcrDocumentToBeUpdated.Document_Name__c = newAttachment.Name;               
                    gcrDocumentToBeUpdated.Effective_Date__c = System.today();
                    if(!masterAgreementFolder.isEmpty())
                        gcrDocumentToBeUpdated.Folder__c = masterAgreementFolder[0].id; 
                    gcrDocumentToBeUpdated.Expiration_Renewal_Date__c = System.today().addMonths(12);
                    if(newAttachment.Name == GCRContentDocumentDetailsContHelper.MSLSA)
                        gcrDocumentToBeUpdated.Contract_Type__c = GCRContentDocumentDetailsContHelper.MSLSA_DEF;
                    else if(newAttachment.Name == GCRContentDocumentDetailsContHelper.NDA)
                        gcrDocumentToBeUpdated.Contract_Type__c = GCRContentDocumentDetailsContHelper.NDA_DEF;
                    gcrDocumentToBeUpdated.SLA__c = 'N/A';
                    gcrDocumentToBeUpdated.Maint_SLA__c = 'Standard';
                    gcrDocumentToBeUpdated.Pricing_Terms__c = 'N/A';
                    gcrDocumentToBeUpdated.Shipping_Terms__c = 'None';
                    gcrDocumentToBeUpdated.Penalties__c = 'None';
                    gcrDocumentToBeUpdated.Warranty_Period_Start__c = 'Software Delivery';
                    gcrDocumentToBeUpdated.Product_Services_Covered_by_Contract1__c = 'Software;Professional Services;';
                    gcrDocumentToBeUpdated.Maintenance_Type__c = 'None';
                    gcrDocumentToBeUpdated.Payment_Terms__c = 'Net 30';
                    gcrDocumentToBeUpdated.Maintenance_Rate__c = '';
                    gcrDocumentToBeUpdated.Finance_Comments__c = 'Generated from Quote Approval';
                    gcrDocumentToBeUpdated.Account_Name__c= currentDocuSignStatusRecord.dsfs__Company__c; 
                    gcrDocumentToBeUpdated.Active__c = true;
                     
                    Database.upsertResult srList = Database.upsert(gcrDocumentToBeUpdated, false);
                                        
                    Id newUpsertId;
                
                      if(srList.isSuccess()){
                        newUpsertId= srList.getId();
                        
                     }
                   
                    System.debug('VIKNEUPSERT' + newUpsertId);
                                        
                    if((currentDocuSignStatusRecord.GCR_Content_Document__c == null || currentDocuSignStatusRecord.GCR_Content_Document__c == '') && newUpsertId!= null ) {
                     currentDocuSignStatusRecordToUpdate = new  dsfs__DocuSign_Status__c(id = docuSignStatusRecordId);
                     currentDocuSignStatusRecordToUpdate.GCR_Content_Document__c =  newUpsertId;
                     System.debug('VIKSSS' + newUpsertId + ' TTTT' + currentDocuSignStatusRecordToUpdate.id );
                     update currentDocuSignStatusRecordToUpdate;
                    }
                    
                   
                    
                }
            }       
        }
    }
    /*
    public static void updateGCRContentDocument(Map<id, dsfs__DocuSign_Status__c> newMap, Map<id, dsfs__DocuSign_Status__c> oldMap){
        dsfs__DocuSign_Status__c currentDocuSignStatusRecord;
        for(dsfs__DocuSign_Status__c eachDSStatus : newMap.values()){
            if(eachDSStatus.dsfs__Envelope_Status__c == 'Completed' 
                && (oldMap == null || oldMap.get(eachDSStatus.id).dsfs__Envelope_Status__c != 'Completed')){
                currentDocuSignStatusRecord = eachDSStatus;
                break;
            }
        }
        if(currentDocuSignStatusRecord == null || currentDocuSignStatusRecord.GCR_Content_Document__c == null)
            return;
        List<Attachment> atts = [SELECT id, Name FROM Attachment WHERE parentId =: currentDocuSignStatusRecord.id];
        if(atts.isEmpty())
            return;
        
        List<GCR_Content_Document_Folder__c> masterAgreementFolder = [SELECT id FROM GCR_Content_Document_Folder__c 
            WHERE Name =: GCRContentDocumentDetailsContHelper.MASTER_AGREEMENT_FOLDER]; 
        
        GCR_Content_Document_Detail__c gcrDocumentToBeUpdated = new GCR_Content_Document_Detail__c(id = currentDocuSignStatusRecord.GCR_Content_Document__c);
        gcrDocumentToBeUpdated.Document_Name__c = atts[0].Name;             
        gcrDocumentToBeUpdated.Effective_Date__c = System.today();
        if(!masterAgreementFolder.isEmpty())
            gcrDocumentToBeUpdated.Folder__c = masterAgreementFolder[0].id; 
        gcrDocumentToBeUpdated.Expiration_Renewal_Date__c = System.today().addMonths(12);
        if(atts[0].Name == GCRContentDocumentDetailsContHelper.MSLSA)
            gcrDocumentToBeUpdated.Contract_Type__c = GCRContentDocumentDetailsContHelper.MSLSA_DEF;
        else if(atts[0].Name == GCRContentDocumentDetailsContHelper.NDA)
            gcrDocumentToBeUpdated.Contract_Type__c = GCRContentDocumentDetailsContHelper.NDA_DEF;
        update gcrDocumentToBeUpdated;
        
    }
    */
}