objects/Genesys_Case_Updates__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The case to which this case update is linked.</description>
        <inlineHelpText>The case to which this case update is linked.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Updates</relationshipLabel>
        <relationshipName>Case_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_By_Name__c</fullName>
        <formula>CreatedBy.FirstName &amp; &quot; &quot; &amp; CreatedBy.LastName</formula>
        <label>Created By Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Make_Public__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls the visibility of the comment
If the checkbox is checked, then the comment can be viewed by customers via Portal
If the checkbox is not checked, the comment is internal-only</description>
        <inlineHelpText>Please select this box if you would like to make this update publicly visibile to customers/partners/pro-serv in the customer portal.</inlineHelpText>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Posted_On_Calc__c</fullName>
        <formula>IF (ISBLANK(Posted_Date__c),
     LastModifiedDate,
     Posted_Date__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Posted On Calc</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Info Required from Customer</fullName>
                </value>
                <value>
                    <fullName>Proposed Solution</fullName>
                </value>
                <value>
                    <fullName>Update to Customer</fullName>
                </value>
                <value>
                    <fullName>PS Update</fullName>
                </value>
                <value>
                    <fullName>Request to Re-open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Update</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Updates</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>This record type will track the private case comments</description>
        <label>Private</label>
    </recordTypes>
    <recordTypes>
        <fullName>Public</fullName>
        <active>true</active>
        <description>This record type will track the public case comments</description>
        <label>Public</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseUpdateRelatedListController.cls
/*
  Naresh Kumar
  05/15/2013
  Suman 10/09/13 Query and order by last modified date for case updates 
*/
public without sharing class CaseUpdateRelatedListController {
  String caseId {get;set;}
  public String selectedCUId {get;set;}
  public transient List<Genesys_Case_Updates__c> caseUpdates{get;set;}//ST 08/22/13 added transient to reduce viewstate
  public boolean caseClose {get;set;}
  public Case currentCase {get;set;}
  public String caseNumberField {get;set;}
  public String caseUpdatePrivateRecordTypeId {get;set;}
  public Boolean isReadOnlyProfile {get;set;}
  public Boolean isCaseAccessReadOnly {get; set; }
  
  public CaseUpdateRelatedListController(ApexPages.StandardController stdController){

/*remove after 4/12
 if ( ContactUtil.isSBContact() )  {	
  	  isReadOnlyProfile = true;
  	  isCaseAccessReadOnly = true;
 }
 else 
 ///end remove
*/
       isReadOnlyProfile = CaseUtil.isCurrentUserProfileReadOnly();
    
        caseId = stdController.getId();        
        currentCase = (Case)stdController.getRecord();        
        caseUpdates = new List<Genesys_Case_Updates__c>();
        caseNumberField = Label.Case_Update_CaseNumber_Field;
        RecordType rType = [SELECT id FROM RecordType WHERE DeveloperName = 'Private' AND SobjectType = 'Genesys_Case_Updates__c' LIMIT 1];
        caseUpdatePrivateRecordTypeId = rType.id;
        loadRecords();
        caseClosed();        
  }
  public CaseUpdateRelatedListController(){
    caseId = ApexPages.currentPage().getParameters().get('id');
    currentCase = [SELECT id, CaseNumber, Sold_To_Account__c, End_User_Account__c FROM Case WHERE id =: caseId];
    caseUpdates = new List<Genesys_Case_Updates__c>();        
        loadRecords();
        caseClosed(); 

/* remove after 4/12
 if ( ContactUtil.isSBContact() )  {	
  	  isReadOnlyProfile = true;
  	  isCaseAccessReadOnly = true;
 }
 else  {        
  ///end remove 
*/    
        isCaseAccessReadOnly = CaseUtil.isCaseAccessLevelReadOnly(currentCase);
        isReadOnlyProfile = CaseUtil.isCurrentUserProfileReadOnly();      
}
  
  public void caseClosed() {
    Case caseRecord = [Select id,Status from Case where id =:caseId];
    if(caseRecord != null && caseRecord.Status != null && caseRecord.Status =='Closed')
      caseClose = false; 
    else 
      caseClose = true;   
    
  }
  
  private void loadRecords(){    
    caseUpdates = [SELECT id, Name, Created_By_Name__c,Type__c, Status__c, Make_Public__c, Summary__c, CreatedDate, 
                          lastmodifieddate,Description__c,Posted_On_Calc__c
          FROM Genesys_Case_Updates__c WHERE Case__c =: caseId and Make_Public__c = true order by Posted_On_Calc__c desc ];
        System.debug('NKC debug caseUpdates ['+caseUpdates+']');
  }
  
  public void deleteCaseUpdate(){
        Genesys_Case_Updates__c gcu = new Genesys_Case_Updates__c(id = selectedCUId);
        try{
        delete gcu;
        }
        catch(Exception ex){
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'There is some error on the page. Info = '+ex.getMessage());
            ApexPages.addMessage(errorMessage);
        }
        loadRecords();
    }
    
}