objects/Global_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders(Revenue/Non-Revenue)</relationshipLabel>
        <relationshipName>End_User_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_End__c</fullName>
        <label>Maint. End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maintenance_Start__c</fullName>
        <label>Maint. Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_Cloud_Billing_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <description>What it Does ? Indicates that though this may be a Cloud Billing Order, it does not need a Cloud Billing Contract for monthly processing
Downstream Impact ? Prevents Order from being displayed in the Cloud Billing Landing Page for Contract Creation
Which department is owner ?  Cloud Billing/Finance</description>
        <inlineHelpText>Does not need a Cloud Billing Contract</inlineHelpText>
        <label>No Cloud Billing Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Numb_of_Maint_Months__c</fullName>
        <label># of Maint Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offering_Type__c</fullName>
        <formula>IF(CONTAINS(Quote__r.Offering_Type__c,&apos;Subscription&apos;), Quote__r.Offering_Type__c,

IF(Text(Opportunity__r.Lines_of_Businesses__c) == &apos;Business Edition&apos; &amp;&amp; 
(RecordType.Name == &apos;Cloud Billing Master Order&apos; || RecordType.Name == &apos;Cloud Monthly Billing Order&apos;),
&apos;PureEngage&apos;,  TEXT(Opportunity__r.Lines_of_Businesses__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offering Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order (Sold To)</relationshipLabel>
        <relationshipName>Sold_To_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subsidaries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subsidary</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Subsidary__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subsidary__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Synced_with_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Synced with Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Order_Trigger_Class_Test.cls
/*
Raghu R : 2/3/2014 : MDM Project : Test Class for the triger Order_Trigger and Order_Trigger_class.

Erik D : May 15 2018 tests for trigger Order_Trigger
*/
@isTest(SeeAllData=true)
public class Order_Trigger_Class_Test {
    
      static testMethod void onAfterUpdate_test_indirect_allSame()   
      {
      test.startTest();
       
      Account testAccount_1 = TestUtil.createAccounts(1, true)[0];
      Account testAccount_2 = TestUtil.createAccounts(1, true)[0];
      Global_Setting__c obj1;
      
      BigMachines__Quote__c testQuote = TestUtil.createQuotes(1, true)[0];   
      Opportunity testOpp = TestUtil.createOpportunities(1, true)[0];
      Order__c ord_1 = new Order__c();
      ord_1.Quote__c = testQuote.id;
      ord_1.Maintenance_Start__c = Date.today();
      ord_1.Maintenance_End__c = Date.today().addYears(1);
      ord_1.Opportunity__c = testOpp.id;
      ord_1.Numb_of_Maint_Months__c = 12;
      ord_1.End_User_Name__c = testAccount_1.id;
      ord_1.Sold_To_Name__c = testAccount_2.id;
      ord_1.status__c = 'In Progress';
      insert ord_1;
      test.stopTest();     
      Order__c ord_2 = new Order__c(Id=ord_1.id);
      ord_2.Subsidaries__c =  Global_Setting__c.getInstance('Japan').Id__c;
      ord_2.status__c = 'Approved';
      ord_2.End_User_Name__c = testAccount_1.id;
      ord_2.Sold_To_Name__c = testAccount_2.id;
      update ord_2; 
      
      Account_Order_Address__c ordAdr_1 = new Account_Order_Address__c();
      ordAdr_1.Address__c = 'Test1';
      ordAdr_1.Address2__c = 'Test1';
      ordAdr_1.Address_Type__c = 'Sold To';
      ordAdr_1.Order__c = ord_1.id;
      insert ordAdr_1;
      
      Account_Order_Address__c ordAdr_2 = new Account_Order_Address__c();
      ordAdr_2.Address__c = 'Test1';
      ordAdr_2.Address2__c = 'Test1';
      ordAdr_2.Address_Type__c = 'End User';
      ordAdr_2.Order__c = ord_1.id;
      insert ordAdr_2;
      
      Account_Order_Address__c ordAdr_3 = new Account_Order_Address__c();
      ordAdr_1.Address__c = 'Test1';
      ordAdr_1.Address2__c = 'Test1';
      ordAdr_1.Address_Type__c = 'Bill To';
      ordAdr_1.Order__c = ord_2.id;
      insert ordAdr_3;
      
      Account_Order_Address__c ordAdr_4 = new Account_Order_Address__c();
      ordAdr_2.Address__c = 'Test1';
      ordAdr_2.Address2__c = 'Test1';
      ordAdr_2.Address_Type__c = 'Ship To';
      ordAdr_2.Order__c = ord_2.id;
      insert ordAdr_4;
            
      Map<Id, Order__c> oldMap= new Map<Id, Order__c>{ord_1.Id => ord_1};
      Map<Id,Order__c> newMap= new Map<Id,Order__c>{ord_2.Id => ord_2}; 

      Order_Trigger_Class.onAfterUpdate(oldMap,newMap);
      
      
      }
      
      static testMethod void onAfterUpdate_test_indirect_alldiff()   
      {
      test.startTest();
       
      Account testAccount_1 = TestUtil.createAccounts(1, true)[0];
      Account testAccount_2 = TestUtil.createAccounts(1, true)[0];
      Global_Setting__c obj1;
      
      BigMachines__Quote__c testQuote = TestUtil.createQuotes(1, true)[0];   
      Opportunity testOpp = TestUtil.createOpportunities(1, true)[0];
      Order__c ord_1 = new Order__c();
      ord_1.Quote__c = testQuote.id;
      ord_1.Maintenance_Start__c = Date.today();
      ord_1.Maintenance_End__c = Date.today().addYears(1);
      ord_1.Opportunity__c = testOpp.id;
      ord_1.Numb_of_Maint_Months__c = 12;
      ord_1.End_User_Name__c = testAccount_1.id;
      ord_1.Sold_To_Name__c = testAccount_2.id;
      ord_1.status__c = 'In Progress';
      insert ord_1;
      test.stopTest();     
      Order__c ord_2 = new Order__c(Id=ord_1.id);
      ord_2.Subsidaries__c =  Global_Setting__c.getInstance('Japan').Id__c;
      ord_2.status__c = 'Approved';
      ord_2.End_User_Name__c = testAccount_1.id;
      ord_2.Sold_To_Name__c = testAccount_2.id;
      update ord_2; 
      
      Account_Order_Address__c ordAdr_1 = new Account_Order_Address__c();
      ordAdr_1.Address__c = 'Test1';
      ordAdr_1.Address2__c = 'Test1';
      ordAdr_1.Address_Type__c = 'Sold To';
      ordAdr_1.Order__c = ord_1.id;
      insert ordAdr_1;
      
      Account_Order_Address__c ordAdr_2 = new Account_Order_Address__c();
      ordAdr_2.Address__c = 'Test2';
      ordAdr_2.Address2__c = 'Test2';
      ordAdr_2.Address_Type__c = 'End User';
      ordAdr_2.Order__c = ord_1.id;
      insert ordAdr_2;
      
      Account_Order_Address__c ordAdr_3 = new Account_Order_Address__c();
      ordAdr_1.Address__c = 'Test3';
      ordAdr_1.Address2__c = 'Test3';
      ordAdr_1.Address_Type__c = 'Bill To';
      ordAdr_1.Order__c = ord_2.id;
      insert ordAdr_3;
      
      Account_Order_Address__c ordAdr_4 = new Account_Order_Address__c();
      ordAdr_2.Address__c = 'Test4';
      ordAdr_2.Address2__c = 'Test4';
      ordAdr_2.Address_Type__c = 'Ship To';
      ordAdr_2.Order__c = ord_2.id;
      insert ordAdr_4;
            
      Map<Id, Order__c> oldMap= new Map<Id, Order__c>{ord_1.Id => ord_1};
      Map<Id,Order__c> newMap= new Map<Id,Order__c>{ord_2.Id => ord_2}; 

      Order_Trigger_Class.onAfterUpdate(oldMap,newMap);
      
      }
      
      static testMethod void onAfterUpdate_test_indirect_soldToBilltoSame()   
      {
      test.startTest();
       
      Account testAccount_1 = TestUtil.createAccounts(1, true)[0];
      Account testAccount_2 = TestUtil.createAccounts(1, true)[0];
      Global_Setting__c obj1;
      
      BigMachines__Quote__c testQuote = TestUtil.createQuotes(1, true)[0];   
      Opportunity testOpp = TestUtil.createOpportunities(1, true)[0];
      Order__c ord_1 = new Order__c();
      ord_1.Quote__c = testQuote.id;
      ord_1.Maintenance_Start__c = Date.today();
      ord_1.Maintenance_End__c = Date.today().addYears(1);
      ord_1.Opportunity__c = testOpp.id;
      ord_1.Numb_of_Maint_Months__c = 12;
      ord_1.End_User_Name__c = testAccount_1.id;
      ord_1.Sold_To_Name__c = testAccount_2.id;
      ord_1.status__c = 'In Progress';
      insert ord_1;
      test.stopTest();     
      Order__c ord_2 = new Order__c(Id=ord_1.id);
      ord_2.Subsidaries__c =  Global_Setting__c.getInstance('Japan').Id__c;
      ord_2.status__c = 'Approved';
      ord_2.End_User_Name__c = testAccount_1.id;
      ord_2.Sold_To_Name__c = testAccount_2.id;
      update ord_2; 
      
      Account_Order_Address__c ordAdr_1 = new Account_Order_Address__c();
      ordAdr_1.Address__c = 'Test1';
      ordAdr_1.Address2__c = 'Test1';
      ordAdr_1.Address_Type__c = 'Sold To';
      ordAdr_1.Order__c = ord_1.id;
      insert ordAdr_1;
      
      Account_Order_Address__c ordAdr_2 = new Account_Order_Address__c();
      ordAdr_2.Address__c = 'Test2';
      ordAdr_2.Address2__c = 'Test2';
      ordAdr_2.Address_Type__c = 'End User';
      ordAdr_2.Order__c = ord_1.id;
      insert ordAdr_2;
      
      Account_Order_Address__c ordAdr_3 = new Account_Order_Address__c();
      ordAdr_1.Address__c = 'Test1';
      ordAdr_1.Address2__c = 'Test1';
      ordAdr_1.Address_Type__c = 'Bill To';
      ordAdr_1.Order__c = ord_2.id;
      insert ordAdr_3;
      
      Account_Order_Address__c ordAdr_4 = new Account_Order_Address__c();
      ordAdr_2.Address__c = 'Test1';
      ordAdr_2.Address2__c = 'Test1';
      ordAdr_2.Address_Type__c = 'Ship To';
      ordAdr_2.Order__c = ord_2.id;
      insert ordAdr_4;
            
      Map<Id, Order__c> oldMap= new Map<Id, Order__c>{ord_1.Id => ord_1};
      Map<Id,Order__c> newMap= new Map<Id,Order__c>{ord_2.Id => ord_2}; 

      Order_Trigger_Class.onAfterUpdate(oldMap,newMap);
      
      }
      
      
        static testMethod void onAfterUpdate_test_direct_alldiff()   
      {
      test.startTest();
       
      Account testAccount_1 = TestUtil.createAccounts(1, true)[0];
      Account testAccount_2 = TestUtil.createAccounts(1, true)[0];
      Global_Setting__c obj1;
      
      BigMachines__Quote__c testQuote = TestUtil.createQuotes(1, true)[0];   
      Opportunity testOpp = TestUtil.createOpportunities(1, true)[0];
      Order__c ord_1 = new Order__c();
      ord_1.Quote__c = testQuote.id;
      ord_1.Maintenance_Start__c = Date.today();
      ord_1.Maintenance_End__c = Date.today().addYears(1);
      ord_1.Opportunity__c = testOpp.id;
      ord_1.Numb_of_Maint_Months__c = 12;
      ord_1.End_User_Name__c = testAccount_1.id;
      ord_1.Sold_To_Name__c = testAccount_2.id;
      ord_1.status__c = 'In Progress';
      insert ord_1;
      test.stopTest();     
      Order__c ord_2 = new Order__c(Id=ord_1.id);
      ord_2.Subsidaries__c =  Global_Setting__c.getInstance('Japan').Id__c;
      ord_2.status__c = 'Approved';
      ord_2.End_User_Name__c = testAccount_1.id;
      ord_2.Sold_To_Name__c = testAccount_1.id;
      update ord_2; 
      
      Account_Order_Address__c ordAdr_1 = new Account_Order_Address__c();
      ordAdr_1.Address__c = 'Test1';
      ordAdr_1.Address2__c = 'Test1';
      ordAdr_1.Address_Type__c = 'Sold To';
      ordAdr_1.Order__c = ord_1.id;
      insert ordAdr_1;
      
      Account_Order_Address__c ordAdr_2 = new Account_Order_Address__c();
      ordAdr_2.Address__c = 'Test2';
      ordAdr_2.Address2__c = 'Test2';
      ordAdr_2.Address_Type__c = 'End User';
      ordAdr_2.Order__c = ord_1.id;
      insert ordAdr_2;
      
      Account_Order_Address__c ordAdr_3 = new Account_Order_Address__c();
      ordAdr_1.Address__c = 'Test3';
      ordAdr_1.Address2__c = 'Test3';
      ordAdr_1.Address_Type__c = 'Bill To';
      ordAdr_1.Order__c = ord_1.id;
      insert ordAdr_3;
      
      Account_Order_Address__c ordAdr_4 = new Account_Order_Address__c();
      ordAdr_2.Address__c = 'Test4';
      ordAdr_2.Address2__c = 'Test4';
      ordAdr_2.Address_Type__c = 'Ship To';
      ordAdr_2.Order__c = ord_1.id;
      insert ordAdr_4;
            
      Map<Id, Order__c> oldMap= new Map<Id, Order__c>{ord_1.Id => ord_1};
      Map<Id,Order__c> newMap= new Map<Id,Order__c>{ord_2.Id => ord_2}; 

      Order_Trigger_Class.onAfterUpdate(oldMap,newMap);
      
      delete ord_1;
      
      }
    
    static testMethod void onInsertSubscriptionOfferingType() {
        test.startTest();
        Account testAccount_1 = TestUtil.createAccounts(1, true)[0];
        BigMachines__Quote__c testQuote = TestUtil.createQuotes(1, true)[0];   
        testQuote.Offering_Type__c = 'PureEngage Subscription'; // Should make the order for this quote Offering_Type__c = 'PureEngage Subscription'
        update testQuote;
        
        Opportunity testOpp = TestUtil.createOpportunities(1, true)[0];
        Order__c ord_1 = new Order__c();
        ord_1.Quote__c = testQuote.id;
        ord_1.Maintenance_Start__c = Date.today();
        ord_1.Maintenance_End__c = Date.today().addYears(1);
        ord_1.Opportunity__c = testOpp.id;
        ord_1.Numb_of_Maint_Months__c = 12;
        ord_1.End_User_Name__c = testAccount_1.id;
        ord_1.Sold_To_Name__c = testAccount_1.id;
/*
       if(!objOrder.Synced_with_Contract__c 
       && objOrder.status__c == 'Completed' 
       && !objOrder.No_Cloud_Billing_Contract__c 
       && objOrder.Offering_Type__c != null 
       && objOrder.Offering_Type__c.contains('Subscription')) 
           list_OrdersforContracts.add(objOrder);    
    }
*/
        ord_1.Synced_with_Contract__c = false;
        ord_1.status__c = 'Completed';
        ord_1.No_Cloud_Billing_Contract__c = false;
        insert ord_1;
        test.stopTest();     
        
    }  
}