objects/ININ_Debug_Log__c.object
<CustomObject>
    <description>Generic log object for debugging.</description>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ININ Debug Log</label>
    <nameField>
        <displayFormat>DL-{000000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ININ Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ININDebugLog.cls
public class ININDebugLog {

    List<ININ_Debug_Log__c> logQueue;
    
    public ININDebugLog()
    {
        logQueue = new List<ININ_Debug_Log__c>();
    }
    
    static public void LogNow(string source, string message)
    {
        ININ_Debug_Log__c log = new ININ_Debug_Log__c();
        log.Source__c = source;
        log.Message__c = message;
        
        insert log;
    }

    public void AddToQueue(string source, string message)
    {
        ININ_Debug_Log__c log = new ININ_Debug_Log__c();
        log.Source__c = source;
        log.Message__c = message;
        
        logQueue.add(log);
    }
    
    public void FlushQueue()
    {
        if (logQueue.size() > 0)
        {
            insert logQueue;
        }
    }
    
}