objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Billing_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <externalId>true</externalId>
        <label>Invoice #</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Quote Billing Plans</relationshipLabel>
        <relationshipName>Quote_Billing_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Support_Period_End_Date__c</fullName>
        <label>Support Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Support_Period_Start_Date__c</fullName>
        <label>Support Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Billing Plan</label>
    <nameField>
        <displayFormat>QBP-{000000}</displayFormat>
        <label>Quote Billing Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Billing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BillingPlanExtension.cls
public without sharing class BillingPlanExtension {
	String orderId {get;set;}
	public List<Quote_Billing_Plan__c> quoteBillingPlans {get;set;}
	public Boolean noRecordsFound {get;set;}
	public BillingPlanExtension(ApexPages.StandardController sc){
		orderId = sc.getId();
		System.debug('NKC debug orderId ['+orderId+']');
		init();
	}
	
	private void init(){
		Order__c order = [SELECT Quote__c FROM Order__c WHERE id =: orderId];
		quoteBillingPlans = [SELECT id, Name, Invoice__c, Invoice_Date__c, Amount__c, Support_Period_Start_Date__c, 
			Support_Period_End_Date__c, Comments__c FROM Quote_Billing_Plan__c WHERE Quote__c =: order.Quote__c];
		if(quoteBillingPlans.isEmpty())
			noRecordsFound = true;
		else
			noRecordsFound = false;
	}

}