objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <externalId>true</externalId>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Attached</fullName>
                </value>
                <value>
                    <fullName>Send Email</fullName>
                </value>
                <value>
                    <fullName>Email Sent</fullName>
                </value>
                <value>
                    <fullName>Invoice or Order Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offering_Type__c</fullName>
        <formula>IF(CONTAINS(Quote__r.Offering_Type__c,&apos;Subscription&apos;), Quote__r.Offering_Type__c,

IF(Text(Opportunity__r.Lines_of_Businesses__c) == &apos;Business Edition&apos; &amp;&amp; 
(RecordType.Name == &apos;Cloud Billing Master Order&apos; || RecordType.Name == &apos;Cloud Monthly Billing Order&apos;),
&apos;PureEngage&apos;,  TEXT(Opportunity__r.Lines_of_Businesses__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offering Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/InvoiceButtonEntentionController.cls
public class InvoiceButtonEntentionController {
    public Invoice__c objInvoice {get; private set;}

    //CTORs
    public InvoiceButtonEntentionController(ApexPages.StandardController stdController) {
        System.debug('enter with Standard Controller');
        Id idInvoice = stdController.getRecord().id;
        objInvoice = getInvoice(idInvoice);
    }
/*
    public InvoiceButtonEntentionController(id idInvoice) {
        System.debug('enter with Manual call');
        objInvoice = getInvoice(idInvoice);
    }
*/
	// Methods
    private Invoice__c getInvoice(id idInvoice) {
        Invoice__c objInvoice = [
            select
            Id,
            Order__r.Offering_Type__c,
            Invoice_Number__c,
            Status__c,
            (SELECT Id FROM Attachments)
            from Invoice__c where id = :idInvoice
        ];
        System.debug('Got invoice ' + objInvoice);
        return objInvoice;
    }

    public PageReference generateInvoicePDF() {
        String strURL = '/apex/CloudInvoicePdf?scontrolCaching=1&id=' + objInvoice.Id;
        System.Debug('Trying Page: ' + strURL);
        PageReference objPageReference = new PageReference(strURL);
        return objPageReference;
    }

    public PageReference generateInvoiceExcel() {
        String strURL = '/apex/CloudInvoiceExcel?scontrolCaching=1&id=' + objInvoice.Id;
        System.Debug('Trying Page: ' + strURL);
        PageReference objPageReference = new PageReference(strURL);
        return objPageReference;
    }

    public PageReference sendInvoice() {
        
        objInvoice.Status__c = 'Send Email';
        update objInvoice;

        String strURL = '/' + objInvoice.Id;
        PageReference objPageReference = new PageReference(strURL);//ApexPages.currentPage();
        objPageReference.setRedirect(false);
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Emailing invoice.'));
        return objPageReference;
    }
}