objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offering_Type__c</fullName>
        <formula>IF(CONTAINS(Quote__r.Offering_Type__c,&apos;Subscription&apos;), Quote__r.Offering_Type__c,

IF(Text(Opportunity__r.Lines_of_Businesses__c) == &apos;Business Edition&apos; &amp;&amp; 
(RecordType.Name == &apos;Cloud Billing Master Order&apos; || RecordType.Name == &apos;Cloud Monthly Billing Order&apos;),
&apos;PureEngage&apos;,  TEXT(Opportunity__r.Lines_of_Businesses__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offering Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CBInvoicePDFExtensionController.cls
/*
 * Class Name  	:  CBInvoicePDFExtensionController
 * Description 	:  This Class is used to Handle the Invoice and Send to Specific PDF format based on Order's Offering Type.
 * Test Class  	:  CloudInvoiceComponentControllerTest
 * Util Classes	:  
 * Created By  	:  Vijay Gopi.
 */
public class CBInvoicePDFExtensionController {
	
    public Invoice__c objInvoice {get; set;}
    
    
    public CBInvoicePDFExtensionController(ApexPages.StandardController controller){
        objInvoice = (Invoice__c)controller.getRecord();
        
        fetchPDFByOfferingType();
    }
    
    public void fetchPDFByOfferingType(){
        objInvoice = [SELECT Id , Order__r.Offering_Type__c, Order__r.Sales_Org__c  FROM Invoice__c WHERE Id = :objInvoice.Id];
        
    }
    
}