objects/License_Request_Log__c.object
<CustomObject>
    <fields>
        <fullName>MAC_Address__c</fullName>
        <label>MAC Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Machine_Name__c</fullName>
        <label>Machine Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This describes the type of request logged by users</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Dummy</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Regular</fullName>
                    <default>true</default>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License Request Log</label>
    <nameField>
        <displayFormat>LRL-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Request Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LicenseRequestUpdateTest.cls
//@isTest (SeeAllData = True)
@isTest
private class LicenseRequestUpdateTest {
   public static void createLogs(){
       List<License_Request_Log__c> logs = new List<License_Request_Log__c>();
       Integer i = 0; 
       for(i=0;i<5;i++)
           logs.add(new License_Request_Log__c(Machine_Name__c='MVICIC001',MAC_Address__c='D65056BA0823',type__c=''));
       
       insert logs;     
   }
    static testmethod void RequestUpdateMethod() {
   /* List<License_Request_Log__c> reqList = [Select Id, Type__c from License_Request_Log__c Limit 1];
    for (License_Request_Log__c l: reqList) {
            l.type__c = '';
    }
    update reqList;
    */
    createLogs();
    Test.startTest();
    LicenseRequestUpdateBatch c = new LicenseRequestUpdateBatch();
    Database.executeBatch(c);
    Test.stopTest();
    
    }
}