objects/License_Request_Log__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <formula>AND(IsActive__c == true, AND(Expiration_Date__c != NULL, DATEVALUE(Expiration_Date__c) &lt; TODAY()) == false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>License Request Log</relationshipLabel>
        <relationshipName>License_Request_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>License Request Log (Sold To)</relationshipLabel>
        <relationshipName>License_Request_Log1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This describes the type of request logged by users</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Dummy</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Regular</fullName>
                    <default>true</default>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License Request Log</label>
    <nameField>
        <displayFormat>LRL-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Request Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/License_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>License Snapshot</relationshipLabel>
        <relationshipName>License_Snapshot</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>License Snapshot</relationshipLabel>
        <relationshipName>License_Snapshot</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>License Snapshot (Sold To)</relationshipLabel>
        <relationshipName>License_Snapshot1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License Snapshot</label>
    <nameField>
        <displayFormat>LS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Snapshot</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product__c.object
<CustomObject>
    <description>What it does?  Object containing information about products associated with a DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Upgrade_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Upgrade Requests</relationshipLabel>
        <relationshipName>Product_Upgrade_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Upgrade Requests</relationshipLabel>
        <relationshipName>Product_Upgrade_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Version</fullName>
                </value>
                <value>
                    <fullName>Purchase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Upgrade Request</label>
    <nameField>
        <displayFormat>PUR-{000000}</displayFormat>
        <label>Request#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Upgrade Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pure_Connect_Version_Upgrade__c.object
<CustomObject>
    <fields>
        <fullName>Mapping_Type__c</fullName>
        <label>Mapping Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Part_Name__c</fullName>
        <formula>New_Product__r.Product_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New Part Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Part_Number__c</fullName>
        <label>New Part Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Part_Name__c</fullName>
        <formula>Old_Product__r.Product_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Old Part Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Part_Number__c</fullName>
        <label>Old Part Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Pure Connect Version Upgrade</label>
    <nameField>
        <displayFormat>PCVU-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pure Connect Version Upgrades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LMSSnapshotComponentControllerTest.cls
@isTest(seeAllData=true)
public class LMSSnapshotComponentControllerTest {
	@isTest
    static void testLMSSnapshotComponentController(){
    	Test.startTest();
    	//License_Request_Log__c requestLog = [SELECT End_User__c, Sold_To__c FROM License_Request_Log__c WHERE Active__c = true LIMIT 1];
    	License_Snapshot__c snapShotRecord = [SELECT id, Part_Number__c, End_User__c, Sold_To__c, Product__c FROM License_Snapshot__c WHERE IsActive__c = true LIMIT 1];
    	
    	LMSSnapshotComponentController controller = new LMSSnapshotComponentController();
    	controller.endUserAccountId = snapShotRecord.End_User__c;
    	controller.soldToAccountIds = new List<String>{snapShotRecord.Sold_To__c};
    	controller.userType = 'Internal';
    	boolean pendindRefersh = controller.getPendingRefresh();
    	List<LMSSnapshotComponentController.SnapshotRecordWrapper> snapshotData = controller.getSnapshotData();
    	Product_Upgrade_Request__c pur = new Product_Upgrade_Request__c(Account__c = snapShotRecord.End_User__c, Product__c = snapShotRecord.Product__c, Quantity__c = 10, Type__c = 'Version');
    	insert pur;
    	Pure_Connect_Version_Upgrade__c pcvu = new Pure_Connect_Version_Upgrade__c(Mapping_Type__c = 'Test', New_Part_Number__c = snapShotRecord.Part_Number__c, Old_Part_Number__c = snapShotRecord.Part_Number__c);
    	insert pcvu;
    	
    	controller.selectedPartNumber = snapShotRecord.Part_Number__c;
    	controller.showHistory();
    	controller.showLineItems();
    	controller.closeLineItems();
    	controller.refreshSnapshot();
    	controller.selectedPartNumber = snapShotRecord.Part_Number__c + 'A';
    	controller.showLineItems();
    	controller.userType = 'Partner';
    	pendindRefersh = controller.getPendingRefresh();
    	snapshotData = controller.getSnapshotData();
        
        LMSSnapshotComponentController.UpgradeRequestWrapper upgradeRequestWrapper = new LMSSnapshotComponentController.UpgradeRequestWrapper('Old_APN_Number__c', 'Old_Part_Name__c', 'New_APN_Number__c', 'New_Part_Name__c', DateTime.Now(), 100);
        Test.stopTest();
    }    
}