objects/MPLS_RVA_Quote_Request__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Special Inquiry</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Awaiting Salesperson Requirements</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MPLS / RVA / Data Center Quote Request</label>
    <nameField>
        <label>MPLS/RVA/Data Center Quote Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPLS / RVA / Data Center Quote Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QuoteRequestDataCenterSubmit.cls
/* Name           : QuoteRequestDataCenterSubmit
Purpose        : Change the Status of MPLS/RVA/DataCenter QuoteRequest to 'Submitted'
Developer      : Vikas Menon 
Created Date   : 07-Jan-2013
*/
global class QuoteRequestDataCenterSubmit {
    // A Web Service Method that Changes the 'Status' field of MPLS/RVA/DataCenter QuoteRequest to 'Submitted'
    
    webservice static String submitStatus(Id qId){       
        String msg = 'success'; 
        try{
            update new MPLS_RVA_Quote_Request__c(id = qId, status__c = 'Submitted');
        }catch(Exception e){
            msg = 'fail';
            //msg = 'fail Reason - '+e;
        }
        return msg;
        
    }
}