objects/Opportunity_Approval__c.object
<CustomObject>
    <description>What it Does? Tracks approvals by the Finance teams for Opportunities
Downstream Impact? Affects OM/Finance approvals on master record opportunities
Owner? Finance/Order Management, Professional Services</description>
    <fields>
        <fullName>Approval_Type__c</fullName>
        <description>What it does? Indicates the type of opportunity approval
Downstream Impact? N/A
Owner? Finance/Order Management, Professional Services</description>
        <label>Approval Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Finance_Approval_Status__c</fullName>
        <description>What it does? Indicates the status of the OM/Finance team review and approval of the PS Opportunity (Master PS record), which when approved will be used to create a corresponding finance RC record in RevPro 
Downstream impact? used as a filter for RevPro RC creation and as a check on PS Orders 
Owner? Professional Services / Order Management / Finance</description>
        <label>Finance Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Finance_Review_Request_Sent__c</fullName>
        <description>What it Does? Stores the date when the Finance/OM review notification was sent for the PS opportunity 
Downstream Impact? affects the SLA tracking and notifications 
Owner? Professional Services, Order Management/Finance</description>
        <label>Finance Review Request Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? The lookup to the related opportunity record for this approval item
Owner? Finance/Order Management, Professional Services</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Approvals</relationshipLabel>
        <relationshipName>Opportunity_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Approval</label>
    <nameField>
        <displayFormat>OApp-{YYYY}-{MM}-{0000000}</displayFormat>
        <label>Opportunity Approval ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Oppty_Approval_Regional_SLAs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the Opportunity Approval SLA values for combinations of Type and Region, including the number of days when the quarter end SLA override will apply</description>
    <fields>
        <fullName>Opportunity_Approval_Queue_Association__c</fullName>
        <description>What it does? Indicates the name of the associated approval queue to which the opportunity approval should be associated
Downstream Impact? Used in the automated creation of an Opportunity Approval from the opportunity helpers
Owner? Finance/Order Management</description>
        <label>Opportunity Approval Queue Association</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>What it Does? The Region of the Opportunity Approval record to which the SLAs will apply
Owner? Finance/Order Management</description>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What it Does? The Type of the Opportunity Approval record to which the SLAs will apply
Owner? Finance/Order Management</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Approval Regional SLAs</label>
</CustomObject>

classes/AssociatedOpportunityApprovalHelper.cls
//Nik Mills - 10-Nov-2018
//For use in creating or updating an OpportunityApproval record associated to an Opportunity
//Primary IT Contact: Nik Mills
//Code Coverage: AssociatedOpportunityApprovalHelper_Test

public class AssociatedOpportunityApprovalHelper {

    @InvocableMethod(label='Set Opportunity Approval' description='Creates or Updates an Opportunity Approval associated to the main Opportunity.')        
    public static void SetOpportunityApproval(list<ID> oppIDs)
    {
        System.Debug('NikM Debug:: Set Opportunity Approval invocable called');
        list<Opportunity> opps = [SELECT Id, Name, RecordTypeId, PS_Region__c, PSA_Closed_OM_Oppty_Submit_Status__c FROM Opportunity WHERE Id IN :oppIDs];
        list<Opportunity_Approval__c> oppApprs = [SELECT Id, Name, OwnerId FROM Opportunity_Approval__c WHERE Opportunity__c IN :oppIDs];
        List<RecordType> rtypes = [Select Id from RecordType where SobjectType = 'Opportunity'
            and DeveloperName =: 'Professional_Services'];
        List<Group> Queues;
        List<Group> DefaultQueues;
  
        for (Opportunity Opp : opps)
        {     
            System.Debug('NikM Debug:: Opportunity ' + Opp.Name + ' with ID ' + Opp.Id + ' passed to AssocOppApprHelper - ');
            // Check if this is a PS Opportunity and if so, then proceed
            if (Opp.RecordTypeId == rtypes[0].Id)
            {            
                list<Oppty_Approval_Regional_SLAs__c> OpptyApprovalSLAs;
                // Need to get the SLA details and set them on the record now, depending on the date that the record was created
                OpptyApprovalSLAs = [SELECT Opportunity_Approval_Queue_Association__c FROM Oppty_Approval_Regional_SLAs__c WHERE Region__c =: Opp.PS_Region__c AND Type__c = 'Professional Services' ];
    
                // If there is no associated opportunity approval record and the PSA Close Submit status is submitted, then we need to create a new record
                if (oppApprs.isEmpty())
                {
                    if (Opp.PSA_Closed_OM_Oppty_Submit_Status__c == 'Submitted')
                    {
                        Opportunity_Approval__c newOpptyApproval = new Opportunity_Approval__c();
                        newOpptyApproval.Approval_Type__c = 'Professional Services';
                        newOpptyApproval.Finance_Approval_Status__c = 'Submitted';
                        newOpptyApproval.Opportunity__c = Opp.Id;
                        newOpptyApproval.Finance_Review_Request_Sent__c = system.now();
                        
                        Queues = [SELECT Id FROM group WHERE Type = 'Queue' AND NAME =: OpptyApprovalSLAs[0].Opportunity_Approval_Queue_Association__c];
                        DefaultQueues = [SELECT Id FROM group WHERE Type = 'Queue' AND NAME ='WW Order Management Oppty Approvals'];
                        
                        if (!Queues.isEmpty())
                        {
                            If (Queues[0].Id != null)
                            {
                                newOpptyApproval.OwnerId = Queues[0].Id;
                            }
                            else
                            {
                                newOpptyApproval.OwnerId = DefaultQueues[0].Id;
                            }
                        }
                        else
                        {
                            // Unable to get the queue name, so assign as default
                            newOpptyApproval.OwnerId = DefaultQueues[0].Id;
                        }
                        
                        insert newOpptyApproval;
                    }
                }
                else
                {
                    // There is an existing record, so check if the PSA Closed Submit Status is resubmitted, in which case we need to update the associated Opportunity Approval
                    for (Opportunity_Approval__c OA : OppApprs)
                    {
                        if (Opp.PSA_Closed_OM_Oppty_Submit_Status__c == 'Resubmitted')
                        {
                            OA.Finance_Approval_Status__c = 'Resubmitted';
                            OA.Finance_Review_Request_Sent__c = system.now();
                            update OA;
                        }
                        
                        if (Opp.PSA_Closed_OM_Oppty_Submit_Status__c == 'Cancelled')
                        {
                            // Opportunity approval was cancelled, so update to mark the object as cancelled
                            OA.Finance_Approval_Status__c = 'Cancelled';
                            update OA;
                        }
                    }
                }
            }
  
        }
    }    
}