objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>Text( Opportunity__r.Type )</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product__c.object
<CustomObject>
    <description>What it does?  Object containing information about products associated with a DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Group__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Groups</relationshipLabel>
        <relationshipName>Product_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standalone</fullName>
                </value>
                <value>
                    <fullName>Contact Center</fullName>
                </value>
                <value>
                    <fullName>Add-Ons</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Campaign Bundles</fullName>
                </value>
                <value>
                    <fullName>PureSuccess</fullName>
                </value>
                <value>
                    <fullName>A la Carte</fullName>
                </value>
                <value>
                    <fullName>A la Carte Partner</fullName>
                </value>
                <value>
                    <fullName>Partner PureSuccess</fullName>
                </value>
                <value>
                    <fullName>EQUIP</fullName>
                </value>
                <value>
                    <fullName>GUIDE</fullName>
                </value>
                <value>
                    <fullName>DRIVE</fullName>
                </value>
                <value>
                    <fullName>Top 5 Plays</fullName>
                </value>
                <value>
                    <fullName>PureBridge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Group_Item__c.object
<CustomObject>
    <fields>
        <fullName>Allocation_type__c</fullName>
        <description>Based on the new Change of GU Training Unit</description>
        <label>Allocation type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription Token</fullName>
                </value>
                <value>
                    <fullName>GU Training Units</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Product Group Items</relationshipLabel>
        <relationshipName>Product_Group_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Product_Type__c</field>
                <operation>equals</operation>
                <value>Mandatory, Mandatory Substitutable, Substitutable, Optional, Lab, HA</value>
            </filterItems>
            <filterItems>
                <field>Product2.NG5_NA_USD_Price__c</field>
                <operation>notEqual</operation>
                <value>-1</value>
            </filterItems>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Group Items</relationshipLabel>
        <relationshipName>Product_Group_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Group Item</label>
    <nameField>
        <displayFormat>PGI-{00000}</displayFormat>
        <label>Product Group Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Group Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Puresuccess_audit_log__c.object
<CustomObject>
    <fields>
        <fullName>Errortype__c</fullName>
        <label>Errortype</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Stacktrace__c</fullName>
        <label>Stacktrace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Token_Allocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Token Allocation</label>
        <referenceTo>Token_Allocations__c</referenceTo>
        <relationshipLabel>Puresuccess_package_audit_logs</relationshipLabel>
        <relationshipName>Puresuccess_package_audit_logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Puresuccess package</fullName>
                </value>
                <value>
                    <fullName>Subscription token</fullName>
                </value>
                <value>
                    <fullName>Gutraining units</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <label>id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Puresuccess_package_audit_log</label>
    <nameField>
        <label>Puresuccess_ Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Puresuccess_package_audit_logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Token_Allocations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Token Allocations</relationshipLabel>
        <relationshipName>Token_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Allocation_Type__c</fullName>
        <description>Purpose of this field is to identify the type of allocation. this new change is part of GU Training Unit</description>
        <label>Allocation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription Token</fullName>
                    <default>true</default>
                    <label>Subscription Token</label>
                </value>
                <value>
                    <fullName>GU Training Units</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Token Allocations</relationshipLabel>
        <relationshipName>Token_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Group_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Group Item</label>
        <referenceTo>Product_Group_Item__c</referenceTo>
        <relationshipLabel>Token Allocations</relationshipLabel>
        <relationshipName>Token_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Group</label>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Token Allocations</relationshipLabel>
        <relationshipName>Token_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Token Allocations</relationshipLabel>
        <relationshipName>Token_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refresh_date__c</fullName>
        <label>Refresh date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Token_Offering_Type__c</fullName>
        <formula>Order__r.Order_Category__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Token Offering Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token_Status__c</fullName>
        <label>Token Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Consumed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tokens__c</fullName>
        <label>Tokens</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Token Allocation</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Token Allocations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Token Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/refreshtokenbatch.cls
global class refreshtokenbatch implements Database.Batchable<sObject>,database.stateful {
global List<Puresuccess_audit_log__c> logs;
global refreshtokenbatch(){
logs = new List<Puresuccess_audit_log__c>();
}
global Database.QueryLocator start(Database.BatchableContext BC) {
string status = 'Expired';
String token= 'SELECT id,Name,Account__c,Order__c,Token_Offering_Type__c,Product_Group__c,Allocation_Type__c,Token_Status__c,Product__c,Product_Group_Item__c,Tokens__c,refresh_date__c FROM Token_Allocations__c where refresh_date__c=TODAY  and Token_Status__c!=\'' + String.escapeSingleQuotes(status)+'\'';
    system.debug('query'+token);
    return Database.getQueryLocator(token);
}
global void execute(Database.BatchableContext BC, List<Token_Allocations__c> scope) {
for(Token_Allocations__c a :scope)
{
try{
ID tid=a.id;
//refreshTokenAllocation.refreshTokenAllocationPackageMethod(tid);
}
catch (Exception e) {
                logs.add(new Puresuccess_audit_log__c(
                       Name =a.Name,
                       id__c=a.id,
                       Stacktrace__c = e.getStackTraceString(),
                       Type__c='Subscription token',
                       Errortype__c=e.getTypeName(),
                    Token_Allocation__c=a.id
                    ));
                system.debug('logs'+logs);
                throw e;
            }
}
}

global void finish(Database.BatchableContext BC) {
            system.debug('logs'+logs);
           insert logs;
}
}