objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>License_FYM_detail__c</fullName>
        <label>License/FYM detail</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>License only order</fullName>
                </value>
                <value>
                    <fullName>Maintenance Only Order</fullName>
                </value>
                <value>
                    <fullName>Both License &amp; Maintenance Order</fullName>
                </value>
                <value>
                    <fullName>PPU Order</fullName>
                </value>
                <value>
                    <fullName>PS Orders</fullName>
                </value>
                <value>
                    <fullName>Cloud Billing Order</fullName>
                </value>
                <value>
                    <fullName>AppFoundry Order</fullName>
                </value>
                <value>
                    <fullName>Hardware Order</fullName>
                </value>
                <value>
                    <fullName>Rental Order</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Cloud Billing</fullName>
                </value>
                <value>
                    <fullName>Cloud Order</fullName>
                </value>
                <value>
                    <fullName>Cloud Premier Billing Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Order_Number__c</fullName>
        <description>What it does? Used to link to Original Master Order. 
Downstream Impact? -	Effects Revenue Forecasting. 
Which Department is Owner? -Finance.</description>
        <label>Master Order #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PS_CAS_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>What it does? Indicates that this is a PS CAS related order
Downstream Impact? used for determining PS CAS orders and in relation to the RevPro integrations
Owner? Order Management / IT</description>
        <label>PS CAS Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PS_CAS_Related_Oppty_Line_of_Business__c</fullName>
        <description>What it does? Stores the PS Line of Business from the PS Opportunity related to the CAS Opportunity, if this is a PS CAS Order
Downstream Impact? Used in the formula for the PS Line of Business which is in turn used in the Order Category formula field, which affects the Netsuite integration and Netsuite Credit Holds processing
Owner? OM team / IT</description>
        <label>PS CAS Related Oppty Line of Business</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PS_Line_of_Business__c</fullName>
        <formula>IF( OR(PS_CAS_Order__c, PS_Subscription_GC_Order__c ), PS_CAS_Related_Oppty_Line_of_Business__c , TEXT(Opportunity__r.PS_Line_of_Business__c))</formula>
        <label>PS Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PS_Subscription_GC_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>What it Does? Indicates that this order is a PS Subscription order created by the Genesys Care team on behalf of the PS Organisation
Downstream Impact? Affects PS Orders and indicates whether they are subscription items being handled by the GC team for PS and RevPro
Owner? OM/IT</description>
        <label>PS Subscription GC Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Description__c</fullName>
        <formula>Product__r.Description</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POB_Type__c</fullName>
        <description>What it Does? RevPro : Store the POB Type 
Downstream Impact? RevPro integration 
Which department is owner? IT</description>
        <label>POB Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>POB_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Type_Formula__c</fullName>
        <formula>if( Quote_Product__r.Service_Contract_Line_ID__c !=&apos;&apos; , &apos;Renewal&apos;,&apos;New&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New/Renewal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isPSContractOrSubscriptionProduct__c</fullName>
        <description>What it does? Indicates at the order line level if the associated Product is a PS Contract or PS Subscription item
Downstream Impact? Used for PS Order processing and CAS/Subscription notifications
Owner? PS/IT</description>
        <formula>Product__r.PS_Contract__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>is PS Contract or Subscription Product ?</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/POB_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cloud-Committed</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud-Ramp-Uncommitted</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud-Uncommitted</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware Support</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware Support Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Latitude License - Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Latitude License - Perpetual</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance - FYM</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Perpetual License</fullName>
    </customValue>
    <customValue>
        <fullName>Premise Subscription - Committed</fullName>
    </customValue>
    <customValue>
        <fullName>Premise Uncommitted - Usage</fullName>
    </customValue>
    <customValue>
        <fullName>PS - CAS</fullName>
    </customValue>
    <customValue>
        <fullName>PS - CAS - Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Expert App</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Fixed Fee on Date</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Fixed Price Percent Complete</fullName>
    </customValue>
    <customValue>
        <fullName>PS - T&amp;M</fullName>
    </customValue>
    <customValue>
        <fullName>PureSuccess Token</fullName>
    </customValue>
    <customValue>
        <fullName>Royalties</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Training On Demand</fullName>
    </customValue>
    <customValue>
        <fullName>Upon Booking Ratable</fullName>
    </customValue>
    <customValue>
        <fullName>Point In Time - Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Variable Model</fullName>
    </customValue>
    <customValue>
        <fullName>Over Time - TAM</fullName>
    </customValue>
    <customValue>
        <fullName>Over Time - PS Fee</fullName>
    </customValue>
    <masterLabel>POB Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/ProfessionalServicesCASOrderHandler.cls
//
// Description: Called from within the Order_Before trigger before insert and before update
//   This will check the Order is a PS CAS 1st year item, and for the presence of a PS Opportunity linked to the CAS Opportunity
//   If present, the code will update some of the PS CAS Order fields so that it can be processed correctly through for RevPro
//   and associated to the master PS Opportunity / Revenue Contract
//
// Test Class : ProfessionalServicesCASOrderHandler_Test
//
// Revisions:
//   April 2019 - Created by Nik Mills
//   September 2019 - Updated to include handling of PS Expert Apps Subscription items in the same way as CAS is processed


Public without sharing Class ProfessionalServicesCASOrderHandler
{
    public static Boolean PSCAS_ORDERBEFORE_TRIGGER_PROCESS = true;

    public static void CheckAndUpdatePSCASOrderForRevPro(List<Order__c> newOrders, List<Order__c> oldOrders)
    {
        if (Util.Bypass_Trigger_Chk) return;
        
        boolean isPSCASFirstYear;
        boolean isOrderLineItem1stYearCAS;
        boolean isPSEASubscription;
        boolean isOrderLinePSEASubscription;
        String linkedPSOpptyID;
        String linkedPSOpptyNumber;
        String linkedPSOpptyPSLoB;
        String ordRecName;
        String opptyRecName;
        
        Map<ID, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Order__c.getRecordTypeInfosByID();
        
        for (Order__c ord: newOrders)
        {
            ordRecName = rtMap.get(ord.RecordTypeId).getName();
            System.Debug('NikM: DEBUG>>>>> Checking for PS CAS or EA Subscription Order (Order Name: ' + ord.Name + ', Record Type Name: ' + ordRecName + ', Status: ' + ord.Status__c + ')');

            isPSCASFirstYear = false;
            isOrderLineItem1stYearCAS = false;
            isPSEASubscription = false;
            isOrderLinePSEASubscription = false;
            linkedPSOpptyID = '';
            linkedPSOpptyNumber = '';
            linkedPSOpptyPSLoB = '';
            
            if (ordRecName == 'General Orders')
            {
                // Check status of the Order is OK to do the update
                if (ord.Status__c == 'Send to ERP' || ord.Status__c == 'Processed in ERP' || ord.Status__c == 'Completed' || ord.Status__c == 'Cancelled' || 
                    ord.Status__c == 'Credit' || ord.Status__c == 'Rejected')
                {
                        System.Debug('NikM: DEBUG>>>>> Exit CAS or EA Subscription Order check for General order as exempt due to Status');
                        return;
                }
                else
                {
                    if (ord.Opportunity__c == null)
                    {
                        System.Debug('NikM: DEBUG>>>>> Exit CAS or EA Subscription check for General order as linked opportunity is null');
                        return;
                    }
                    List<Opportunity> linkedOpp = [SELECT Id, RecordType.Name, Master_Opportunity__c, Master_Opportunity__r.OpportunityNumber__c, Master_Opportunity__r.PS_Line_Of_Business__c
                                 FROM Opportunity WHERE Id =: ord.Opportunity__c];
                    opptyRecName = linkedOpp[0].RecordType.Name;
                    linkedPSOpptyID = linkedOpp[0].Master_Opportunity__c;
                    
                    System.Debug('>>>>>>Debug: NikM: Handling checks for PS CAS 1st Year or EA Subscription Orders. Related Opportunity Master Opp link is: '+ linkedPSOpptyID);

                    if (linkedPSOpptyID != null)
                    {
                        System.Debug('>>>>>>Debug: NikM: Setting Linked PS Opportunity details for 1st Year CAS item');

                        linkedPSOpptyNumber = linkedOpp[0].Master_Opportunity__r.OpportunityNumber__c;
                        linkedPSOpptyPSLoB = linkedOpp[0].Master_Opportunity__r.PS_Line_of_Business__c;
                    }

                    System.Debug('NikM: DEBUG>>>>> Associated Opportunity Record Name : ' + opptyRecName);
                    // Check if this is a CAS 1st Year or EA Subscription order
                    if (opptyRecName == 'Genesys Renewal')
                    {
                        List<Order_Line_Item__c> orderLineItems = [SELECT Id, Order__c, Support_Type_Formula__c, Description__c, POB_Type__c, Material_Description__c, isPSContractOrSubscriptionProduct__c
                                                                    FROM Order_Line_Item__c WHERE Order__c = :ord.Id];
                                                                    
                        for (Order_Line_Item__c oli: OrderLineItems)
                        {
                            if (oli.Support_Type_Formula__c == 'New' && (oli.POB_Type__c == 'PS - CAS' || (oli.Material_Description__c.Contains('Custom App Support') || 
                                                                                                           oli.Material_Description__c.Contains('Subscription Service for PS Expert Apps' ) ) ) )
                            {
                                isOrderLineItem1stYearCAS = true;
                            }
                            if (oli.Support_Type_Formula__c == 'New' && (oli.POB_Type__c == 'PS - Fixed Fee on Date' && oli.isPSContractOrSubscriptionProduct__c))
                            {
                                isOrderLinePSEASubscription = true;
                            }
                        }
                        
                        if (!isOrderLineItem1stYearCAS && !isOrderLinePSEASubscription)
                        {
                            System.Debug('NikM: DEBUG>>>>> Exit CAS or EA Subscription check for General order as not 1st Year CAS (POB != PS - CAS or No CAS product) or EA Subscription (PS Contract == false && POB Type == PS - Fixed Fee on Date');
                            return;
                        }
                    }

                    // If this is a first year PS CAS order, set some of the required fields 
                    // NOTE: if there is no linked master PS opportunity, the PS line of business and master order would be set to blanks)
                    if (isOrderLineItem1stYearCAS)
                    {
                        System.Debug('>>>>>>Debug: NikM: Updating CAS Order details for PS 1st Year CAS processing');
                        ord.License_FYM_detail__c = 'PS Orders';
                        ord.PS_CAS_Order__c = true;
                        ord.PS_CAS_Related_Oppty_Line_of_Business__c = linkedPSOpptyPSLoB;

                        // Check if the Master Order number needs to be updated
                        if ((ord.Master_Order_Number__c == '' || ord.Master_Order_Number__c == null) && linkedPSOpptyID != '') // Master Order Ref is blank so set to the linked PS Oppty value
                        {
                            ord.Master_Order_Number__c= linkedPSOpptyNumber;
                        }
                        
                        if (ord.Master_Order_Number__c == ord.Name && linkedPSOpptyID != '') // Master Order Ref is same as Order, so override with linked PS Oppty value
                        {
                            ord.Master_Order_Number__c = linkedPSOpptyNumber;
                        }
                        PSCAS_ORDERBEFORE_TRIGGER_PROCESS = false;
                    }
                    if (isOrderLinePSEASubscription)
                    {
                        System.Debug('>>>>>>Debug: NikM: Updating EA Subscription Order details for  processing');
                        ord.License_FYM_detail__c = 'PS Orders';
                        ord.PS_Subscription_GC_Order__c = true;
                        ord.PS_CAS_Related_Oppty_Line_of_Business__c = linkedPSOpptyPSLoB;

                        // Check if the Master Order number needs to be updated
                        if ((ord.Master_Order_Number__c == '' || ord.Master_Order_Number__c == null) && linkedPSOpptyID != '') // Master Order Ref is blank so set to the linked PS Oppty value
                        {
                            ord.Master_Order_Number__c= linkedPSOpptyNumber;
                        }
                        
                        if (ord.Master_Order_Number__c == ord.Name && linkedPSOpptyID != '') // Master Order Ref is same as Order, so override with linked PS Oppty value
                        {
                            ord.Master_Order_Number__c = linkedPSOpptyNumber;
                        }
                        PSCAS_ORDERBEFORE_TRIGGER_PROCESS = false;
                    }
                }
            }
        }
    }
}