objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Associated_Opportunity_Product_ID__c</fullName>
        <description>What it does?The salesforce ID of the Opportunity Product item to which this Order Line Item relates. This is just the ID and not a lookup and will be used with the integration to RevPro to identify to which SO line this Order Line Item is associated. 
Owner? Professional Services / Finance</description>
        <inlineHelpText>The ID of the Opportunity Product item to which this Order Line Item relates, and used for association of this to the RevPro SO Lines</inlineHelpText>
        <label>Associated Opportunity Product ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Associated_Opportunity_Product_Name__c</fullName>
        <description>What it does? Stores the name of the associated opportunity product linked to this order line item and any additional link information from the opportunity products for PS. Used for RevPro CAS linking
Downstream Impact? CAS process for PS
Owner? Professional Services/IT</description>
        <label>Associated Opportunity Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Description__c</fullName>
        <formula>Product__r.Description</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Line_18_Digit_ID__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Line 18 Digit ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POB_Type__c</fullName>
        <description>What it Does? RevPro : Store the POB Type 
Downstream Impact? RevPro integration 
Which department is owner? IT</description>
        <label>POB Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>POB_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>TEXT(Product__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Base Item</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_ID_Formula__c</fullName>
        <formula>if( Quote_Product__r.Project_ID__c  !=&apos;&apos;, Quote_Product__r.Project_ID__c  ,If(Contract_Line_Item__r.Upd_Project_Id__c != &apos;&apos;, Contract_Line_Item__r.Upd_Project_Id__c , Project_ID__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project_ID_Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Downstream Impact: Only used for Cloud Billing
Department Owner: Cloud Billing
Help Text: Used to store and bill for the number of gigabytes in usage data
Used to store and bill for the quantity of items in the Order Line</description>
        <inlineHelpText>Used to store and bill for the quantity of items in the Order Line (Quantity__c)</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Solution_Names_Covered1_Formula__c</fullName>
        <formula>If(Contract_Line_Item__r.Upd_Solution_Name__c != &apos;&apos;,Contract_Line_Item__r.Upd_Solution_Name__c , If(    Quote_Product__r.Solution_Names_Covered1__c != &apos;&apos;,Quote_Product__r.Solution_Names_Covered1__c ,Solution_Names_Covered1__c )  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solution_Names_Covered1_Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution_Names_Covered1__c</fullName>
        <label>Solution_Names_Covered</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>Formula based off of Quantity multiplied by Sales Price.</description>
        <formula>if(Order__r.RecordType.Name = &apos;Cloud Monthly Billing Order&apos; &amp;&amp;  Order__r.Sales_Org__c != &apos;PureCloud&apos;, 
FLOOR((Sales_Price__c * BigMachines_Quantity__c)*100)/100, 
Sales_Price__c * BigMachines_Quantity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula based off of Quantity multiplied by Sales Price.</inlineHelpText>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/POB_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cloud-Committed</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud-Ramp-Uncommitted</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud-Uncommitted</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware Support</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware Support Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Latitude License - Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Latitude License - Perpetual</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance - FYM</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Perpetual License</fullName>
    </customValue>
    <customValue>
        <fullName>Premise Subscription - Committed</fullName>
    </customValue>
    <customValue>
        <fullName>Premise Uncommitted - Usage</fullName>
    </customValue>
    <customValue>
        <fullName>PS - CAS</fullName>
    </customValue>
    <customValue>
        <fullName>PS - CAS - Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Expert App</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Fixed Fee on Date</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Fixed Price Percent Complete</fullName>
    </customValue>
    <customValue>
        <fullName>PS - T&amp;M</fullName>
    </customValue>
    <customValue>
        <fullName>PureSuccess Token</fullName>
    </customValue>
    <customValue>
        <fullName>Royalties</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Training On Demand</fullName>
    </customValue>
    <customValue>
        <fullName>Upon Booking Ratable</fullName>
    </customValue>
    <customValue>
        <fullName>Point In Time - Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Variable Model</fullName>
    </customValue>
    <customValue>
        <fullName>Over Time - TAM</fullName>
    </customValue>
    <customValue>
        <fullName>Over Time - PS Fee</fullName>
    </customValue>
    <masterLabel>POB Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/OrderLineItemToOpptyProductLinker.cls
// OrderLineItemToOpptyProductLinker controller class
// Used for the manual linking of an Order Line Item to an Opportunity Product, which is part of the RevPro integration functionality,
//  in particular as used by PS
// Author: Nik Mills
// Created: February 2019
// Test class/coverage provided by OrderLineItemToOpportunityProductLinker_Test

public with sharing class OrderLineItemToOpptyProductLinker
{
    public PageReference sourcePageRef;

    public String originatingOrderLineItemId {get;set;}
    public String selectedOppProductId {get;set;}
    public String BaseURL {get;set;}
    public String masterPSOpptyName {get;set;}
    public String masterPSOpptyID {get;set;}
    public String masterPSOpptyNumber {get;set;}
    public String parentOrderName {get;set;}
    public String sourceOrderLineItemName {get;set;}
    public String sourceOrderLineItemMaterialDescription {get;set;}
    public String sourceOrderLineItemSolutionNamesCoveredFormula {get;set;}
    public Decimal sourceOrderLineItemTotalPrice {get;set;}
    public String alreadyLinkedProductName {get;set;}
    public String sourceOrderLineItemCurrency {get;set;}
    public Boolean isAlreadyLinked {get;set;}
    public Boolean itemsAreAvailableToLinkTo {get;set;}
    public Boolean isPSMasterOpportunityLinkFound {get;set;}
    public Boolean isRecordSelected {get;set;}

    public List<OpportunityLineItem> opptyProducts;
    private List<OpportunityLineItem> selectedOpptyProd;
    private List<Order_Line_Item__c> thisOrderLineItem;
    private String psRecordTypeId;
    
    private ApexPages.StandardController stdCtrl;

    public OrderLineItemToOpptyProductLinker()
    {
        originatingOrderLineItemId = ApexPages.CurrentPage().getparameters().get('sourceOrderLineItemId');
        isAlreadyLinked = false;
        itemsAreAvailableToLinkTo = false;
        isPSMasterOpportunityLinkFound = false;
        isRecordSelected = false;
         
        CommonMethod();
        GetAssociatedOpportunityProducts();
    }
    
    public void CommonMethod()
    {
        BaseURL = string.valueof(URL.getSalesforceBaseUrl().toExternalForm());
    }
       
    public void GetAssociatedOpportunityProducts()
    {
        System.Debug('NikM: Originating Order Line Item ID is: ' + originatingOrderLineItemId);
        // For CAS Linking for PS, the Order Line item will have a parent Order, which is linked to a CAS 1st Year or Renewal Opportunity,
        // which is turn should be linked to a PS Master Opportunity record
        if (originatingOrderLineItemId != null)
        {
            thisOrderLineItem = [SELECT Order_Line_18_Digit_ID__c, Name, Product__r.Name, Material_Description__c, Order__c, Order__r.Name, Order__r.Opportunity__c, 
                                CurrencyIsoCode, Total_Price__c, Order__r.Opportunity__r.Master_Opportunity__c, Order__r.Opportunity__r.Master_Opportunity__r.Name, 
                                Order__r.Opportunity__r.Master_Opportunity__r.RecordType.Name, Order__r.Opportunity__r.Master_Opportunity__r.OpportunityNumber__c, 
                                Associated_Opportunity_Product_ID__c, Associated_Opportunity_Product_Name__c,
                                Project_Name__c, Project_ID_Formula__c, Solution_Names_Covered1__c, Solution_Names_Covered1_Formula__c 
                                FROM Order_Line_Item__c WHERE Id =:originatingOrderLineItemId];
   
            masterPSOpptyName = thisOrderLineItem[0].Order__r.Opportunity__r.Master_Opportunity__r.Name;
            masterPSOpptyID = thisOrderLineItem[0].Order__r.Opportunity__r.Master_Opportunity__c;
            masterPSOpptyNumber = thisOrderLineItem[0].Order__r.Opportunity__r.Master_Opportunity__r.OpportunityNumber__c;
            parentOrderName = thisOrderLineItem[0].Order__r.Name;
            sourceOrderLineItemName = thisOrderLineItem[0].Name;
            sourceOrderLineItemMaterialDescription = thisOrderLineItem[0].Material_Description__c;
            sourceOrderLineItemTotalPrice = thisOrderLineItem[0].Total_Price__c;
            sourceOrderLineItemCurrency = thisOrderLineItem[0].CurrencyIsoCode;
            sourceOrderLineItemSolutionNamesCoveredFormula = thisOrderLineItem[0].Solution_Names_Covered1_Formula__c;
        
            System.Debug('NikM: Linked Opportunity Master Oppportunity is: ' + thisOrderLineItem[0].Order__r.Opportunity__r.Master_Opportunity__c + ', Master Opp Record Type is: ' + thisOrderLineItem[0].Order__r.Opportunity__r.Master_Opportunity__r.RecordType.Name);
            // Check that the Opportunity being linked to is a PS Opportunity, otherwise do not query further and return
            if (thisOrderLineItem[0].Order__r.Opportunity__r.Master_Opportunity__c != null)
            {
                if (thisOrderLineItem[0].Order__r.Opportunity__r.Master_Opportunity__r.RecordType.Name == 'Professional Services')
                {
                    isPSMasterOpportunityLinkFound = true;
                }
                else
                {
                    return;
                }
            }
            else
            {
                return;
            }
        
            System.Debug('NikM: About to retrieve oppty Products linked to Master Order Oppty ' + thisOrderLineItem[0].Order__r.Opportunity__r.Master_Opportunity__c);
            opptyProducts = [SELECT Id, Opportunity_Product_Line_Item_ID__c, Description__c, OpportunityId, Opportunity.Name, Product2Id, Product2.Name, Quantity__c, 
                UnitPrice, TotalPrice, POB_Type__c, Product_Category__c, Linked_Oppty_Product__c, Linked_Oppty_Product_ID__c, Linked_Oppty_Product_Name__c, Product_Type__c
                FROM OpportunityLineItem WHERE OpportunityId =: masterPSOpptyID AND (Product_Category__c = 'CAS' OR Product2.PS_Expert_Apps_Subscription_Item__c = TRUE)];
                
            // DEV Note: Will need to eventually limit the above query further to only the CAS or EA Subscription Items
            
            if (!opptyProducts.isEmpty())
            {
                itemsAreAvailableToLinkTo = true;
            }
                
            if (thisOrderLineItem[0].Associated_Opportunity_Product_ID__c != null && thisOrderLineItem[0].Associated_Opportunity_Product_ID__c != '')
            {
                selectedOppProductId = thisOrderLineItem[0].Associated_Opportunity_Product_ID__c ;
                alreadyLinkedProductName = thisOrderLineItem[0].Associated_Opportunity_Product_Name__c ;
                isAlreadyLinked = true;
                isRecordSelected = true;
            }
        }
    }
    
    public List<OpportunityLineItem> getopptyProducts()
    {
        return opptyProducts;
    }
    
    private PageReference ReturnToOrderLineItemPage()
    {
        sourcePageRef = new PageReference(BaseURL + '/' + originatingOrderLineItemId);
        sourcePageRef.setRedirect(true);
        return sourcePageRef;    
    }
    
    public PageReference LinkSelectedRecord()
    {
        System.Debug('Selected Oppty Product to Link ID is:' + selectedOppProductId);
        if (selectedOppProductId != null && selectedOppProductId != '')
        {
            isRecordSelected = true;
            thisOrderLineItem[0].Associated_Opportunity_Product_ID__c = selectedOppProductId;
            selectedOpptyProd = [SELECT Product2.Name, Linked_Oppty_Product_Name__c FROM OpportunityLineItem WHERE Id =: selectedOppProductId];
            
            thisOrderLineItem[0].Associated_Opportunity_Product_Name__c = selectedOpptyProd[0].Product2.Name + ' [Linked to ' + selectedOpptyProd[0].Linked_Oppty_Product_Name__c + ']';
            update thisOrderLineItem[0];
            
            return ReturnToOrderLineItemPage();
        }
        else
        {
            isRecordSelected = false;
           
            return null;
        }
    }
   
    public PageReference ClearLinkedItem()
    {
        // remove the linked opportunity product from the sourceOpptyProduct and return back to the OLI page
        thisOrderLineItem[0].Associated_Opportunity_Product_ID__c = null;
        thisOrderLineItem[0].Associated_Opportunity_Product_Name__c = null;
        update thisOrderLineItem[0];

        return ReturnToOrderLineItemPage();
    }
           
    public PageReference Cancel()
    {
        // Cancelled so return back to the Opportunity Product Line item page
        return ReturnToOrderLineItemPage();
    }
}