objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To Name2</relationshipLabel>
        <relationshipName>Bill_To_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bypass_Entitlements__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Entitlements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bypass_Service_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Service Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <label>Submitted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic</fullName>
                </value>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>No Delivery Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ERP_Hold__c</fullName>
        <defaultValue>true</defaultValue>
        <label>ERP Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders(Revenue/Non-Revenue)</relationshipLabel>
        <relationshipName>End_User_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exclude_From_Report__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude From Report</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoiced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoiced?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_FYM_detail__c</fullName>
        <label>License/FYM detail</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>License only order</fullName>
                </value>
                <value>
                    <fullName>Maintenance Only Order</fullName>
                </value>
                <value>
                    <fullName>Both License &amp; Maintenance Order</fullName>
                </value>
                <value>
                    <fullName>PPU Order</fullName>
                </value>
                <value>
                    <fullName>PS Orders</fullName>
                </value>
                <value>
                    <fullName>Cloud Billing Order</fullName>
                </value>
                <value>
                    <fullName>AppFoundry Order</fullName>
                </value>
                <value>
                    <fullName>Hardware Order</fullName>
                </value>
                <value>
                    <fullName>Rental Order</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Cloud Billing</fullName>
                </value>
                <value>
                    <fullName>Cloud Order</fullName>
                </value>
                <value>
                    <fullName>Cloud Premier Billing Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Net_Suite_Order__c</fullName>
        <label>Net Suite Order #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpenAir_Project_Number__c</fullName>
        <label>PS Project Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <defaultValue>IF($RecordType.Id =&apos;012U0000000M2Tw&apos; || $RecordType.Id =&apos;012U0000000MGoM&apos;, &apos;GEN_Opportunity_Record_Type_New&apos;, null)</defaultValue>
        <label>Opportunity Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <defaultValue>IF($RecordType.Id =&apos;012U0000000M2Tw&apos;, TODAY(), null)</defaultValue>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <defaultValue>IF($RecordType.Id =&apos;012U0000000M2Tw&apos;, &apos;Non-Revenue&apos;, &apos;Revenue&apos;)

/*IF($RecordType.Id =&apos;012U0000000MGoM&apos;, &apos;Revenue&apos;, null))*/</defaultValue>
        <label>Order Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Date__c</fullName>
        <defaultValue>IF($RecordType.Id =&apos;012U0000000M2Tw&apos;, TODAY(), null)</defaultValue>
        <label>PO Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Number__c</fullName>
        <defaultValue>IF($RecordType.Id =&apos;012U0000000M2Tw&apos;, text(0), null)</defaultValue>
        <label>PO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PS_OpenAir_Invoice_Filter__c</fullName>
        <description>The primary invoice type filter for the PS OpenAir/PureProject orders (Invoices)</description>
        <label>PS Invoice Filter</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PS_OpenAir_Sales_Order_Line__c</fullName>
        <description>The PS OpenAir Sales Order line name / reference information passed through by the PureProject (and formerly OpenAir)-&gt;Salesforce integration code</description>
        <label>PS Sales Order Line</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PS_OpenAir_Sales_Order_Type__c</fullName>
        <description>The Classification Type of the Sales Order taken from the OpenAir (PS) system</description>
        <label>PS Sales Order Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-Critical</fullName>
                </value>
                <value>
                    <fullName>2-High</fullName>
                </value>
                <value>
                    <fullName>3-Medium</fullName>
                    <default>true</default>
                    <label>3-Medium</label>
                </value>
                <value>
                    <fullName>4-Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SML_Not_Include__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SML Not Include</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order (Sold To)</relationshipLabel>
        <relationshipName>Sold_To_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Instructions__c</fullName>
        <label>Special Instructions</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subsidaries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subsidary</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Subsidary__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subsidary__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Integrator_Information__c</fullName>
        <label>System Integrator Information</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Order__c</fullName>
        <description>USD Equivalent</description>
        <label>Total Order $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_PS_Charges__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order PS Charges</label>
    <nameField>
        <label>Order PS Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order PS Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidary__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Invoice_Footer__c</fullName>
        <label>Billing Invoice Footer</label>
        <length>10000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subsidary</label>
    <nameField>
        <label>Subsidary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OrderPSChargesTriggerHandlerTest.cls
@isTest (seeAllData = true)
private class OrderPSChargesTriggerHandlerTest {

    @isTest static void setup() 
    {
    
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Order__c; 
        Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
         
        Account accObj = new Account();
        accObj.Phone = '02079918888';                            // Phone
        accObj.Website = 'http://www.hsbc.com';                  // Website
        accObj.SicDesc = 'Bank Holding Companies';               // SIC Description
        accObj.NaicsCode = '551111';                             // NAICS Code
        accObj.YearStarted = '2001';                             // Year Started
        accObj.Name = 'Offices of Bank Holding Companies';       // NAICS Description
        accObj.Tradestyle = 'Hsbc';                              // Tradestyle
        accObj.Type = 'Customer';                                // Type
        accObj.Industry = 'Banking';                             // Industry
        accObj.RecordTypeId  =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('EMG - Customer Record Type').getRecordTypeId();
        insert accObj;
        
        Subsidary__c Ssobj = new Subsidary__c();
        Ssobj.Name = '8325';                             // Subsidary Name
        Ssobj.Active__c = true;                          // Active
        Ssobj.Description__c = '8325 Netherlands';       // Description
        Ssobj.Billing_Invoice_Footer__c = 'Questions';   // Billing Invoice Footer
        insert Ssobj;
        
        Opportunity OppObj = new Opportunity();
        OppObj.Account = accObj;                                                      // Account Name
        OppObj.StageName = '6.Closed';                                                // Stage
        OppObj.Name = 'PS-1-1601388970-HSBC - Contact Centre Transformation Program'; // Opportunity Name
        OppObj.CloseDate = Date.newInstance(2014,03,03);                              // Close Date
        OppObj.Type = 'New logo';                                                     // Type
        OppObj.Probability = 100;                                                     // Probability (%)
        //insert OppObj;
        
        Order__c sobj = new Order__c();
        sobj.Name = 'PS-108817-10126-1';                                              // Order Name
        sobj.Order__c = 'PS-108817-10126';                                            // Order #
        sobj.Status__c = 'Completed';                                                 // Status
        sobj.PO_Number__c = 'DO8590860';                                              // PO Number
        sobj.PO_Date__c = Date.newInstance(2017,03,03);                               // PO Date
        sobj.Order_Type__c = 'Revenue';                                               // Order Type
        sobj.Special_Instructions__c = 'Cons 2678 @ 190.93 and PM 1792.75 @ 206.20';  // Special Instructions
        sobj.Priority__c = '3-Medium';                                                // Priority
        sobj.Payment_Terms__c = 'Due 42 days from invoice date';                      // Payment Terms
        sobj.License_FYM_detail__c = 'PS Orders';                                     // License/FYM detail
        sobj.Opportunity_Type__c = 'GEN_Opportunity_Record_Type_New';                 // Opportunity Type
        sobj.System_Integrator_Information__c = '16101-10126';                        // System Integrator Information
        sobj.OpenAir_Project_Number__c = '108817';                                    // OpenAir Project Number
        sobj.PS_OpenAir_Sales_Order_Line__c = '1-1601388970~DO8590860~Labor';         // PS OpenAir Sales Order Line
        sobj.PS_OpenAir_Sales_Order_Type__c = 'Labor';                                // PS OpenAir Sales Order Type
        sobj.PS_OpenAir_Invoice_Filter__c = 'Time';                                   // PS OpenAir Invoice Filter
        sobj.Bypass_Service_Contract__c = false;                                      // Bypass Service Contract
        sobj.Bypass_Entitlements__c = false;                                          // Bypass Entitlements
        sobj.Exclude_From_Report__c = false;                                          // Exclude From Report
        sobj.Delivery_Method__c = 'No Delivery Required';                             // Delivery Method
        sobj.Total_Order__c = 880975.65;                                              // Total Order $
        sobj.SML_Not_Include__c = false;                                              // SML Not Include
        sobj.Total_Hours__c = 4470.75;                                                // Total Hours
        sobj.Date_Submitted__c = Date.newInstance(2017,03,03);                        // Submitted Date
        sobj.Invoiced__c = true;                                                      // Invoiced?
        sobj.ERP_Hold__c = true;                                                      // ERP Hold
        sobj.Due_Date__c = Date.newInstance(2017,03,03);                              // Due Date
        sobj.Invoice_Number__c = 'INV-8325-30890';                                    // Invoice Number
        sobj.Net_Suite_Order__c = 'SO-8325-27602';                                    // Net Suite Order #
        sobj.Invoice_Date__c = Date.newInstance(2017,03,03);                          // Invoice Date
        sobj.Order_Date__c = Date.newInstance(2017,03,03);                            // Order Date
        sobj.Order_Number__c = 'SO-8325-27602';                                       // Order Number
        sobj.RecordTypeId  = AccountRecordTypeInfo.get('PS Orders').getRecordTypeId();// Record Type
        //sobj.Opportunity__c = OppObj.Id;                                              // Opportunity Name
        //sobj.Subsidaries__c = Ssobj.Id;                                               // Subsidary
        //sobj.End_User_Name__c = accObj.Id;                                            // End User
        //sobj.Sold_To_Name__c = accObj.Id;                                             // Sold To Name
        //sobj.Bill_To_Name__c = accObj.Id;                                             // Bill To
        //sobj.Ship_To_Name__c = accObj.Id;                                             // Ship To Name
        insert sobj;
        
        List<Order_PS_Charges__c> listPsCharges = new List<Order_PS_Charges__c>();
        Order_PS_Charges__c orderpsCharges = new Order_PS_Charges__c();
        orderpsCharges.Name = 'Galluppi, Alessio';                               // Order PS Charge Name
        orderpsCharges.product_Name__c = 'Regular Consulting - (USD All - Org)'; // product Name
        orderpsCharges.Order_PS_Charge__c =sobj.Id;
        orderpsCharges.Hours__c=100;
        orderpsCharges.Minutes__c=10;
        orderpsCharges.Charge_Type__c='T';
        listPsCharges.add(orderpsCharges);
        
        Order_PS_Charges__c orderpsCharges1 = new Order_PS_Charges__c();
        orderpsCharges1.Name = 'Galluppi, Alessio';                               // Order PS Charge Name
        orderpsCharges1.product_Name__c = 'Regular Consulting - (USD All - Org)'; // product Name
        orderpsCharges1.Order_PS_Charge__c =sobj.Id;
        orderpsCharges1.Hours__c=100;
        orderpsCharges1.Minutes__c=10;
        orderpsCharges1.Charge_Type__c='T';
        listPsCharges.add(orderpsCharges1);
        
        insert listPsCharges; 
        
    }
    
    static testMethod void PreEvaluationDocuments_Test() {
        
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Order__c; 
        Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        
        Order__c sobj = new Order__c();
        sobj.Name = 'PS-108817-10126-1';                                              // Order Name
        sobj.Order__c = 'PS-108817-10126';                                            // Order #
        sobj.Status__c = 'Completed';                                                 // Status
        sobj.PO_Number__c = 'DO8590860';                                              // PO Number
        sobj.PO_Date__c = Date.newInstance(2017,03,03);                               // PO Date
        sobj.Order_Type__c = 'Revenue';                                               // Order Type
        sobj.Special_Instructions__c = 'Cons 2678 @ 190.93 and PM 1792.75 @ 206.20';  // Special Instructions
        sobj.Priority__c = '3-Medium';                                                // Priority
        sobj.Payment_Terms__c = 'Due 42 days from invoice date';                      // Payment Terms
        sobj.License_FYM_detail__c = 'PS Orders';                                     // License/FYM detail
        sobj.Opportunity_Type__c = 'GEN_Opportunity_Record_Type_New';                 // Opportunity Type
        sobj.System_Integrator_Information__c = '16101-10126';                        // System Integrator Information
        sobj.OpenAir_Project_Number__c = '108817';                                    // OpenAir Project Number
        sobj.PS_OpenAir_Sales_Order_Line__c = '1-1601388970~DO8590860~Labor';         // PS OpenAir Sales Order Line
        sobj.PS_OpenAir_Sales_Order_Type__c = 'Labor';                                // PS OpenAir Sales Order Type
        sobj.PS_OpenAir_Invoice_Filter__c = 'Time';                                   // PS OpenAir Invoice Filter
        sobj.Bypass_Service_Contract__c = false;                                      // Bypass Service Contract
        sobj.Bypass_Entitlements__c = false;                                          // Bypass Entitlements
        sobj.Exclude_From_Report__c = false;                                          // Exclude From Report
        sobj.Delivery_Method__c = 'No Delivery Required';                             // Delivery Method
        sobj.Total_Order__c = 880975.65;                                              // Total Order $
        sobj.SML_Not_Include__c = false;                                              // SML Not Include
        sobj.Total_Hours__c = 4470.75;                                                // Total Hours
        sobj.Date_Submitted__c = Date.newInstance(2017,03,03);                        // Submitted Date
        sobj.Invoiced__c = true;                                                      // Invoiced?
        sobj.ERP_Hold__c = true;                                                      // ERP Hold
        sobj.Due_Date__c = Date.newInstance(2017,03,03);                              // Due Date
        sobj.Invoice_Number__c = 'INV-8325-30890';                                    // Invoice Number
        sobj.Net_Suite_Order__c = 'SO-8325-27602';                                    // Net Suite Order #
        sobj.Invoice_Date__c = Date.newInstance(2017,03,03);                          // Invoice Date
        sobj.Order_Date__c = Date.newInstance(2017,03,03);                            // Order Date
        sobj.Order_Number__c = 'SO-8325-27602';                                       // Order Number
        sobj.RecordTypeId  = AccountRecordTypeInfo.get('PS Orders').getRecordTypeId();// Record Type
        //sobj.Opportunity__c = OppObj.Id;                                              // Opportunity Name
        //sobj.Subsidaries__c = Ssobj.Id;                                               // Subsidary
        //sobj.End_User_Name__c = accObj.Id;                                            // End User
        //sobj.Sold_To_Name__c = accObj.Id;                                             // Sold To Name
        //sobj.Bill_To_Name__c = accObj.Id;                                             // Bill To
        //sobj.Ship_To_Name__c = accObj.Id;                                             // Ship To Name
        insert sobj;
        
        List<Order_PS_Charges__c> listPsCharges = new List<Order_PS_Charges__c>();
        Order_PS_Charges__c orderpsCharges = new Order_PS_Charges__c();
        orderpsCharges.Name = 'Galluppi, Alessio';                               // Order PS Charge Name
        orderpsCharges.product_Name__c = 'Regular Consulting - (USD All - Org)'; // product Name
        orderpsCharges.Order_PS_Charge__c =sobj.Id;
        orderpsCharges.Hours__c=100;
        orderpsCharges.Minutes__c=10;
        orderpsCharges.Rate__c=111.00;
        orderpsCharges.Charge_Type__c='T';
        listPsCharges.add(orderpsCharges);
        
        Order_PS_Charges__c orderpsCharges1 = new Order_PS_Charges__c();
        orderpsCharges1.Name = 'Galluppi, Alessio';                               // Order PS Charge Name
        orderpsCharges1.product_Name__c = 'Regular Consulting - (USD All - Org)'; // product Name
        orderpsCharges1.Order_PS_Charge__c =sobj.Id;
        orderpsCharges1.Hours__c=100;
        orderpsCharges1.Minutes__c=10;
        orderpsCharges1.Rate__c=140.00;
        orderpsCharges1.Charge_Type__c='T';
        listPsCharges.add(orderpsCharges1);
        
        insert listPsCharges;
        
        Test.startTest();
        UpdateOrderPSChargesBatch  obj = new UpdateOrderPSChargesBatch();
        DataBase.executeBatch(obj); 
        Test.stopTest();
        
        ApexPages.StandardController sc = new ApexPages.standardController(sobj);
        OrderSummaryOfPSChargesExt ext = new OrderSummaryOfPSChargesExt(sc);
        //PageReference pageRef = Page.OrderSummaryOfPSCharges;
        //Test.setCurrentPage(pageRef);
    }
    
}