objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? To set up the relationship between order and pure cloud quote.
Downstream Impact? Carried over to the order
Which department is owner? Sales Ops/Order Management</description>
        <inlineHelpText>If there is a Zuora Quote for this order, this is its lookup to that Quote</inlineHelpText>
        <label>Zuora Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Order_Quote_Attachment_Class.cls
public with sharing class Order_Quote_Attachment_Class {

    List<Attachment> attachments ;
    private final Order__c order;
    Public Boolean noAtchmnts {get;set;}

    public Order_Quote_Attachment_Class(ApexPages.StandardController controller) {
    attachments = new List<Attachment>();
    this.order = (Order__c)controller.getRecord();    
    }
    
    public Order__c getorder() {
     return order;  
    }
    
    
    public List<Attachment> getAllAtachments()
    {
     Order__c newOrd = [Select Id,Quote__c,Zuora_Quote__c from Order__c where id=:order.Id];
     if(newOrd != null)
     {
         if(newOrd.Quote__c != null) 
         {    
             attachments = [SELECT Name,Description,LastModifiedById FROM Attachment WHERE ParentID =:newOrd.Quote__c];
         }
         else if(newOrd.Zuora_Quote__c != null) 
         {
             attachments = [SELECT Name,Description,LastModifiedById FROM Attachment WHERE ParentID =:newOrd.Zuora_Quote__c];
         }
     }
     return attachments;
    }
}