objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Direct_Sales__c</fullName>
        <formula>if(Opportunity__r.Direct_Sales__c,&apos;Yes&apos;,&apos;No&apos;)</formula>
        <label>Direct Sales</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders(Revenue/Non-Revenue)</relationshipLabel>
        <relationshipName>End_User_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Oppty_Approval_Status__c</fullName>
        <description>What it does? Provides a lookup reference to the status of the OM team opportunity approval for an associated PS Opportunity it this is a PS Order record
Owner? Order Management/Professional Services/IT</description>
        <formula>IF(  ISPICKVAL(License_FYM_detail__c, &apos;PS Orders&apos;),
  TEXT(Opportunity__r.Finance_Oppty_Approval_Status__c), 
 &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Finance Opportunity Approval Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_FYM_detail__c</fullName>
        <label>License/FYM detail</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>License only order</fullName>
                </value>
                <value>
                    <fullName>Maintenance Only Order</fullName>
                </value>
                <value>
                    <fullName>Both License &amp; Maintenance Order</fullName>
                </value>
                <value>
                    <fullName>PPU Order</fullName>
                </value>
                <value>
                    <fullName>PS Orders</fullName>
                </value>
                <value>
                    <fullName>Cloud Billing Order</fullName>
                </value>
                <value>
                    <fullName>AppFoundry Order</fullName>
                </value>
                <value>
                    <fullName>Hardware Order</fullName>
                </value>
                <value>
                    <fullName>Rental Order</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Cloud Billing</fullName>
                </value>
                <value>
                    <fullName>Cloud Order</fullName>
                </value>
                <value>
                    <fullName>Cloud Premier Billing Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Lines_with_POB_Mismatch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>What it Does? Indicates whether an Order has a POB Type present which is not matched to the POB Types on the linked opportunity (used for PS initially)
Downstream Impact? Will limit an order from being processed if there is a POB Type mismatch
Owner? IT/RevPro team</description>
        <label>Order Lines with POB Mismatch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order (Sold To)</relationshipLabel>
        <relationshipName>Sold_To_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Instructions__c</fullName>
        <label>Special Instructions</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>Text( Opportunity__r.Type )</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>PS_Orders</fullName>
        <active>true</active>
        <label>PS Orders</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Name__c</fullName>
        <label>End User Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POB_Type__c</fullName>
        <description>What it Does? RevPro : Store the POB Type 
Downstream Impact? RevPro integration 
Which department is owner? IT</description>
        <label>POB Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>POB_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <label>Sold To Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/POB_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Cloud-Committed</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud-Ramp-Uncommitted</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud-Uncommitted</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware Support</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware Support Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Latitude License - Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Latitude License - Perpetual</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance - FYM</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Perpetual License</fullName>
    </customValue>
    <customValue>
        <fullName>Premise Subscription - Committed</fullName>
    </customValue>
    <customValue>
        <fullName>Premise Uncommitted - Usage</fullName>
    </customValue>
    <customValue>
        <fullName>PS - CAS</fullName>
    </customValue>
    <customValue>
        <fullName>PS - CAS - Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Expert App</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Fixed Fee on Date</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Fixed Price Percent Complete</fullName>
    </customValue>
    <customValue>
        <fullName>PS - T&amp;M</fullName>
    </customValue>
    <customValue>
        <fullName>PureSuccess Token</fullName>
    </customValue>
    <customValue>
        <fullName>Royalties</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Training On Demand</fullName>
    </customValue>
    <customValue>
        <fullName>Upon Booking Ratable</fullName>
    </customValue>
    <customValue>
        <fullName>Point In Time - Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>PS - Variable Model</fullName>
    </customValue>
    <customValue>
        <fullName>Over Time - TAM</fullName>
    </customValue>
    <customValue>
        <fullName>Over Time - PS Fee</fullName>
    </customValue>
    <masterLabel>POB Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/PSOrderPOBTypeCheck_Test.cls
//Nik Mills - 09-Sep-2019
//For code coverage and testing of the PSOrderPOBTypeCheck helper class
@IsTest(SeeAllData=true)
public class PSOrderPOBTypeCheck_Test
{
    static Opportunity testPSOpp;
    static Opportunity testCASOpp;
    static Order__c testOrder;
    static Order__c testPSOrder;
    
    static testMethod void testaPSPOBCheckBypassedForCancelled()
    {
        List<Order__c> allOrders = new List<Order__c>();
    
        createOrderTestData();
        testOrder.Status__c = 'Cancelled';
        
        Test.StartTest();
        update testOrder;
        
        allOrders.add(testOrder);
        
        PSOrderPOBTypeCheck.CheckPSOrderPOBTypeMatchesForRevPro(allOrders, null);
        
        System.AssertEquals(true, testOrder.Order_Lines_with_POB_Mismatch__c == false, 'testOrder Order Lines with mismatch is not false');
        
        Test.StopTest();
    }
   
    static testMethod void testbPSOrderPOBTypeMismatched()
    {
        List<Opportunity> AllOpps = new List<Opportunity>();
        List<OpportunityLineItem> testOppProds;
        List<Order__c> allOrders = new List<Order__c>();
       
        createPSOpptyTestData();
        AllOpps.add(testPSOpp);

        List<Pricebook2> pBook = [SELECT Id, Name
                                  FROM Pricebook2
                                  WHERE Name =: 'Professional Services'];

        List<PriceBookEntry> pbEntry = [SELECT Id, Product2Id, PriceBook2.Name, CurrencyIsoCode
                                        FROM PriceBookEntry
                                        WHERE PriceBook2Id =: pBook[0].Id AND IsActive = true AND CurrencyIsoCode =: 'USD'];

        Util.Bypass_Trigger_Chk = true;
                                                         
        OpportunityLineItem oli1 = new OpportunityLineItem(OpportunityId=testPSOpp.Id, PriceBookEntryId=pbEntry[0].Id, Quantity=1, UnitPrice=4000, POB_Type__c='PS - T&M', Description__c='Test OLI Item 1 - PS T&M');
        OpportunityLineItem oli2 = new OpportunityLineItem(OpportunityId=testPSOpp.Id, PriceBookEntryId=pbEntry[0].Id, Quantity=1, UnitPrice=2500, POB_Type__c='PS - Expert App', Description__c='Test OLI Item 2 - ExpApp');

        insert oli1;
        insert oli2;

        Product2 testProduct = TestUtil.createProducts(1, false)[0];
        testProduct.Type__c = 'Professional Services';
        testProduct.zqu__SKU__c = 'OppTest123';
        testProduct.Description = 'Custom App Support (Testing)';
        testProduct.POB_Type__c = 'PS - CAS';
        insert testProduct;

        List<Product2> list_ofProduct2 = new List<Product2>();
        list_ofProduct2.add(testProduct);

        createPSOrderTestData();
        testPSOrder.Opportunity__c = testPSOpp.Id;
        
        Order_Line_Item__c orderli1 = TestUtil.createOrderLines(list_ofProduct2, testPSOrder.id, false)[0];
        orderli1.POB_Type__c = 'PS - CAS';
        insert orderli1;

        allOrders.add(testPSOrder);

        Util.Bypass_Trigger_Chk = false;
        
        Test.StartTest();

        testPSOrder.Special_Instructions__c = 'Testing';
        update testPSOrder;
        
        PSOrderPOBTypeCheck.CheckPSOrderPOBTypeMatchesForRevPro(allOrders, null);
        
        Test.StopTest();

        //List<Order__c> orders = [SELECT Id, Order_Lines_with_POB_Mismatch__c FROM Order__c WHERE Id = :testPSOrder.Id];

        //for (Order__c o : orders)
        //{
        //    System.AssertEquals(true, o.Order_Lines_with_POB_Mismatch__c == true, 'The value of PS POB Mismatch was not set to True');
        //}
    }
    
    
    // Create a PS Specific standalone test opportunity
    static void createPSOpptyTestData() {
        Util.Bypass_Trigger_Chk = true;
        
        List < RecordType > rtypes = [Select Id from RecordType where SobjectType = 'Opportunity'
            and DeveloperName =: 'Professional_Services'
        ];
        
        List <Pricebook2> pBook = [SELECT Id, Name
                                                FROM Pricebook2
                                                WHERE Name =: 'Professional Services'];
        
        Account acc = TestUtil.createAccounts(1, true)[0];
        testPSOpp = new Opportunity( Name='Test Opp', accountId = acc.Id );
        testPSOpp.RecordTypeId = rtypes[0].Id;
        testPSOpp.closeDate = Date.today().addMonths(1);
        testPSOpp.CurrencyIsoCode = 'USD';       
        testPSOpp.StageName = '1.Recognize Needs';     
        testPSOpp.Lines_of_Businesses__c = 'PureEngage';
        testPSOpp.PS_Parent_Opp_Not_Linked_Reason__c = 'Other';
        testPSOpp.Direct_Sales__c = true;
        testPSOpp.PriceBook2Id = pBook[0].Id;
        testPSOpp.Finance_Oppty_Approval_Status__c = 'Approved';
        
        insert testPSOpp;
        Util.Bypass_Trigger_Chk = false; 
    }

    static void createOrderTestData() {
        Util.Bypass_Trigger_Chk = true;
        
        List < RecordType > rtypes = [Select Id from RecordType where SobjectType = 'Order__c'
            and DeveloperName =: 'PS_Orders'
        ];
        
        testOrder = TestUtil.createOrders(1, true)[0];
        testOrder.RecordTypeId = rtypes[0].Id;
        
        Util.Bypass_Trigger_Chk = false;
    }

    static void createPSOrderTestData() {
        List<Order__c> orders = new List<Order__c>();
        
        Account acc = TestUtil.createAccounts(1, true)[0];    

        List < RecordType > rtypes = [Select Id from RecordType where SobjectType = 'Order__c'
            and DeveloperName =: 'PS_Orders'
        ];

        testPSOrder = new Order__c();
        testPSOrder.Name = 'PS - TEST Order 1';
        testPSOrder.Order__c = 'PS - Test Order 1';
        testPSOrder.License_FYM_detail__c = 'PS Orders';
        testPSOrder.RecordTypeId = rtypes[0].Id;
        testPSOrder.Status__c = 'Submitted';
        testPSOrder.End_User_Name__c = acc.Id;
        testPSOrder.Sold_To_Name__c = acc.Id;
         
        insert testPSOrder;
    }

}