objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Maintenance_End__c</fullName>
        <label>Maint. End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maintenance_Start__c</fullName>
        <label>Maint. Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Completed_by_AE__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>this flag will trigger email notification to RCL</inlineHelpText>
        <label>Order Completed by CM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Bundles__c</fullName>
        <inlineHelpText>Product bundles used for NRO Partner orders</inlineHelpText>
        <label>Product Bundles Labs</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Core Bundle</fullName>
                </value>
                <value>
                    <fullName>Developer Bundle</fullName>
                </value>
                <value>
                    <fullName>Advanced Solution</fullName>
                </value>
                <value>
                    <fullName>Advisor Bundle</fullName>
                </value>
                <value>
                    <fullName>BEP Bundle</fullName>
                </value>
                <value>
                    <fullName>PureConnect Labs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <description>for a Partner order request</description>
        <inlineHelpText>This box is if you need to add products not included in the bundles or remove products that you don’t need in the bundles. Please include the product name, version, and quantity.</inlineHelpText>
        <label>Product Description</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Group_Account_Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Party_Account</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order (Sold To)</relationshipLabel>
        <relationshipName>Sold_To_Name2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                    <default>true</default>
                    <label>Internal</label>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-Submitted</fullName>
                </value>
                <value>
                    <fullName>Send to ERP</fullName>
                </value>
                <value>
                    <fullName>Processed In ERP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Partner_Portal_Deal_Registration_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Lab_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lab Order</label>
        <type>Checkbox</type>
    </fields>
    <label>Partner Portal Tabs and Sections Config</label>
</CustomObject>

classes/PartnerNROrderController.cls
public class PartnerNROrderController {
    
    public List<Order__c> orderLst {get; set;}
    public Boolean canAccess {get; set;}
    public String orderId {get; set;}
    
    public PartnerNROrderController() {
        
        String NROrderPartnerType = '';
        List<Partner_Portal_Deal_Registration_Config__c> partnerConfig = Partner_Portal_Deal_Registration_Config__c.getall().values();
        for(Partner_Portal_Deal_Registration_Config__c ppdr: partnerConfig){
            if(ppdr.Lab_Order__c == true){
                if(NROrderPartnerType == '')
                    NROrderPartnerType = '\''+ppdr.Name+'\'';
                else 
            		NROrderPartnerType = NROrderPartnerType + ', \''+ppdr.Name+'\'' ;
            }
        }
        
        String query = 'SELECT Id, Contact.Account.Id FROM User WHERE id = \''+UserInfo.getUserId()+'\' AND Contact.Account.PartnerType__c INCLUDES (' +NROrderPartnerType+ ')';
        List<User> usr = Database.query(query);
        /*
        List<User> usr = [SELECT Id, Contact.Account.Id 
                          FROM User 
                          WHERE id =: UserInfo.getUserId()
                          AND Contact.Account.PartnerType__c 
                          INCLUDES ('VAR','Specialized Reseller','Cloud Partner','Managed Services Provider')];
        */
        canAccess = usr.isEmpty() ? false : true;
        
        if ( canAccess )  {
            orderLst = [SELECT Id, Name, Status__c, Product_Description__c, CreatedDate,
                        Product_Bundles__c, CreatedBy.Name, CreatedBy.Id,
                        Maintenance_End__c, Maintenance_Start__c, Order_Completed_by_AE__c
                        FROM Order__c
                        WHERE Sold_To_Name__c = :usr[0].Contact.Account.Id
                        AND Source__c = 'Web'
                        AND CreatedDate = LAST_N_DAYS:365
                        ORDER BY CreatedDate DESC];
        }
        
    }
    
    public PageReference openRequestForm()  {        
        return new PageReference('/partner/apex/PartnerNROrderForm');  
    }
    
    public PageReference showDetails() {
        
        return new PageReference('/partner/apex/PartnerNROrderDetails?Id=' + orderId);        
    }
    
    public PageReference editRequestForm()  {        
        return new PageReference('/partner/apex/PartnerNROrderForm?Id=' + orderId);  
    }
    
    
}