objects/partner_portal_prospect__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Company_Name__c</fullName>
        <label>Customer Company Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Portal Opportunity Registration (End User Account)</relationshipLabel>
        <relationshipName>Partner_Portal_Opportunity_Registration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genesys_AE__c</fullName>
        <label>Account Executive at Genesys</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Offer__c</fullName>
        <description>What it Does? Stores list of lead offers.
Downstream Impact? N/A 
Which department is owner? IT
DL 1/16/19 Requested to update label only to Lead Platform</description>
        <inlineHelpText>The combination of previous platform type &amp; offering type selections made to classify a deal registration</inlineHelpText>
        <label>Lead Platform</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Lead_Offer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Currency__c</fullName>
        <description>need to remove Australian and Canadian Dollar for opportunity type GEN - Opportunity Record Type</description>
        <label>Opportunity Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USD - U.S. Dollar</fullName>
                    <default>true</default>
                    <label>USD - U.S. Dollar</label>
                </value>
                <value>
                    <fullName>BRL - Brazilian Real</fullName>
                </value>
                <value>
                    <fullName>GBP - British Pound</fullName>
                </value>
                <value>
                    <fullName>EUR - Euro</fullName>
                </value>
                <value>
                    <fullName>JPY - Japanese Yen</fullName>
                </value>
                <value>
                    <fullName>AUD - Australian Dollar</fullName>
                </value>
                <value>
                    <fullName>CAD - Canadian Dollar</fullName>
                </value>
                <value>
                    <fullName>NZD - New Zealand Dollar</fullName>
                </value>
                <value>
                    <fullName>SGD - Singapore Dollar</fullName>
                </value>
                <value>
                    <fullName>ZAR - South African Rand</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request Submitted</fullName>
                    <default>true</default>
                    <label>Request Submitted</label>
                </value>
                <value>
                    <fullName>Request Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_is_the_Expected_Close_Date__c</fullName>
        <label>What is the Expected Close Date?</label>
        <type>Date</type>
    </fields>
    <label>Partner Portal Opportunity Registration</label>
    <nameField>
        <label>Customer Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Opportunity Registration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Lead_Offer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PureCloud</fullName>
    </customValue>
    <customValue>
        <fullName>PureConnect Premise</fullName>
    </customValue>
    <customValue>
        <fullName>PureEngage Premise</fullName>
    </customValue>
    <customValue>
        <fullName>PureConnect Premise Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>PureEngage Premise Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>PureConnect Premise Rental</fullName>
    </customValue>
    <customValue>
        <fullName>PureEngage Premise Rental</fullName>
    </customValue>
    <customValue>
        <fullName>PureConnect Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>PureEngage Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>PureEngage Cloud Partner PPU</fullName>
    </customValue>
    <customValue>
        <fullName>PureConnect Cloud Partner PPU</fullName>
    </customValue>
    <customValue>
        <fullName>Premier Edition Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Outbound Engagement Cloud</fullName>
    </customValue>
    <description>List of lead offers.</description>
    <masterLabel>Lead Offer</masterLabel>
</GlobalValueSet>

classes/PartnerPortalRegistration_Class_Test.cls
@isTest (seeAllData=true)
public class PartnerPortalRegistration_Class_Test {
    
    private static partner_portal_prospect__c  pOpp1;
    private static Account  acnt;
    private static Contact cnt;
    private static User user;

    static testMethod void testMethod_1() {
        Test.startTest();
        Profile partnerProfile = [SELECT id FROM Profile WHERE Name = 'Genesys Portal End User' LIMIT 1];       
        Account testAccount = TestUtil.createAccounts(1, true)[0];
        Contact testContact = TestUtil.createContacts(1, testAccount, true)[0];
        User testUser;
        Test.stopTest();
        testUser = TestCommon.createUser('testU', 'testUser132@test132.com.test', 'Test', 'Test', partnerProfile.id, false);        
        testUser.ContactId = testContact.id;
        insert testUser;
        
        System.runAs(testUser){
            
            pOpp1 = new partner_portal_prospect__c
                                ( Name='Test Account', Customer_Company_Name__c = 'Customer Company Name', Status__c = 'Request Submitted', Genesys_AE__c='exec',
                                Opportunity_Currency__c = 'USD - U.S. Dollar',Lead_Offer__c='PureConnect Premise', End_User_Account__c=testAccount.id, What_is_the_Expected_Close_Date__c=system.today());
                                               
            List<Product2> prd = [select id,name from product2 where isActive=true limit 2]; 
           //insert pOpp1 ;
            ApexPages.StandardController sc1 = new ApexPages.standardController(pOpp1);                
            PartnerPortalRegistration_Class controller1 = new PartnerPortalRegistration_Class(sc1); 
            controller1.oppProdsTab1.add(new PartnerPortalRegistration_Class.oppProduct(prd[0], 1));
            controller1.oppProdsTab1.add(new PartnerPortalRegistration_Class.oppProduct(prd[1], 2));
            //controller1.resetCurriency();
            if ( !controller1.oppProdsTab1.isEmpty() ) {
                controller1.oppProdsTab1[0].isSelected = true;
                controller1.oppProdsTab1[0].amount = '123';
            }
          //  PartnerPortalRegistration_Class.oppProduct  prdc = new PartnerPortalRegistration_Class.oppProduct(prd[0],0);
            controller1.opp.opportunity_Currency__c = 'USD';
            controller1.saveOpp();
            controller1.cancelOpp();  
            controller1.resetCurriency();  
            
        }
    }
}