objects/Partner_Application__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Applications</relationshipLabel>
        <relationshipName>Partner_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AnnualSalesRevenue_PL__c</fullName>
        <label>Annual Sales Revenue</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AppointOrDismissMD_PL__c</fullName>
        <label>Appoint Or Dismiss MD</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BannedEmployee_PL__c</fullName>
        <label>Banned Employee</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>this is description.</description>
        <inlineHelpText>Company Name (Full Legal Company Name including legal entity designation suffix (e.g. B.V., GmbH, S.P.A.))</inlineHelpText>
        <label>Company Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Conflict_of_Interest_PL__c</fullName>
        <label>Conflict of Interest</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Convicted_Executive_PL__c</fullName>
        <label>Convicted Executive</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CountryCurrentlyUnderUS_PL__c</fullName>
        <label>Country Currently Under US</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_or_Former_Genesys_Employee_PL__c</fullName>
        <label>Current or Former Genesys Employee</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExportEnforcementActivity_PL__c</fullName>
        <label>Export Enforcement Activity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Government_Veto_PL__c</fullName>
        <label>Government Veto</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ownership_PL__c</fullName>
        <label>Ownership</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PublicInternationalOrg_PL__c</fullName>
        <label>Public International Org</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RightToAppointOrDismiss_PL__c</fullName>
        <label>Right To Appoint Or Dismiss</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Application</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Partner Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PartnerApplicationAutoCancellBatchTest.cls
@isTest(seeAllData=true)
private class PartnerApplicationAutoCancellBatchTest {

    static testMethod void myUnitTest() {
    	Test.startTest();
    	Partner_Application__c pa = new Partner_Application__c();
    	pa.Company_Name__c = 'Test Company';
    	pa.Status__c = 'In Progress';
    	pa.Account__c = TestUtil.createAccounts(1, true)[0].id;
        pa.AnnualSalesRevenue_PL__c = 'No';
        pa.Ownership_PL__c = 'No';
        pa.RightToAppointOrDismiss_PL__c = 'No';
        pa.AppointOrDismissMD_PL__c = 'No';
        pa.Government_Veto_PL__c = 'No';
        pa.PublicInternationalOrg_PL__c = 'No';
        pa.Convicted_Executive_PL__c = 'No';
        pa.BannedEmployee_PL__c = 'No';
        pa.ExportEnforcementActivity_PL__c = 'No';
        pa.CountryCurrentlyUnderUS_PL__c = 'No';
        pa.Conflict_of_Interest_PL__c = 'No';
        pa.Current_or_Former_Genesys_Employee_PL__c = 'No';
    	insert pa;
    	PartnerApplicationAutoCancellationBatch obj = new PartnerApplicationAutoCancellationBatch(); 
    	Database.executeBatch(obj);
    	Test.stopTest();
    }
}