objects/Partner_Portal_Announcement__c.object
<CustomObject>
    <description>Announcements that show on various pages of the Partner Portal community.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description in partner portal slider</description>
        <inlineHelpText>Enter the Description of Announcement. If Read More link is required. Please add this piece of text and replace &apos;Description URL&apos; with actual URL link
&lt;a href=&quot;Description URL&quot; target=&quot;_blank&quot;&gt;Read More&lt;/a&gt;</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <description>Image URL location in http://xxxxxxxx/yyyy.jpeg format</description>
        <inlineHelpText>Image URL location in http://xxxxxxxx/yyyy.jpeg format</inlineHelpText>
        <label>Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title in partner portal slider images</description>
        <inlineHelpText>Title in partner portal slider images</inlineHelpText>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Used to separate Portal Announcement Records for Image Slider or for other purposes</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Portal Announcement</label>
    <nameField>
        <label>Partner Announcement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Portal_Banners_Controller.cls
public with sharing class Portal_Banners_Controller {

    public List<Partner_Portal_Announcement__c> announcementsList{get;set;}

    public Portal_Banners_Controller()
    {
        announcementsList = new List<Partner_Portal_Announcement__c>();
        for(Partner_Portal_Announcement__c rec : [Select Id,name,type__c,title__c,description__c,image__c from Partner_Portal_Announcement__c]){
            if(rec.type__c!=null && rec.type__c.equalsIgnoreCase('Banner'))
                announcementsList.add(rec);
        }
    } 

}