objects/Partner_KPI_Header_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partner_KPI1_Header_Stage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cases_Closed_by_Default_YTD__c</fullName>
        <label>Cases Closed by Default YTD</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cases_Closed_by_Default__c</fullName>
        <label>Cases Closed by Default</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Closed_By_Default__c</fullName>
        <label>Closed By Default</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Closure_Assessment_YTD__c</fullName>
        <label>Closure Assessment YTD</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Closure_Assessment__c</fullName>
        <label>Closure Assessment</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Name__c</fullName>
        <formula>Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period_From__c</fullName>
        <label>Period From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_To__c</fullName>
        <label>Period To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Problem_Description__c</fullName>
        <label>Problem Description</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quality_Assessment_YTD__c</fullName>
        <label>Quality Assessment YTD</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quality_Assessment__c</fullName>
        <label>Quality Assessment</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_Information__c</fullName>
        <label>Supporting Information</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_KPI_Score__c</fullName>
        <label>Total KPI Score</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_YTD_KPI_Score__c</fullName>
        <label>Total YTD KPI Score</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Training_Assessment_YTD__c</fullName>
        <label>Training Assessment YTD</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Assessment__c</fullName>
        <label>Training Assessment</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>YTD_Closed_By_Default__c</fullName>
        <label>YTD Closed By Default</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Partner KPI Header Stage</label>
    <nameField>
        <displayFormat>PKPI1-{00000}</displayFormat>
        <label>Partner KPI1 Header Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner KPI Header Stage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PartnerKPIHeadersExportController.cls
public class PartnerKPIHeadersExportController {
	public String selectedPeriod {get; set;} 
    public List<Partner_KPI_Header_Stage__c> kpiHeaders {get; set;}
    public PartnerKPIHeadersExportController(){
        selectedPeriod = ApexPages.currentPage().getParameters().get('sp');
        String selectedSoldToFilter = ApexPages.currentPage().getParameters().get('stfilter');
        String filterStr = 'WHERE Period__c = :selectedPeriod';
        if(selectedSoldToFilter != NULL && selectedSoldToFilter != '-- ALL --'){
            filterStr += ' AND Account__c = \'' + selectedSoldToFilter + '\'';
        }
        
        String query = 'SELECT id, Name, Unique_Key__c, Account__c, Account_Name__c, Partner_Name__c, Region__c, Period__c, Period_From__c, Period_To__c, Quarter__c, ' 
                     + 'Problem_Description__c, Supporting_Information__c, Closure_Assessment__c, Closure_Assessment_YTD__c,  Quality_Assessment__c, Quality_Assessment_YTD__c,'
                     + 'Training_Assessment__c, Training_Assessment_YTD__c, Cases_Closed_by_Default__c, Cases_Closed_by_Default_YTD__c, Total_KPI_Score__c, Total_YTD_KPI_Score__c,' 
                     + 'Closed_By_Default__c, YTD_Closed_By_Default__c FROM Partner_KPI_Header_Stage__c ' + filterStr;
        System.debug('query = ' + query);
        kpiHeaders  = Database.query(query);
        
    }
}