objects/Partner_Rebate__c.object
<CustomObject>
    <description>This object is responsible for storing Partner Rebate specific Information.</description>
    <fields>
        <fullName>Active_Days__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Rebate Validity Period in Days</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Name lookup to account</description>
        <label>Partner Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012U0000000Le3f</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>notEqual</operation>
                <value>Merged</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Rebates</relationshipLabel>
        <relationshipName>Partner_Rabates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publish_Date__c</fullName>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Published_to_Partner_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If published to Partner Portal then true else False</description>
        <label>Publish to Partner Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rebate_Name__c</fullName>
        <description>Name should be  Entered by the user</description>
        <label>Rebate Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rebate_Year__c</fullName>
        <description>Stores rebate Year</description>
        <label>Rebate Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Rebate</label>
    <nameField>
        <displayFormat>PR-{000000000}</displayFormat>
        <label>Partner Rebate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Rebates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PartnerRebateControllerTest.cls
@istest(seealldata=true)
public class PartnerRebateControllerTest{
        
    public static testmethod void Method1(){
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        system.debug('portalRole is ' + portalRole);
        
        Profile profile1 = [Select Id from Profile where name = 'Genesys Portal End User'];
        
        //Create account
        Account portalAccount1 = new Account();
        portalAccount1.Name = 'TestAccount';
        //portalAccount1.OwnerId = portalAccountOwner1.Id;        
        insert portalAccount1;
        
        //Create contact
        Contact contact1 = new Contact( );
        contact1.FirstName = 'Test6';
        contact1.Lastname = 'Test7';        
        contact1.AccountId = portalAccount1.Id;        
        contact1.HomePhone = '1236547890';
        contact1.MobilePhone = '9012345678';
        contact1.MailingStreet = 'xyz';
        contact1.MailingCity = 'CA';
        contact1.MailingState = 'calfornia';
        contact1.MailingPostalCode = '654321';
        contact1.MailingCountry = 'USA';              
        insert contact1;
        
        User portalAccountOwner1 = new User();
        //portalAccountOwner1.UserRoleId = portalRole.Id;
        portalAccountOwner1.ProfileId = profile1.Id;
        portalAccountOwner1.Username = 'Sriktest@test.com';
        portalAccountOwner1.Alias = 'Test1';
        portalAccountOwner1.Email='test1@test.com';
        portalAccountOwner1.EmailEncodingKey='UTF-8';
        portalAccountOwner1.Firstname='Test2';
        portalAccountOwner1.Lastname='Test3';
        portalAccountOwner1.LanguageLocaleKey='en_US';
        portalAccountOwner1.LocaleSidKey='en_US';
        portalAccountOwner1.TimeZoneSidKey='America/Chicago';
        portalAccountOwner1.ContactId = contact1.id;
        insert portalAccountOwner1;
        
        Partner_Rebate__c PR = new Partner_Rebate__c();
        PR.Rebate_Name__c= 'TestPR';
        insert PR;
        
        system.runas(portalAccountOwner1){
            
            PartnerPortal_PeriodicReview_Class prtnPrtlPerRevObj = new PartnerPortal_PeriodicReview_Class();
            PartnerRebateController obj1  = new PartnerRebateController(prtnPrtlPerRevObj);
            
            list<recordType> rtList = [SELECT id FROM recordType WHERE name = 'Enterprise - Business Partner'];
            
            //CREATE ACCOUNT
            account actObj = new account();
            actObj.name = 'actTest';
            actObj.Channel_Manager__c = userInfo.getUserId();
            if(rtList.size()> 0) {
                actObj.recordTypeId = rtList[0].id;
            }
            insert actObj;
            
            // CREATE CONTACT
            contact conObj = new contact();
            conObj.lastname = 'test';
            conObj.Designated_Partner_Contact__c = true;
            conObj.AccountId = actObj.id;
            conObj.Email = 'test@yahoo.com';
            insert conObj;
            
            //  CREATE Partner_Rebate__c
            Partner_Rebate__c partRevObj = new Partner_Rebate__c();
            partRevObj.Rebate_Year__c = '2015';
            partRevObj.Rebate_Name__c = 'test';
            partRevObj.Published_to_Partner_Portal__c = true;
            partRevObj.Active_Days__c = 5;
            partRevObj.Publish_Date__c = date.today();
            partRevObj.Partner_Name__c = actObj.id;
 //           insert partRevObj;
           
            
            ApexPages.standardController controller = new ApexPages.StandardController(partRevObj);
            PartnerRebateController obj2  = new PartnerRebateController(controller);
            obj2.saveTermsWithAgree();
            obj2.saveTermsWithDisagree();
            
            obj2.doCancel();
            obj2.isERPublished = true;
            obj2.isExpired = true;
            obj2.FlagYes = true;
        }
    }
}