objects/PKB_Article_Feedback_Deflection__c.object
<CustomObject>
    <description>Stores data about feedback provided to an article and any customer deflection the article may have contributed to.</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>7000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Feedback_Source__c</fullName>
        <label>Feedback Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ContactUs</fullName>
                </value>
                <value>
                    <fullName>Search</fullName>
                </value>
                <value>
                    <fullName>RelatedArticle</fullName>
                </value>
                <value>
                    <fullName>TutorialsPage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Article Feedback</label>
    <nameField>
        <displayFormat>AFD-{0000000}</displayFormat>
        <label>PKB Article Feedback</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TechTutorialsForm.cls
public with sharing class TechTutorialsForm {
public String inputText1{get;set;}
public void submitSuggestion() { 	
    PKB_Article_Feedback_Deflection__c afd = new PKB_Article_Feedback_Deflection__c(

      Feedback_Source__c = 'TutorialsPage',
      Comments__c = inputText1
    );
    try{
        afd.OwnerId = [SELECT Id,Name FROM Group WHERE Name ='Feedback' and Type = 'Queue' limit 1].Id;
    }catch(Exception e){

    }
    insert afd;
  }
}