objects/Product__c.object
<CustomObject>
    <description>What it does?  Object containing information about products associated with a DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipLabel>Product Mappings</relationshipLabel>
        <relationshipName>Product_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sellable_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sellable Item</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sellable Item Mappings</relationshipLabel>
        <relationshipName>Product_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Mapping</label>
    <nameField>
        <label>Product Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Mapping2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Support_Product__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Product_Name__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Parent_Product__r.Id,Parent_Product__r.Product_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipLabel>Support Products</relationshipLabel>
        <relationshipName>Support_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Support Product</label>
    <nameField>
        <label>Support Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DownloadsControllerWithoutSharing.cls
/*
Class	: DownloadsController
Author –  Vinay Lakshmeesh
Date –    3/28/2013
Usage   : Without Sharing class for DownloadsController.
Revision History
*/
public without sharing class DownloadsControllerWithoutSharing {
	
	public static List<ContractLineItem> queryContractLineItem(Set<Id> serviceContractIds){
		return [SELECT PricebookEntry.Name,
       				   PricebookEntry.Product2Id,
       				   ServiceContractId
				FROM ContractLineItem
				WHERE ServiceContractId IN :serviceContractIds];
	}
	
	public static List<Product_Mapping__c> queryProductMapping(Set<Id> productMapKeySet ){
		return [SELECT p.Product__r.Product_Type__c,
				       p.Product__r.Name,
				       p.Product__c,
				       p.Name,
				       p.Product__r.Parent_Product_Name__c,
				       p.Product__r.Parent_Product__c
				FROM Product_Mapping__c p
				WHERE 
				  //p.Product__r.Product_Type__c = 'Product'
				  //AND 
				  Product__r.Customer_Available__c = true and
				  Sellable_Item__c IN: productMapKeySet];
	}
	
	public static List<Support_Product__c> querySupportProd(Set<Id> prodMapkeySet){
		return [SELECT Id,Name,Parent_Product__c 
				FROM   Support_Product__c 
				WHERE  Customer_Available__c =true
				       AND Parent_Product__c in :prodMapkeySet 
					   AND Product_Type__c = 'Component'];
	}
	
}