objects/Product__c.object
<CustomObject>
    <description>What it does?  Object containing information about products associated with a DR.   Downstream Impact?  None.  Which Department is Owner?  Sales Ops.

Part of the DEMO REQUEST process.</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipLabel>Product Mappings</relationshipLabel>
        <relationshipName>Product_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sellable_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sellable Item</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sellable Item Mappings</relationshipLabel>
        <relationshipName>Product_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Mapping</label>
    <nameField>
        <label>Product Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Mapping2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Version__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipLabel>Product Versions</relationshipLabel>
        <relationshipName>Product_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Product Version</label>
    <nameField>
        <label>Product Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Support_Product__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Product_Name__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Parent_Product__r.Id,Parent_Product__r.Product_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Support_Product__c</referenceTo>
        <relationshipLabel>Support Products</relationshipLabel>
        <relationshipName>Support_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Version</label>
        <referenceTo>Product_Version__c</referenceTo>
        <relationshipLabel>Support Products</relationshipLabel>
        <relationshipName>Support_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Support Product</label>
    <nameField>
        <label>Support Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateCustPortalCaseExtnWithoutSharing.cls
/*****************************************************
Class: CreateCustPortalCaseExtnWithoutSharing
Author – Vinay Lakshmeesh
Date – 3/28/2013
Usage : Class for CreateCustomerPortalCaseExtenstion to run with without sharing
Revision History
******************************************************/

public without sharing class CreateCustPortalCaseExtnWithoutSharing {
	
	public static List<ContractLineItem> queryContractLineItem(Set<Id> serviceContractIds){
		return [Select PricebookEntry.Name,PricebookEntry.Product2Id,
					   ServiceContractId 
			    From   ContractLineItem 
			    where  ServiceContractId in :serviceContractIds];
	}
	
	public static List<Product_Mapping__c> queryProductMapping(Set<Id> prodMapKeySet){
		return [Select Id,p.Product__r.Product_Type__c, 
					   p.Product__r.Name, p.Product__c, 
					   p.Name,p.Product__r.Parent_Product_Name__c, 
					   p.Product__r.Parent_Product__c 
			    From   Product_Mapping__c p 
			    where  p.Product__r.Product_Type__c = 'Product' and 
			    	   Sellable_Item__c in: prodMapKeySet ];
	}
	/*
	public static List<Product_Mapping__c> queryProductMappingProLine(Set<Id> prodMapKeySet,Id proLineId){
		return [Select Id,p.Product__r.Product_Type__c, 
					   p.Product__r.Name, p.Product__c, 
					   p.Name,p.Product__r.Parent_Product_Name__c, 
					   p.Product__r.Parent_Product__c 
			    From   Product_Mapping__c p 
			    where  p.Product__r.Product_Type__c = 'Product' and 
			    	   Sellable_Item__c in: prodMapKeySet
			    	   and Product__r.Parent_Product__c =:proLineId];
	}
	
	public static List<Product_Mapping__c> queryProductMappingProd(Set<Id> prodMapKeySet,Id prodId){
		return [Select Id,p.Product__r.Product_Type__c, 
					   p.Product__r.Name, p.Product__c, 
					   p.Name,p.Product__r.Parent_Product_Name__c, 
					   p.Product__r.Parent_Product__c 
			    From   Product_Mapping__c p 
			    where  p.Product__r.Product_Type__c = 'Product' and 
			    	   Sellable_Item__c in: prodMapKeySet
			    	   and Product__c=:prodId];
	}*/
	
	public static List<Product_Mapping__c> queryProductMappingAll(Set<Id> prodMapKeySet,Set<String> prodId,Set<String> proLineId){
		system.debug('--|prodId'+prodId);
		system.debug('--|prodMapKeySet'+prodMapKeySet);
		system.debug('--|proLineId'+proLineId);
		String selectQuery = 'Select Id,Product__r.Product_Type__c, Product__r.Name, Product__c, Name,Product__r.Parent_Product_Name__c, Product__r.Parent_Product__c,Product__r.Customer_Available__c From   Product_Mapping__c  ';
		String WhereClause = ' where Product__r.Product_Type__c = \'Product\' and Sellable_Item__c in: prodMapKeySet and Product__r.Customer_Available__c = true';
		if(prodId!=null && prodId.size()>0){
			 WhereClause =  WhereClause + ' and Product__c in:prodId';
		}
		if(proLineId!=null  && proLineId.size()>0){
			WhereClause =  WhereClause + ' and Product__r.Parent_Product__c in:proLineId';
		}
		String Query;
		Query = selectQuery;
		if(WhereClause!=null){
			Query += WhereClause;
		}
		system.debug('--Query'+Query);
		return database.query(Query);
		/*return [Select Id,p.Product__r.Product_Type__c, 
					   p.Product__r.Name, p.Product__c, 
					   p.Name,p.Product__r.Parent_Product_Name__c, 
					   p.Product__r.Parent_Product__c 
			    From   Product_Mapping__c p 
			    where  p.Product__r.Product_Type__c = 'Product' and 
			    	   Sellable_Item__c in: prodMapKeySet
			    	   and Product__c in:prodId
			    	   and Product__r.Parent_Product__c in:proLineId];*/
	}
	public static List<Support_Product__c> querySupportProduct(List<Id> prodLineId){
		return [SELECT Id,Name,Parent_Product__c,Customer_Available__c 
				FROM   Support_Product__c 
				WHERE  Id IN :prodLineId AND Customer_Available__c =true];
	}
	
	public static List<Support_Product__c> querySupportProdComponent(Set<Id> prodMapkeySet){
		system.debug('--prodMapkeySet'+prodMapkeySet);
		return [SELECT Id,Name,Parent_Product__c,Customer_Available__c 
				FROM   Support_Product__c 
				WHERE  Parent_Product__c in :prodMapkeySet 
					   and Product_Type__c = 'Component' AND Customer_Available__c =true];
	}
	
	public static List<Product_Version__c> queryCompVersion(Id comp){
		return [SELECT Id,Version__c,Name 
		        FROM   Product_Version__c 
		        WHERE Parent_Product__c = :comp AND Customer_Available__c =true ORDER BY Name DESC];
	}
}