objects/PureCloud_Monthly_Minimum__c.object
<CustomObject>
    <description>Master object for the PureCloud monthly minimums by currency.</description>
    <fields>
        <fullName>Monthly_Minimum__c</fullName>
        <description>The monthly minimum for PureCloud in the currency of the record.</description>
        <inlineHelpText>The monthly minimum for PureCloud in the currency of the record.</inlineHelpText>
        <label>Monthly Minimum</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PureCloud Monthly Minimum</label>
    <nameField>
        <displayFormat>PMM-{0000}</displayFormat>
        <label>PureCloud Monthly Minimum Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PureCloud Monthly Minimums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PureCloudMonthlyMinimumFactory.cls
@isTest
public class PureCloudMonthlyMinimumFactory {
    
    public static List<PureCloud_Monthly_Minimum__c> createPureCloudMonthlyMinimums()
    {
        List<PureCloud_Monthly_Minimum__c> monthlyMinimums = new List<PureCloud_Monthly_Minimum__c>();

        monthlyMinimums.add(new PureCloud_Monthly_Minimum__c(
            CurrencyISOCode = 'USD',
            Monthly_Minimum__c = 2000
        )); 
        
        monthlyMinimums.add(new PureCloud_Monthly_Minimum__c(
            CurrencyISOCode = 'CAD',
            Monthly_Minimum__c = 2200
        ));

        return monthlyMinimums;
    }
}