objects/PureCloud_Trial__c.object
<CustomObject>
    <description>A method of requesting and tracking PureCloud preview and beta participants</description>
    <fields>
        <fullName>Service_Packages__c</fullName>
        <label>Service Packages</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PureCloud Bronze Annual Prepay Premier Success Service</fullName>
                </value>
                <value>
                    <fullName>PureCloud Silver Annual Prepay Premier Success Service</fullName>
                </value>
                <value>
                    <fullName>PureCloud Gold Annual Prepay Premier Success Service</fullName>
                </value>
                <value>
                    <fullName>PureCloud Platinum Annual Prepay Premier Success Service</fullName>
                </value>
                <value>
                    <fullName>PureCloud Bronze Monthly Premier Success Service</fullName>
                </value>
                <value>
                    <fullName>PureCloud Silver Monthly Premier Success Service</fullName>
                </value>
                <value>
                    <fullName>PureCloud Gold Monthly Premier Success Service</fullName>
                </value>
                <value>
                    <fullName>PureCloud Platinum Monthly Premier Success Service</fullName>
                </value>
                <value>
                    <fullName>PureCloud Services Tokens Bundle</fullName>
                </value>
                <value>
                    <fullName>PureCloud QuickStart Enablement (does not exist yet, new in Jan 2017)</fullName>
                </value>
                <value>
                    <fullName>PureCloud QuickStart Core Enablement (retiring 12/31/16)</fullName>
                </value>
                <value>
                    <fullName>PureCloud QuickStart Enhanced Enablement (retiring 12/31/16)</fullName>
                </value>
                <value>
                    <fullName>PureCloud QuickStart API Enablement (retiring 12/31/16)</fullName>
                </value>
                <value>
                    <fullName>PureCloud Engage Outbound Dialer Enablement Package (retiring 12/31/16)</fullName>
                </value>
                <value>
                    <fullName>PureCloud Bronze Success Package</fullName>
                </value>
                <value>
                    <fullName>PureCloud Silver Success Package</fullName>
                </value>
                <value>
                    <fullName>PureCloud Gold Success Package</fullName>
                </value>
                <value>
                    <fullName>PureCloud Foundation Package</fullName>
                </value>
                <value>
                    <fullName>PureCloud Services Tokens Bundle 1K MACD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PureCloud Project</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>PureCloud Project</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PureCloud Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PureCloudProjectUtil.cls
/************************************************************************************
Purpose : Utility class for methods related to PureCloud Project object
Written By : Ranjith Punneli
Test Classes : PureCloudProjectTest
*************************************************************************************/

public without sharing class PureCloudProjectUtil {

    public static Set<String> getServicePackagesPicklistVals()  {
        Set<String> set_ServicePackages = new Set<String>();
        DescribeFieldResult fieldResult = Schema.getGlobalDescribe().get('PureCloud_Trial__c').getDescribe().fields.getMap().get('Service_Packages__c').getDescribe();
        List<Schema.PicklistEntry> list_ServicePackages = fieldResult.getPicklistValues();
           
        for(Schema.PicklistEntry plSrvPackage : list_ServicePackages)  {
            set_ServicePackages.add((plSrvPackage.getValue().toLowerCase()));
        }   
        return set_ServicePackages;
    }
}