objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Add-On</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Non_Recurring_Fees__c</fullName>
        <label>Total Non-Recurring Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Proposal_Group__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <label>Group Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Quote Proposal Groups</relationshipLabel>
        <relationshipName>Quote_Proposal_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Proposal Group</label>
    <nameField>
        <displayFormat>PGN-{00000}</displayFormat>
        <label>Proposal Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Proposal Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Subscription__c.object
<CustomObject>
    <description>To store subscription for different offering types</description>
    <fields>
        <fullName>ACV__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores annual contract value
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Annual Contract Value.</inlineHelpText>
        <label>ACV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>What it Does? Stores end user account
Downstream Impact? Effects reporting and billing integration
Which department is owner? IT/PureCloud Team</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amendment_For__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Stores previous subscription which is amended
Downstream Impact? Effects reporting and billing integration
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Previous CCDB/Subscription record that this CCDB/Subscription amended.</inlineHelpText>
        <label>Amendment For</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>CCDBs/Subscriptions (Amendment For)</relationshipLabel>
        <relationshipName>NewSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMRR__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores monthly committed value
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Committed Monthly Recurring Revenue.</inlineHelpText>
        <label>CMRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Lookup to quote object which is approved
Downstream Impact? Effects reporting and quote amendment
Which department is owner? IT/PureCloud Team</description>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <description>What it Does? Stores term end date for this subscription
Downstream Impact? Effects reporting and billing
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Date in which the initial term or renewal term ends.</inlineHelpText>
        <label>Subscription Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <description>What it Does? Stores term start date for this subscription
Downstream Impact? Effects reporting and billing
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Date in which the initial term or renewal term begins, which is the start date plus the ramp period, if applicable.</inlineHelpText>
        <label>Subscription Term Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TAM_Services_Amount__c</fullName>
        <description>What it does? CCDB / renewal opportunity 
Downstream Impact? Renewal opportunity. 
Which Department is Owner? IT</description>
        <inlineHelpText>Total amount of Technical Account Manager (TAM) services purchased by customer.</inlineHelpText>
        <label>TAM Services Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TCV__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores total contract value
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Total Contract Value.</inlineHelpText>
        <label>TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Education__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores total education amount
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <label>Total Education</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Hardware__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores total hardware amount
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <label>Total Hardware</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Non_Recurring_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores total non recurring amount
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <label>Total Non Recurring Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Services__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores total services amount
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <label>Total Services</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CCDB/Subscription</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>CCDB/Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCDBs/Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProposalCloudControllerTest.cls
@isTest(seealldata=true)
private class ProposalCloudControllerTest {
    @isTest(seealldata=true)
    static void intialTest() {
        //Skipping all triggers as we do not need any updates from triggers for the purposes of this unit test
        Util.Bypass_Trigger_Chk = true;
        
        //Create account, opp and quote
        List<Account> list_NewAccts = TestDataFactoryForQuoteTool.createAccounts(1);
        System.assertEquals(list_NewAccts.size(), 1);
        List<Opportunity> list_NewOpps = TestDataFactoryForQuoteTool.createOpportunties(list_NewAccts[0].Id, 1);
        System.assertEquals(list_NewOpps.size(), 1);
        List<BigMachines__Quote__c> list_NewQuotes = TestDataFactoryForQuoteTool.createQuotes(list_NewOpps[0].Id, list_NewAccts[0].Id, 1);
        System.assertEquals(list_NewQuotes.size(), 1);
        list_NewQuotes[0].Group_Product_By__c = 'Standard View';
        update list_NewQuotes[0];
        
        list_NewOpps[0].Primary_Quote__c=list_NewQuotes[0].Id;
        update list_NewOpps[0];
         //Add quote line items         
        List<BigMachines__Quote_Product__c> list_NewQuoteProds = TestDataFactoryForQuoteTool.createQuoteProducts(list_NewQuotes[0].Id);
        System.assertEquals(list_NewQuoteProds.size(), 2);  
        
        //Unit tests for CreateQuoteCloudController methods        
        Test.setCurrentPageReference(new PageReference('Page.ProposalCloud')); 
        System.currentPageReference().getParameters().put('id', list_NewQuotes[0].Id);  
        ProposalCloudController objProposalCloudCntrl = new ProposalCloudController(); 
        
        list_NewQuotes[0].Group_Product_By__c = 'Proposal View';
        update list_NewQuotes[0];
        
        Test.setCurrentPageReference(new PageReference('Page.ProposalCloud')); 
        System.currentPageReference().getParameters().put('id', list_NewQuotes[0].Id);  
        ProposalCloudController objProposalCloudCntr2 = new ProposalCloudController();
        
    }

    @isTest
    static void test2() {
        //Skipping all triggers as we do not need any updates from triggers for the purposes of this unit test
        Util.Bypass_Trigger_Chk = true;
        
        //Create account, opp and quote
        List<Account> list_NewAccts = TestDataFactoryForQuoteTool.createAccounts(1);
        System.assertEquals(list_NewAccts.size(), 1);
        List<Opportunity> list_NewOpps = TestDataFactoryForQuoteTool.createOpportunties(list_NewAccts[0].Id, 1);
        System.assertEquals(list_NewOpps.size(), 1);
        List<BigMachines__Quote__c> list_NewQuotes = TestDataFactoryForQuoteTool.createQuotes(list_NewOpps[0].Id, list_NewAccts[0].Id, 1);
        System.assertEquals(list_NewQuotes.size(), 1);
        list_NewQuotes[0].Group_Product_By__c = 'Standard View';
        update list_NewQuotes[0];
        Subscription__C objsub = new Subscription__c(Account__c=list_NewAccts[0].id,Subscription_Start_Date__c = Date.today(),ACV__c = 0.00,CMRR__c=0.00,TAM_Services_Amount__c =0.00,TCV__c=0.00,Total_Education__c=0.00,Total_Hardware__c=0.00,Total_Non_Recurring_Fees__c = 0.00,Total_Services__c=0.00);
        insert objsub;
        list_NewQuotes[0].Amendment_For__c = objsub.id;
        list_NewQuotes[0].Order_Type__c = Label.Amend_Subscription;
        list_NewQuotes[0].Subscription_Start_Date__c =Date.today();
        list_NewQuotes[0].Subscription_End_Date__c = Date.today()+365;
        update list_NewQuotes[0];
        
        list_NewOpps[0].Primary_Quote__c=list_NewQuotes[0].Id;
        update list_NewOpps[0];
         //Add quote line items         
        List<BigMachines__Quote_Product__c> list_NewQuoteProds = TestDataFactoryForQuoteTool.createQuoteProducts(list_NewQuotes[0].Id);
        System.assertEquals(list_NewQuoteProds.size(), 2);  
        
        //Unit tests for CreateQuoteCloudController methods        
        Test.setCurrentPageReference(new PageReference('Page.ProposalCloud')); 
        System.currentPageReference().getParameters().put('id', list_NewQuotes[0].Id);  
        ProposalCloudController objProposalCloudCntrl = new ProposalCloudController(); 
        
        list_NewQuotes[0].Group_Product_By__c = 'Proposal View';
        update list_NewQuotes[0];
        
        Test.setCurrentPageReference(new PageReference('Page.ProposalCloud')); 
        System.currentPageReference().getParameters().put('id', list_NewQuotes[0].Id);  
        ProposalCloudController objProposalCloudCntr2 = new ProposalCloudController();
        
    }

    @isTest
    static void testProposalGroup(){

        //Skipping all triggers as we do not need any updates from triggers for the purposes of this unit test
        Util.Bypass_Trigger_Chk = true;
        
        //Create account, opp and quote
        List<Account> list_NewAccts = TestDataFactoryForQuoteTool.createAccounts(1);
        System.assertEquals(list_NewAccts.size(), 1);
        List<Opportunity> list_NewOpps = TestDataFactoryForQuoteTool.createOpportunties(list_NewAccts[0].Id, 1);
        System.assertEquals(list_NewOpps.size(), 1);
        List<BigMachines__Quote__c> list_NewQuotes = TestDataFactoryForQuoteTool.createQuotes(list_NewOpps[0].Id, list_NewAccts[0].Id, 1);
        System.assertEquals(list_NewQuotes.size(), 1);
        list_NewQuotes[0].Group_Product_By__c = 'Standard View';
        update list_NewQuotes[0];
        Subscription__C objsub = new Subscription__c(Account__c=list_NewAccts[0].id,Subscription_Start_Date__c = Date.today(),ACV__c = 0.00,CMRR__c=0.00,TAM_Services_Amount__c =0.00,TCV__c=0.00,Total_Education__c=0.00,Total_Hardware__c=0.00,Total_Non_Recurring_Fees__c = 0.00,Total_Services__c=0.00);
        insert objsub;
        list_NewQuotes[0].Amendment_For__c = objsub.id;
        list_NewQuotes[0].Order_Type__c = Label.Amend_Subscription;
        list_NewQuotes[0].Subscription_Start_Date__c =Date.today();
        list_NewQuotes[0].Subscription_End_Date__c = Date.today()+365;
        update list_NewQuotes[0];
        
        list_NewOpps[0].Primary_Quote__c=list_NewQuotes[0].Id;
        update list_NewOpps[0];
         //Add quote line items         
        List<BigMachines__Quote_Product__c> list_NewQuoteProds = TestDataFactoryForQuoteTool.createQuoteProducts(list_NewQuotes[0].Id);
        System.assertEquals(list_NewQuoteProds.size(), 2);  

        Quote_Proposal_Group__c objQP = new Quote_Proposal_Group__c();

        objQP.Group_Number__c = '12222';
        objQP.Name__c = 'Test';
        objQP.Description__c = 'Test';
        objQP.Quote__c =list_NewQuotes[0].Id;

        insert objQP;

        //Unit tests for CreateQuoteCloudController methods        
        Test.setCurrentPageReference(new PageReference('Page.ProposalCloud')); 
        System.currentPageReference().getParameters().put('id', list_NewQuotes[0].Id);  
        ProposalCloudController objProposalCloudCntrl = new ProposalCloudController(); 
        
        list_NewQuotes[0].Group_Product_By__c = 'Proposal View';
        update list_NewQuotes[0];
        
        Test.setCurrentPageReference(new PageReference('Page.ProposalCloud')); 
        System.currentPageReference().getParameters().put('id', list_NewQuotes[0].Id);  
        ProposalCloudController objProposalCloudCntr2 = new ProposalCloudController();
    }


}