objects/Quote__c.object
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Service_Contracts__c.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipLabel>Quote Service Contracts</relationshipLabel>
        <relationshipName>Quote_Service_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Quote Service Contracts</relationshipLabel>
        <relationshipName>Quote_Service_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Service Contract</label>
    <nameField>
        <label>Quote Service Contracts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityCoTermSCExtension.cls
//Naresh Kumar	06/02/2014
public with sharing class OpportunityCoTermSCExtension {
	public List<Quote_Service_Contracts__c> quoteSC {get;set;}
	public Boolean showGrid {get;set;}
	public OpportunityCoTermSCExtension(ApexPages.StandardController stdCon){
        String oppName = [SELECT Name FROM Opportunity WHERE Id = :stdCon.getId()].Name;
            
		quoteSC = [SELECT Quote__c, Quote__r.Name, Quote__r.BigMachines__Status__c, Service_Contract__c,
		Service_Contract__r.Renewal_Opportunity__r.Name, Service_Contract__r.Renewal_Opportunity__c 
			FROM Quote_Service_Contracts__c WHERE  Service_Contract__r.Renewal_Opportunity__c = :stdCon.getId() AND Quote__c != NULL];
		if(quoteSC.isEmpty() || oppName.startsWith('Downsize') || oppName.startsWith('Drop') )
			showGrid = false;
		else
			showGrid = true;
	}
}