objects/Rolled_Up_Usage_Data__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billable_30__c</fullName>
        <description>Number of billable seconds (rounded up to 6 seconds) with 30 second floor</description>
        <label>Billable 30</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billable_60__c</fullName>
        <description>Number of billable seconds (rounded up to 60 seconds)</description>
        <label>Billable 60</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billable_6__c</fullName>
        <description>Number of billable seconds (rounded up to 6 seconds)</description>
        <label>Billable 6</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>Channel Type of activity, 1=VOICE, 2=EMAIL, or 3=TEXT</description>
        <label>Channel Type</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <description>Number of messages included in this rollup</description>
        <label>Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Destination_Country_Code__c</fullName>
        <description>Country Code being summarized, e.g. 1 for USA, 44 for UK, etc.&apos;</description>
        <label>Destination Country Code</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Device_Type__c</fullName>
        <description>Device type being summarized, e.g. 0 for Email, 3 for Landline Phone, 13 for Wireless Phone, etc.</description>
        <label>Device Type</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Origin_Country_Code_ISO__c</fullName>
        <description>Origination ISO 3166 country code for this activity if one exists.</description>
        <label>Origin Country Code ISO</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin_Country_Code__c</fullName>
        <description>Origination country code for this activity if one exists.</description>
        <label>Origin Country Code</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PCV_Category__c</fullName>
        <description>The PureCloud Voice category hash.
Downstream Impact: Only used for PureCloud Voice, not extensible
Department Owner: Cloud Billing</description>
        <inlineHelpText>The PureCloud Voice category hash</inlineHelpText>
        <label>PCV Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCV_Group__c</fullName>
        <description>The PureCloud Voice group.
Downstream Impact: Only used for PureCloud Voice, not extensible
Department Owner: Cloud Billing</description>
        <inlineHelpText>The PureCloud Voice group.</inlineHelpText>
        <label>PCV Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCV_Type__c</fullName>
        <description>The PureCloud Voice Type.
Downstream Impact: Only used for PureCloud Voice, not extensible
Department Owner: Cloud Billing</description>
        <inlineHelpText>The PureCloud Voice Type</inlineHelpText>
        <label>PCV Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCV_Zone__c</fullName>
        <description>The PureCloud Voice zone.
Downstream Impact: Only used for PureCloud Voice, not extensible
Department Owner: Cloud Billing</description>
        <inlineHelpText>The PureCloud Voice zone.</inlineHelpText>
        <label>PCV Zone</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform_Id__c</fullName>
        <label>Platform Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this record has been processed by the Rating Engine.</description>
        <label>Processed ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region_Code__c</fullName>
        <description>•	US – USA
•	EU – Europe
•	AP - APAC</description>
        <label>Region Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rollup_Id__c</fullName>
        <description>UID of record from ETL.</description>
        <externalId>true</externalId>
        <label>Rollup Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Class__c</fullName>
        <description>Channel specific service modifier</description>
        <label>Service Class</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Identifier__c</fullName>
        <formula>IF(Service_Type__c == 1 || Service_Type__c == 3,IF(Destination_Country_Code_ISO__c == &apos;CA&apos;, &apos;CA&apos; &amp; &apos;#&apos;, Text(Destination_Country_Code__c) &amp; &apos;#&apos;),&apos;&apos;) &amp;
IF(Service_Type__c == 2 || Service_Type__c == 4,IF(Origin_Country_Code_ISO__c == &apos;CA&apos;, &apos;CA&apos; &amp; &apos;#&apos;, Text(Origin_Country_Code__c) &amp; &apos;#&apos;),&apos;&apos;) &amp; 
IF(Service_Type__c == 9 || Service_Type__c = 10 || Service_Type__c == 12, Text(Destination_Country_Code__c) &amp; &apos;#&apos;, &apos;&apos;) &amp; Text(Service_Type__c) &amp; &apos;#&apos; &amp;
Text(Channel_Type__c) &amp; &apos;#&apos; &amp;
Text(Service_Class__c) &amp; &apos;#&apos; &amp;
Text(Device_Type__c) &amp;
IF( Service_Type__c == 14 || Service_Type__c == 19,&apos;#&apos; &amp; Region_Code__c &amp; &apos;#&apos; &amp; Text(Usage_Type__c),&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>Service Type of activity</description>
        <label>Service Type</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Name__c</fullName>
        <label>Source Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start of hour being summarized</description>
        <inlineHelpText>Adjusted from GMT to your Time Zone</inlineHelpText>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Duration__c</fullName>
        <description>Total Duration (seconds) of messages summarized</description>
        <label>Total Duration</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZIP_Postal_Code__c</fullName>
        <description>Zip / Postal Code</description>
        <inlineHelpText>Zip / Postal Code</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Rolled Up Usage Data</label>
    <nameField>
        <displayFormat>RUD-{0000000}</displayFormat>
        <label>Rolled Up Usage Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rolled Up Usage Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RolledUpUsageDataFactory.cls
@isTest
public class RolledUpUsageDataFactory {

    public static Rolled_Up_Usage_Data__c createRolledUpUsageDataInboundUS()
    {
        return createRolledUpUsageData(
            'BEEEC',
            'Tenant123',
            'test-1',
            1,
            3,
            2,
            0,
            1,
            null,
            null,
            null,
            66,
            90,
            120,
            DateTime.now(),
            null
        );
    }

    public static Rolled_Up_Usage_Data__c createRolledUpUsageDataWirelessOutboundUS()
    {
        return createRolledUpUsageData(       
            'BEEEC',
            'Tenant123',
            'test-2',
            1,
            13,
            1,
            0,
            1,
            'US',
            null,
            null,
            126,
            150,
            180,
            DateTime.now(),
            null
        );
    }

    public static Rolled_Up_Usage_Data__c createRolledUpUsageDataOutboundWithTax(String platformId, String zipPostalCode)
    {
        return createPCVRolledUpUsageData(
            'PCL',
            platformId,
            'test-2',
            1,
            0,
            'US',
            'US',
            '0',
            '1',
            'USAGE#US#purchased#US#0.67500',
            12600, //REMOVE?
            15000, // REMOVE?
            18000, // REMOVE?
            DateTime.now(),
            zipPostalCode
        );
    }

    public static Rolled_Up_Usage_Data__c createRolledUpUsageData(String sourceName, String platformId, String rollupId, Integer channelType, Integer deviceType, Integer serviceType, Integer serviceClass, 
        Integer originCountryCode, String originISOCode, Integer destinationCountryCode, String regionCode, Integer billable6, Integer billable30, Integer billable60, DateTime startTime, String zipPostalCode)
    {
        return new Rolled_Up_Usage_Data__c(
            Source_Name__c = sourceName,
            Platform_Id__c = platformId,
            Rollup_Id__c = rollupId,
            Channel_Type__c = channelType,
            Device_Type__c = deviceType,
            Service_Type__c = serviceType,
            Service_Class__c = serviceClass,
            Origin_Country_Code__c = originCountryCode,
            Origin_Country_Code_ISO__c = originISOCode,
            Destination_Country_Code__c = destinationCountryCode,
            Billable_6__c = billable6,
            Billable_30__c = billable30,
            Billable_60__c = billable60,
            Start_Time__c = startTime
        );
    }

    public static Rolled_Up_Usage_Data__c createPCVRolledUpUsageData(String sourceName, String platformId, String rollupId, Integer serviceType, Integer activityType, 
       String regionCode, String pcvGroup, String pcvZone, String pcvType, String pcvCategory, Integer billable6, Integer billable30, Integer billable60, DateTime startTime, String zipPostalCode)
    {
        return new Rolled_Up_Usage_Data__c(
            Source_Name__c = sourceName,
            Platform_Id__c = platformId,
            Rollup_Id__c = rollupId,
            Channel_Type__c = 0,
            Device_Type__c = 0,
            Service_Type__c = serviceType,
            Activity_Type__c = activityType,
            Region_Code__c = regionCode,
            PCV_Group__c = pcvGroup,
            PCV_Zone__c = pcvZone,
            PCV_Type__c = pcvType,
            PCV_Category__c = pcvCategory,
            Service_Class__c = 0,
            Origin_Country_Code__c = 0,
            Origin_Country_Code_ISO__c = '',
            Destination_Country_Code__c = 0,
            Billable_6__c = billable6,
            Billable_30__c = billable30,
            Billable_60__c = billable60,
            Start_Time__c = startTime,
            ZIP_Postal_Code__c = zipPostalCode,
            Total_Duration__c = 450,
            Count__c = 400,
            Processed__c = false
        );
    }

    public static List<Rolled_Up_Usage_Data__c> reselectUsageData()
    {
        return [SELECT 
                    Source_Name__c
                    , Platform_Id__c
                    , Service_Type__c
                    , Channel_Type__c
                    , Service_Class__c
                    , Destination_Country_Code__c
                    , Origin_Country_Code__c
                    , Origin_Country_Code_ISO__c
                    , Billable_6__c
                    , Billable_30__c
                    , Billable_60__c
                    , Start_Time__c
                    , Service_Identifier__c
                FROM Rolled_Up_Usage_Data__c];
    }
}