objects/RQI_Audit__c.object
<CustomObject>
    <fields>
        <fullName>Answer_New_1__c</fullName>
        <label>Answer 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Answer_new_2__c</fullName>
        <label>Answer 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Author</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RQI_Audits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>RQI Audits</relationshipLabel>
        <relationshipName>RQI_Audits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RQI Audit</label>
    <nameField>
        <displayFormat>RQI-{0000}</displayFormat>
        <label>RQI Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RQI Audits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestRQIAverageCtrl.cls
@isTest(SeeAllData=true)
private class TestRQIAverageCtrl {

    static testMethod void testRQIAverage() {	
		
		List<case> needOneCase = [select id from case limit 1];
		
		RQI_Audit__c assessment = new RQI_Audit__c(Case__c = needOneCase[0].Id, Answer_New_1__c  = 'No' , Answer_new_2__c  = 'Yes', Status__c='Complete' ,Author__c = TestAQIRQIUtils.createTestAgent(UserInfo.getUserID()).Id);
     	insert assessment;
    	
		RQIAverageCtrl AAC = new RQIAverageCtrl(new ApexPages.standardController(assessment));
		System.assert(AAC.theAverage != null);
		
    }
}