objects/Sales_University_Training__c.object
<CustomObject>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LOID__c</fullName>
        <label>LOID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transcript_Status__c</fullName>
        <label>Transcript Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_University_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales University Training</label>
    <nameField>
        <label>Sales University Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales University Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SalesUniversityTraining.cls
public with sharing class SalesUniversityTraining {

    public List<Sales_University_Training__c> getUnivTraining(){
        
        return [SELECT Id,Course_Name__c,Due_Date__c,Transcript_Status__c,LOID__c
                 FROM Sales_University_Training__c WHERE User__c =: UserInfo.getUserId() and Transcript_Status__c in ('Registered','In Progress','Registered / Past Due','Pending Prerequisite')];
    }
}