objects/Salesaid_Action_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <label>Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_Activity__c</fullName>
        <label>Proposed Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>rownumber__c</fullName>
        <label>#</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Salesaid Action Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Salesaid Action Plan  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesaid Action Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Actionplanwrapper.cls
public class Actionplanwrapper
  {
  
  public ID ActionplanID{get;set;}
         public boolean Complete{get;set;}
         public String Description{get;set;}
         public String Owner{get;set;}
         public String Activity{get;set;}
         public Date target{get;set;}
         public ID sales_aid{get;set;}
         public Integer index{get;set;}
         public Salesaid_Action_Plan__c SAP;
         public Actionplanwrapper(Salesaid_Action_Plan__c SAP)  
         {
         ActionplanID=SAP.id;
         Complete=SAP.Complete__c;
         Description=SAP.Description__c;
         Owner=SAP.Owner__c;
         Activity=SAP.Proposed_Activity__c;
         target=SAP.target_Date__c;
         
         }
      public  Actionplanwrapper(Integer i)
      {
      index=i;
      SAP=new Salesaid_Action_Plan__c();
      SAP.rownumber__c=i+1;
      }   
         
  }