objects/Subscription__c.object
<CustomObject>
    <description>To store subscription for different offering types</description>
    <fields>
        <fullName>ACV__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores annual contract value
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Annual Contract Value.</inlineHelpText>
        <label>ACV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Stores partner account
Downstream Impact? Effects reporting and billing
Which department is owner? IT/PureCloud Team</description>
        <label>Sold To/Business Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Subscriptions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMRR__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores monthly committed value
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Committed Monthly Recurring Revenue.</inlineHelpText>
        <label>CMRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sale_Type__c</fullName>
        <description>What it Does? Identifies if the subscription is based on partner or not
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <label>Sale Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                    <default>true</default>
                    <label>Direct</label>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <description>What it Does? Stores term end date for this subscription
Downstream Impact? Effects reporting and billing
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Date in which the initial term or renewal term ends.</inlineHelpText>
        <label>Subscription Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TCV__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What it Does? Stores total contract value
Downstream Impact? Effects reporting
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Total Contract Value.</inlineHelpText>
        <label>TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CCDB/Subscription</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>CCDB/Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCDBs/Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Subscription_Product__c.object
<CustomObject>
    <fields>
        <fullName>Subscription__c</fullName>
        <description>What it Does? Stores parent subscription
Downstream Impact? Effects reporting and quote amendment/renewal
Which department is owner? IT/PureCloud Team</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscription Products</relationshipLabel>
        <relationshipName>Subscription_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Product</label>
    <nameField>
        <displayFormat>SP-{000000000}</displayFormat>
        <label>Subscription Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SubscriptionAutoRenewalTest.cls
/************************************************************************************
Purpose : Unit test class for SubscriptionAutoRenewal, SubscriptionAutoRenewalScheduler
Written By : Ranjith Punneli
Test Classes : N/A
*************************************************************************************/
@isTest
private class SubscriptionAutoRenewalTest {
    @isTest(seealldata=true)
    static void intialTest() {
        //Skipping all triggers as we do not need any updates from triggers for the purposes of this unit test
        Util.Bypass_Trigger_Chk = true;
        
        //Create account, opp and quote
        List<Account> list_NewAccts = TestDataFactoryForQuoteTool.createAccounts(1);
        System.assertEquals(list_NewAccts.size(), 1);
        List<Opportunity> list_NewOpps = TestDataFactoryForQuoteTool.createOpportunties(list_NewAccts[0].Id, 1);
        System.assertEquals(list_NewOpps.size(), 1);
        List<BigMachines__Quote__c> list_NewQuotes = TestDataFactoryForQuoteTool.createPCQuotes(list_NewOpps[0].Id, list_NewAccts[0].Id, 1);
        System.assertEquals(list_NewQuotes.size(), 1);
        list_NewOpps[0].Primary_Quote__c=list_NewQuotes[0].Id;
        update list_NewOpps[0];
        //Add quote line items         
        List<BigMachines__Quote_Product__c> list_NewQuoteProds = TestDataFactoryForQuoteTool.createPCQuoteProducts(list_NewQuotes[0].Id);
      
        List<Account_Order_Address__c> list_NewQtAddrs = TestDataFactoryForQuoteTool.createAOAs(list_NewQuotes[0].Id);
        System.assertEquals(list_NewQtAddrs.size(), 4); 
        
        //Create subscription & products        
        List<Subscription_Product__c> list_NewSubscriptionProds = new List<Subscription_Product__c>();
        List<Subscription__c> list_NewSubscriptions = new List<Subscription__c>();
        Subscription__c objNewSubscription = SubscriptionUtil.buildSubscrFromQuote(list_NewQuotes[0]);  
        objNewSubscription.CMRR__c = objNewSubscription.ACV__c = objNewSubscription.TCV__c = 0;
        objNewSubscription.Subscription_End_Date__c = Date.today();
        objNewSubscription.Sale_Type__c = 'Indirect';
        objNewSubscription.Business_Partner__c = [SELECT Id FROM Account WHERE Name = 'Atea AS' AND Legacy_Account_ID__c = '102351' LIMIT 1].Id;
        list_NewSubscriptions.add(objNewSubscription);
        insert list_NewSubscriptions;
        for(BigMachines__Quote_Product__c objQtProd: list_NewQuoteProds) {                    
            Subscription_Product__c objNewSubscriptionProd = SubscriptionUtil.buildSubscrProdFromQuoteProd(objQtProd);             
            objNewSubscriptionProd.Subscription__c = objNewSubscription.Id;
            list_NewSubscriptionProds.add(objNewSubscriptionProd);
        }  
        insert list_NewSubscriptionProds;
        
        Test.StartTest();    
            SubscriptionAutoRenewalScheduler objSubscriptionAutoRenewalScheduler = new SubscriptionAutoRenewalScheduler();
            String strSchd = '0 48 * * * ?'; 
            System.schedule('Schedule to auto renew subscriptions', strSchd, objSubscriptionAutoRenewalScheduler);
          //SubscriptionAutoRenewal objSubscriptionAutoRenewal = new SubscriptionAutoRenewal(Date.today());   
        Test.stopTest();
    }
}