objects/Subscription__c.object
<CustomObject>
    <description>To store subscription for different offering types</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>What it Does? Stores end user account
Downstream Impact? Effects reporting and billing integration
Which department is owner? IT/PureCloud Team</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Category__c</fullName>
        <description>What it Does? Stores type of billing (M2M, Annual M2M or Annual Pre-Pay)
Downstream Impact? Effects reporting and billing
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Method in which we bill customers for their committed licenses, whether pre-pay or monthly.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual Pre-Pay</fullName>
                </value>
                <value>
                    <fullName>Annual M2M</fullName>
                </value>
                <value>
                    <fullName>M2M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <description>What it Does? Stores billing period of the subscription 
Downstream Impact? Effects DQ and reporting
Which department is owner? IT/PureCloud Team</description>
        <label>Billing Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offering_Type__c</fullName>
        <description>What it Does? Stores different types of offering
Downstream Impact? Effects reporting and quote amendment/creation
Which department is owner? IT/PureCloud Team</description>
        <label>Offering Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PureConnect Cloud</fullName>
                    <default>true</default>
                    <label>PureConnect Cloud</label>
                </value>
                <value>
                    <fullName>PureCloud</fullName>
                </value>
                <value>
                    <fullName>PureEngage Cloud</fullName>
                </value>
                <value>
                    <fullName>PureEngage Subscription</fullName>
                </value>
                <value>
                    <fullName>PureConnect Subscription</fullName>
                </value>
                <value>
                    <fullName>Premier Edition Cloud</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_LookUp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Stores opportunity sfdc id 
Downstream Impact? Effects cloud deployment creation and CCDB updates
Which department is owner? IT/PureCloud Team</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What it Does? Lookup to quote object which is approved
Downstream Impact? Effects reporting and quote amendment
Which department is owner? IT/PureCloud Team</description>
        <label>Quote</label>
        <referenceTo>BigMachines__Quote__c</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>What it Does? Captures the current status of this subscription
Downstream Impact? Effects reporting and integration with billing
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Current state of this CCDB/Subscription record.  NOTE: Only active CCDB/Subscription records can be amended or renewed.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Pending Product Deactivation</fullName>
                </value>
                <value>
                    <fullName>Do Not Use</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <description>What it Does? Stores term start date for this subscription
Downstream Impact? Effects reporting and billing
Which department is owner? IT/PureCloud Team</description>
        <inlineHelpText>Date in which the initial term or renewal term begins, which is the start date plus the ramp period, if applicable.</inlineHelpText>
        <label>Subscription Term Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CCDB/Subscription</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>CCDB/Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCDBs/Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CCDBRelatedLisController.cls
/*
Class Name = CCDBRelatedLisController
Purpose = Class represent the logic of CCDB related list. User Story# S-647340, Task# T-848007
Developed By = Sushen Adhikary
Developed Date = 10-Dec-2019
Modified By = Sushen Adhikary
Modified Date = 12-Dec-2019
*/
public class CCDBRelatedLisController {       
    public List<Subscription__c> lstSubscription{get;set;} 
    
    public CCDBRelatedLisController(ApexPages.StandardController controller) {
        List<User> lstuser = [Select id,Profile.Name from User where Profile.Name In ('Genesys Portal Gold Partner','Genesys Portal Partner')];
        try {
            Account objAcct = (account)controller.getRecord();        
            
            if(objAcct != null){                
                lstSubscription =[SELECT id,Name,Offering_Type__c,Quote__r.name,Status__c,Billing_Category__c,Billing_Period__c,Subscription_Start_Date__c FROM Subscription__c WHERE Account__c= :objAcct.id and Status__c != 'Inactive' and Opportunity_LookUp__r.CreatedById IN :lstuser]; 
                System.Debug('lstSubscription=' + lstSubscription);
            }
        }
        catch(Exception ex){
            System.Debug('Exception occured from class CCDBRelatedLisController, ERROR='+ ex);
        }
    }  
}