objects/Survey_Integration_Inbound__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>inbound survey integration settings</description>
    <fields>
        <fullName>Security_Token__c</fullName>
        <label>Security Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Survey Integration Inbound</label>
</CustomObject>

objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Like_the_least__c</fullName>
        <label>Areas partner likes the least</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Like_the_most__c</fullName>
        <label>Areas partner likes the most</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NPS_Rating__c</fullName>
        <label>NPS Rating</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_of_Organization__c</fullName>
        <label>Part of Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Respondent_ID__c</fullName>
        <externalId>true</externalId>
        <label>Respondent ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Type__c</fullName>
        <label>Survey Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transactional</fullName>
                    <default>true</default>
                    <label>Transactional</label>
                </value>
                <value>
                    <fullName>Relationship</fullName>
                </value>
                <value>
                    <fullName>NPS Interview</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>SMART</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verbatim__c</fullName>
        <label>Verbatim</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyResponsePartnerImport.cls
@RestResource(urlMapping='/SurveyResponsePartnerImport/*')
global without sharing class SurveyResponsePartnerImport {
	
	@HttpPost
    global static String importResp(String ContactId, String AccountId, String External_ID,String First_name,String security_token,
                                    String Last_name, String Contact_Email, String Verbatim, String NPS_Rating,
                                    String PartOfOrg, String LikeLeast, String LikeMost)  {
                                    	
       String LogName = 'Survey Response';
       String LogSource = 'SurveyResponsePartnerImport'; 
       String baseLogMsg = External_ID;
       String retValue='';  
        
       if ( NPS_Rating == '' ) {
       	   String logMsg = baseLogMsg + ': NPS Rating Blank';
           ErrorLogUtil.insertLog(LogName, logMsg, LogSource);          
           return logMsg;
      	}
        
        if ( !verifyToken(security_token) ) {
           String logMsg = baseLogMsg + ': Invalid Security Token.';
           ErrorLogUtil.insertLog(LogName, logMsg, LogSource);         
           return logMsg;
        }       

        try { 	        	
	            Survey_Response__c surveyResp_inst = new Survey_Response__c( Respondent_ID__c = External_ID, Survey_Type__c ='Partner', 
	            						            Account__c = AccountId, Contact__c = ContactId, 
	           										First_Name__c = First_name, Last_Name__c = Last_name, Email_Address__c = Contact_Email,	           										 
	           									    NPS_Rating__c = NPS_Rating, Verbatim__c = Verbatim, 
	            							Part_of_Organization__c = PartOfOrg, Like_the_Least__c = LikeLeast, Like_the_most__c = LikeMost
	                                              );
	            									 
	            insert surveyResp_inst;
	            retValue = surveyResp_inst.id;
	   }	     
	   catch (Exception ex) {
	   	    String logMsg = baseLogMsg + ': ' + ex.getMessage();
	   	    ErrorLogUtil.insertLog(LogName, logMsg, LogSource);   
        	return ex.getMessage();
        } 
            
        return retValue;                                     	
    	
    }
    
      private static Boolean verifyToken(String token)  {
	   	    Survey_Integration_Inbound__c custConf = Survey_Integration_Inbound__c.getOrgDefaults();    	     
	        return ( custConf.Security_Token__c == null || custConf.Security_Token__c !=  token ) ? false : true;    			 			    	
	  }

}