objects/Technology_License_Form__c.object
<CustomObject>
    <fields>
        <fullName>Country_of_sale__c</fullName>
        <label>Country of sale</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>Russia</fullName>
                </value>
                <value>
                    <fullName>Sweden</fullName>
                </value>
                <value>
                    <fullName>United Arab Emirates</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
                <value>
                    <fullName>United States</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <inlineHelpText>Please provide the name of the customer that you sold the licenses to</inlineHelpText>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_billing__c</fullName>
        <inlineHelpText>Date of billing</inlineHelpText>
        <label>Date of billing</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoicing_Model__c</fullName>
        <inlineHelpText>Invoicing Model</inlineHelpText>
        <label>Invoicing Model</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lump sum payment</fullName>
                </value>
                <value>
                    <fullName>Monthly Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Involved_Genesys_Sales_Person_s__c</fullName>
        <inlineHelpText>Please provide information about involved Genesys Sales persons, if any</inlineHelpText>
        <label>Involved Genesys Sales Person(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Licenses_sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Licenses sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Technology License Forms</relationshipLabel>
        <relationshipName>Technology_License_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Sold__c</fullName>
        <inlineHelpText>Please provide the name of the product you sold</inlineHelpText>
        <label>Product Sold</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Currency__c</fullName>
        <inlineHelpText>Sales Currency</inlineHelpText>
        <label>Sales Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>Euro</fullName>
                </value>
                <value>
                    <fullName>Australian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_price_per_license__c</fullName>
        <label>Sales price per license</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_sale__c</fullName>
        <label>Total sales price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>AppFoundry Royalty Report</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Technology License Form : Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppFoundry Royalty Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LicenseReportExportController.cls
public class LicenseReportExportController {
    public List<Technology_License_Form__c> licenseFormList {get; set;}
    public Id userAccountId;
    
    public LicenseReportExportController() {
    	userAccountId = getUserAccountId(); 
    	licenseFormList = new List<Technology_License_Form__c>();
        init();    
    }
    public void init() {
        licenseFormList = [select Id,Product_Sold__c,Number_of_Licenses_sold__c,Sales_price_per_license__c,Customer_Name__c,Total_sale__c,CreatedDate,Sales_Currency__c,Invoicing_Model__c,Date_of_billing__c,Country_of_sale__c,Involved_Genesys_Sales_Person_s__c from Technology_License_Form__c where Partner_Account__c =: userAccountId];
    }
    
    public static Id getUserAccountId() {
    	List<User> currentUser = [select AccountId from User where Id =: Userinfo.getUserid()];
    	System.debug('currentUser---'+currentUser);
    	return currentUser[0].AccountId;	
    }
}